<?xml version="1.0" encoding="UTF-8"?>
<TS language="en_US" sourcelanguage="en" version="2.1">
  <context>
    <name>global</name>
    <message>
      <source>{{PRODUCT_NAME}}</source>
      <translation>Xstream Cloud</translation>
    </message>
    <message>
      <source>{{CLIENT_PROTOCOL}}</source>
      <translation>xccelo-vms</translation>
    </message>
    <message>
      <source>{{VMS_NAME}}</source>
      <translation>Xstream</translation>
    </message>
    <message>
      <source>{{downloadLink}}</source>
      <translation>www.xccelo.com/xstream</translation>
    </message>
    <message>
      <source>{{supportLink}}</source>
      <translation>support.xstream@xccelo.com</translation>
    </message>
    <message>
      <source>{{supportLinkText}}</source>
      <translation>support.xstream@xccelo.com</translation>
    </message>
    <message>
      <source>{{companyUrl}}</source>
      <translation>www.xccelo.com</translation>
    </message>
    <message>
      <source>{{iOSappID}}</source>
      <translation>disabled</translation>
    </message>
    <message>
      <source>{{IOS_APP_LINK}}</source>
      <translation>disabled</translation>
    </message>
    <message>
      <source>{{ANDROID_APP_LINK}}</source>
      <translation>https://play.google.com/store/apps/details?id=com.xccelo.xstream</translation>
    </message>
    <message>
      <source>{{COMPANY_NAME}}</source>
      <translation>Xccelo GmbH</translation>
    </message>
  </context>
</TS>
