#!/bin/bash -e

COMPANY_NAME=@deb.customization.company.name@

. /usr/share/debconf/confmodule

if [ -n "$DEBIAN_SCRIPT_DEBUG" ]; then set -v -x; DEBIAN_SCRIPT_TRACE=1; fi
${DEBIAN_SCRIPT_TRACE:+ echo "#42#DEBUG# RUNNING $0 $*" 1>&2 }

UPGRADING=${2:+yes}

export PATH=$PATH:/sbin:/usr/sbin:/bin:/usr/bin

BASE_DIR="/opt/$COMPANY_NAME/mediaserver"

ETC_DIR="$BASE_DIR/etc"
BIN_DIR="$BASE_DIR/bin"

CONFIG_FILE="$ETC_DIR/mediaserver.conf"
RUNTIME_CONFIG_FILE="$ETC_DIR/running_time.conf"
DB_PATH="$BASE_DIR/var/ecs.sqlite"

CFG_HELPER="$BIN_DIR/config_helper.py $CONFIG_FILE"

# Default MS parameters
PORT_DEFAULT="7001"
TRANSPORT_DEAULT="auto"
PUBLIC_IP_ENABLED_DEFAULT="auto"
CAMERA_SETTINGS_OPTIMIZATION_DEFAULT=true
STATISTICS_REPORT_ALLOWED_DEFAULT=true
SYSTEM_USER=$COMPANY_NAME

TARGET_DEVICE='@targetDevice@'
WITH_ROOT_TOOL='@withRootTool@'

is_systemd_used()
{
    [[ $(readlink -m /sbin/init) =~ .*systemd$ ]]
}

is_rpi()
{
    if [[ $TARGET_DEVICE == "linux_arm32" ]]
    then
        grep '^Hardware.*:.*BCM2835[[:space:]]*$' /proc/cpuinfo &>/dev/null
    else
        false
    fi
}

function is_local_addr {
    local hostname=$1;
    local addr=$(gethostip $hostname -d)

    if [ $? -ne 0 ]; then
    addr=$hostname
    fi

    [[ "$addr" =~ ^127.[0-9]+.[0-9]+.[0-9]+$ ]] && return 0

    ip -4 -o addr | awk '{gsub("/", " "); print $4;}' | grep "^$addr$" > /dev/null 2>&1
}

function find_free_port {
    local port=$1

    while :
    do
        netstat -nl4t | awk '{print $4;}' | grep ":$port" > /dev/null 2>&1
        if [ $? -ne 0 ]
        then
            echo $port
            return
        else
            port=$((port+10))
        fi
    done
}

function check_new_system {
    local port=$1

    for ((i = 1; i <= 5; i++))
    do
        sleep 1
        echo "[$i] Checking if the server is running..."
        INFO=$(wget "http://localhost:$port/api/moduleInformation" --quiet -O-) && break
    done

    echo "$INFO" | grep -q '"localSystemId":\s*"{00000000-0000-0000-0000-000000000000}"'
}

function display_complete_setup_hint {
    local port=$1

    [ -n "$UPGRADING" ] && return

    if check_new_system $port
    then
        db_fset @deb.customization.company.name@-mediaserver/complete-setup-hint seen false
        db_input critical @deb.customization.company.name@-mediaserver/complete-setup-hint || true
        db_go
    fi
}

install_modification_specific_config()
{
    local -r config_file_path="${BASE_DIR}/share/configs/mediaserver.conf.$TARGET_DEVICE.template"

    if [[ -f ${config_file_path} ]]
    then
        cp  "${config_file_path}" "${BASE_DIR}/etc/mediaserver.conf"
    fi
}

# This is necessary because changed configuration options should take effect
# immediately.

service $COMPANY_NAME-mediaserver stop || true

if [[ $WITH_ROOT_TOOL == 'true' ]]
then
    service $COMPANY_NAME-root-tool stop || true
fi

case "$1" in
    configure)
        SYSTEM_NAME_DEFAULT=System_$RANDOM

        ECS_HOST="$($CFG_HELPER appserverHost)"
        if [ -n "$ECS_HOST" ]; then
            if is_local_addr "$ECS_HOST"; then
                $CFG_HELPER appserverHost -d
                $CFG_HELPER appserverPort -d
                $CFG_HELPER appserverLogin -d
                $CFG_HELPER appserverPassword -d
            else
                $CFG_HELPER pendingSwitchToClusterMode "yes"
                $CFG_HELPER appserverPassword -d
            fi
        fi

        [ ! -d "$BASE_DIR/var" ] && mkdir -p "$BASE_DIR/var"

        if [ -z "$UPGRADING" ]
        then
            PORT="$($CFG_HELPER port)"
            [ -z "$PORT" ] && PORT=$(find_free_port $PORT_DEFAULT)
            $CFG_HELPER port "$PORT"

            if [ ! -f $DB_PATH ]
            then
                APPSERVER_PASSWORD="admin"
                $CFG_HELPER appserverPassword "$APPSERVER_PASSWORD"
                $CFG_HELPER lowPriorityPassword 1
            fi

            TRANSPORT="$($CFG_HELPER rtspTransport)"
            [ -z "$TRANSPORT" ] && TRANSPORT=$TRANSPORT_DEFAULT
            $CFG_HELPER rtspTransport "$TRANSPORT"

            $CFG_HELPER systemName ""

            CAMERA_SETTINGS_OPTIMIZATION="$($CFG_HELPER cameraSettingsOptimization)"
            [ -z "$CAMERA_SETTINGS_OPTIMIZATION" ] && CAMERA_SETTINGS_OPTIMIZATION=$CAMERA_SETTINGS_OPTIMIZATION_DEFAULT
            $CFG_HELPER cameraSettingsOptimization "$CAMERA_SETTINGS_OPTIMIZATION"

            STATISTICS_REPORT_ALLOWED="$($CFG_HELPER statisticsReportAllowed)"
            [ -z "$STATISTICS_REPORT_ALLOWED" ] && STATISTICS_REPORT_ALLOWED=$STATISTICS_REPORT_ALLOWED_DEFAULT
            $CFG_HELPER statisticsReportAllowed "$STATISTICS_REPORT_ALLOWED"
        else
            PORT="$($CFG_HELPER port)"
            [ -z "$PORT" ] && PORT=$(find_free_port $PORT_DEFAULT)
            $CFG_HELPER port "$PORT"

            SYSTEM_NAME="$($CFG_HELPER systemName)"
            [ -z "$SYSTEM_NAME" ] && $CFG_HELPER systemName "$SYSTEM_NAME_DEFAULT"
        fi

        useradd --system "$SYSTEM_USER" || true

        # Allow core dumps creation.
        chown "$SYSTEM_USER:$SYSTEM_USER" "$BIN_DIR"

        if [[ $WITH_ROOT_TOOL == 'true' ]]
        then
            chown "root:${SYSTEM_USER}" "${BIN_DIR}/root-tool-bin"
            chmod u+s "${BIN_DIR}/root-tool-bin"
            setcap CAP_NET_BIND_SERVICE=+eip "$BIN_DIR/mediaserver-bin"
        fi

        touch "$RUNTIME_CONFIG_FILE"

  ;;

  abort-upgrade|abort-remove|abort-configure)
  ;;

  *)
    echo "postinst called with unknown argument '$1'" 1>&2
    exit 1
  ;;
esac

# Dirty hack to prevent apport from catching our crash dumps.
echo manual > /etc/init/apport.override
systemctl disable apport >/dev/null 2>&1 || true
service apport stop >/dev/null 2>&1 || true

[[ -L "${BASE_DIR}/lib/ffmpeg" ]] && unlink "${BASE_DIR}/lib/ffmpeg"

if is_rpi
then
    # RPi requires specially compiled ffmpeg with mmal support - for RPi camera.
    ( cd "${BASE_DIR}/lib"; ln -s ffmpeg-rpi ffmpeg )

    bash "${BASE_DIR}/var/scripts/rpi/cam_setup.sh"

    # Plan the reboot after the package installation. This mark will be processed in install.sh.
    touch "/var/run/reboot-required"
else
    ( cd "${BASE_DIR}/lib"; ln -s ffmpeg-arm32 ffmpeg )
fi

install_modification_specific_config

if is_systemd_used
then
    # Systemd requires explicit enabling of the service to start it on boot.
    if [[ $WITH_ROOT_TOOL == 'true' ]]
    then
        systemctl enable $COMPANY_NAME-root-tool || exit $?
    fi

    systemctl enable $COMPANY_NAME-mediaserver || exit $?
fi

startServer()
{
    if [[ $WITH_ROOT_TOOL == 'true' ]]
    then
        service $COMPANY_NAME-root-tool start || return $?
    fi

    service $COMPANY_NAME-mediaserver start
}

if startServer
then
    sleep 1
    echo Started service $(ps aux | grep "mediaserver-bin -e" | grep -v grep)
else
    # We do not fail installation process because in this case dpkg makes a package hard to remove.
    echo "WARNING: Unable to start service" 1>&2
fi

display_complete_setup_hint $PORT
