#!/bin/bash -e

. /usr/share/debconf/confmodule

if [ -n "$DEBIAN_SCRIPT_DEBUG" ]; then set -v -x; DEBIAN_SCRIPT_TRACE=1; fi
${DEBIAN_SCRIPT_TRACE:+ echo "#42#DEBUG# RUNNING $0 $*" 1>&2 }

COMPANY_NAME="@deb.customization.company.name@"
CLOUD_GROUP_SUFFIX="@cloud_group_suffix@"
CLOUD_NAME="@cloudName@"

BASE_DIR="/opt/$COMPANY_NAME/mediaserver"
ETC_DIR="$BASE_DIR/etc"
BIN_DIR="$BASE_DIR/bin"

CONFIG_FILE="$ETC_DIR/mediaserver.conf"
CFG_HELPER="$BIN_DIR/config_helper.py $CONFIG_FILE"

WITH_ROOT_TOOL='@withRootTool@'

isInDockerContainer()
{
    [[ $(cat "/var/run/systemd/container" 2>/dev/null) == "docker" ]]
}

if ! isInDockerContainer
then
    systemctl stop $COMPANY_NAME-mediaserver || true

    if [[ $WITH_ROOT_TOOL == 'true' ]]
    then
        systemctl stop $COMPANY_NAME-root-tool || true
    fi
fi

systemctl disable $COMPANY_NAME-mediaserver

if [[ $WITH_ROOT_TOOL == 'true' ]]
then
    systemctl disable $COMPANY_NAME-root-tool
fi

if [ "$1" = "remove" ]
then
    REMOVE="Remove the Database"
    KEEP="Keep current version"
    CHOICES="$REMOVE, $KEEP"

    db_subst @deb.customization.company.name@-mediaserver/removeDatabase choices $CHOICES
    db_set @deb.customization.company.name@-mediaserver/removeDatabase "$KEEP"
    db_fset @deb.customization.company.name@-mediaserver/removeDatabase seen false

    db_input high @deb.customization.company.name@-mediaserver/removeDatabase || true
    db_go || true
    db_get @deb.customization.company.name@-mediaserver/removeDatabase

    # The following check is needed for the correct uninstallation
    # when the media server folder or some files were removed manually
    if [ -f "$CFG_HELPER" ]; then
        $CFG_HELPER sysIdTime -d
    fi

    if [ "$RET" = "$REMOVE" ]
    then
        find "/opt/$COMPANY_NAME/mediaserver/var" -name "*.sqlite*" \
            -a ! -name "ecs_static.sqlite*" \
            |xargs rm -f
    fi
fi
