#!/bin/sh -e
#
# Backwards compartability for appstart

SERVICE=@deb.customization.company.name@-mediaserver
COMMAND=$1

echo "Rather than invoking init scripts through /etc/init.d, use the service(8)" >&2
echo "utility, e.g. service $SERVICE $COMMAND" >&2
echo >&2

service $SERVICE $COMMAND || exit $?

