# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-08 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_message_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('data', jsonfield.fields.JSONField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('send_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.CharField(blank=True, default=b'', help_text=b"What's the target? (release type, customization or cloud instance)", max_length=255)),
                ('type', models.CharField(blank=True, default=b'', help_text=b"What's the event? (submitted_release, published_{{type}}, cloud_...)", max_length=255)),
                ('user_email', models.CharField(max_length=255)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.Event'),
        ),
    ]
