# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-08 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20161208_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='customization',
            field=models.CharField(default=b'default', max_length=255),
        ),
    ]
