# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-30 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20170303_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
