# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-22 01:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_cloudnotifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloudnotification',
            options={'permissions': (('send_cloud_notification', 'Can send cloud notifications'),)},
        ),
        migrations.AlterField(
            model_name='cloudnotification',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_cloudnotification', to=settings.AUTH_USER_MODEL),
        ),
    ]
