# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-17 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0032_customization_public_release_history'),
        ('notifications', '0008_auto_20171222_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudnotification',
            name='customizations',
            field=models.ManyToManyField(to='cms.Customization'),
        ),
    ]
