#!/bin/bash

TOOLCHAIN_PREFIX=/usr/local/codesourcery/arm-2013.11/bin/arm-none-linux-gnueabi-

CUSTOMIZATION=digitalwatchdog
PRODUCT_NAME=dwspectrum
MODULE_NAME=appserver
VERSION=2.2.0

PACKAGE_NAME=$CUSTOMIZATION-$PRODUCT_NAME-$MODULE_NAME-$VERSION-edge.tar.gz

BUILD_DIR=/tmp/hdw_isd_build.tmp.$MODULE_NAME
PREFIX_DIR=/usr/local/apps/$CUSTOMIZATION

if [ "$USER" != "ivigasin" ]
then
    SRC_DIR=/home/ak/develop/netoptix_vms.arm
    TARGET_DIR=/var/www
else
    SRC_DIR=$HOME/workspace/netoptix_vms
    TARGET_DIR=$HOME/tmp/isd
fi

BUILD_OUTPUT_DIR=$SRC_DIR/build_environment/target
LIBS_DIR=$BUILD_OUTPUT_DIR/lib/release

rm -rf $BUILD_DIR
mkdir -p $BUILD_DIR/$PREFIX_DIR

#copying libs
mkdir -p $BUILD_DIR/$PREFIX_DIR/$MODULE_NAME/
cp -rf $SRC_DIR/$MODULE_NAME/* $BUILD_DIR/$PREFIX_DIR/$MODULE_NAME/
rm -rf $BUILD_DIR/$PREFIX_DIR/$MODULE_NAME/{repo,setup,vms/custom,scripts,migrations/0*}

cp -rf $SRC_DIR/$MODULE_NAME/setup/build/stage/lib/llutil.so $BUILD_DIR/$PREFIX_DIR/$MODULE_NAME
$TOOLCHAIN_PREFIX"strip" $BUILD_DIR/$PREFIX_DIR/$MODULE_NAME/llutil.so
mkdir $BUILD_DIR/$PREFIX_DIR/$MODULE_NAME/ecapi
touch $BUILD_DIR/$PREFIX_DIR/$MODULE_NAME/ecapi/__init__.py
cp -rf $SRC_DIR/$MODULE_NAME/setup/build/stage/lib/ecapi.pb2.so $BUILD_DIR/$PREFIX_DIR/$MODULE_NAME/ecapi/pb2.so
$TOOLCHAIN_PREFIX"strip" $BUILD_DIR/$PREFIX_DIR/$MODULE_NAME/ecapi/pb2.so

#conf
cp -rf $SRC_DIR/edge_firmware/isd/maven/filter-resources/usr/local/apps/networkoptix/appserver/entcontroller.conf $BUILD_DIR/$PREFIX_DIR/$MODULE_NAME/

#start script
mkdir -p $BUILD_DIR/etc/init.d/
install -m 755 $SRC_DIR/edge_firmware/isd/maven/filter-resources/etc/init.d/S99networkoptix-$MODULE_NAME $BUILD_DIR/etc/init.d/S99$CUSTOMIZATION-$MODULE_NAME


#building package
pushd $BUILD_DIR
tar czf $PACKAGE_NAME .$PREFIX_DIR ./etc

if [ ! -z $TARGET_DIR ]; then
  cp $PACKAGE_NAME $TARGET_DIR 
fi

popd

cp $BUILD_DIR/$PACKAGE_NAME .
