#!/bin/bash

CUSTOMIZATION=networkoptix
PRODUCT_NAME=hdwitness
MODULE_NAME=appserver
VERSION=2.1.0

PACKAGE_NAME=$CUSTOMIZATION-$PRODUCT_NAME-$MODULE_NAME-$VERSION-edge.tar.gz

BUILD_DIR=/tmp/hdw_isd_build.tmp.$MODULE_NAME
PREFIX_DIR=/usr/local/apps/$CUSTOMIZATION

SRC_DIR=/home/ak/develop/netoptix_vms.arm
BUILD_OUTPUT_DIR=$SRC_DIR/build_environment/target
LIBS_DIR=$BUILD_OUTPUT_DIR/lib/release
TARGET_DIR=/var/www


rm -rf $BUILD_DIR
mkdir -p $BUILD_DIR/$PREFIX_DIR

#copying libs
mkdir -p $BUILD_DIR/$PREFIX_DIR/$MODULE_NAME/
cp -rf $SRC_DIR/$MODULE_NAME/* $BUILD_DIR/$PREFIX_DIR/$MODULE_NAME/
rm -rf $BUILD_DIR/$PREFIX_DIR/$MODULE_NAME/repo

#conf
cp -rf $SRC_DIR/edge_firmware/isd/maven/filter-resources/usr/local/apps/networkoptix/appserver/entcontroller.conf $BUILD_DIR/$PREFIX_DIR/$MODULE_NAME/

#start script
mkdir -p $BUILD_DIR/etc/init.d/
cp $SRC_DIR/edge_firmware/isd/maven/filter-resources/etc/init.d/S99networkoptix-$MODULE_NAME $BUILD_DIR/etc/init.d/
chmod u+x,g+x $BUILD_DIR/etc/init.d/S99networkoptix-$MODULE_NAME


#building package
pushd $BUILD_DIR
tar czf $PACKAGE_NAME .$PREFIX_DIR ./etc

if [ ! -z $TARGET_DIR ]; then
  cp $PACKAGE_NAME $TARGET_DIR 
fi

popd

cp $BUILD_DIR/$PACKAGE_NAME .
