#!/bin/bash

TOOLCHAIN_PREFIX=/usr/local/codesourcery/arm-2013.11/bin/arm-none-linux-gnueabi-

CUSTOMIZATION=digitalwatchdog
PRODUCT_NAME=dwspectrum
MODULE_NAME=mediaserver
VERSION=2.2.0

PACKAGE_NAME=$CUSTOMIZATION-$PRODUCT_NAME-$MODULE_NAME-$VERSION-edge.tar.gz

BUILD_DIR=/tmp/hdw_isd_build.tmp
PREFIX_DIR=/usr/local/apps/$CUSTOMIZATION

if [ "$USER" != "ivigasin" ]
then
    SRC_DIR=/home/ak/develop/netoptix_vms.arm
    TARGET_DIR=/var/www
else
    SRC_DIR=$HOME/workspace/netoptix_vms
    TARGET_DIR=$HOME/tmp/isd
fi

BUILD_OUTPUT_DIR=$SRC_DIR/build_environment/target
LIBS_DIR=$BUILD_OUTPUT_DIR/lib/release

LIBS_TO_COPY=\
( libavcodec.so.54.23.100 \
libavdevice.so.54.0.100 \
libavfilter.so.2.77.100 \
libavformat.so.54.6.100 \
libavutil.so.51.54.100 \
libcommon.so.220.0.0 \
libpostproc.so.52.0.100 \
libQt5Concurrent.so.5.1.1 \
libQt5Core.so.5.1.1 \
libQt5Gui.so.5.1.1 \
libQt5Multimedia.so.5.1.1 \
libQt5Network.so.5.1.1 \
libQt5Sql.so.5.1.1 \
libQt5Xml.so.5.1.1 \
libsigar.so \
libswresample.so.0.15.100 \
libswscale.so.2.1.100 \
libvpx.so.1.2.0 )



rm -rf $BUILD_DIR
mkdir -p $BUILD_DIR/$PREFIX_DIR

#copying libs
mkdir -p $BUILD_DIR/$PREFIX_DIR/$MODULE_NAME/lib/
for var in "${LIBS_TO_COPY[@]}"
do
  $TOOLCHAIN_PREFIX"strip" $LIBS_DIR/${var}
  cp $LIBS_DIR/${var} $BUILD_DIR/$PREFIX_DIR/$MODULE_NAME/lib/
done

#generating links
pushd $BUILD_DIR/$PREFIX_DIR/$MODULE_NAME/lib/
LIBS="`find ./ -name '*.so.*.*.*'`"
for var in $LIBS
do
    ln -s $var "`echo $var | cut -d . -f 1,2,3,4`"
done
popd


#copying bin
mkdir -p $BUILD_DIR/$PREFIX_DIR/$MODULE_NAME/bin/
cp $BUILD_OUTPUT_DIR/bin/release/mediaserver $BUILD_DIR/$PREFIX_DIR/$MODULE_NAME/bin/

mkdir -p $BUILD_DIR/$PREFIX_DIR/$MODULE_NAME/bin/plugins/
cp $LIBS_DIR/libisd_native_plugin.so $BUILD_DIR/$PREFIX_DIR/$MODULE_NAME/bin/plugins/
#pushd $BUILD_DIR/$PREFIX_DIR/$MODULE_NAME/plugins/
#ln -s libisd_native_plugin.so libisd_native_plugin.so
#popd

#conf
mkdir -p $BUILD_DIR/$PREFIX_DIR/$MODULE_NAME/etc/
cp $SRC_DIR/edge_firmware/isd/maven/filter-resources/usr/local/apps/networkoptix/$MODULE_NAME/etc/mediaserver.conf $BUILD_DIR/$PREFIX_DIR/$MODULE_NAME/etc/

#start script
mkdir -p $BUILD_DIR/etc/init.d/
install -m 755 $SRC_DIR/edge_firmware/isd/maven/filter-resources/etc/init.d/S99networkoptix-$MODULE_NAME $BUILD_DIR/etc/init.d/S99$CUSTOMIZATION-$MODULE_NAME


#building package
pushd $BUILD_DIR
tar czf $PACKAGE_NAME .$PREFIX_DIR ./etc

if [ ! -z $TARGET_DIR ]; then
  cp $PACKAGE_NAME $TARGET_DIR 
fi

popd

cp $BUILD_DIR/$PACKAGE_NAME .
