INSERT INTO "vms_resourcetype" ( id,name,description,"manufacture_id" ) VALUES ( '631','THIRD_PARTY Camera',NULL,'13' );
INSERT INTO "vms_resourcetype" ( id,name,description,"manufacture_id" ) VALUES ( '632','THIRD_PARTY_COMMON',NULL,'13' );
INSERT INTO "vms_resourcetype" ( id,name,description,"manufacture_id" ) VALUES ( '513','VIRTUAL_CAMERA Camera',NULL,'4' );
INSERT INTO "vms_resourcetype" ( id,name,description,"manufacture_id" ) VALUES ( '514','SERVER_DESKTOP_CAMERA',NULL,'4' );

INSERT INTO "vms_resourcetype_parents" ( id,"from_resourcetype_id","to_resourcetype_id" ) VALUES ( '715','631','6' );
INSERT INTO "vms_resourcetype_parents" ( id,"from_resourcetype_id","to_resourcetype_id" ) VALUES ( '716','632','631' );
INSERT INTO "vms_resourcetype_parents" ( id,"from_resourcetype_id","to_resourcetype_id" ) VALUES ( '597','513','6' );
INSERT INTO "vms_resourcetype_parents" ( id,"from_resourcetype_id","to_resourcetype_id" ) VALUES ( '598','514','513' );

INSERT INTO "vms_propertytype" ( id,"resource_type_id",name,type,min,max,step,"values","ui_values","default_value",netHelper,"group","sub_group",description,ui,readonly ) VALUES ( '418','632','supportedMotion','1',NULL,NULL,NULL,NULL,NULL,'SoftwareGrid, MotionWindow',NULL,NULL,NULL,NULL,'0','0' );
INSERT INTO "vms_propertytype" ( id,"resource_type_id",name,type,min,max,step,"values","ui_values","default_value",netHelper,"group","sub_group",description,ui,readonly ) VALUES ( '419','632','motionWindowCnt','1',NULL,NULL,NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,'0','0' );
INSERT INTO "vms_propertytype" ( id,"resource_type_id",name,type,min,max,step,"values","ui_values","default_value",netHelper,"group","sub_group",description,ui,readonly ) VALUES ( '420','632','motionMaskWindowCnt','1',NULL,NULL,NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,'0','0' );
INSERT INTO "vms_propertytype" ( id,"resource_type_id",name,type,min,max,step,"values","ui_values","default_value",netHelper,"group","sub_group",description,ui,readonly ) VALUES ( '421','632','motionSensWindowCnt','1',NULL,NULL,NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,'0','0' );
INSERT INTO "vms_propertytype" ( id,"resource_type_id",name,type,min,max,step,"values","ui_values","default_value",netHelper,"group","sub_group",description,ui,readonly ) VALUES ( '422','632','isAudioSupported','1',NULL,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'0','0' );
INSERT INTO "vms_propertytype" ( id,"resource_type_id",name,type,min,max,step,"values","ui_values","default_value",netHelper,"group","sub_group",description,ui,readonly ) VALUES ( '423','632','hasDualStreaming','1',NULL,NULL,NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,'0','0' );
INSERT INTO "vms_propertytype" ( id,"resource_type_id",name,type,min,max,step,"values","ui_values","default_value",netHelper,"group","sub_group",description,ui,readonly ) VALUES ( '424','632','streamFpsSharing','1',NULL,NULL,NULL,NULL,NULL,'sharePixels',NULL,NULL,NULL,NULL,'0','0' );
INSERT INTO "vms_propertytype" ( id,"resource_type_id",name,type,min,max,step,"values","ui_values","default_value",netHelper,"group","sub_group",description,ui,readonly ) VALUES ( '425','632','channelsAmount','1',NULL,NULL,NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,'0','0' );
INSERT INTO "vms_propertytype" ( id,"resource_type_id",name,type,min,max,step,"values","ui_values","default_value",netHelper,"group","sub_group",description,ui,readonly ) VALUES ( '426','632','dts','1',NULL,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'0','0' );
INSERT INTO "vms_propertytype" ( id,"resource_type_id",name,type,min,max,step,"values","ui_values","default_value",netHelper,"group","sub_group",description,ui,readonly ) VALUES ( '427','632','cameraCapabilities','1',NULL,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'0','0' );
INSERT INTO "vms_propertytype" ( id,"resource_type_id",name,type,min,max,step,"values","ui_values","default_value",netHelper,"group","sub_group",description,ui,readonly ) VALUES ( '428','632','ptzCapabilities','1',NULL,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'0','0' );
INSERT INTO "vms_propertytype" ( id,"resource_type_id",name,type,min,max,step,"values","ui_values","default_value",netHelper,"group","sub_group",description,ui,readonly ) VALUES ( '429','632','MaxFPS','1',NULL,NULL,NULL,NULL,NULL,'8',NULL,NULL,NULL,NULL,'0','0' );
INSERT INTO "vms_propertytype" ( id,"resource_type_id",name,type,min,max,step,"values","ui_values","default_value",netHelper,"group","sub_group",description,ui,readonly ) VALUES ( '430','632','analog','1',NULL,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'0','0' );
INSERT INTO "vms_propertytype" ( id,"resource_type_id",name,type,min,max,step,"values","ui_values","default_value",netHelper,"group","sub_group",description,ui,readonly ) VALUES ( '168','514','cameraCapabilities','1',NULL,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'0','0' );
INSERT INTO "vms_propertytype" ( id,"resource_type_id",name,type,min,max,step,"values","ui_values","default_value",netHelper,"group","sub_group",description,ui,readonly ) VALUES ( '169','514','ptzCapabilities','1',NULL,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'0','0' );
INSERT INTO "vms_propertytype" ( id,"resource_type_id",name,type,min,max,step,"values","ui_values","default_value",netHelper,"group","sub_group",description,ui,readonly ) VALUES ( '170','514','hasDualStreaming','1',NULL,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'0','0' );
INSERT INTO "vms_propertytype" ( id,"resource_type_id",name,type,min,max,step,"values","ui_values","default_value",netHelper,"group","sub_group",description,ui,readonly ) VALUES ( '171','514','isAudioSupported','1',NULL,NULL,NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,'0','0' );
INSERT INTO "vms_propertytype" ( id,"resource_type_id",name,type,min,max,step,"values","ui_values","default_value",netHelper,"group","sub_group",description,ui,readonly ) VALUES ( '172','514','MaxFPS','1',NULL,NULL,NULL,NULL,NULL,'30',NULL,NULL,NULL,NULL,'0','0' );
INSERT INTO "vms_propertytype" ( id,"resource_type_id",name,type,min,max,step,"values","ui_values","default_value",netHelper,"group","sub_group",description,ui,readonly ) VALUES ( '173','514','noRecordingParams','1',NULL,NULL,NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,'0','0' );
