#!/bin/sh -e
#
# Backwards compartability for upstart

SERVICE=@deb.customization.company.name@-mediaserver

echo "Rather than invoking init scripts through /etc/init.d, use the service(8)" >&2
echo "utility, e.g. service $SERVICE start" >&2
echo >&2

