# Copyright 2018-present Network Optix, Inc. Licensed under MPL 2.0: www.mozilla.org/MPL/2.0/

version: '3'
services:
  webapp:
    image: mediaserver
    ports:
      - "7001:7001"
    network_mode: "host"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ~/video:/recordings
      - ~/data/:/opt/networkoptix/mediaserver/var
    tmpfs:
      - /run
      - /run/lock