// Copyright 2018-present Network Optix, Inc. Licensed under MPL 2.0: www.mozilla.org/MPL/2.0/

#pragma once

#include "analytics_sdk_event.h"
#include "analytics_sdk_object_detected.h"
#include "camera_disconnected_event.h"
#include "camera_input_event.h"
#include "conflict_event.h"
#include "custom_event.h"
#include "fan_error_event.h"
#include "instant_event.h"
#include "ip_conflict_event.h"
#include "ldap_sync_issue_event.h"
#include "license_issue_event.h"
#include "motion_event.h"
#include "network_issue_event.h"
#include "plugin_diagnostic_event.h"
#include "poe_over_budget_event.h"
#include "prolonged_event.h"
#include "reasoned_event.h"
#include "server_certificate_error.h"
#include "server_conflict_event.h"
#include "server_failure_event.h"
#include "server_started_event.h"
#include "software_trigger_event.h"
#include "storage_failure_event.h"
