/* soapActionBindingProxy.cpp
   Generated by gSOAP 2.8.55 for generated_with_wsdl2h/axis_soap_event_action

gSOAP XML Web services tools
Copyright (C) 2000-2017, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#include "soapActionBindingProxy.h"

ActionBindingProxy::ActionBindingProxy()
{	this->soap = soap_new();
	this->soap_own = true;
	ActionBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

ActionBindingProxy::ActionBindingProxy(const ActionBindingProxy& rhs)
{	this->soap = rhs.soap;
	this->soap_own = false;
	this->soap_endpoint = rhs.soap_endpoint;
}

ActionBindingProxy::ActionBindingProxy(struct soap *_soap)
{	this->soap = _soap;
	this->soap_own = false;
	ActionBindingProxy_init(_soap->imode, _soap->omode);
}

ActionBindingProxy::ActionBindingProxy(const char *endpoint)
{	this->soap = soap_new();
	this->soap_own = true;
	ActionBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = endpoint;
}

ActionBindingProxy::ActionBindingProxy(soap_mode iomode)
{	this->soap = soap_new();
	this->soap_own = true;
	ActionBindingProxy_init(iomode, iomode);
}

ActionBindingProxy::ActionBindingProxy(const char *endpoint, soap_mode iomode)
{	this->soap = soap_new();
	this->soap_own = true;
	ActionBindingProxy_init(iomode, iomode);
	soap_endpoint = endpoint;
}

ActionBindingProxy::ActionBindingProxy(soap_mode imode, soap_mode omode)
{	this->soap = soap_new();
	this->soap_own = true;
	ActionBindingProxy_init(imode, omode);
}

ActionBindingProxy::~ActionBindingProxy()
{	if (this->soap_own)
		soap_free(this->soap);
}

void ActionBindingProxy::ActionBindingProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this->soap, imode);
	soap_omode(this->soap, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] = {
        {"SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://schemas.xmlsoap.org/soap/envelope/", NULL},
        {"SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://schemas.xmlsoap.org/soap/encoding/", NULL},
        {"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
        {"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
        {"ns6", "http://www.w3.org/2005/08/addressing", NULL, NULL},
        {"ns4", "http://docs.oasis-open.org/wsrf/bf-2", NULL, NULL},
        {"ns2", "http://docs.oasis-open.org/wsn/t-1", NULL, NULL},
        {"ns3", "http://docs.oasis-open.org/wsn/b-2", NULL, NULL},
        {"ns1", "http://www.axis.com/vapix/ws/event1", NULL, NULL},
        {"ns5", "http://www.axis.com/vapix/ws/action1", NULL, NULL},
        {NULL, NULL, NULL, NULL}
    };
	soap_set_namespaces(this->soap, namespaces);
}

ActionBindingProxy *ActionBindingProxy::copy()
{	ActionBindingProxy *dup = SOAP_NEW_COPY(ActionBindingProxy);
	if (dup)
		soap_copy_context(dup->soap, this->soap);
	return dup;
}

ActionBindingProxy& ActionBindingProxy::operator=(const ActionBindingProxy& rhs)
{	if (this->soap != rhs.soap)
	{	if (this->soap_own)
			soap_free(this->soap);
		this->soap = rhs.soap;
		this->soap_own = false;
		this->soap_endpoint = rhs.soap_endpoint;
	}
	return *this;
}

void ActionBindingProxy::destroy()
{	soap_destroy(this->soap);
	soap_end(this->soap);
}

void ActionBindingProxy::reset()
{	this->destroy();
	soap_done(this->soap);
	soap_initialize(this->soap);
	ActionBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

void ActionBindingProxy::soap_noheader()
{	this->soap->header = NULL;
}

::SOAP_ENV__Header *ActionBindingProxy::soap_header()
{	return this->soap->header;
}

::SOAP_ENV__Fault *ActionBindingProxy::soap_fault()
{	return this->soap->fault;
}

const char *ActionBindingProxy::soap_fault_string()
{	return *soap_faultstring(this->soap);
}

const char *ActionBindingProxy::soap_fault_detail()
{	return *soap_faultdetail(this->soap);
}

int ActionBindingProxy::soap_close_socket()
{	return soap_closesock(this->soap);
}

int ActionBindingProxy::soap_force_close_socket()
{	return soap_force_closesock(this->soap);
}

void ActionBindingProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this->soap, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void ActionBindingProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this->soap, os);
}
#endif

char *ActionBindingProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this->soap, buf, len);
}
#endif

int ActionBindingProxy::GetActionTemplates(const char *endpoint, const char *soap_action, _ns5__GetActionTemplates *ns5__GetActionTemplates, _ns5__GetActionTemplatesResponse &ns5__GetActionTemplatesResponse)
{	struct soap *soap = this->soap;
	struct __ns5__GetActionTemplates soap_tmp___ns5__GetActionTemplates;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.axis.com/vapix/ws/action1/GetActionTemplates";
	soap_tmp___ns5__GetActionTemplates.ns5__GetActionTemplates = ns5__GetActionTemplates;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns5__GetActionTemplates(soap, &soap_tmp___ns5__GetActionTemplates);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns5__GetActionTemplates(soap, &soap_tmp___ns5__GetActionTemplates, "-ns5:GetActionTemplates", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns5__GetActionTemplates(soap, &soap_tmp___ns5__GetActionTemplates, "-ns5:GetActionTemplates", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns5__GetActionTemplatesResponse*>(&ns5__GetActionTemplatesResponse)) // NULL ref?
		return soap_closesock(soap);
	ns5__GetActionTemplatesResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns5__GetActionTemplatesResponse.soap_get(soap, "ns5:GetActionTemplatesResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ActionBindingProxy::AddActionConfiguration(const char *endpoint, const char *soap_action, _ns5__AddActionConfiguration *ns5__AddActionConfiguration, _ns5__AddActionConfigurationResponse &ns5__AddActionConfigurationResponse)
{	struct soap *soap = this->soap;
	struct __ns5__AddActionConfiguration soap_tmp___ns5__AddActionConfiguration;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.axis.com/vapix/ws/action1/AddActionConfiguration";
	soap_tmp___ns5__AddActionConfiguration.ns5__AddActionConfiguration = ns5__AddActionConfiguration;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns5__AddActionConfiguration(soap, &soap_tmp___ns5__AddActionConfiguration);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns5__AddActionConfiguration(soap, &soap_tmp___ns5__AddActionConfiguration, "-ns5:AddActionConfiguration", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns5__AddActionConfiguration(soap, &soap_tmp___ns5__AddActionConfiguration, "-ns5:AddActionConfiguration", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns5__AddActionConfigurationResponse*>(&ns5__AddActionConfigurationResponse)) // NULL ref?
		return soap_closesock(soap);
	ns5__AddActionConfigurationResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns5__AddActionConfigurationResponse.soap_get(soap, "ns5:AddActionConfigurationResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ActionBindingProxy::RemoveActionConfiguration(const char *endpoint, const char *soap_action, _ns5__RemoveActionConfiguration *ns5__RemoveActionConfiguration, _ns5__RemoveActionConfigurationResponse &ns5__RemoveActionConfigurationResponse)
{	struct soap *soap = this->soap;
	struct __ns5__RemoveActionConfiguration soap_tmp___ns5__RemoveActionConfiguration;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.axis.com/vapix/ws/action1/RemoveActionConfiguration";
	soap_tmp___ns5__RemoveActionConfiguration.ns5__RemoveActionConfiguration = ns5__RemoveActionConfiguration;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns5__RemoveActionConfiguration(soap, &soap_tmp___ns5__RemoveActionConfiguration);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns5__RemoveActionConfiguration(soap, &soap_tmp___ns5__RemoveActionConfiguration, "-ns5:RemoveActionConfiguration", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns5__RemoveActionConfiguration(soap, &soap_tmp___ns5__RemoveActionConfiguration, "-ns5:RemoveActionConfiguration", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns5__RemoveActionConfigurationResponse*>(&ns5__RemoveActionConfigurationResponse)) // NULL ref?
		return soap_closesock(soap);
	ns5__RemoveActionConfigurationResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns5__RemoveActionConfigurationResponse.soap_get(soap, "ns5:RemoveActionConfigurationResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ActionBindingProxy::GetActionConfigurations(const char *endpoint, const char *soap_action, _ns5__GetActionConfigurations *ns5__GetActionConfigurations, _ns5__GetActionConfigurationsResponse &ns5__GetActionConfigurationsResponse)
{	struct soap *soap = this->soap;
	struct __ns5__GetActionConfigurations soap_tmp___ns5__GetActionConfigurations;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.axis.com/vapix/ws/action1/GetActionConfigurations";
	soap_tmp___ns5__GetActionConfigurations.ns5__GetActionConfigurations = ns5__GetActionConfigurations;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns5__GetActionConfigurations(soap, &soap_tmp___ns5__GetActionConfigurations);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns5__GetActionConfigurations(soap, &soap_tmp___ns5__GetActionConfigurations, "-ns5:GetActionConfigurations", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns5__GetActionConfigurations(soap, &soap_tmp___ns5__GetActionConfigurations, "-ns5:GetActionConfigurations", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns5__GetActionConfigurationsResponse*>(&ns5__GetActionConfigurationsResponse)) // NULL ref?
		return soap_closesock(soap);
	ns5__GetActionConfigurationsResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns5__GetActionConfigurationsResponse.soap_get(soap, "ns5:GetActionConfigurationsResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ActionBindingProxy::GetRecipientTemplates(const char *endpoint, const char *soap_action, _ns5__GetRecipientTemplates *ns5__GetRecipientTemplates, _ns5__GetRecipientTemplatesResponse &ns5__GetRecipientTemplatesResponse)
{	struct soap *soap = this->soap;
	struct __ns5__GetRecipientTemplates soap_tmp___ns5__GetRecipientTemplates;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.axis.com/vapix/ws/action1/GetRecipientTemplates";
	soap_tmp___ns5__GetRecipientTemplates.ns5__GetRecipientTemplates = ns5__GetRecipientTemplates;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns5__GetRecipientTemplates(soap, &soap_tmp___ns5__GetRecipientTemplates);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns5__GetRecipientTemplates(soap, &soap_tmp___ns5__GetRecipientTemplates, "-ns5:GetRecipientTemplates", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns5__GetRecipientTemplates(soap, &soap_tmp___ns5__GetRecipientTemplates, "-ns5:GetRecipientTemplates", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns5__GetRecipientTemplatesResponse*>(&ns5__GetRecipientTemplatesResponse)) // NULL ref?
		return soap_closesock(soap);
	ns5__GetRecipientTemplatesResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns5__GetRecipientTemplatesResponse.soap_get(soap, "ns5:GetRecipientTemplatesResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ActionBindingProxy::AddRecipientConfiguration(const char *endpoint, const char *soap_action, _ns5__AddRecipientConfiguration *ns5__AddRecipientConfiguration, _ns5__AddRecipientConfigurationResponse &ns5__AddRecipientConfigurationResponse)
{	struct soap *soap = this->soap;
	struct __ns5__AddRecipientConfiguration soap_tmp___ns5__AddRecipientConfiguration;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.axis.com/vapix/ws/action1/AddRecipientConfiguration";
	soap_tmp___ns5__AddRecipientConfiguration.ns5__AddRecipientConfiguration = ns5__AddRecipientConfiguration;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns5__AddRecipientConfiguration(soap, &soap_tmp___ns5__AddRecipientConfiguration);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns5__AddRecipientConfiguration(soap, &soap_tmp___ns5__AddRecipientConfiguration, "-ns5:AddRecipientConfiguration", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns5__AddRecipientConfiguration(soap, &soap_tmp___ns5__AddRecipientConfiguration, "-ns5:AddRecipientConfiguration", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns5__AddRecipientConfigurationResponse*>(&ns5__AddRecipientConfigurationResponse)) // NULL ref?
		return soap_closesock(soap);
	ns5__AddRecipientConfigurationResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns5__AddRecipientConfigurationResponse.soap_get(soap, "ns5:AddRecipientConfigurationResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ActionBindingProxy::RemoveRecipientConfiguration(const char *endpoint, const char *soap_action, _ns5__RemoveRecipientConfiguration *ns5__RemoveRecipientConfiguration, _ns5__RemoveRecipientConfigurationResponse &ns5__RemoveRecipientConfigurationResponse)
{	struct soap *soap = this->soap;
	struct __ns5__RemoveRecipientConfiguration soap_tmp___ns5__RemoveRecipientConfiguration;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.axis.com/vapix/ws/action1/RemoveRecipientConfiguration";
	soap_tmp___ns5__RemoveRecipientConfiguration.ns5__RemoveRecipientConfiguration = ns5__RemoveRecipientConfiguration;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns5__RemoveRecipientConfiguration(soap, &soap_tmp___ns5__RemoveRecipientConfiguration);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns5__RemoveRecipientConfiguration(soap, &soap_tmp___ns5__RemoveRecipientConfiguration, "-ns5:RemoveRecipientConfiguration", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns5__RemoveRecipientConfiguration(soap, &soap_tmp___ns5__RemoveRecipientConfiguration, "-ns5:RemoveRecipientConfiguration", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns5__RemoveRecipientConfigurationResponse*>(&ns5__RemoveRecipientConfigurationResponse)) // NULL ref?
		return soap_closesock(soap);
	ns5__RemoveRecipientConfigurationResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns5__RemoveRecipientConfigurationResponse.soap_get(soap, "ns5:RemoveRecipientConfigurationResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ActionBindingProxy::GetRecipientConfigurations(const char *endpoint, const char *soap_action, _ns5__GetRecipientConfigurations *ns5__GetRecipientConfigurations, _ns5__GetRecipientConfigurationsResponse &ns5__GetRecipientConfigurationsResponse)
{	struct soap *soap = this->soap;
	struct __ns5__GetRecipientConfigurations soap_tmp___ns5__GetRecipientConfigurations;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.axis.com/vapix/ws/action1/GetRecipientConfigurations";
	soap_tmp___ns5__GetRecipientConfigurations.ns5__GetRecipientConfigurations = ns5__GetRecipientConfigurations;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns5__GetRecipientConfigurations(soap, &soap_tmp___ns5__GetRecipientConfigurations);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns5__GetRecipientConfigurations(soap, &soap_tmp___ns5__GetRecipientConfigurations, "-ns5:GetRecipientConfigurations", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns5__GetRecipientConfigurations(soap, &soap_tmp___ns5__GetRecipientConfigurations, "-ns5:GetRecipientConfigurations", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns5__GetRecipientConfigurationsResponse*>(&ns5__GetRecipientConfigurationsResponse)) // NULL ref?
		return soap_closesock(soap);
	ns5__GetRecipientConfigurationsResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns5__GetRecipientConfigurationsResponse.soap_get(soap, "ns5:GetRecipientConfigurationsResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ActionBindingProxy::AddActionRule(const char *endpoint, const char *soap_action, _ns5__AddActionRule *ns5__AddActionRule, _ns5__AddActionRuleResponse &ns5__AddActionRuleResponse)
{	struct soap *soap = this->soap;
	struct __ns5__AddActionRule soap_tmp___ns5__AddActionRule;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.axis.com/vapix/ws/action1/AddActionRule";
	soap_tmp___ns5__AddActionRule.ns5__AddActionRule = ns5__AddActionRule;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns5__AddActionRule(soap, &soap_tmp___ns5__AddActionRule);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns5__AddActionRule(soap, &soap_tmp___ns5__AddActionRule, "-ns5:AddActionRule", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns5__AddActionRule(soap, &soap_tmp___ns5__AddActionRule, "-ns5:AddActionRule", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns5__AddActionRuleResponse*>(&ns5__AddActionRuleResponse)) // NULL ref?
		return soap_closesock(soap);
	ns5__AddActionRuleResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns5__AddActionRuleResponse.soap_get(soap, "ns5:AddActionRuleResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ActionBindingProxy::GetActionRules(const char *endpoint, const char *soap_action, _ns5__GetActionRules *ns5__GetActionRules, _ns5__GetActionRulesResponse &ns5__GetActionRulesResponse)
{	struct soap *soap = this->soap;
	struct __ns5__GetActionRules soap_tmp___ns5__GetActionRules;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.axis.com/vapix/ws/action1/GetActionRules";
	soap_tmp___ns5__GetActionRules.ns5__GetActionRules = ns5__GetActionRules;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns5__GetActionRules(soap, &soap_tmp___ns5__GetActionRules);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns5__GetActionRules(soap, &soap_tmp___ns5__GetActionRules, "-ns5:GetActionRules", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns5__GetActionRules(soap, &soap_tmp___ns5__GetActionRules, "-ns5:GetActionRules", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns5__GetActionRulesResponse*>(&ns5__GetActionRulesResponse)) // NULL ref?
		return soap_closesock(soap);
	ns5__GetActionRulesResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns5__GetActionRulesResponse.soap_get(soap, "ns5:GetActionRulesResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ActionBindingProxy::RemoveActionRule(const char *endpoint, const char *soap_action, _ns5__RemoveActionRule *ns5__RemoveActionRule, _ns5__RemoveActionRuleResponse &ns5__RemoveActionRuleResponse)
{	struct soap *soap = this->soap;
	struct __ns5__RemoveActionRule soap_tmp___ns5__RemoveActionRule;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.axis.com/vapix/ws/action1/RemoveActionRule";
	soap_tmp___ns5__RemoveActionRule.ns5__RemoveActionRule = ns5__RemoveActionRule;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns5__RemoveActionRule(soap, &soap_tmp___ns5__RemoveActionRule);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns5__RemoveActionRule(soap, &soap_tmp___ns5__RemoveActionRule, "-ns5:RemoveActionRule", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns5__RemoveActionRule(soap, &soap_tmp___ns5__RemoveActionRule, "-ns5:RemoveActionRule", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns5__RemoveActionRuleResponse*>(&ns5__RemoveActionRuleResponse)) // NULL ref?
		return soap_closesock(soap);
	ns5__RemoveActionRuleResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns5__RemoveActionRuleResponse.soap_get(soap, "ns5:RemoveActionRuleResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
