TARGET_SDK="iphoneos"
TARGET_NAME="consolebuildtest"
WORKSPACE="ihdwitness.xcworkspace"
PROJECT_BUILDDIR="$HOME/workspace/ios-client/build"
PROJECT_NAME="consolebuildtest"
BUILD_HISTORY_DIR="$HOME/workspace/ios-client/dist"
DEVELOPPER_NAME="iPhone Distribution: Network Optix, Inc. (L6FE34GJWM)"
PROVISONNING_PROFILE="$HOME/Library/MobileDevice/Provisioning Profiles/6596960B-4292-4413-8D1D-03D171057542.mobileprovision"
APPLICATION_NAME="HDWitness"
BUILD_CONFIGURATION="Release"

xcodebuild -workspace ${WORKSPACE} -scheme ${APPLICATION_NAME} -sdk "${TARGET_SDK}" -configuration "${BUILD_CONFIGURATION}" SYMROOT="${PROJECT_BUILDDIR}/${PROJECT_NAME}"
/usr/bin/xcrun -sdk "${TARGET_SDK}" PackageApplication -v "${PROJECT_BUILDDIR}/${PROJECT_NAME}/${BUILD_CONFIGURATION}-${TARGET_SDK}/${APPLICATION_NAME}.app" -o "${BUILD_HISTORY_DIR}/${APPLICATION_NAME}.ipa" --sign "${DEVELOPPER_NAME}" --embed "${PROVISONNING_PROFILE}"
