# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-29 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=1024)),
                ('source', models.CharField(default='', max_length=1024)),
                ('system_id', models.CharField(max_length=1024)),
                ('email', models.CharField(max_length=1024)),
                ('direction', models.CharField(max_length=100)),
            ],
        ),
    ]
