pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ['accounts.htm','Cloud Users &#62; Accounts','Accounts',''],
	['branding_elements.htm','Content Management &#62; Editing Pages &#62; Branding','Branding',''],
	['cloud_maintenance_503_page.htm','Content Management &#62; Editing Pages &#62; Cloud Maintenance (503) page','Cloud Maintenance (503) page',''],
	['cloud_users.htm','Cloud Users','Cloud Users',''],
	['cms_overview.htm','Cloud Customization Management (CMS) Overview','Cloud Portal Customization Management System (CMS) Overview',''],
	['content_management.htm','Content Management','Content Management',''],
	['editing_pages.htm','Content Management &#62; Editing Pages','Editing Pages',''],
	['landing_page.htm','Content Management &#62; Editing Pages &#62; Landing page','Landing page',''],
	['license_agreement_page.htm','Content Management &#62; Editing Pages &#62; License Agreement page','License Agreement page',''],
	['logging_in_to_cms.htm','Logging in to CMS','Logging in to CMS',''],
	['portal_management.htm','Portal Management Dashboard','Portal Management Dashboard',''],
	['privacy_policy_page.htm','Content Management &#62; Editing Pages &#62; Privacy Policy page','Privacy Policy page',''],
	['reviewing_revisions.htm','Content Management &#62; Reviewing and Publishing Revisions','Reviewing and Publishing Revisions',''],
	['support_page.htm','Content Management &#62; Editing Pages &#62; Support page','Support page','']];
