<?xml version="1.0" encoding="UTF-8"?>
<TS language="en_US" sourcelanguage="en" version="2.1">
  <context>
    <name>global</name>
    <message>
      <source>{{PRODUCT_NAME}}</source>
      <translation>Qcloud</translation>
    </message>
    <message>
      <source>{{CLIENT_PROTOCOL}}</source>
      <translation>qulu-vms</translation>
    </message>        
    <message>
      <source>{{VMS_NAME}}</source>
      <translation>Qulu</translation>
    </message>
    <message>
      <source>{{downloadLink}}</source>
      <translation>http://vista-cctv.com/product/qulu/</translation>
    </message>
    <message>
      <source>{{supportLink}}</source>
      <translation>mailto:support@vista-cctv.com</translation>
    </message>
    <message>
      <source>{{supportLinkText}}</source>
      <translation>support@vista-cctv.com</translation>
    </message>
    <message>
      <source>{{companyUrl}}</source>
      <translation>http://vista-cctv.com</translation>
    </message>
    <message>
      <source>{{iOSappID}}</source>
      <translation>N3KX2CKR5P.com.vista.quluMobile</translation>
    </message>  
    <message>
      <source>{{IOS_APP_LINK}}</source>
      <translation>https://itunes.apple.com/us/app/qulu/id1090487857?mt=8</translation>
    </message>
    <message>
      <source>{{ANDROID_APP_LINK}}</source>
      <translation>https://play.google.com/store/apps/details?id=com.vista.qulumobile</translation>
    </message>        
    <message>
      <source>{{COMPANY_NAME}}</source>
      <translation>Vista CCTV</translation>
    </message>
  </context>
</TS>
