#define CompanyName "${company.name}"
#define ProductName "${display.product.name}"
#define Box "${box}"
#define Arch "${arch}"
#define BuildConfiguration "${build.configuration}"
#define AppVersion "${release.version}.${buildNumber}"
#define ServerUpgradeCode "${customization.upgradeCode}"
#define ClientUpgradeCode "${customization.clientUpgradeCode}"