# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-16 02:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', 'update_user_customization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': (('can_view_release', 'Can view releases and patches'),)},
        ),
    ]
