# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-21 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_account_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='language',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
