# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-09 09:04
from __future__ import unicode_literals

from django.db import migrations

#If not account.activated_date and account.last_login: activated_date = created_date
#If not (account.activated_date or account.last_login): Ignore account and wait for activates/restore/login
def updateActivatedDate(apps, schema_editor):
    Account = apps.get_model('api', 'account')
    accounts = Account.objects.filter(activated_date__isnull=True)
    if accounts.exists():
        for account in accounts:
            if account.last_login:
                account.activated_date = account.created_date
                account.save()


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('api', '0013_auto_20171216_0210'),
    ]

    operations = [
        migrations.RunPython(updateActivatedDate),
    ]
