# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-10-12 02:42
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('cms', '0041_auto_20181012_0242'),
        ('api', '0018_auto_20180612_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroupsToCustomizationPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Customization')),
            ],
            options={
                'db_table': 'cms_usergroupstocustomizationpermissions',
                'permissions': (('can_view_pending', 'Can view pending versions of integrations'),),
            },
        ),
        migrations.CreateModel(
            name='ProxyGroup',
            fields=[
            ],
            options={
                'verbose_name': 'Group',
                'proxy': True,
                'verbose_name_plural': 'Groups',
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AddField(
            model_name='usergroupstocustomizationpermissions',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
