# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-11-08 02:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20181012_0242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': (('can_view_release', 'Can view releases and patches'), ('invite_users', 'Invite users'))},
        ),
    ]
