# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-02-21 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20181113_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountloginhistory',
            name='ip',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
