// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resource.proto

package com.networkoptix.hdwitness.protobuf;

public final class ResourceProtos {
  private ResourceProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ResourceOrBuilder extends
      com.google.protobuf.GeneratedMessage.
          ExtendableMessageOrBuilder<Resource> {
    
    // required .pb.Resource.Type type = 1;
    boolean hasType();
    com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Type getType();
    
    // optional int32 id = 2;
    boolean hasId();
    int getId();
    
    // optional int32 typeId = 3;
    boolean hasTypeId();
    int getTypeId();
    
    // optional int32 parentId = 4;
    boolean hasParentId();
    int getParentId();
    
    // optional string name = 5;
    boolean hasName();
    String getName();
    
    // optional string url = 6;
    boolean hasUrl();
    String getUrl();
    
    // optional .pb.Resource.Status status = 7;
    boolean hasStatus();
    com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Status getStatus();
    
    // optional bool disabled = 8;
    boolean hasDisabled();
    boolean getDisabled();
    
    // optional string guid = 9;
    boolean hasGuid();
    String getGuid();
    
    // repeated .pb.Resource.Property property = 10;
    java.util.List<com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property> 
        getPropertyList();
    com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property getProperty(int index);
    int getPropertyCount();
    java.util.List<? extends com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.PropertyOrBuilder> 
        getPropertyOrBuilderList();
    com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.PropertyOrBuilder getPropertyOrBuilder(
        int index);
  }
  public static final class Resource extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        Resource> implements ResourceOrBuilder {
    // Use Resource.newBuilder() to construct.
    private Resource(Builder builder) {
      super(builder);
    }
    private Resource(boolean noInit) {}
    
    private static final Resource defaultInstance;
    public static Resource getDefaultInstance() {
      return defaultInstance;
    }
    
    public Resource getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.networkoptix.hdwitness.protobuf.ResourceProtos.internal_static_pb_Resource_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.networkoptix.hdwitness.protobuf.ResourceProtos.internal_static_pb_Resource_fieldAccessorTable;
    }
    
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      Camera(0, 0),
      Server(1, 1),
      User(2, 2),
      Layout(3, 3),
      ;
      
      public static final int Camera_VALUE = 0;
      public static final int Server_VALUE = 1;
      public static final int User_VALUE = 2;
      public static final int Layout_VALUE = 3;
      
      
      public final int getNumber() { return value; }
      
      public static Type valueOf(int value) {
        switch (value) {
          case 0: return Camera;
          case 1: return Server;
          case 2: return User;
          case 3: return Layout;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Type[] VALUES = {
        Camera, Server, User, Layout, 
      };
      
      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:pb.Resource.Type)
    }
    
    public enum Status
        implements com.google.protobuf.ProtocolMessageEnum {
      Offline(0, 0),
      Unauthorized(1, 1),
      Online(2, 2),
      Recording(3, 3),
      ;
      
      public static final int Offline_VALUE = 0;
      public static final int Unauthorized_VALUE = 1;
      public static final int Online_VALUE = 2;
      public static final int Recording_VALUE = 3;
      
      
      public final int getNumber() { return value; }
      
      public static Status valueOf(int value) {
        switch (value) {
          case 0: return Offline;
          case 1: return Unauthorized;
          case 2: return Online;
          case 3: return Recording;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Status>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Status>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Status>() {
              public Status findValueByNumber(int number) {
                return Status.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.getDescriptor().getEnumTypes().get(1);
      }
      
      private static final Status[] VALUES = {
        Offline, Unauthorized, Online, Recording, 
      };
      
      public static Status valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Status(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:pb.Resource.Status)
    }
    
    public interface PropertyOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // required string name = 1;
      boolean hasName();
      String getName();
      
      // required string value = 2;
      boolean hasValue();
      String getValue();
      
      // optional int32 id = 3;
      boolean hasId();
      int getId();
    }
    public static final class Property extends
        com.google.protobuf.GeneratedMessage
        implements PropertyOrBuilder {
      // Use Property.newBuilder() to construct.
      private Property(Builder builder) {
        super(builder);
      }
      private Property(boolean noInit) {}
      
      private static final Property defaultInstance;
      public static Property getDefaultInstance() {
        return defaultInstance;
      }
      
      public Property getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.networkoptix.hdwitness.protobuf.ResourceProtos.internal_static_pb_Resource_Property_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.networkoptix.hdwitness.protobuf.ResourceProtos.internal_static_pb_Resource_Property_fieldAccessorTable;
      }
      
      private int bitField0_;
      // required string name = 1;
      public static final int NAME_FIELD_NUMBER = 1;
      private java.lang.Object name_;
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            name_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      // required string value = 2;
      public static final int VALUE_FIELD_NUMBER = 2;
      private java.lang.Object value_;
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getValue() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            value_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      // optional int32 id = 3;
      public static final int ID_FIELD_NUMBER = 3;
      private int id_;
      public boolean hasId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getId() {
        return id_;
      }
      
      private void initFields() {
        name_ = "";
        value_ = "";
        id_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        if (!hasName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasValue()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getValueBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeInt32(3, id_);
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getValueBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, id_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.PropertyOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.networkoptix.hdwitness.protobuf.ResourceProtos.internal_static_pb_Resource_Property_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.networkoptix.hdwitness.protobuf.ResourceProtos.internal_static_pb_Resource_Property_fieldAccessorTable;
        }
        
        // Construct using com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          name_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          value_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          id_ = 0;
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property.getDescriptor();
        }
        
        public com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property getDefaultInstanceForType() {
          return com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property.getDefaultInstance();
        }
        
        public com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property build() {
          com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property buildPartial() {
          com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property result = new com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.name_ = name_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.value_ = value_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.id_ = id_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property) {
            return mergeFrom((com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property other) {
          if (other == com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property.getDefaultInstance()) return this;
          if (other.hasName()) {
            setName(other.getName());
          }
          if (other.hasValue()) {
            setValue(other.getValue());
          }
          if (other.hasId()) {
            setId(other.getId());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          if (!hasName()) {
            
            return false;
          }
          if (!hasValue()) {
            
            return false;
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                name_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                value_ = input.readBytes();
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                id_ = input.readInt32();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // required string name = 1;
        private java.lang.Object name_ = "";
        public boolean hasName() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setName(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
          return this;
        }
        public Builder clearName() {
          bitField0_ = (bitField0_ & ~0x00000001);
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        void setName(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
        }
        
        // required string value = 2;
        private java.lang.Object value_ = "";
        public boolean hasValue() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public String getValue() {
          java.lang.Object ref = value_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            value_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setValue(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
          return this;
        }
        public Builder clearValue() {
          bitField0_ = (bitField0_ & ~0x00000002);
          value_ = getDefaultInstance().getValue();
          onChanged();
          return this;
        }
        void setValue(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
        }
        
        // optional int32 id = 3;
        private int id_ ;
        public boolean hasId() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        public int getId() {
          return id_;
        }
        public Builder setId(int value) {
          bitField0_ |= 0x00000004;
          id_ = value;
          onChanged();
          return this;
        }
        public Builder clearId() {
          bitField0_ = (bitField0_ & ~0x00000004);
          id_ = 0;
          onChanged();
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:pb.Resource.Property)
      }
      
      static {
        defaultInstance = new Property(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:pb.Resource.Property)
    }
    
    private int bitField0_;
    // required .pb.Resource.Type type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Type type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Type getType() {
      return type_;
    }
    
    // optional int32 id = 2;
    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getId() {
      return id_;
    }
    
    // optional int32 typeId = 3;
    public static final int TYPEID_FIELD_NUMBER = 3;
    private int typeId_;
    public boolean hasTypeId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getTypeId() {
      return typeId_;
    }
    
    // optional int32 parentId = 4;
    public static final int PARENTID_FIELD_NUMBER = 4;
    private int parentId_;
    public boolean hasParentId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getParentId() {
      return parentId_;
    }
    
    // optional string name = 5;
    public static final int NAME_FIELD_NUMBER = 5;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string url = 6;
    public static final int URL_FIELD_NUMBER = 6;
    private java.lang.Object url_;
    public boolean hasUrl() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          url_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional .pb.Resource.Status status = 7;
    public static final int STATUS_FIELD_NUMBER = 7;
    private com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Status status_;
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Status getStatus() {
      return status_;
    }
    
    // optional bool disabled = 8;
    public static final int DISABLED_FIELD_NUMBER = 8;
    private boolean disabled_;
    public boolean hasDisabled() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public boolean getDisabled() {
      return disabled_;
    }
    
    // optional string guid = 9;
    public static final int GUID_FIELD_NUMBER = 9;
    private java.lang.Object guid_;
    public boolean hasGuid() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public String getGuid() {
      java.lang.Object ref = guid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          guid_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getGuidBytes() {
      java.lang.Object ref = guid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        guid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .pb.Resource.Property property = 10;
    public static final int PROPERTY_FIELD_NUMBER = 10;
    private java.util.List<com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property> property_;
    public java.util.List<com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property> getPropertyList() {
      return property_;
    }
    public java.util.List<? extends com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.PropertyOrBuilder> 
        getPropertyOrBuilderList() {
      return property_;
    }
    public int getPropertyCount() {
      return property_.size();
    }
    public com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property getProperty(int index) {
      return property_.get(index);
    }
    public com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.PropertyOrBuilder getPropertyOrBuilder(
        int index) {
      return property_.get(index);
    }
    
    private void initFields() {
      type_ = com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Type.Camera;
      id_ = 0;
      typeId_ = 0;
      parentId_ = 0;
      name_ = "";
      url_ = "";
      status_ = com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Status.Offline;
      disabled_ = false;
      guid_ = "";
      property_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPropertyCount(); i++) {
        if (!getProperty(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessage
        .ExtendableMessage<com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource>.ExtensionWriter extensionWriter =
          newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, typeId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, parentId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getNameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getUrlBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeEnum(7, status_.getNumber());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBool(8, disabled_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getGuidBytes());
      }
      for (int i = 0; i < property_.size(); i++) {
        output.writeMessage(10, property_.get(i));
      }
      extensionWriter.writeUntil(536870912, output);
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, typeId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, parentId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getNameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getUrlBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, status_.getNumber());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, disabled_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getGuidBytes());
      }
      for (int i = 0; i < property_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, property_.get(i));
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource, Builder> implements com.networkoptix.hdwitness.protobuf.ResourceProtos.ResourceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.networkoptix.hdwitness.protobuf.ResourceProtos.internal_static_pb_Resource_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.networkoptix.hdwitness.protobuf.ResourceProtos.internal_static_pb_Resource_fieldAccessorTable;
      }
      
      // Construct using com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPropertyFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Type.Camera;
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        typeId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        parentId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        url_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        status_ = com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Status.Offline;
        bitField0_ = (bitField0_ & ~0x00000040);
        disabled_ = false;
        bitField0_ = (bitField0_ & ~0x00000080);
        guid_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        if (propertyBuilder_ == null) {
          property_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000200);
        } else {
          propertyBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.getDescriptor();
      }
      
      public com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource getDefaultInstanceForType() {
        return com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.getDefaultInstance();
      }
      
      public com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource build() {
        com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource buildPartial() {
        com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource result = new com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.typeId_ = typeId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.parentId_ = parentId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.url_ = url_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.disabled_ = disabled_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.guid_ = guid_;
        if (propertyBuilder_ == null) {
          if (((bitField0_ & 0x00000200) == 0x00000200)) {
            property_ = java.util.Collections.unmodifiableList(property_);
            bitField0_ = (bitField0_ & ~0x00000200);
          }
          result.property_ = property_;
        } else {
          result.property_ = propertyBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource) {
          return mergeFrom((com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource other) {
        if (other == com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasTypeId()) {
          setTypeId(other.getTypeId());
        }
        if (other.hasParentId()) {
          setParentId(other.getParentId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasUrl()) {
          setUrl(other.getUrl());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasDisabled()) {
          setDisabled(other.getDisabled());
        }
        if (other.hasGuid()) {
          setGuid(other.getGuid());
        }
        if (propertyBuilder_ == null) {
          if (!other.property_.isEmpty()) {
            if (property_.isEmpty()) {
              property_ = other.property_;
              bitField0_ = (bitField0_ & ~0x00000200);
            } else {
              ensurePropertyIsMutable();
              property_.addAll(other.property_);
            }
            onChanged();
          }
        } else {
          if (!other.property_.isEmpty()) {
            if (propertyBuilder_.isEmpty()) {
              propertyBuilder_.dispose();
              propertyBuilder_ = null;
              property_ = other.property_;
              bitField0_ = (bitField0_ & ~0x00000200);
              propertyBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPropertyFieldBuilder() : null;
            } else {
              propertyBuilder_.addAllMessages(other.property_);
            }
          }
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        for (int i = 0; i < getPropertyCount(); i++) {
          if (!getProperty(i).isInitialized()) {
            
            return false;
          }
        }
        if (!extensionsAreInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Type value = com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              typeId_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              parentId_ = input.readInt32();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              name_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              url_ = input.readBytes();
              break;
            }
            case 56: {
              int rawValue = input.readEnum();
              com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Status value = com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Status.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(7, rawValue);
              } else {
                bitField0_ |= 0x00000040;
                status_ = value;
              }
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              disabled_ = input.readBool();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              guid_ = input.readBytes();
              break;
            }
            case 82: {
              com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property.Builder subBuilder = com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addProperty(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .pb.Resource.Type type = 1;
      private com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Type type_ = com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Type.Camera;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Type getType() {
        return type_;
      }
      public Builder setType(com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Type.Camera;
        onChanged();
        return this;
      }
      
      // optional int32 id = 2;
      private int id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getId() {
        return id_;
      }
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 typeId = 3;
      private int typeId_ ;
      public boolean hasTypeId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getTypeId() {
        return typeId_;
      }
      public Builder setTypeId(int value) {
        bitField0_ |= 0x00000004;
        typeId_ = value;
        onChanged();
        return this;
      }
      public Builder clearTypeId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        typeId_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 parentId = 4;
      private int parentId_ ;
      public boolean hasParentId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getParentId() {
        return parentId_;
      }
      public Builder setParentId(int value) {
        bitField0_ |= 0x00000008;
        parentId_ = value;
        onChanged();
        return this;
      }
      public Builder clearParentId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        parentId_ = 0;
        onChanged();
        return this;
      }
      
      // optional string name = 5;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000010);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        name_ = value;
        onChanged();
      }
      
      // optional string url = 6;
      private java.lang.Object url_ = "";
      public boolean hasUrl() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUrl(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        url_ = value;
        onChanged();
        return this;
      }
      public Builder clearUrl() {
        bitField0_ = (bitField0_ & ~0x00000020);
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      void setUrl(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        url_ = value;
        onChanged();
      }
      
      // optional .pb.Resource.Status status = 7;
      private com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Status status_ = com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Status.Offline;
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Status getStatus() {
        return status_;
      }
      public Builder setStatus(com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Status value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000040;
        status_ = value;
        onChanged();
        return this;
      }
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000040);
        status_ = com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Status.Offline;
        onChanged();
        return this;
      }
      
      // optional bool disabled = 8;
      private boolean disabled_ ;
      public boolean hasDisabled() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public boolean getDisabled() {
        return disabled_;
      }
      public Builder setDisabled(boolean value) {
        bitField0_ |= 0x00000080;
        disabled_ = value;
        onChanged();
        return this;
      }
      public Builder clearDisabled() {
        bitField0_ = (bitField0_ & ~0x00000080);
        disabled_ = false;
        onChanged();
        return this;
      }
      
      // optional string guid = 9;
      private java.lang.Object guid_ = "";
      public boolean hasGuid() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public String getGuid() {
        java.lang.Object ref = guid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          guid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setGuid(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        guid_ = value;
        onChanged();
        return this;
      }
      public Builder clearGuid() {
        bitField0_ = (bitField0_ & ~0x00000100);
        guid_ = getDefaultInstance().getGuid();
        onChanged();
        return this;
      }
      void setGuid(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000100;
        guid_ = value;
        onChanged();
      }
      
      // repeated .pb.Resource.Property property = 10;
      private java.util.List<com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property> property_ =
        java.util.Collections.emptyList();
      private void ensurePropertyIsMutable() {
        if (!((bitField0_ & 0x00000200) == 0x00000200)) {
          property_ = new java.util.ArrayList<com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property>(property_);
          bitField0_ |= 0x00000200;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property, com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property.Builder, com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.PropertyOrBuilder> propertyBuilder_;
      
      public java.util.List<com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property> getPropertyList() {
        if (propertyBuilder_ == null) {
          return java.util.Collections.unmodifiableList(property_);
        } else {
          return propertyBuilder_.getMessageList();
        }
      }
      public int getPropertyCount() {
        if (propertyBuilder_ == null) {
          return property_.size();
        } else {
          return propertyBuilder_.getCount();
        }
      }
      public com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property getProperty(int index) {
        if (propertyBuilder_ == null) {
          return property_.get(index);
        } else {
          return propertyBuilder_.getMessage(index);
        }
      }
      public Builder setProperty(
          int index, com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property value) {
        if (propertyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropertyIsMutable();
          property_.set(index, value);
          onChanged();
        } else {
          propertyBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setProperty(
          int index, com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property.Builder builderForValue) {
        if (propertyBuilder_ == null) {
          ensurePropertyIsMutable();
          property_.set(index, builderForValue.build());
          onChanged();
        } else {
          propertyBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addProperty(com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property value) {
        if (propertyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropertyIsMutable();
          property_.add(value);
          onChanged();
        } else {
          propertyBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addProperty(
          int index, com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property value) {
        if (propertyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropertyIsMutable();
          property_.add(index, value);
          onChanged();
        } else {
          propertyBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addProperty(
          com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property.Builder builderForValue) {
        if (propertyBuilder_ == null) {
          ensurePropertyIsMutable();
          property_.add(builderForValue.build());
          onChanged();
        } else {
          propertyBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addProperty(
          int index, com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property.Builder builderForValue) {
        if (propertyBuilder_ == null) {
          ensurePropertyIsMutable();
          property_.add(index, builderForValue.build());
          onChanged();
        } else {
          propertyBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllProperty(
          java.lang.Iterable<? extends com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property> values) {
        if (propertyBuilder_ == null) {
          ensurePropertyIsMutable();
          super.addAll(values, property_);
          onChanged();
        } else {
          propertyBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearProperty() {
        if (propertyBuilder_ == null) {
          property_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000200);
          onChanged();
        } else {
          propertyBuilder_.clear();
        }
        return this;
      }
      public Builder removeProperty(int index) {
        if (propertyBuilder_ == null) {
          ensurePropertyIsMutable();
          property_.remove(index);
          onChanged();
        } else {
          propertyBuilder_.remove(index);
        }
        return this;
      }
      public com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property.Builder getPropertyBuilder(
          int index) {
        return getPropertyFieldBuilder().getBuilder(index);
      }
      public com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.PropertyOrBuilder getPropertyOrBuilder(
          int index) {
        if (propertyBuilder_ == null) {
          return property_.get(index);  } else {
          return propertyBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.PropertyOrBuilder> 
           getPropertyOrBuilderList() {
        if (propertyBuilder_ != null) {
          return propertyBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(property_);
        }
      }
      public com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property.Builder addPropertyBuilder() {
        return getPropertyFieldBuilder().addBuilder(
            com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property.getDefaultInstance());
      }
      public com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property.Builder addPropertyBuilder(
          int index) {
        return getPropertyFieldBuilder().addBuilder(
            index, com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property.getDefaultInstance());
      }
      public java.util.List<com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property.Builder> 
           getPropertyBuilderList() {
        return getPropertyFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property, com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property.Builder, com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.PropertyOrBuilder> 
          getPropertyFieldBuilder() {
        if (propertyBuilder_ == null) {
          propertyBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property, com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property.Builder, com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.PropertyOrBuilder>(
                  property_,
                  ((bitField0_ & 0x00000200) == 0x00000200),
                  getParentForChildren(),
                  isClean());
          property_ = null;
        }
        return propertyBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:pb.Resource)
    }
    
    static {
      defaultInstance = new Resource(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:pb.Resource)
  }
  
  public interface ResourcesOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .pb.Resource resource = 1;
    java.util.List<com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource> 
        getResourceList();
    com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource getResource(int index);
    int getResourceCount();
    java.util.List<? extends com.networkoptix.hdwitness.protobuf.ResourceProtos.ResourceOrBuilder> 
        getResourceOrBuilderList();
    com.networkoptix.hdwitness.protobuf.ResourceProtos.ResourceOrBuilder getResourceOrBuilder(
        int index);
  }
  public static final class Resources extends
      com.google.protobuf.GeneratedMessage
      implements ResourcesOrBuilder {
    // Use Resources.newBuilder() to construct.
    private Resources(Builder builder) {
      super(builder);
    }
    private Resources(boolean noInit) {}
    
    private static final Resources defaultInstance;
    public static Resources getDefaultInstance() {
      return defaultInstance;
    }
    
    public Resources getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.networkoptix.hdwitness.protobuf.ResourceProtos.internal_static_pb_Resources_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.networkoptix.hdwitness.protobuf.ResourceProtos.internal_static_pb_Resources_fieldAccessorTable;
    }
    
    // repeated .pb.Resource resource = 1;
    public static final int RESOURCE_FIELD_NUMBER = 1;
    private java.util.List<com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource> resource_;
    public java.util.List<com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource> getResourceList() {
      return resource_;
    }
    public java.util.List<? extends com.networkoptix.hdwitness.protobuf.ResourceProtos.ResourceOrBuilder> 
        getResourceOrBuilderList() {
      return resource_;
    }
    public int getResourceCount() {
      return resource_.size();
    }
    public com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource getResource(int index) {
      return resource_.get(index);
    }
    public com.networkoptix.hdwitness.protobuf.ResourceProtos.ResourceOrBuilder getResourceOrBuilder(
        int index) {
      return resource_.get(index);
    }
    
    private void initFields() {
      resource_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getResourceCount(); i++) {
        if (!getResource(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < resource_.size(); i++) {
        output.writeMessage(1, resource_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < resource_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, resource_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.networkoptix.hdwitness.protobuf.ResourceProtos.Resources parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.networkoptix.hdwitness.protobuf.ResourceProtos.Resources parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.networkoptix.hdwitness.protobuf.ResourceProtos.Resources parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.networkoptix.hdwitness.protobuf.ResourceProtos.Resources parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.networkoptix.hdwitness.protobuf.ResourceProtos.Resources parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.networkoptix.hdwitness.protobuf.ResourceProtos.Resources parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.networkoptix.hdwitness.protobuf.ResourceProtos.Resources parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.networkoptix.hdwitness.protobuf.ResourceProtos.Resources parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.networkoptix.hdwitness.protobuf.ResourceProtos.Resources parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.networkoptix.hdwitness.protobuf.ResourceProtos.Resources parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.networkoptix.hdwitness.protobuf.ResourceProtos.Resources prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.networkoptix.hdwitness.protobuf.ResourceProtos.ResourcesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.networkoptix.hdwitness.protobuf.ResourceProtos.internal_static_pb_Resources_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.networkoptix.hdwitness.protobuf.ResourceProtos.internal_static_pb_Resources_fieldAccessorTable;
      }
      
      // Construct using com.networkoptix.hdwitness.protobuf.ResourceProtos.Resources.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getResourceFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (resourceBuilder_ == null) {
          resource_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          resourceBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.networkoptix.hdwitness.protobuf.ResourceProtos.Resources.getDescriptor();
      }
      
      public com.networkoptix.hdwitness.protobuf.ResourceProtos.Resources getDefaultInstanceForType() {
        return com.networkoptix.hdwitness.protobuf.ResourceProtos.Resources.getDefaultInstance();
      }
      
      public com.networkoptix.hdwitness.protobuf.ResourceProtos.Resources build() {
        com.networkoptix.hdwitness.protobuf.ResourceProtos.Resources result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.networkoptix.hdwitness.protobuf.ResourceProtos.Resources buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.networkoptix.hdwitness.protobuf.ResourceProtos.Resources result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.networkoptix.hdwitness.protobuf.ResourceProtos.Resources buildPartial() {
        com.networkoptix.hdwitness.protobuf.ResourceProtos.Resources result = new com.networkoptix.hdwitness.protobuf.ResourceProtos.Resources(this);
        int from_bitField0_ = bitField0_;
        if (resourceBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            resource_ = java.util.Collections.unmodifiableList(resource_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.resource_ = resource_;
        } else {
          result.resource_ = resourceBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.networkoptix.hdwitness.protobuf.ResourceProtos.Resources) {
          return mergeFrom((com.networkoptix.hdwitness.protobuf.ResourceProtos.Resources)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.networkoptix.hdwitness.protobuf.ResourceProtos.Resources other) {
        if (other == com.networkoptix.hdwitness.protobuf.ResourceProtos.Resources.getDefaultInstance()) return this;
        if (resourceBuilder_ == null) {
          if (!other.resource_.isEmpty()) {
            if (resource_.isEmpty()) {
              resource_ = other.resource_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureResourceIsMutable();
              resource_.addAll(other.resource_);
            }
            onChanged();
          }
        } else {
          if (!other.resource_.isEmpty()) {
            if (resourceBuilder_.isEmpty()) {
              resourceBuilder_.dispose();
              resourceBuilder_ = null;
              resource_ = other.resource_;
              bitField0_ = (bitField0_ & ~0x00000001);
              resourceBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getResourceFieldBuilder() : null;
            } else {
              resourceBuilder_.addAllMessages(other.resource_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getResourceCount(); i++) {
          if (!getResource(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Builder subBuilder = com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addResource(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .pb.Resource resource = 1;
      private java.util.List<com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource> resource_ =
        java.util.Collections.emptyList();
      private void ensureResourceIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          resource_ = new java.util.ArrayList<com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource>(resource_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource, com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Builder, com.networkoptix.hdwitness.protobuf.ResourceProtos.ResourceOrBuilder> resourceBuilder_;
      
      public java.util.List<com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource> getResourceList() {
        if (resourceBuilder_ == null) {
          return java.util.Collections.unmodifiableList(resource_);
        } else {
          return resourceBuilder_.getMessageList();
        }
      }
      public int getResourceCount() {
        if (resourceBuilder_ == null) {
          return resource_.size();
        } else {
          return resourceBuilder_.getCount();
        }
      }
      public com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource getResource(int index) {
        if (resourceBuilder_ == null) {
          return resource_.get(index);
        } else {
          return resourceBuilder_.getMessage(index);
        }
      }
      public Builder setResource(
          int index, com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource value) {
        if (resourceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResourceIsMutable();
          resource_.set(index, value);
          onChanged();
        } else {
          resourceBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setResource(
          int index, com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Builder builderForValue) {
        if (resourceBuilder_ == null) {
          ensureResourceIsMutable();
          resource_.set(index, builderForValue.build());
          onChanged();
        } else {
          resourceBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addResource(com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource value) {
        if (resourceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResourceIsMutable();
          resource_.add(value);
          onChanged();
        } else {
          resourceBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addResource(
          int index, com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource value) {
        if (resourceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResourceIsMutable();
          resource_.add(index, value);
          onChanged();
        } else {
          resourceBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addResource(
          com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Builder builderForValue) {
        if (resourceBuilder_ == null) {
          ensureResourceIsMutable();
          resource_.add(builderForValue.build());
          onChanged();
        } else {
          resourceBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addResource(
          int index, com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Builder builderForValue) {
        if (resourceBuilder_ == null) {
          ensureResourceIsMutable();
          resource_.add(index, builderForValue.build());
          onChanged();
        } else {
          resourceBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllResource(
          java.lang.Iterable<? extends com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource> values) {
        if (resourceBuilder_ == null) {
          ensureResourceIsMutable();
          super.addAll(values, resource_);
          onChanged();
        } else {
          resourceBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearResource() {
        if (resourceBuilder_ == null) {
          resource_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          resourceBuilder_.clear();
        }
        return this;
      }
      public Builder removeResource(int index) {
        if (resourceBuilder_ == null) {
          ensureResourceIsMutable();
          resource_.remove(index);
          onChanged();
        } else {
          resourceBuilder_.remove(index);
        }
        return this;
      }
      public com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Builder getResourceBuilder(
          int index) {
        return getResourceFieldBuilder().getBuilder(index);
      }
      public com.networkoptix.hdwitness.protobuf.ResourceProtos.ResourceOrBuilder getResourceOrBuilder(
          int index) {
        if (resourceBuilder_ == null) {
          return resource_.get(index);  } else {
          return resourceBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.networkoptix.hdwitness.protobuf.ResourceProtos.ResourceOrBuilder> 
           getResourceOrBuilderList() {
        if (resourceBuilder_ != null) {
          return resourceBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(resource_);
        }
      }
      public com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Builder addResourceBuilder() {
        return getResourceFieldBuilder().addBuilder(
            com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.getDefaultInstance());
      }
      public com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Builder addResourceBuilder(
          int index) {
        return getResourceFieldBuilder().addBuilder(
            index, com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.getDefaultInstance());
      }
      public java.util.List<com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Builder> 
           getResourceBuilderList() {
        return getResourceFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource, com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Builder, com.networkoptix.hdwitness.protobuf.ResourceProtos.ResourceOrBuilder> 
          getResourceFieldBuilder() {
        if (resourceBuilder_ == null) {
          resourceBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource, com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Builder, com.networkoptix.hdwitness.protobuf.ResourceProtos.ResourceOrBuilder>(
                  resource_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          resource_ = null;
        }
        return resourceBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:pb.Resources)
    }
    
    static {
      defaultInstance = new Resources(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:pb.Resources)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_Resource_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pb_Resource_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_Resource_Property_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pb_Resource_Property_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_Resources_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pb_Resources_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016resource.proto\022\002pb\"\233\003\n\010Resource\022\037\n\004typ" +
      "e\030\001 \002(\0162\021.pb.Resource.Type\022\n\n\002id\030\002 \001(\005\022\016" +
      "\n\006typeId\030\003 \001(\005\022\020\n\010parentId\030\004 \001(\005\022\014\n\004name" +
      "\030\005 \001(\t\022\013\n\003url\030\006 \001(\t\022#\n\006status\030\007 \001(\0162\023.pb" +
      ".Resource.Status\022\020\n\010disabled\030\010 \001(\010\022\014\n\004gu" +
      "id\030\t \001(\t\022\'\n\010property\030\n \003(\0132\025.pb.Resource" +
      ".Property\0323\n\010Property\022\014\n\004name\030\001 \002(\t\022\r\n\005v" +
      "alue\030\002 \002(\t\022\n\n\002id\030\003 \001(\005\"4\n\004Type\022\n\n\006Camera" +
      "\020\000\022\n\n\006Server\020\001\022\010\n\004User\020\002\022\n\n\006Layout\020\003\"B\n\006" +
      "Status\022\013\n\007Offline\020\000\022\020\n\014Unauthorized\020\001\022\n\n",
      "\006Online\020\002\022\r\n\tRecording\020\003*\010\010d\020\200\200\200\200\002\"+\n\tRe" +
      "sources\022\036\n\010resource\030\001 \003(\0132\014.pb.ResourceB" +
      "5\n#com.networkoptix.hdwitness.protobufB\016" +
      "ResourceProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_pb_Resource_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_pb_Resource_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_pb_Resource_descriptor,
              new java.lang.String[] { "Type", "Id", "TypeId", "ParentId", "Name", "Url", "Status", "Disabled", "Guid", "Property", },
              com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.class,
              com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Builder.class);
          internal_static_pb_Resource_Property_descriptor =
            internal_static_pb_Resource_descriptor.getNestedTypes().get(0);
          internal_static_pb_Resource_Property_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_pb_Resource_Property_descriptor,
              new java.lang.String[] { "Name", "Value", "Id", },
              com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property.class,
              com.networkoptix.hdwitness.protobuf.ResourceProtos.Resource.Property.Builder.class);
          internal_static_pb_Resources_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_pb_Resources_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_pb_Resources_descriptor,
              new java.lang.String[] { "Resource", },
              com.networkoptix.hdwitness.protobuf.ResourceProtos.Resources.class,
              com.networkoptix.hdwitness.protobuf.ResourceProtos.Resources.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
