#!/bin/bash

# VERSION: ${release.version}.${buildNumber}

## This command will run each time after networkoptix-embedded-tools is installed

export CUSTOMIZATION=${deb.customization.company.name}
export DATAPART=/dev/mmcblk0p2
export MNTDATAPART=/mnt/data
export BOOTPART=/dev/mmcblk0p1
export MNTBOOTPART=/mnt/boot

mkdir -p $MNTBOOTPART
mount -t vfat $BOOTPART $MNTBOOTPART
cp -f /root/tools/uboot/* $MNTBOOTPART
umount $BOOTPART
rm -Rf $MNTBOOTPART
export DEBIAN_FRONTEND=noninteractive
dpkg -i /opt/deb/libvdpau/*.deb

cp /etc/apt/sources.list /etc/apt/sources.list_bk
echo "deb file:/opt/deb/libc6 /" > /etc/apt/sources.list
apt-get update
apt-get install libc-l10n libc6-armhf-cross libc-bin libc-dev-bin libc6 libc6-dbg libc6-dev locales -y -qq --force-yes
mv /etc/apt/sources.list_bk /etc/apt/sources.list
touch /dev/cedar_dev
chmod 777 /dev/disp
chmod 777 /dev/cedar_dev
usermod -aG video root
rm -Rf /opt/networkoptix/mediaserver/lib

mkdir -p $MNTDATAPART
mount -t ext4 $DATAPART $MNTDATAPART
cp -f /opt/$CUSTOMIZATION/mediaserver/var/ecs_static.sqlite /root/tools/nx/ecs_static.sqlite
rm -Rf $MNTDATAPART/opt/$CUSTOMIZATION
tar xfv /tmp/$DISTRIB.tar.gz -C $MNTDATAPART
mkdir -p $MNTDATAPART/opt/$CUSTOMIZATION/mediaserver/var
cp -f /root/tools/nx/ecs_static.sqlite $MNTDATAPART/opt/$CUSTOMIZATION/mediaserver/var
echo "statisticsReportAllowed=true" >> $MNTDATAPART/opt/$CUSTOMIZATION/mediaserver/etc/mediaserver.conf
umount $DATAPART
sync

exit 0