#!/bin/bash

# VERSION: ${release.version}.${buildNumber}

## This command will run each time after networkoptix-embedded-tools is installed

export CUSTOMIZATION=${deb.customization.company.name}
export DATAPART=/dev/mmcblk0p2
export MNTDATAPART=/mnt/data
export BOOTPART=/dev/mmcblk0p1
export MNTBOOTPART=/mnt/boot

mkdir -p $MNTBOOTPART
mount -t vfat $BOOTPART $MNTBOOTPART
cp -f /root/tools/uboot/* $MNTBOOTPART
umount $BOOTPART
rm -Rf $MNTBOOTPART
apt-get update
export DEBIAN_FRONTEND=noninteractive
dpkg -i /opt/deb/libvdpau/*.deb
cp -f /opt/deb/libc6/*.deb /var/cache/apt/archives
apt-get -d -t experimental install libc-l10n libc6-armhf-cross libc-bin libc-dev-bin libc6 libc6-dbg libc6-dev locales
apt-get -t experimental install libc-l10n libc6-armhf-cross libc-bin libc-dev-bin libc6 libc6-dbg libc6-dev locales -y -qq
touch /dev/cedar_dev
chmod 777 /dev/disp
chmod 777 /dev/cedar_dev
usermod -aG video root
rm -Rf /opt/networkoptix/mediaserver/lib
sync

exit 0