#ifndef IP1829_H
#define IP1829_H

#include "../include/portnumber.h"

#if 1	/* BSP_MODI */
#define SET_NETWORK_LOOP_DETECTION_BLOCK	0x01
#define GET_NETWORK_LOOP_STATUS				0x02
#define GET_PORT_LINK_STATUS					0x03
#define GET_PORT_MAC_ADDR						0x04
#define SET_PORT_STATUS						0x05
#define SET_NETWORK_LOOP_DETECTION_NOBLOCK	0x06
typedef enum
{
	GT_PORT_DISABLE = 0,
	GT_PORT_BLOCKING,
	GT_PORT_LEARNING,
	GT_PORT_FORWARDING
}PORT_STATUS;

struct LinkStatus
{
    int port;
    unsigned int link;
};
struct LoopStatus
{
	int port;
	int status;
};
struct PortMacAddr
{
	int index;
	int block;
	int port;
	unsigned char mac[6];
};
#endif

/*===================================================================*/
/* max number of fid */
#define	MAX_FID_NUM		16
/* max LUT table block number */
#define	MAX_BLOCK_NUM	2
/* max LUT table entry number */
#define MAX_LUT_ENTRY_NUM	8192
#define MAX_IMP_ENTRY_NUM	128
/* LUT table aging time unit(second) */
#define	AGING_TIME_UNIT	55
/* max PVID number */
#define MAX_PVID_NUM	4096
/* mac Protocol Based VLAN entry number */
#define MAX_PRO_VLAN_ENTRY_NUM	4
/* max link speed of TP port */
#define MAX_TP_SPEED 100000000
/* max link speed of Giga port */
#define MAX_GIGA_SPEED 1000000000
/*===================================================================*/
#define TYPECHECK(t)		(sizeof(t))

#define _CMDID_NRBITS		8
#define _CMDID_SUBGBITS		4
#define _CMDID_RSVD1BITS	4
#define _CMDID_GRPBITS		8
#define _CMDID_USGBITS		4

#define _CMDID_NRMASK		((1 << _CMDID_NRBITS)-1)
#define _CMDID_SUBGMASK		((1 << _CMDID_SUBGBITS)-1)
#define _CMDID_GRPMASK		((1 << _CMDID_GRPBITS)-1)
#define _CMDID_USGMASK		((1 << _CMDID_USGBITS)-1)

#define _CMDID_NRSHIFT		0
#define _CMDID_SUBGSHIFT	(_CMDID_NRSHIFT+_CMDID_NRBITS)
#define _CMDID_GRPSHIFT		(_CMDID_SUBGSHIFT+_CMDID_SUBGBITS+_CMDID_RSVD1BITS)
#define _CMDID_USGSHIFT		(_CMDID_GRPSHIFT+_CMDID_GRPBITS)

#define MAKECMDID(usg, grp, subg, nr)	( (usg << _CMDID_USGSHIFT) | (grp << _CMDID_GRPSHIFT) | \
					(subg << _CMDID_SUBGSHIFT) | (nr << _CMDID_NRSHIFT) )

#define _CMDID_USG_COMMON	0x0
#define _CMDID_USG_IP1829	0x1
#define _CMDID_USG_DBS		0x2
#define NUM_CMDID_USG		0x3

/*===================================================================*/
#define _CMDID_GRP_BASIC	0x01

/*-------------------------------------------------------------------*/
#define _CMDID_SUBG_SMI		0x1
#define ID_COMMON_SET_PORT_AN \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_SMI, 0)
#define ID_COMMON_GET_PORT_AN \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_SMI, 1)
#define ID_COMMON_SET_PORT_SPEED \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_SMI, 2)
#define ID_COMMON_GET_PORT_SPEED \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_SMI, 3)
#define ID_COMMON_SET_PORT_DUPLEX \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_SMI, 4)
#define ID_COMMON_GET_PORT_DUPLEX \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_SMI, 5)
#define ID_COMMON_SET_PORT_PAUSE \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_SMI, 6)
#define ID_COMMON_GET_PORT_PAUSE \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_SMI, 7)
#define ID_COMMON_SET_PORT_ASYM_PAUSE \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_SMI, 8)
#define ID_COMMON_GET_PORT_ASYM_PAUSE \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_SMI, 9)
#define ID_COMMON_SET_PORT_LINK_STATUS \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_SMI, 10)
#define ID_COMMON_GET_PORT_LINK_STATUS \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_SMI, 11)
#define ID_COMMON_SET_PORT_BACKPRESSURE \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_SMI, 12)
#define ID_COMMON_GET_PORT_BACKPRESSURE \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_SMI, 13)
#define ID_COMMON_SET_PORT_POWER_DOWN \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_SMI, 14)
#define ID_COMMON_GET_PORT_POWER_DOWN \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_SMI, 15)
#define ID_COMMON_SET_PORT_FORCE_LINK \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_SMI, 16)
#define ID_COMMON_GET_PORT_FORCE_LINK \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_SMI, 17)
#define ID_COMMON_SET_PORT_UNI_DIRECTION \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_SMI, 18)
#define ID_COMMON_GET_PORT_UNI_DIRECTION \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_SMI, 19)
#define ID_COMMON_SET_MDIO_DIV \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_SMI, 20)


/*-------------------------------------------------------------------*/
#define _CMDID_SUBG_CAP		0x2
enum{
	IDX_COMMON_L2_SET_CAP_ACT,		//0
	IDX_COMMON_L2_GET_CAP_ACT,
	IDX_COMMON_CAP_SET_IN_BAND,
	IDX_COMMON_CAP_GET_IN_BAND,
	IDX_COMMON_CAP_SET_IN_BAND_RESTRICT,
	IDX_COMMON_CAP_GET_IN_BAND_RESTRICT,
	IDX_COMMON_CAP_SET_IN_BAND_RESTRICT_CONFIG,
	IDX_COMMON_CAP_GET_IN_BAND_RESTRICT_CONFIG,
	IDX_COMMON_CAP_SET_SWITCH_MAC,
	IDX_COMMON_CAP_GET_SWITCH_MAC,
	IDX_COMMON_CAP_SET_L3_ACT,		//10
	IDX_COMMON_CAP_GET_L3_ACT,
	IDX_COMMON_CAP_SET_L3_USER,
	IDX_COMMON_CAP_GET_L3_USER,
	IDX_COMMON_CAP_SET_ETHER_USER,
	IDX_COMMON_CAP_GET_ETHER_USER,
	IDX_COMMON_CAP_SET_IPV6_TCPUDP_ENABLE,
	IDX_COMMON_CAP_GET_IPV6_TCPUDP_ENABLE,
	IDX_COMMON_CAP_SET_IPV6_TCPUDP_FLAG_ENABLE,
	IDX_COMMON_CAP_GET_IPV6_TCPUDP_FLAG_ENABLE,
	IDX_COMMON_CAP_SET_IPV6_STOP_FINDING,	//20
	IDX_COMMON_CAP_GET_IPV6_STOP_FINDING,
	IDX_COMMON_CAP_SET_IPV6_TO_ALL_PORTS_HIGHER,
	IDX_COMMON_CAP_GET_IPV6_TO_ALL_PORTS_HIGHER,
	IDX_COMMON_CAP_SET_IPV6_TO_CPU_HIGHER,
	IDX_COMMON_CAP_GET_IPV6_TO_CPU_HIGHER,
	IDX_COMMON_CAP_SET_IPV6_ACT,
	IDX_COMMON_CAP_GET_IPV6_ACT,
	IDX_COMMON_CAP_SET_IPV6_USER_DEFINE,
	IDX_COMMON_CAP_GET_IPV6_USER_DEFINE,
	IDX_COMMON_CAP_SET_ICMPV6_USER_DEFINE,	//30
	IDX_COMMON_CAP_GET_ICMPV6_USER_DEFINE,
	NUM_COMMON_CAP	//32
};

#define ID_COMMON_CAP(idx)	\
	MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_CAP, idx)

#define	ID_COMMON_L2_SET_CAP_ACT \
	ID_COMMON_CAP(IDX_COMMON_L2_SET_CAP_ACT)
#define	ID_COMMON_L2_GET_CAP_ACT \
	ID_COMMON_CAP(IDX_COMMON_L2_GET_CAP_ACT)
#define	ID_COMMON_CAP_SET_IN_BAND \
	ID_COMMON_CAP(IDX_COMMON_CAP_SET_IN_BAND)
#define	ID_COMMON_CAP_GET_IN_BAND \
	ID_COMMON_CAP(IDX_COMMON_CAP_GET_IN_BAND)
#define	ID_COMMON_CAP_SET_IN_BAND_RESTRICT \
	ID_COMMON_CAP(IDX_COMMON_CAP_SET_IN_BAND_RESTRICT)
#define	ID_COMMON_CAP_GET_IN_BAND_RESTRICT \
	ID_COMMON_CAP(IDX_COMMON_CAP_GET_IN_BAND_RESTRICT)
#define	ID_COMMON_CAP_SET_IN_BAND_RESTRICT_CONFIG \
	ID_COMMON_CAP(IDX_COMMON_CAP_SET_IN_BAND_RESTRICT_CONFIG)
#define	ID_COMMON_CAP_GET_IN_BAND_RESTRICT_CONFIG \
	ID_COMMON_CAP(IDX_COMMON_CAP_GET_IN_BAND_RESTRICT_CONFIG)
#define	ID_COMMON_CAP_SET_SWITCH_MAC \
	ID_COMMON_CAP(IDX_COMMON_CAP_SET_SWITCH_MAC)
#define	ID_COMMON_CAP_GET_SWITCH_MAC \
	ID_COMMON_CAP(IDX_COMMON_CAP_GET_SWITCH_MAC)
#define	ID_COMMON_CAP_SET_L3_ACT \
	ID_COMMON_CAP(IDX_COMMON_CAP_SET_L3_ACT)
#define	ID_COMMON_CAP_GET_L3_ACT \
	ID_COMMON_CAP(IDX_COMMON_CAP_GET_L3_ACT)
#define	ID_COMMON_CAP_SET_L3_USER \
	ID_COMMON_CAP(IDX_COMMON_CAP_SET_L3_USER)
#define	ID_COMMON_CAP_GET_L3_USER \
	ID_COMMON_CAP(IDX_COMMON_CAP_GET_L3_USER)
#define	ID_COMMON_CAP_SET_ETHER_USER \
	ID_COMMON_CAP(IDX_COMMON_CAP_SET_ETHER_USER)
#define	ID_COMMON_CAP_GET_ETHER_USER \
	ID_COMMON_CAP(IDX_COMMON_CAP_GET_ETHER_USER)
#define	ID_COMMON_CAP_SET_IPV6_TCPUDP_ENABLE \
	ID_COMMON_CAP(IDX_COMMON_CAP_SET_IPV6_TCPUDP_ENABLE)
#define	ID_COMMON_CAP_GET_IPV6_TCPUDP_ENABLE \
	ID_COMMON_CAP(IDX_COMMON_CAP_GET_IPV6_TCPUDP_ENABLE)
#define	ID_COMMON_CAP_SET_IPV6_TCPUDP_FLAG_ENABLE \
	ID_COMMON_CAP(IDX_COMMON_CAP_SET_IPV6_TCPUDP_FLAG_ENABLE)
#define	ID_COMMON_CAP_GET_IPV6_TCPUDP_FLAG_ENABLE \
	ID_COMMON_CAP(IDX_COMMON_CAP_GET_IPV6_TCPUDP_FLAG_ENABLE)
#define	ID_COMMON_CAP_SET_IPV6_STOP_FINDING \
	ID_COMMON_CAP(IDX_COMMON_CAP_SET_IPV6_STOP_FINDING)
#define	ID_COMMON_CAP_GET_IPV6_STOP_FINDING \
	ID_COMMON_CAP(IDX_COMMON_CAP_GET_IPV6_STOP_FINDING)
#define	ID_COMMON_CAP_SET_IPV6_TO_ALL_PORTS_HIGHER \
	ID_COMMON_CAP(IDX_COMMON_CAP_SET_IPV6_TO_ALL_PORTS_HIGHER)
#define	ID_COMMON_CAP_GET_IPV6_TO_ALL_PORTS_HIGHER \
	ID_COMMON_CAP(IDX_COMMON_CAP_GET_IPV6_TO_ALL_PORTS_HIGHER)
#define	ID_COMMON_CAP_SET_IPV6_TO_CPU_HIGHER \
	ID_COMMON_CAP(IDX_COMMON_CAP_SET_IPV6_TO_CPU_HIGHER)
#define	ID_COMMON_CAP_GET_IPV6_TO_CPU_HIGHER \
	ID_COMMON_CAP(IDX_COMMON_CAP_GET_IPV6_TO_CPU_HIGHER)
#define	ID_COMMON_CAP_SET_IPV6_ACT \
	ID_COMMON_CAP(IDX_COMMON_CAP_SET_IPV6_ACT)
#define	ID_COMMON_CAP_GET_IPV6_ACT \
	ID_COMMON_CAP(IDX_COMMON_CAP_GET_IPV6_ACT)
#define	ID_COMMON_CAP_SET_IPV6_USER_DEFINE \
	ID_COMMON_CAP(IDX_COMMON_CAP_SET_IPV6_USER_DEFINE)
#define	ID_COMMON_CAP_GET_IPV6_USER_DEFINE \
	ID_COMMON_CAP(IDX_COMMON_CAP_GET_IPV6_USER_DEFINE)
#define	ID_COMMON_CAP_SET_ICMPV6_USER_DEFINE \
	ID_COMMON_CAP(IDX_COMMON_CAP_SET_ICMPV6_USER_DEFINE)
#define	ID_COMMON_CAP_GET_ICMPV6_USER_DEFINE \
	ID_COMMON_CAP(IDX_COMMON_CAP_GET_ICMPV6_USER_DEFINE)


/*-------------------------------------------------------------------*/
#define _CMDID_SUBG_LUT		0x3

enum{
	IDX_COMMON_SET_SMAC_LEARNING,		//0
	IDX_COMMON_GET_SMAC_LEARNING,
	IDX_COMMON_SET_SMAC_LEARNING_CNT_CTRL,
	IDX_COMMON_GET_SMAC_LEARNING_CNT_CTRL,
	IDX_COMMON_SET_SMAC_LEARN_CNT_CTRL_THRESHOLD,
	IDX_COMMON_GET_SMAC_LEARN_CNT_CTRL_THRESHOLD,
	IDX_COMMON_LUT_SET_PORT_FLUSH,
	IDX_COMMON_SET_LUT_AGING_TIME,
	IDX_COMMON_GET_LUT_AGING_TIME,
	IDX_COMMON_SET_LUT_AGING_TIME_ENABLE,
	IDX_COMMON_GET_LUT_AGING_TIME_ENABLE,	//10
	IDX_COMMON_SET_LUT_LEARN_NSA,
	IDX_COMMON_GET_LUT_LEARN_NSA,
	IDX_COMMON_SET_LUT_HASHING_ALGORITHM,
	IDX_COMMON_GET_LUT_HASHING_ALGORITHM,
	IDX_COMMON_SET_LUT_BINDING_ENABLE,
	IDX_COMMON_GET_LUT_BINDING_ENABLE,
	IDX_COMMON_SET_LUT_LEARN_DRP_PKT_BY_VLAN_IGS_CHK,
	IDX_COMMON_GET_LUT_LEARN_DRP_PKT_BY_VLAN_IGS_CHK,
	NUM_COMMON_LUT//19
};

enum{
	IDX_1829_LUT_SET_LEARN_MODE,	//0
	IDX_1829_LUT_GET_LEARN_MODE,
	IDX_1829_LUT_SET_UNKNOWN_SA_RULE,
	IDX_1829_LUT_GET_UNKNOWN_SA_RULE,
	IDX_1829_LUT_SET_ENTRY,
	IDX_1829_LUT_GET_ENTRY,
	IDX_1829_LUT_GET_VALID_ENTRY,
	NUM_1829_LUT	//6
};

#define ID_COMMON_LUT(idx)	\
	MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_LUT, idx)

#define	ID_COMMON_SET_SMAC_LEARNING \
	ID_COMMON_LUT(IDX_COMMON_SET_SMAC_LEARNING)
#define	ID_COMMON_GET_SMAC_LEARNING \
	ID_COMMON_LUT(IDX_COMMON_GET_SMAC_LEARNING)
#define	ID_COMMON_SET_SMAC_LEARNING_CNT_CTRL \
	ID_COMMON_LUT(IDX_COMMON_SET_SMAC_LEARNING_CNT_CTRL)
#define	ID_COMMON_GET_SMAC_LEARNING_CNT_CTRL \
	ID_COMMON_LUT(IDX_COMMON_GET_SMAC_LEARNING_CNT_CTRL)
#define	ID_COMMON_SET_SMAC_LEARN_CNT_CTRL_THRESHOLD \
	ID_COMMON_LUT(IDX_COMMON_SET_SMAC_LEARN_CNT_CTRL_THRESHOLD)
#define	ID_COMMON_GET_SMAC_LEARN_CNT_CTRL_THRESHOLD \
	ID_COMMON_LUT(IDX_COMMON_GET_SMAC_LEARN_CNT_CTRL_THRESHOLD)
#define	ID_COMMON_LUT_SET_PORT_FLUSH \
	ID_COMMON_LUT(IDX_COMMON_LUT_SET_PORT_FLUSH)
#define	ID_COMMON_SET_LUT_AGING_TIME \
	ID_COMMON_LUT(IDX_COMMON_SET_LUT_AGING_TIME)
#define	ID_COMMON_GET_LUT_AGING_TIME \
	ID_COMMON_LUT(IDX_COMMON_GET_LUT_AGING_TIME)
#define	ID_COMMON_SET_LUT_AGING_TIME_ENABLE \
	ID_COMMON_LUT(IDX_COMMON_SET_LUT_AGING_TIME_ENABLE)
#define	ID_COMMON_GET_LUT_AGING_TIME_ENABLE \
	ID_COMMON_LUT(IDX_COMMON_GET_LUT_AGING_TIME_ENABLE)
#define	ID_COMMON_SET_LUT_LEARN_NSA \
	ID_COMMON_LUT(IDX_COMMON_SET_LUT_LEARN_NSA)
#define	ID_COMMON_GET_LUT_LEARN_NSA \
	ID_COMMON_LUT(IDX_COMMON_GET_LUT_LEARN_NSA)
#define	ID_COMMON_SET_LUT_HASHING_ALGORITHM \
	ID_COMMON_LUT(IDX_COMMON_SET_LUT_HASHING_ALGORITHM)
#define	ID_COMMON_GET_LUT_HASHING_ALGORITHM \
	ID_COMMON_LUT(IDX_COMMON_GET_LUT_HASHING_ALGORITHM)
#define	ID_COMMON_SET_LUT_BINDING_ENABLE \
	ID_COMMON_LUT(IDX_COMMON_SET_LUT_BINDING_ENABLE)
#define	ID_COMMON_GET_LUT_BINDING_ENABLE \
	ID_COMMON_LUT(IDX_COMMON_GET_LUT_BINDING_ENABLE)
#define	ID_COMMON_SET_LUT_LEARN_DRP_PKT_BY_VLAN_IGS_CHK \
	ID_COMMON_LUT(IDX_COMMON_SET_LUT_LEARN_DRP_PKT_BY_VLAN_IGS_CHK)
#define	ID_COMMON_GET_LUT_LEARN_DRP_PKT_BY_VLAN_IGS_CHK \
	ID_COMMON_LUT(IDX_COMMON_GET_LUT_LEARN_DRP_PKT_BY_VLAN_IGS_CHK)

#define ID_1829_LUT(idx)	\
	MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_LUT, idx)

#define	ID_1829_LUT_SET_LEARN_MODE \
	ID_1829_LUT(IDX_1829_LUT_SET_LEARN_MODE)
#define	ID_1829_LUT_GET_LEARN_MODE \
	ID_1829_LUT(IDX_1829_LUT_GET_LEARN_MODE)
#define	ID_1829_LUT_SET_UNKNOWN_SA_RULE \
	ID_1829_LUT(IDX_1829_LUT_SET_UNKNOWN_SA_RULE)
#define	ID_1829_LUT_GET_UNKNOWN_SA_RULE \
	ID_1829_LUT(IDX_1829_LUT_GET_UNKNOWN_SA_RULE)
#define	ID_1829_LUT_SET_ENTRY \
	ID_1829_LUT(IDX_1829_LUT_SET_ENTRY)
#define	ID_1829_LUT_GET_ENTRY \
	ID_1829_LUT(IDX_1829_LUT_GET_ENTRY)
#define	ID_1829_LUT_GET_VALID_ENTRY \
	ID_1829_LUT(IDX_1829_LUT_GET_VALID_ENTRY)


/*-------------------------------------------------------------------*/
#define _CMDID_SUBG_SNIFFER	0x4
#define ID_COMMON_SET_SNIFFER_SOURCE \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_SNIFFER, 0)
#define ID_COMMON_GET_SNIFFER_SOURCE \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_SNIFFER, 1)
#define ID_COMMON_SET_SNIFFER_DEST_GRP1 \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_SNIFFER, 2)
#define ID_COMMON_GET_SNIFFER_DEST_GRP1 \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_SNIFFER, 3)
#define ID_COMMON_SET_SNIFFER_DEST_GRP2 \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_SNIFFER, 4)
#define ID_COMMON_GET_SNIFFER_DEST_GRP2 \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_SNIFFER, 5)
#define ID_COMMON_SNIFFER1_SET_METHOD \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_SNIFFER, 6)
#define ID_COMMON_SNIFFER1_GET_METHOD \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_SNIFFER, 7)
#define ID_1829_SNIFFER1_SET_PKT_MODIFY \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_SNIFFER, 0)
#define ID_1829_SNIFFER1_GET_PKT_MODIFY \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_SNIFFER, 1)
#define ID_1829_SNIFFER1_SET_TAG_MODIFY_FOR_CPU_STAG \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_SNIFFER, 2)
#define ID_1829_SNIFFER1_GET_TAG_MODIFY_FOR_CPU_STAG \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_SNIFFER, 3)
#define ID_1829_SNIFFER1_SET_TAG_MODIFY_FOR_ACL_REDIR_2CPU \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_SNIFFER, 4)
#define ID_1829_SNIFFER1_GET_TAG_MODIFY_FOR_ACL_REDIR_2CPU \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_SNIFFER, 5)
#define ID_1829_SNIFFER1_SET_TAG_MODIFY_FOR_PKT_2MIRROR_PORT \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_SNIFFER, 6)
#define ID_1829_SNIFFER1_GET_TAG_MODIFY_FOR_PKT_2MIRROR_PORT \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_SNIFFER, 7)
#define ID_1829_SNIFFER2_SET_LUT_TRIGGER_TARGET_FOR_GRP1 \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_SNIFFER, 8)
#define ID_1829_SNIFFER2_GET_LUT_TRIGGER_TARGET_FOR_GRP1 \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_SNIFFER, 9)
#define ID_1829_SNIFFER2_SET_LUT_TRIGGER_TARGET_FOR_GRP2 \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_SNIFFER, 10)
#define ID_1829_SNIFFER2_GET_LUT_TRIGGER_TARGET_FOR_GRP2 \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_SNIFFER, 11)

/*-------------------------------------------------------------------*/
#define _CMDID_SUBG_STORM	0x5
#define ID_COMMON_STORM_CTRL_SET_FUNC \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_STORM, 0)
#define ID_COMMON_STORM_CTRL_GET_FUNC \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_STORM, 1)
#define ID_COMMON_STORM_CTRL_SET_THRESHOLD \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_STORM, 2)
#define ID_COMMON_STORM_CTRL_GET_THRESHOLD \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_STORM, 3)
#define ID_COMMON_STORM_SET_COUNTER_CLR_PERIOD \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_STORM, 4)
#define ID_COMMON_STORM_GET_COUNTER_CLR_PERIOD \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_STORM, 5)
#define ID_COMMON_STORM_SET_BLOCK_FRAME_2CPU \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_STORM, 6)
#define ID_COMMON_STORM_GET_BLOCK_FRAME_2CPU \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_STORM, 7)
#define ID_COMMON_STORM_SET_DROP_INTERRUPT \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_STORM, 8)
#define ID_COMMON_STORM_GET_DROP_INTERRUPT \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_STORM, 9)
#define ID_1829_MCST_STORM_SET_NBLOCK_IP_PKT \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_STORM, 0)
#define ID_1829_MCST_STORM_GET_NBLOCK_IP_PKT \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_STORM, 1)
#define ID_1829_MCST_STORM_SET_IGNORE_01005EXXXXXX \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_STORM, 2)
#define ID_1829_MCST_STORM_GET_IGNORE_01005EXXXXXX \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_STORM, 3)

/*-------------------------------------------------------------------*/
#define _CMDID_SUBG_EOC		0x6
#define ID_COMMON_EOC_SET_FUNC \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_EOC, 0)
#define ID_COMMON_EOC_GET_FUNC \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_EOC, 1)
#define ID_COMMON_EOC_GET_STATUS \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_EOC, 2)
#define ID_COMMON_EOC_SET_RELEASE_TIME \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_EOC, 3)
#define ID_COMMON_EOC_GET_RELEASE_TIME \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_EOC, 4)
#define ID_1829_EOC_SET_ALL_BLOCK_CLEARED \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_EOC, 0)
#define ID_1829_EOC_SET_CLR_BLOCK_WHEN_RCV_A_GOOD_PKT \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_EOC, 1)
#define ID_1829_EOC_GET_CLR_BLOCK_WHEN_RCV_A_GOOD_PKT \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_EOC, 2)

/*-------------------------------------------------------------------*/
#define _CMDID_SUBG_LD		0x7
#define ID_COMMON_LOOP_DETECT_SET_FUNC \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_LD, 0)
#define ID_COMMON_LOOP_DETECT_GET_FUNC \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_LD, 1)
#define ID_COMMON_LOOP_DETECT_SET_TIME_UNIT \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_LD, 2)
#define ID_COMMON_LOOP_DETECT_GET_TIME_UNIT \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_LD, 3)
#define ID_COMMON_LOOP_DETECT_SET_PKT_SEND_TIMER \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_LD, 4)
#define ID_COMMON_LOOP_DETECT_GET_PKT_SEND_TIMER \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_LD, 5)
#define ID_COMMON_LOOP_DETECT_SET_BLOCK_RELEASE_TIMER \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_LD, 6)
#define ID_COMMON_LOOP_DETECT_GET_BLOCK_RELEASE_TIMER \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_LD, 7)
#define ID_COMMON_LOOP_DETECT_GET_STATUS \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_LD, 8)
#define ID_1829_LOOP_DETECT_SET_SMAC_B40 \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_LD, 0)
#define ID_1829_LOOP_DETECT_GET_SMAC_B40 \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_LD, 1)
#define ID_1829_LOOP_DETECT_SET_RE_RANDOM \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_LD, 2)
#define ID_1829_LOOP_DETECT_GET_RE_RANDOM \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_LD, 3)
#define ID_1829_LOOP_DETECT_SET_DMAC \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_LD, 4)
#define ID_1829_LOOP_DETECT_GET_DMAC \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_LD, 5)
#define ID_1829_LOOP_DETECT_SET_ETHERTYPE \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_LD, 6)
#define ID_1829_LOOP_DETECT_GET_ETHERTYPE \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_LD, 7)
#define ID_1829_LOOP_DETECT_SET_SUB_TYPE \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_LD, 8)
#define ID_1829_LOOP_DETECT_GET_SUB_TYPE \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_LD, 9)
#define ID_1829_LOOP_DETECT_SET_DEVICE_ID \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_LD, 10)
#define ID_1829_LOOP_DETECT_GET_DEVICE_ID \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_LD, 11)

/*-------------------------------------------------------------------*/
#define _CMDID_SUBG_WOL		0x8
#define ID_COMMON_WOL_SET_FUNC \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_WOL, 0)
#define ID_COMMON_WOL_GET_FUNC \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_WOL, 1)
#define ID_COMMON_WOL_SET_MODE \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_WOL, 2)
#define ID_COMMON_WOL_GET_MODE \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_WOL, 3)
#define ID_COMMON_WOL_SET_INTERRUPT_2CPU \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_WOL, 4)
#define ID_COMMON_WOL_GET_INTERRUPT_2CPU \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_WOL, 5)
#define ID_COMMON_WOL_SET_IDLE_PERIOD_UNIT \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_WOL, 6)
#define ID_COMMON_WOL_GET_IDLE_PERIOD_UNIT \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_WOL, 7)
#define ID_COMMON_WOL_SET_IDLE_PERIOD_THRESHOLD \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_WOL, 8)
#define ID_COMMON_WOL_GET_IDLE_PERIOD_THRESHOLD \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_WOL, 9)
#define ID_COMMON_WOL_SET_STATUS_IN_SLAVE_MODE \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_WOL, 10)
#define ID_COMMON_WOL_GET_STATUS \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_WOL, 11)
#define ID_1829_WOL_SET_WAKE_IF_TX_GET_ANY_PKT \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_WOL, 0)
#define ID_1829_WOL_GET_WAKE_IF_TX_GET_ANY_PKT \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_WOL, 1)
#define ID_1829_WOL_SET_WAKE_IF_RX_GET_ANY_PKT \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_WOL, 2)
#define ID_1829_WOL_GET_WAKE_IF_RX_GET_ANY_PKT \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_WOL, 3)
#define ID_1829_WOL_SET_WAKE_IF_PKT_MATCH_ACL_2CPU \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_WOL, 4)
#define ID_1829_WOL_GET_WAKE_IF_PKT_MATCH_ACL_2CPU \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_WOL, 5)

/*-------------------------------------------------------------------*/
#define _CMDID_SUBG_STAG	0x9
#define ID_COMMON_SET_CPU_PORT_LINK \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_STAG, 0)
#define ID_COMMON_GET_CPU_PORT_LINK \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_STAG, 1)
#define ID_COMMON_STAG_SET_FUNC \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_STAG, 2)
#define ID_COMMON_STAG_GET_FUNC \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_STAG, 3)
#define ID_COMMON_STAG_SET_TYPE_LENGTH \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_STAG, 4)
#define ID_COMMON_STAG_GET_TYPE_LENGTH \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_STAG, 5)

/*-------------------------------------------------------------------*/
#define _CMDID_SUBG_IGMP	0xA
#define ID_IP1829_IGMP_SET_SNOOPING_FUNCTION \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_IGMP, 0)
#define ID_IP1829_IGMP_GET_SNOOPING_FUNCTION \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_IGMP, 1)
#define ID_IP1829_IGMP_SET_MCT_BY_CPU \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_IGMP, 2)
#define ID_IP1829_IGMP_GET_MCT_BY_CPU \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_IGMP, 3)
#define ID_IP1829_IGMP_SET_GROUP_MEM_AGING \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_IGMP, 4)
#define ID_IP1829_IGMP_GET_GROUP_MEM_AGING \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_IGMP, 5)
#define ID_IP1829_IGMP_SET_ROUTER_LIST_MAKE_BY_CPU \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_IGMP, 6)
#define ID_IP1829_IGMP_GET_ROUTER_LIST_MAKE_BY_CPU \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_IGMP, 7)
#define ID_IP1829_IGMP_SET_PACKET_FORWARD_RULE \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_IGMP, 8)
#define ID_IP1829_IGMP_GET_PACKET_FORWARD_RULE \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_IGMP, 9)
#define ID_IP1829_IGMP_SET_ROUTER_LIST \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_IGMP, 10)
#define ID_IP1829_IGMP_GET_ROUTER_LIST \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_IGMP, 11)
#define ID_IP1829_IGMP_SET_HASHING_METHOD \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_IGMP, 12)
#define ID_IP1829_IGMP_GET_HASHING_METHOD \
	MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_IGMP, 13)
#define ID_IP1829_MLD_SET_FORWARD_RULE \
	MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_IGMP, 14)
#define ID_IP1829_MLD_GET_FORWARD_RULE \
	MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_IGMP, 15)
#define ID_IP1829_MT_SET_RULE \
	MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_IGMP, 16)
#define ID_IP1829_MT_GET_RULE \
	MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_IGMP, 17)
#define ID_IP1829_SLT_SET_RULE \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_IGMP, 18)
#define ID_IP1829_SLT_GET_RULE \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_IGMP, 19)


/*-------------------------------------------------------------------*/
#define _CMDID_SUBG_PTP	0xB

enum{
	IDX_COMMON_PTP_SET_ENABLE,
	IDX_COMMON_PTP_GET_ENABLE,
	IDX_COMMON_PTP_SET_TO_CPU,
	IDX_COMMON_PTP_GET_TO_CPU,
	NUM_COMMON_PTP
};

#define ID_COMMON_PTP(idx)	\
	MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_PTP, idx)

#define	ID_COMMON_PTP_SET_ENABLE \
	ID_COMMON_PTP(IDX_COMMON_PTP_SET_ENABLE)
#define	ID_COMMON_PTP_GET_ENABLE \
	ID_COMMON_PTP(IDX_COMMON_PTP_GET_ENABLE)
#define	ID_COMMON_PTP_SET_TO_CPU \
	ID_COMMON_PTP(IDX_COMMON_PTP_SET_TO_CPU)
#define	ID_COMMON_PTP_GET_TO_CPU \
	ID_COMMON_PTP(IDX_COMMON_PTP_GET_TO_CPU)

/*-------------------------------------------------------------------*/
#define _CMDID_SUB_BANDWIDTH	0xC
#define	RATE_SCALE_UNIT	64000
enum{
	IDX_COMMON_BANDWIDTH_SET_INGRESS_RATE,
	IDX_COMMON_BANDWIDTH_GET_INGRESS_RATE,
	IDX_COMMON_BANDWIDTH_SET_EGRESS_RATE,
	IDX_COMMON_BANDWIDTH_GET_EGRESS_RATE,
	IDX_COMMON_BANDWIDTH_SET_EGRESS_PERIOD,
	IDX_COMMON_BANDWIDTH_GET_EGRESS_PERIOD,
	NUM_COMMON_BANDWIDTH
};
#define ID_COMMON_BANDWIDTH(idx)	\
	MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUB_BANDWIDTH, idx)

#define ID_COMMON_BANDWIDTH_SET_INGRESS_RATE \
	ID_COMMON_BANDWIDTH(IDX_COMMON_BANDWIDTH_SET_INGRESS_RATE)
#define ID_COMMON_BANDWIDTH_GET_INGRESS_RATE \
	ID_COMMON_BANDWIDTH(IDX_COMMON_BANDWIDTH_GET_INGRESS_RATE)
#define ID_COMMON_BANDWIDTH_SET_EGRESS_RATE \
	ID_COMMON_BANDWIDTH(IDX_COMMON_BANDWIDTH_SET_EGRESS_RATE)
#define ID_COMMON_BANDWIDTH_GET_EGRESS_RATE \
	ID_COMMON_BANDWIDTH(IDX_COMMON_BANDWIDTH_GET_EGRESS_RATE)
#define ID_COMMON_BANDWIDTH_SET_EGRESS_PERIOD \
	ID_COMMON_BANDWIDTH(IDX_COMMON_BANDWIDTH_SET_EGRESS_PERIOD)
#define ID_COMMON_BANDWIDTH_GET_EGRESS_PERIOD \
	ID_COMMON_BANDWIDTH(IDX_COMMON_BANDWIDTH_GET_EGRESS_PERIOD)

/*-------------------------------------------------------------------*/
#define _CMDID_SUBG_MISC	0xF
#define ID_COMMON_JUMBO_PKT_SET_FUNC \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_MISC, 0)
#define ID_COMMON_JUMBO_PKT_GET_FUNC \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_MISC, 1)
#define ID_COMMON_8021X_PORT_LOCK_SET_FUNC \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_MISC, 2)
#define ID_COMMON_8021X_PORT_LOCK_GET_FUNC \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_MISC, 3)
#define ID_COMMON_MISC_SET_REG \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_MISC, 4)
#define ID_COMMON_MISC_GET_REG \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_MISC, 5)
#define ID_COMMON_MISC_SET_CPU_REG \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_MISC, 6)
#define ID_COMMON_MISC_GET_CPU_REG \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_MISC, 7)
#define ID_COMMON_MISC_SET_SWITCH_RESTART \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_MISC, 8)
#define ID_COMMON_MISC_SET_SWITCH_RESET \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_MISC, 9)
#define ID_COMMON_MISC_SET_CPU_IF_SPEED \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_BASIC, _CMDID_SUBG_MISC, 10)

#define ID_1829_MAC_LOOP_BACK_SET_FUNC \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_MISC, 0)
#define ID_1829_MAC_LOOP_BACK_GET_FUNC \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_MISC, 1)
#define ID_1829_PASS_PAUSE_PKT_SET_FUNC \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_MISC, 2)
#define ID_1829_PASS_PAUSE_PKT_GET_FUNC \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_MISC, 3)
#define ID_1829_PAUSE_PKT_SET_DESTINATION \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_MISC, 4)
#define ID_1829_PAUSE_PKT_GET_DESTINATION \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_MISC, 5)
#define ID_1829_LOCAL_TRAFFIC_SET_FUNC \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_MISC, 6)
#define ID_1829_LOCAL_TRAFFIC_GET_FUNC \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_MISC, 7)
#define ID_1829_MAC_SET_RESET \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_MISC, 8)
#define ID_1829_MAC_GET_RESET \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_MISC, 9)
#define ID_1829_MAC_SELF_TEST_SET_FUNC \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_MISC, 10)
#define ID_1829_MAC_SELF_TEST_GET_FUNC \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_MISC, 11)
#define ID_1829_MAC_SELF_TEST_SET_PKT_NUMBER \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_MISC, 12)
#define ID_1829_MAC_SELF_TEST_GET_PKT_NUMBER \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_MISC, 13)
#define ID_1829_MAC_SELF_TEST_GET_RESULT \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_BASIC, _CMDID_SUBG_MISC, 14)

/*===================================================================*/
#define _CMDID_GRP_VLAN		0x02
/*-------------------------------------------------------------------*/
#define _CMDID_SUBG_VLAN	0x1

enum{
	IDX_COMMON_VLAN_SET_EGRESS_FRAME,	//0
	IDX_COMMON_VLAN_GET_EGRESS_FRAME,
	IDX_COMMON_VLAN_SET_TAGGING,
	IDX_COMMON_VLAN_GET_TAGGING,
	IDX_COMMON_VLAN_SET_TYPE,
	IDX_COMMON_VLAN_GET_TYPE,
	IDX_COMMON_VLAN_SET_GROUP,
	IDX_COMMON_VLAN_SET_QINQ_TYPE,
	IDX_COMMON_VLAN_GET_QINQ_TYPE,
	IDX_COMMON_VLAN_SET_QINQ_P_ADDTAG,
	IDX_COMMON_VLAN_GET_QINQ_P_ADDTAG,	//10
	IDX_COMMON_VLAN_SET_QINQ_P_RMVTAG,
	IDX_COMMON_VLAN_GET_QINQ_P_RMVTAG,
	IDX_COMMON_VLAN_SET_QINQ_P_RXDET,
	IDX_COMMON_VLAN_GET_QINQ_P_RXDET,
	IDX_COMMON_VLAN_SET_QINQ_P_KEEP,
	IDX_COMMON_VLAN_GET_QINQ_P_KEEP,
	IDX_COMMON_VLAN_SET_QINQ_P_INDEX,
	IDX_COMMON_VLAN_GET_QINQ_P_INDEX,
	IDX_COMMON_VLAN_SET_QINQ_INDEX,
	IDX_COMMON_VLAN_GET_QINQ_INDEX,		//20
	IDX_COMMON_VLAN_SET_PORT_ADDTAG,
	IDX_COMMON_VLAN_GET_PORT_ADDTAG,
	IDX_COMMON_VLAN_SET_PORT_RMVTAG,
	IDX_COMMON_VLAN_GET_PORT_RMVTAG,
	IDX_COMMON_VLAN_SET_PORT_FORCE,
	IDX_COMMON_VLAN_GET_PORT_FORCE,
	IDX_COMMON_VLAN_SET_PORT_UPLINK,
	IDX_COMMON_VLAN_GET_PORT_UPLINK,
	IDX_COMMON_VLAN_SET_PORT_EXCLUSIVE,
	IDX_COMMON_VLAN_GET_PORT_EXCLUSIVE,	//30
	IDX_COMMON_VLAN_SET_PORT_EGRESS,
	IDX_COMMON_VLAN_GET_PORT_EGRESS,
	IDX_COMMON_VLAN_SET_PORT_INGRESS_FRAME,
	IDX_COMMON_VLAN_GET_PORT_INGRESS_FRAME,
	IDX_COMMON_VLAN_SET_PORT_INGRESS_CHECK,
	IDX_COMMON_VLAN_GET_PORT_INGRESS_CHECK,
	IDX_COMMON_VLAN_SET_PORT_MEMBER,
	IDX_COMMON_VLAN_GET_PORT_MEMBER,
	IDX_COMMON_VLAN_SET_PORT_VID,
	IDX_COMMON_VLAN_GET_PORT_VID,		//40
	IDX_COMMON_VLAN_SET_PROTOCOL_MODE,
	IDX_COMMON_VLAN_GET_PROTOCOL_MODE,
	IDX_COMMON_VLAN_SET_PROTOCOL_VID,
	IDX_COMMON_VLAN_GET_PROTOCOL_VID,
	IDX_COMMON_VLAN_SET_PROTOCOL_TYPE,
	IDX_COMMON_VLAN_GET_PROTOCOL_TYPE,
	IDX_COMMON_VLAN_CLEAR_PROTOCOL,
	NUM_COMMON_VLAN	//48
};

enum{
	IDX_IP1829_VLAN_SET_ENTRY_MEMBER,	//0
	IDX_IP1829_VLAN_GET_ENTRY_MEMBER,
	IDX_IP1829_VLAN_SET_ENTRY_ADDTAG,
	IDX_IP1829_VLAN_GET_ENTRY_ADDTAG,
	IDX_IP1829_VLAN_SET_ENTRY_RMVTAG,
	IDX_IP1829_VLAN_GET_ENTRY_RMVTAG,
	IDX_IP1829_VLAN_SET_ENTRY_PRIORITY,
	IDX_IP1829_VLAN_GET_ENTRY_PRIORITY,
	IDX_IP1829_VLAN_SET_ENTRY_FID,
	IDX_IP1829_VLAN_GET_ENTRY_FID,
	IDX_IP1829_VLAN_DELETE_ENTRY,
	NUM_IP1829_VLAN	//11
};

#define ID_COMMON_VLAN(idx)	\
	MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_VLAN, _CMDID_SUBG_VLAN, idx)

#define	ID_COMMON_VLAN_SET_EGRESS_FRAME \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_SET_EGRESS_FRAME)
#define ID_COMMON_VLAN_GET_EGRESS_FRAME \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_GET_EGRESS_FRAME)
#define ID_COMMON_VLAN_SET_TAGGING \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_SET_TAGGING)
#define ID_COMMON_VLAN_GET_TAGGING \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_GET_TAGGING)
#define ID_COMMON_VLAN_SET_TYPE \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_SET_TYPE)
#define ID_COMMON_VLAN_GET_TYPE \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_GET_TYPE)
#define ID_COMMON_VLAN_SET_GROUP \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_SET_GROUP)

#define ID_COMMON_VLAN_SET_QINQ_TYPE \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_SET_QINQ_TYPE)
#define ID_COMMON_VLAN_GET_QINQ_TYPE \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_GET_QINQ_TYPE)
#define ID_COMMON_VLAN_SET_QINQ_P_ADDTAG \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_SET_QINQ_P_ADDTAG)
#define ID_COMMON_VLAN_GET_QINQ_P_ADDTAG \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_GET_QINQ_P_ADDTAG)
#define ID_COMMON_VLAN_SET_QINQ_P_RMVTAG \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_SET_QINQ_P_RMVTAG)
#define ID_COMMON_VLAN_GET_QINQ_P_RMVTAG \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_GET_QINQ_P_RMVTAG)
#define ID_COMMON_VLAN_SET_QINQ_P_RXDET \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_SET_QINQ_P_RXDET)
#define ID_COMMON_VLAN_GET_QINQ_P_RXDET \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_GET_QINQ_P_RXDET)
#define ID_COMMON_VLAN_SET_QINQ_P_KEEP \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_SET_QINQ_P_KEEP)
#define ID_COMMON_VLAN_GET_QINQ_P_KEEP \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_GET_QINQ_P_KEEP)
#define ID_COMMON_VLAN_SET_QINQ_P_INDEX \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_SET_QINQ_P_INDEX)
#define ID_COMMON_VLAN_GET_QINQ_P_INDEX \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_GET_QINQ_P_INDEX)
#define ID_COMMON_VLAN_SET_QINQ_INDEX \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_SET_QINQ_INDEX)
#define ID_COMMON_VLAN_GET_QINQ_INDEX \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_GET_QINQ_INDEX)

#define ID_COMMON_VLAN_SET_PORT_ADDTAG \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_SET_PORT_ADDTAG)
#define ID_COMMON_VLAN_GET_PORT_ADDTAG \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_GET_PORT_ADDTAG)
#define ID_COMMON_VLAN_SET_PORT_RMVTAG \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_SET_PORT_RMVTAG)
#define ID_COMMON_VLAN_GET_PORT_RMVTAG \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_GET_PORT_RMVTAG)
#define ID_COMMON_VLAN_SET_PORT_FORCE \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_SET_PORT_FORCE)
#define ID_COMMON_VLAN_GET_PORT_FORCE \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_GET_PORT_FORCE)
#define ID_COMMON_VLAN_SET_PORT_UPLINK \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_SET_PORT_UPLINK)
#define ID_COMMON_VLAN_GET_PORT_UPLINK \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_GET_PORT_UPLINK)
#define ID_COMMON_VLAN_SET_PORT_EXCLUSIVE \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_SET_PORT_EXCLUSIVE)
#define ID_COMMON_VLAN_GET_PORT_EXCLUSIVE \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_GET_PORT_EXCLUSIVE)
#define ID_COMMON_VLAN_SET_PORT_EGRESS \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_SET_PORT_EGRESS)
#define ID_COMMON_VLAN_GET_PORT_EGRESS \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_GET_PORT_EGRESS)
#define ID_COMMON_VLAN_SET_PORT_INGRESS_FRAME \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_SET_PORT_INGRESS_FRAME)
#define ID_COMMON_VLAN_GET_PORT_INGRESS_FRAME \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_GET_PORT_INGRESS_FRAME)
#define ID_COMMON_VLAN_SET_PORT_INGRESS_CHECK \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_SET_PORT_INGRESS_CHECK)
#define ID_COMMON_VLAN_GET_PORT_INGRESS_CHECK \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_GET_PORT_INGRESS_CHECK)
#define ID_COMMON_VLAN_SET_PORT_MEMBER \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_SET_PORT_MEMBER)
#define ID_COMMON_VLAN_GET_PORT_MEMBER \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_GET_PORT_MEMBER)
#define ID_COMMON_VLAN_SET_PORT_VID \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_SET_PORT_VID)
#define ID_COMMON_VLAN_GET_PORT_VID \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_GET_PORT_VID)

#define ID_COMMON_VLAN_SET_PROTOCOL_MODE \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_SET_PROTOCOL_MODE)
#define ID_COMMON_VLAN_GET_PROTOCOL_MODE \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_GET_PROTOCOL_MODE)
#define ID_COMMON_VLAN_SET_PROTOCOL_VID \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_SET_PROTOCOL_VID)
#define ID_COMMON_VLAN_GET_PROTOCOL_VID \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_GET_PROTOCOL_VID)
#define ID_COMMON_VLAN_SET_PROTOCOL_TYPE \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_SET_PROTOCOL_TYPE)
#define ID_COMMON_VLAN_GET_PROTOCOL_TYPE \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_GET_PROTOCOL_TYPE)
#define ID_COMMON_VLAN_CLEAR_PROTOCOL \
	ID_COMMON_VLAN(IDX_COMMON_VLAN_CLEAR_PROTOCOL)

#define ID_IP1829_VLAN(idx) \
	MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_VLAN, _CMDID_SUBG_VLAN, idx)

#define ID_IP1829_VLAN_SET_ENTRY_MEMBER \
	ID_IP1829_VLAN(IDX_IP1829_VLAN_SET_ENTRY_MEMBER)
#define ID_IP1829_VLAN_GET_ENTRY_MEMBER \
	ID_IP1829_VLAN(IDX_IP1829_VLAN_GET_ENTRY_MEMBER)
#define ID_IP1829_VLAN_SET_ENTRY_ADDTAG \
	ID_IP1829_VLAN(IDX_IP1829_VLAN_SET_ENTRY_ADDTAG)
#define ID_IP1829_VLAN_GET_ENTRY_ADDTAG \
	ID_IP1829_VLAN(IDX_IP1829_VLAN_GET_ENTRY_ADDTAG)
#define ID_IP1829_VLAN_SET_ENTRY_RMVTAG \
	ID_IP1829_VLAN(IDX_IP1829_VLAN_SET_ENTRY_RMVTAG)
#define ID_IP1829_VLAN_GET_ENTRY_RMVTAG \
	ID_IP1829_VLAN(IDX_IP1829_VLAN_GET_ENTRY_RMVTAG)
#define ID_IP1829_VLAN_SET_ENTRY_PRIORITY \
	ID_IP1829_VLAN(IDX_IP1829_VLAN_SET_ENTRY_PRIORITY)
#define ID_IP1829_VLAN_GET_ENTRY_PRIORITY \
	ID_IP1829_VLAN(IDX_IP1829_VLAN_GET_ENTRY_PRIORITY)
#define ID_IP1829_VLAN_SET_ENTRY_FID \
	ID_IP1829_VLAN(IDX_IP1829_VLAN_SET_ENTRY_FID)
#define ID_IP1829_VLAN_GET_ENTRY_FID \
	ID_IP1829_VLAN(IDX_IP1829_VLAN_GET_ENTRY_FID)
#define	ID_IP1829_VLAN_DELETE_ENTRY \
	ID_IP1829_VLAN(IDX_IP1829_VLAN_DELETE_ENTRY)

/*===================================================================*/
#define _CMDID_GRP_QOS		0x03
/*-------------------------------------------------------------------*/
#define _CMDID_SUB_QOS    0x1
enum{
  IDX_IP1829_SET_QOS_AGING_FUNCTION,
  IDX_IP1829_GET_QOS_AGING_FUNCTION,
  IDX_IP1829_SET_QOS_AGING_TIME,
  IDX_IP1829_GET_QOS_AGING_TIME,
  IDX_IP1829_SET_QOS_FASTAGING,
  IDX_IP1829_GET_QOS_FASTAGING,

  IDX_IP1829_SET_COS_ACL,
  IDX_IP1829_GET_COS_ACL,
  IDX_IP1829_SET_COS_IGMP,
  IDX_IP1829_GET_COS_IGMP,
  IDX_IP1829_SET_COS_IPADDRESS,
  IDX_IP1829_GET_COS_IPADDRESS,
  IDX_IP1829_SET_COS_MACADDRESS,
  IDX_IP1829_GET_COS_MACADDRESS,
  IDX_IP1829_SET_COS_VID,
  IDX_IP1829_GET_COS_VID,
  IDX_IP1829_SET_COS_TCPUDPPORT,
  IDX_IP1829_GET_COS_TCPUDPPORT,
  IDX_IP1829_SET_COS_DSCP,
  IDX_IP1829_GET_COS_DSCP,
  IDX_IP1829_SET_COS_8021P,
  IDX_IP1829_GET_COS_8021P,
  IDX_IP1829_SET_COS_PHYSICALPORT,
  IDX_IP1829_GET_COS_PHYSICALPORT,
  IDX_IP1829_SET_QOS_8021PEDTION,
  IDX_IP1829_GET_QOS_8021PEDTION,
  IDX_IP1829_SET_QOS_DSCPBASE_DSCP,
  IDX_IP1829_GET_QOS_DSCPBASE_DSCP,
  IDX_IP1829_SET_QOS_DSCPBASE_NOMATCHACTION,
  IDX_IP1829_GET_QOS_DSCPBASE_NOMATCHACTION,
  IDX_IP1829_SET_QOSMODE_GROUP_MEMEBER,
  IDX_IP1829_GET_QOSMODE_GROUP_MEMEBER,
  IDX_IP1829_SET_QOSGROUPB_EN,
  IDX_IP1829_GET_QOSGROUPB_EN,
  IDX_IP1829_SET_QOS_MODE,
  IDX_IP1829_GET_QOS_MODE,
  IDX_IP1829_SET_QOS_METHOD,
  IDX_IP1829_GET_QOS_METHOD,
  IDX_IP1829_SET_QOS_WEIGHT,
  IDX_IP1829_GET_QOS_WEIGHT,
  IDX_IP1829_SET_QOS_MAXBANDWIDTH,
  IDX_IP1829_GET_QOS_MAXBANDWIDTH,
  IDX_IP1829_SET_QOS_UNIT,
  IDX_IP1829_GET_QOS_UNIT,
  IDX_IP1829_SET_QOS_RATIOVALUE0_DEF,
  IDX_IP1829_GET_QOS_RATIOVALUE0_DEF,
  IDX_IP1829_SET_QOS_SBM_DBM,
  IDX_IP1829_GET_QOS_SBM_DBM,
  IDX_IP1829_SET_QOS_DBM_EN,
  IDX_IP1829_GET_QOS_DBM_EN,
  IDX_IP1829_SET_QOS_EGRESSCONTROL,
  IDX_IP1829_GET_QOS_EGRESSCONTROL,

  IDX_IP1829_SET_QOS_REMAP,
  IDX_IP1829_GET_QOS_REMAP,
  NUM_IP1829_QOS

};
#define ID_IP1829_QOS(idx)	\
	MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_QOS, _CMDID_SUB_QOS, idx)

#define ID_IP1829_SET_QOS_AGING_FUNCTION \
	ID_IP1829_QOS(IDX_IP1829_SET_QOS_AGING_FUNCTION)
#define ID_IP1829_GET_QOS_AGING_FUNCTION \
	ID_IP1829_QOS(IDX_IP1829_GET_QOS_AGING_FUNCTION)
#define ID_IP1829_SET_QOS_AGING_TIME \
	ID_IP1829_QOS(IDX_IP1829_SET_QOS_AGING_TIME)
#define ID_IP1829_GET_QOS_AGING_TIME \
	ID_IP1829_QOS(IDX_IP1829_GET_QOS_AGING_TIME)
#define ID_IP1829_SET_QOS_FASTAGING \
	ID_IP1829_QOS(IDX_IP1829_SET_QOS_FASTAGING)
#define ID_IP1829_GET_QOS_FASTAGING \
	ID_IP1829_QOS(IDX_IP1829_GET_QOS_FASTAGING)

#define ID_IP1829_SET_COS_ACL \
	ID_IP1829_QOS(IDX_IP1829_SET_COS_ACL)
#define ID_IP1829_GET_COS_ACL \
	ID_IP1829_QOS(IDX_IP1829_GET_COS_ACL)
#define ID_IP1829_SET_COS_IGMP \
	ID_IP1829_QOS(IDX_IP1829_SET_COS_IGMP)
#define ID_IP1829_GET_COS_IGMP \
	ID_IP1829_QOS(IDX_IP1829_GET_COS_IGMP)
#define ID_IP1829_SET_COS_IPADDRESS \
	ID_IP1829_QOS(IDX_IP1829_SET_COS_IPADDRESS)
#define ID_IP1829_GET_COS_IPADDRESS \
	ID_IP1829_QOS(IDX_IP1829_GET_COS_IPADDRESS)
#define ID_IP1829_SET_COS_MACADDRESS \
	ID_IP1829_QOS(IDX_IP1829_SET_COS_MACADDRESS)
#define ID_IP1829_GET_COS_MACADDRESS \
	ID_IP1829_QOS(IDX_IP1829_GET_COS_MACADDRESS)
#define ID_IP1829_SET_COS_VID \
	ID_IP1829_QOS(IDX_IP1829_SET_COS_VID)
#define ID_IP1829_GET_COS_VID \
	ID_IP1829_QOS(IDX_IP1829_GET_COS_VID)
#define ID_IP1829_SET_COS_TCPUDPPORT \
	ID_IP1829_QOS(IDX_IP1829_SET_COS_TCPUDPPORT)
#define ID_IP1829_GET_COS_TCPUDPPORT \
	ID_IP1829_QOS(IDX_IP1829_GET_COS_TCPUDPPORT)
#define ID_IP1829_SET_COS_DSCP \
	ID_IP1829_QOS(IDX_IP1829_SET_COS_DSCP)
#define ID_IP1829_GET_COS_DSCP \
	ID_IP1829_QOS(IDX_IP1829_GET_COS_DSCP)
#define ID_IP1829_SET_COS_8021P \
	ID_IP1829_QOS(IDX_IP1829_SET_COS_8021P)
#define ID_IP1829_GET_COS_8021P \
	ID_IP1829_QOS(IDX_IP1829_GET_COS_8021P)
#define ID_IP1829_SET_COS_PHYSICALPORT \
	ID_IP1829_QOS(IDX_IP1829_SET_COS_PHYSICALPORT)
#define ID_IP1829_GET_COS_PHYSICALPORT \
	ID_IP1829_QOS(IDX_IP1829_GET_COS_PHYSICALPORT)
#define ID_IP1829_SET_QOS_8021PEDTION \
	ID_IP1829_QOS(IDX_IP1829_SET_QOS_8021PEDTION)
#define ID_IP1829_GET_QOS_8021PEDTION \
	ID_IP1829_QOS(IDX_IP1829_GET_QOS_8021PEDTION)
#define ID_IP1829_SET_QOS_DSCPBASE_DSCP \
	ID_IP1829_QOS(IDX_IP1829_SET_QOS_DSCPBASE_DSCP)
#define ID_IP1829_GET_QOS_DSCPBASE_DSCP \
	ID_IP1829_QOS(IDX_IP1829_GET_QOS_DSCPBASE_DSCP)
#define ID_IP1829_SET_QOS_DSCPBASE_NOMATCHACTION \
	ID_IP1829_QOS(IDX_IP1829_SET_QOS_DSCPBASE_NOMATCHACTION)
#define ID_IP1829_GET_QOS_DSCPBASE_NOMATCHACTION \
	ID_IP1829_QOS(IDX_IP1829_GET_QOS_DSCPBASE_NOMATCHACTION)
/*#define ID_IP1829_SET_QOS_TCPUDPPORT_ENTRY \
	ID_IP1829_QOS(IDX_IP1829_SET_QOS_TCPUDPPORT_ENTRY)
#define ID_IP1829_GET_QOS_TCPUDPPORT_ENTRY \
	ID_IP1829_QOS(IDX_IP1829_GET_QOS_TCPUDPPORT_ENTRY)
#define ID_IP1829_SET_QOS_TCPUDPPORT_USERDEFINE \
	ID_IP1829_QOS(IDX_IP1829_SET_QOS_TCPUDPPORT_USERDEFINE)
#define ID_IP1829_GET_QOS_TCPUDPPORT_USERDEFINE \
	ID_IP1829_QOS(IDX_IP1829_GET_QOS_TCPUDPPORT_USERDEFINE)*/

#define ID_IP1829_SET_QOSMODE_GROUP_MEMEBER \
	ID_IP1829_QOS(IDX_IP1829_SET_QOSMODE_GROUP_MEMEBER)
#define ID_IP1829_GET_QOSMODE_GROUP_MEMEBER \
	ID_IP1829_QOS(IDX_IP1829_GET_QOSMODE_GROUP_MEMEBER)
#define ID_IP1829_SET_QOSGROUPB_EN \
	ID_IP1829_QOS(IDX_IP1829_SET_QOSGROUPB_EN)
#define ID_IP1829_GET_QOSGROUPB_EN \
	ID_IP1829_QOS(IDX_IP1829_GET_QOSGROUPB_EN)
#define ID_IP1829_SET_QOS_MODE \
	ID_IP1829_QOS(IDX_IP1829_SET_QOS_MODE)
#define ID_IP1829_GET_QOS_MODE \
	ID_IP1829_QOS(IDX_IP1829_GET_QOS_MODE)
#define ID_IP1829_SET_QOS_METHOD \
	ID_IP1829_QOS(IDX_IP1829_SET_QOS_METHOD)
#define ID_IP1829_GET_QOS_METHOD \
	ID_IP1829_QOS(IDX_IP1829_GET_QOS_METHOD)
#define ID_IP1829_SET_QOS_WEIGHT \
	ID_IP1829_QOS(IDX_IP1829_SET_QOS_WEIGHT)
#define ID_IP1829_GET_QOS_WEIGHT \
	ID_IP1829_QOS(IDX_IP1829_GET_QOS_WEIGHT)
#define ID_IP1829_SET_QOS_MAXBANDWIDTH \
	ID_IP1829_QOS(IDX_IP1829_SET_QOS_MAXBANDWIDTH)
#define ID_IP1829_GET_QOS_MAXBANDWIDTH \
	ID_IP1829_QOS(IDX_IP1829_GET_QOS_MAXBANDWIDTH)
#define ID_IP1829_SET_QOS_UNIT \
	ID_IP1829_QOS(IDX_IP1829_SET_QOS_UNIT)
#define ID_IP1829_GET_QOS_UNIT \
	ID_IP1829_QOS(IDX_IP1829_GET_QOS_UNIT)
#define ID_IP1829_SET_QOS_RATIOVALUE0_DEF \
	ID_IP1829_QOS(IDX_IP1829_SET_QOS_RATIOVALUE0_DEF)
#define ID_IP1829_GET_QOS_RATIOVALUE0_DEF \
	ID_IP1829_QOS(IDX_IP1829_GET_QOS_RATIOVALUE0_DEF)
#define ID_IP1829_SET_QOS_SBM_DBM \
	ID_IP1829_QOS(IDX_IP1829_SET_QOS_SBM_DBM)
#define ID_IP1829_GET_QOS_SBM_DBM \
	ID_IP1829_QOS(IDX_IP1829_GET_QOS_SBM_DBM)
#define ID_IP1829_SET_QOS_DBM_EN \
	ID_IP1829_QOS(IDX_IP1829_SET_QOS_DBM_EN)
#define ID_IP1829_GET_QOS_DBM_EN \
	ID_IP1829_QOS(IDX_IP1829_GET_QOS_DBM_EN)

#define ID_IP1829_SET_QOS_EGRESSCONTROL \
	ID_IP1829_QOS(IDX_IP1829_SET_QOS_EGRESSCONTROL)
#define ID_IP1829_GET_QOS_EGRESSCONTROL \
	ID_IP1829_QOS(IDX_IP1829_GET_QOS_EGRESSCONTROL)

#define ID_IP1829_SET_QOS_REMAP \
	ID_IP1829_QOS(IDX_IP1829_SET_QOS_REMAP)
#define ID_IP1829_GET_QOS_REMAP \
	ID_IP1829_QOS(IDX_IP1829_GET_QOS_REMAP)

/*===================================================================*/
#define _CMDID_GRP_ACL		0x04
/*-------------------------------------------------------------------*/
#define _CMDID_SUBG_ACL		0x01
enum{
	IDX_IP1829_ACL_SET_RULE,	//0
	IDX_IP1829_ACL_GET_RULE,
	IDX_IP1829_ACL_CLEAN_TABLE,
	IDX_IP1829_ACL_SET_FUNCTION_EN,
	IDX_IP1829_ACL_GET_FUNCTION_EN,
	IDX_IP1829_ACL_GET_USED_RULES,	//5
	IDX_IP1829_ACL_GET_USED_ENTRIES,
	IDX_IP1829_ACL_SET_BW,
	IDX_IP1829_ACL_GET_BW,
	IDX_IP1829_ACL_SET_DSCP,
	IDX_IP1829_ACL_GET_DSCP,		//10
	IDX_IP1829_ACL_SET_VLAN_GROUP,
	IDX_IP1829_ACL_GET_VLAN_GROUP,
	IDX_IP1829_ACL_SET_VID_REMARK,
	IDX_IP1829_ACL_GET_VID_REMARK,
	NUM_IP1829_ACL	
};
#define ID_IP1829_ACL(idx)	\
	MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_ACL, _CMDID_SUBG_ACL, idx)
#define ID_1829_ACL_SET_RULE \
	ID_IP1829_ACL(IDX_IP1829_ACL_SET_RULE)
#define ID_1829_ACL_GET_RULE \
	ID_IP1829_ACL(IDX_IP1829_ACL_GET_RULE)
#define ID_1829_ACL_CLEAN_TABLE \
	ID_IP1829_ACL(IDX_IP1829_ACL_CLEAN_TABLE)
#define ID_1829_ACL_SET_FUNCTION_EN \
	ID_IP1829_ACL(IDX_IP1829_ACL_SET_FUNCTION_EN)
#define ID_1829_ACL_GET_FUNCTION_EN \
	ID_IP1829_ACL(IDX_IP1829_ACL_GET_FUNCTION_EN)
#define ID_1829_ACL_GET_USED_RULES \
	ID_IP1829_ACL(IDX_IP1829_ACL_GET_USED_RULES)
#define ID_1829_ACL_GET_USED_ENTRIES \
	ID_IP1829_ACL(IDX_IP1829_ACL_GET_USED_ENTRIES)
#define ID_1829_ACL_SET_BW \
	ID_IP1829_ACL(IDX_IP1829_ACL_SET_BW)
#define ID_1829_ACL_GET_BW \
	ID_IP1829_ACL(IDX_IP1829_ACL_GET_BW)
#define ID_1829_ACL_SET_DSCP \
	ID_IP1829_ACL(IDX_IP1829_ACL_SET_DSCP)
#define ID_1829_ACL_GET_DSCP \
	ID_IP1829_ACL(IDX_IP1829_ACL_GET_DSCP)
#define ID_1829_ACL_SET_VLAN_GROUP \
	ID_IP1829_ACL(IDX_IP1829_ACL_SET_VLAN_GROUP)
#define ID_1829_ACL_GET_VLAN_GROUP \
	ID_IP1829_ACL(IDX_IP1829_ACL_GET_VLAN_GROUP)
#define ID_1829_ACL_SET_VID_REMARK \
	ID_IP1829_ACL(IDX_IP1829_ACL_SET_VID_REMARK)
#define ID_1829_ACL_GET_VID_REMARK \
	ID_IP1829_ACL(IDX_IP1829_ACL_GET_VID_REMARK)
/*
#define ID_1829_ACL_ \
	ID_IP1829_ACL(IDX_IP1829_ACL_)*/

/*===================================================================*/
#define _CMDID_GRP_SEC		0x05
/*-------------------------------------------------------------------*/
#define _CMDID_SUBG_IMP		0x01
#define ID_COMMON_SET_IMP_MODE \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_SEC, _CMDID_SUBG_IMP, 0)
#define ID_COMMON_GET_IMP_MODE \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_SEC, _CMDID_SUBG_IMP, 1)
#define ID_COMMON_SET_IMP_PASS_NULL_IP \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_SEC, _CMDID_SUBG_IMP, 2)
#define ID_COMMON_GET_IMP_PASS_NULL_IP \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_SEC, _CMDID_SUBG_IMP, 3)
#define ID_COMMON_SET_IMP_HASHING_ALGORITHM \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_SEC, _CMDID_SUBG_IMP, 4)
#define ID_COMMON_GET_IMP_HASHING_ALGORITHM \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_SEC, _CMDID_SUBG_IMP, 5)
#define ID_COMMON_SET_IMP_PORTS \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_SEC, _CMDID_SUBG_IMP, 6)
#define ID_COMMON_GET_IMP_PORTS \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_SEC, _CMDID_SUBG_IMP, 7)
#define ID_1829_IMP_SET_ENTRY \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_SEC, _CMDID_SUBG_IMP, 0)
#define ID_1829_IMP_GET_ENTRY \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_SEC, _CMDID_SUBG_IMP, 1)

/*-------------------------------------------------------------------*/
#define _CMDID_SUBG_COS		0x2
enum{
	IDX_COMMON_TCPUDP_SET_USER_DEFINE,
	IDX_COMMON_TCPUDP_GET_USER_DEFINE,
	IDX_COMMON_TCPUDP_SET_QUEUE,
	IDX_COMMON_TCPUDP_GET_QUEUE,
	IDX_COMMON_TCPUDP_SET_ENABLE,
	IDX_COMMON_TCPUDP_GET_ENABLE,
	IDX_COMMON_TCPUDP_SET_TCP_ENABLE,
	IDX_COMMON_TCPUDP_GET_TCP_ENABLE,
	IDX_COMMON_TCPUDP_SET_UDP_ENABLE,
	IDX_COMMON_TCPUDP_GET_UDP_ENABLE,
	IDX_COMMON_TCPFLAG_SET_DROP_NULL,
	IDX_COMMON_TCPFLAG_GET_DROP_NULL,
	IDX_COMMON_TCPFLAG_SET_DROP_ALLSET,
	IDX_COMMON_TCPFLAG_GET_DROP_ALLSET,
	IDX_COMMON_TCPFLAG_SET_FLAG,
	IDX_COMMON_TCPFLAG_GET_FLAG,
	IDX_COMMON_TCPFLAG_SET_ACTION,
	IDX_COMMON_TCPFLAG_GET_ACTION,
	IDX_COMMON_TCPFLAG_SET_PORT,
	IDX_COMMON_TCPFLAG_GET_PORT,
	NUM_COMMON_TCPUDP
};
#define ID_COMMON_COS(idx)	\
	MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_SEC, _CMDID_SUBG_COS, idx)

#define	ID_COMMON_TCPUDP_SET_USER_DEFINE \
	ID_COMMON_COS(IDX_COMMON_TCPUDP_SET_USER_DEFINE)
#define	ID_COMMON_TCPUDP_GET_USER_DEFINE \
	ID_COMMON_COS(IDX_COMMON_TCPUDP_GET_USER_DEFINE)
#define	ID_COMMON_TCPUDP_SET_QUEUE \
	ID_COMMON_COS(IDX_COMMON_TCPUDP_SET_QUEUE)
#define	ID_COMMON_TCPUDP_GET_QUEUE \
	ID_COMMON_COS(IDX_COMMON_TCPUDP_GET_QUEUE)
#define	ID_COMMON_TCPUDP_SET_ENABLE \
	ID_COMMON_COS(IDX_COMMON_TCPUDP_SET_ENABLE)
#define	ID_COMMON_TCPUDP_GET_ENABLE \
	ID_COMMON_COS(IDX_COMMON_TCPUDP_GET_ENABLE)
#define	ID_COMMON_TCPUDP_SET_TCP_ENABLE \
	ID_COMMON_COS(IDX_COMMON_TCPUDP_SET_TCP_ENABLE)
#define	ID_COMMON_TCPUDP_GET_TCP_ENABLE \
	ID_COMMON_COS(IDX_COMMON_TCPUDP_GET_TCP_ENABLE)
#define	ID_COMMON_TCPUDP_SET_UDP_ENABLE \
	ID_COMMON_COS(IDX_COMMON_TCPUDP_SET_UDP_ENABLE)
#define	ID_COMMON_TCPUDP_GET_UDP_ENABLE \
	ID_COMMON_COS(IDX_COMMON_TCPUDP_GET_UDP_ENABLE)
#define	ID_COMMON_TCPFLAG_SET_DROP_NULL \
	ID_COMMON_COS(IDX_COMMON_TCPFLAG_SET_DROP_NULL)
#define	ID_COMMON_TCPFLAG_GET_DROP_NULL \
	ID_COMMON_COS(IDX_COMMON_TCPFLAG_GET_DROP_NULL)
#define	ID_COMMON_TCPFLAG_SET_DROP_ALLSET \
	ID_COMMON_COS(IDX_COMMON_TCPFLAG_SET_DROP_ALLSET)
#define	ID_COMMON_TCPFLAG_GET_DROP_ALLSET \
	ID_COMMON_COS(IDX_COMMON_TCPFLAG_GET_DROP_ALLSET)
#define	ID_COMMON_TCPFLAG_SET_FLAG \
	ID_COMMON_COS(IDX_COMMON_TCPFLAG_SET_FLAG)
#define	ID_COMMON_TCPFLAG_GET_FLAG \
	ID_COMMON_COS(IDX_COMMON_TCPFLAG_GET_FLAG)
#define	ID_COMMON_TCPFLAG_SET_ACTION \
	ID_COMMON_COS(IDX_COMMON_TCPFLAG_SET_ACTION)
#define	ID_COMMON_TCPFLAG_GET_ACTION \
	ID_COMMON_COS(IDX_COMMON_TCPFLAG_GET_ACTION)
#define	ID_COMMON_TCPFLAG_SET_PORT \
	ID_COMMON_COS(IDX_COMMON_TCPFLAG_SET_PORT)
#define	ID_COMMON_TCPFLAG_GET_PORT \
	ID_COMMON_COS(IDX_COMMON_TCPFLAG_GET_PORT)

/*===================================================================*/
#define _CMDID_GRP_ADV		0x06
/*-------------------------------------------------------------------*/
#define _CMDID_SUBG_STP		0x1
#define ID_COMMON_MSTP_SET_FUNC \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_ADV, _CMDID_SUBG_STP, 0)
#define ID_COMMON_MSTP_GET_FUNC \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_ADV, _CMDID_SUBG_STP, 1)
#define ID_1829_BPDU_SET_CAP_MODE \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_ADV, _CMDID_SUBG_STP, 0)
#define ID_1829_BPDU_GET_CAP_MODE \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_ADV, _CMDID_SUBG_STP, 1)
#define ID_1829_BPDU_SET_PORT_ACT \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_ADV, _CMDID_SUBG_STP, 2)
#define ID_1829_BPDU_GET_PORT_ACT \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_ADV, _CMDID_SUBG_STP, 3)
#define ID_1829_STP_SET_PORT_STATE \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_ADV, _CMDID_SUBG_STP, 4)
#define ID_1829_STP_GET_PORT_STATE \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_ADV, _CMDID_SUBG_STP, 5)
#define ID_1829_STP_SET_ALL_PORTS_STATE \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_ADV, _CMDID_SUBG_STP, 6)
#define ID_1829_STP_GET_ALL_PORTS_STATE \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_ADV, _CMDID_SUBG_STP, 7)

/*-------------------------------------------------------------------*/
#define _CMDID_SUBG_LACP	0x2
#define ID_COMMON_TRUNK_SET_HASH_METHOD \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_ADV, _CMDID_SUBG_LACP, 0)
#define ID_COMMON_TRUNK_GET_HASH_METHOD \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_ADV, _CMDID_SUBG_LACP, 1)
#define ID_COMMON_TRUNK_SET_MEMBER \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_ADV, _CMDID_SUBG_LACP, 2)
#define ID_COMMON_TRUNK_GET_MEMBER \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_ADV, _CMDID_SUBG_LACP, 3)
#define ID_COMMON_CPU_SET_NOT_CARE_TRUNK_AND_VLAN \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_ADV, _CMDID_SUBG_LACP, 4)
#define ID_COMMON_CPU_GET_NOT_CARE_TRUNK_AND_VLAN \
			MAKECMDID(_CMDID_USG_COMMON, _CMDID_GRP_ADV, _CMDID_SUBG_LACP, 5)
#define IP_1829_TRUNK_SET_HASH_METHOD_SEQ \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_ADV, _CMDID_SUBG_LACP, 0)
#define IP_1829_TRUNK_GET_HASH_METHOD_SEQ \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_ADV, _CMDID_SUBG_LACP, 1)
#define IP_1829_TRUNK_SET_GROUP_COMBINE \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_ADV, _CMDID_SUBG_LACP, 2)
#define IP_1829_TRUNK_GET_GROUP_COMBINE \
			MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_ADV, _CMDID_SUBG_LACP, 3)

/*===================================================================*/
#define _CMDID_GRP_MON		0x07
/*-------------------------------------------------------------------*/
#define _CMDID_SUBG_MIB_COUNTER   0x1
enum{
	IDX_1829_SET_MIB_COUNTER_ENABLE,
	IDX_1829_GET_MIB_COUNTER_ENABLE,
	IDX_1829_GET_MIB_COUNTER_ALL,
	IDX_1829_GET_MIB_COUNTER_BY_PORT,
	IDX_1829_GET_MIB_COUNTER_BY_ITEM,
	NUM_1829_MIB_COUNTER
};
#define ID_COMMON_MIB_COUNTER(idx)	\
	MAKECMDID(_CMDID_USG_IP1829, _CMDID_GRP_MON, _CMDID_SUBG_MIB_COUNTER, idx)

#define	ID_1829_SET_MIB_COUNTER_ENABLE \
	ID_COMMON_MIB_COUNTER(IDX_1829_SET_MIB_COUNTER_ENABLE)
#define	ID_1829_GET_MIB_COUNTER_ENABLE \
	ID_COMMON_MIB_COUNTER(IDX_1829_GET_MIB_COUNTER_ENABLE)
#define	ID_1829_GET_MIB_COUNTER_ALL \
	ID_COMMON_MIB_COUNTER(IDX_1829_GET_MIB_COUNTER_ALL)
#define	ID_1829_GET_MIB_COUNTER_BY_PORT \
	ID_COMMON_MIB_COUNTER(IDX_1829_GET_MIB_COUNTER_BY_PORT)
#define	ID_1829_GET_MIB_COUNTER_BY_ITEM \
	ID_COMMON_MIB_COUNTER(IDX_1829_GET_MIB_COUNTER_BY_ITEM)


#endif		/* IP1829_H */
