#pragma once

struct QnMultiserverRequestData;
struct QnChunksRequestData;
struct QnGetBookmarksRequestData;
struct QnGetBookmarkTagsRequestData;
struct QnUpdateBookmarkRequestData;
struct QnDeleteBookmarkRequestData;