/* soapCredentialBindingProxy.cpp
   Generated by gSOAP 2.8.66 for ../result/interim/onvif.h_

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#include "soapCredentialBindingProxy.h"

CredentialBindingProxy::CredentialBindingProxy()
{
    this->soap = soap_new();
    this->soap_own = true;
    CredentialBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

CredentialBindingProxy::CredentialBindingProxy(const CredentialBindingProxy& rhs)
{
    this->soap = rhs.soap;
    this->soap_own = false;
    this->soap_endpoint = rhs.soap_endpoint;
}

CredentialBindingProxy::CredentialBindingProxy(struct soap *_soap)
{
    this->soap = _soap;
    this->soap_own = false;
    CredentialBindingProxy_init(_soap->imode, _soap->omode);
}

CredentialBindingProxy::CredentialBindingProxy(const char *endpoint)
{
    this->soap = soap_new();
    this->soap_own = true;
    CredentialBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
    soap_endpoint = endpoint;
}

CredentialBindingProxy::CredentialBindingProxy(soap_mode iomode)
{
    this->soap = soap_new();
    this->soap_own = true;
    CredentialBindingProxy_init(iomode, iomode);
}

CredentialBindingProxy::CredentialBindingProxy(const char *endpoint, soap_mode iomode)
{
    this->soap = soap_new();
    this->soap_own = true;
    CredentialBindingProxy_init(iomode, iomode);
    soap_endpoint = endpoint;
}

CredentialBindingProxy::CredentialBindingProxy(soap_mode imode, soap_mode omode)
{
    this->soap = soap_new();
    this->soap_own = true;
    CredentialBindingProxy_init(imode, omode);
}

CredentialBindingProxy::~CredentialBindingProxy()
{
    if (this->soap_own)
        soap_free(this->soap);
}

void CredentialBindingProxy::CredentialBindingProxy_init(soap_mode imode, soap_mode omode)
{
    soap_imode(this->soap, imode);
    soap_omode(this->soap, omode);
    soap_endpoint = NULL;
    static const struct Namespace namespaces[] = {
        {"SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://schemas.xmlsoap.org/soap/envelope/", NULL},
        {"SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://schemas.xmlsoap.org/soap/encoding/", NULL},
        {"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
        {"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
        {"chan", "http://schemas.microsoft.com/ws/2005/02/duplex", NULL, NULL},
        {"wsa5", "http://www.w3.org/2005/08/addressing", "http://schemas.xmlsoap.org/ws/2004/08/addressing", NULL},
        {"wsdd", "http://schemas.xmlsoap.org/ws/2005/04/discovery", NULL, NULL},
        {"c14n", "http://www.w3.org/2001/10/xml-exc-c14n#", NULL, NULL},
        {"ds", "http://www.w3.org/2000/09/xmldsig#", NULL, NULL},
        {"saml1", "urn:oasis:names:tc:SAML:1.0:assertion", NULL, NULL},
        {"saml2", "urn:oasis:names:tc:SAML:2.0:assertion", NULL, NULL},
        {"wsu", "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd", NULL, NULL},
        {"xenc", "http://www.w3.org/2001/04/xmlenc#", NULL, NULL},
        {"wsc", "http://docs.oasis-open.org/ws-sx/ws-secureconversation/200512", NULL, NULL},
        {"wsse", "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd", "http://docs.oasis-open.org/wss/oasis-wss-wssecurity-secext-1.1.xsd", NULL},
        {"onvifPacs", "http://www.onvif.org/ver10/pacs", NULL, NULL},
        {"xmime", "http://tempuri.org/xmime.xsd", NULL, NULL},
        {"xop", "http://www.w3.org/2004/08/xop/include", NULL, NULL},
        {"onvifXsd", "http://www.onvif.org/ver10/schema", NULL, NULL},
        {"oasisWsrf", "http://docs.oasis-open.org/wsrf/bf-2", NULL, NULL},
        {"oasisWsnT1", "http://docs.oasis-open.org/wsn/t-1", NULL, NULL},
        {"oasisWsrfR2", "http://docs.oasis-open.org/wsrf/r-2", NULL, NULL},
        {"onvifAccessControl", "http://www.onvif.org/ver10/accesscontrol/wsdl", NULL, NULL},
        {"onvifAccessRules", "http://www.onvif.org/ver10/accessrules/wsdl", NULL, NULL},
        {"onvifActionEngine", "http://www.onvif.org/ver10/actionengine/wsdl", NULL, NULL},
        {"onvifAdvancedSecurity-assb", "http://www.onvif.org/ver10/advancedsecurity/wsdl/AdvancedSecurityServiceBinding", NULL, NULL},
        {"onvifAdvancedSecurity-db", "http://www.onvif.org/ver10/advancedsecurity/wsdl/Dot1XBinding", NULL, NULL},
        {"onvifAdvancedSecurity-kb", "http://www.onvif.org/ver10/advancedsecurity/wsdl/KeystoreBinding", NULL, NULL},
        {"onvifAdvancedSecurity-tsb", "http://www.onvif.org/ver10/advancedsecurity/wsdl/TLSServerBinding", NULL, NULL},
        {"onvifAdvancedSecurity", "http://www.onvif.org/ver10/advancedsecurity/wsdl", NULL, NULL},
        {"onvifAnalytics-aeb", "http://www.onvif.org/ver20/analytics/wsdl/AnalyticsEngineBinding", NULL, NULL},
        {"onvifAnalytics-reb", "http://www.onvif.org/ver20/analytics/wsdl/RuleEngineBinding", NULL, NULL},
        {"onvifAnalytics", "http://www.onvif.org/ver20/analytics/wsdl", NULL, NULL},
        {"onvifAnalyticsDevice", "http://www.onvif.org/ver10/analyticsdevice/wsdl", NULL, NULL},
        {"onvifCredential", "http://www.onvif.org/ver10/credential/wsdl", NULL, NULL},
        {"onvifDevice", "http://www.onvif.org/ver10/device/wsdl", NULL, NULL},
        {"onvifDeviceIO", "http://www.onvif.org/ver10/deviceIO/wsdl", NULL, NULL},
        {"onvifDisplay", "http://www.onvif.org/ver10/display/wsdl", NULL, NULL},
        {"onvifDoorControl", "http://www.onvif.org/ver10/doorcontrol/wsdl", NULL, NULL},
        {"onvifEvents-cpb", "http://www.onvif.org/ver10/events/wsdl/CreatePullPointBinding", NULL, NULL},
        {"onvifEvents-eb", "http://www.onvif.org/ver10/events/wsdl/EventBinding", NULL, NULL},
        {"onvifEvents-ncb", "http://www.onvif.org/ver10/events/wsdl/NotificationConsumerBinding", NULL, NULL},
        {"onvifEvents-npb", "http://www.onvif.org/ver10/events/wsdl/NotificationProducerBinding", NULL, NULL},
        {"onvifEvents-ppb", "http://www.onvif.org/ver10/events/wsdl/PullPointBinding", NULL, NULL},
        {"onvifEvents", "http://www.onvif.org/ver10/events/wsdl", NULL, NULL},
        {"onvifEvents-pps", "http://www.onvif.org/ver10/events/wsdl/PullPointSubscriptionBinding", NULL, NULL},
        {"onvifEvents-psmb", "http://www.onvif.org/ver10/events/wsdl/PausableSubscriptionManagerBinding", NULL, NULL},
        {"oasisWsnB2", "http://docs.oasis-open.org/wsn/b-2", NULL, NULL},
        {"onvifEvents-smb", "http://www.onvif.org/ver10/events/wsdl/SubscriptionManagerBinding", NULL, NULL},
        {"onvifImg", "http://www.onvif.org/ver20/imaging/wsdl", NULL, NULL},
        {"onvifMedia", "http://www.onvif.org/ver10/media/wsdl", NULL, NULL},
        {"onvifMedia2", "http://www.onvif.org/ver20/media/wsdl", NULL, NULL},
        {"onvifNetwork-dlb", "http://www.onvif.org/ver10/network/wsdl/DiscoveryLookupBinding", NULL, NULL},
        {"onvifNetwork-rdb", "http://www.onvif.org/ver10/network/wsdl/RemoteDiscoveryBinding", NULL, NULL},
        {"onvifNetwork", "http://www.onvif.org/ver10/network/wsdl", NULL, NULL},
        {"onvifProvisioning", "http://www.onvif.org/ver10/provisioning/wsdl", NULL, NULL},
        {"onvifPtz", "http://www.onvif.org/ver20/ptz/wsdl", NULL, NULL},
        {"onvifReceiver", "http://www.onvif.org/ver10/receiver/wsdl", NULL, NULL},
        {"onvifRecording", "http://www.onvif.org/ver10/recording/wsdl", NULL, NULL},
        {"onvifReplay", "http://www.onvif.org/ver10/replay/wsdl", NULL, NULL},
        {"onvifScedule", "http://www.onvif.org/ver10/schedule/wsdl", NULL, NULL},
        {"onvifSearch", "http://www.onvif.org/ver10/search/wsdl", NULL, NULL},
        {"onvifThermal", "http://www.onvif.org/ver10/thermal/wsdl", NULL, NULL},
        {NULL, NULL, NULL, NULL}
    };
    soap_set_namespaces(this->soap, namespaces);
}

CredentialBindingProxy *CredentialBindingProxy::copy()
{
    CredentialBindingProxy *dup = SOAP_NEW_UNMANAGED(CredentialBindingProxy);
    if (dup)
    {
        soap_done(dup->soap);
        soap_copy_context(dup->soap, this->soap);
    }
    return dup;
}

CredentialBindingProxy& CredentialBindingProxy::operator=(const CredentialBindingProxy& rhs)
{
    if (this->soap != rhs.soap)
    {
        if (this->soap_own)
            soap_free(this->soap);
        this->soap = rhs.soap;
        this->soap_own = false;
        this->soap_endpoint = rhs.soap_endpoint;
    }
    return *this;
}

void CredentialBindingProxy::destroy()
{
    soap_destroy(this->soap);
    soap_end(this->soap);
}

void CredentialBindingProxy::reset()
{
    this->destroy();
    soap_done(this->soap);
    soap_initialize(this->soap);
    CredentialBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

void CredentialBindingProxy::soap_noheader()
{
    this->soap->header = NULL;
}

void CredentialBindingProxy::soap_header(char *wsa5__MessageID, struct wsa5__RelatesToType *wsa5__RelatesTo, struct wsa5__EndpointReferenceType *wsa5__From, struct wsa5__EndpointReferenceType *wsa5__ReplyTo, struct wsa5__EndpointReferenceType *wsa5__FaultTo, char *wsa5__To, char *wsa5__Action, struct chan__ChannelInstanceType *chan__ChannelInstance, struct wsdd__AppSequenceType *wsdd__AppSequence, struct _wsse__Security *wsse__Security, char *SubscriptionId)
{
    ::soap_header(this->soap);
    this->soap->header->wsa5__MessageID = wsa5__MessageID;
    this->soap->header->wsa5__RelatesTo = wsa5__RelatesTo;
    this->soap->header->wsa5__From = wsa5__From;
    this->soap->header->wsa5__ReplyTo = wsa5__ReplyTo;
    this->soap->header->wsa5__FaultTo = wsa5__FaultTo;
    this->soap->header->wsa5__To = wsa5__To;
    this->soap->header->wsa5__Action = wsa5__Action;
    this->soap->header->chan__ChannelInstance = chan__ChannelInstance;
    this->soap->header->wsdd__AppSequence = wsdd__AppSequence;
    this->soap->header->wsse__Security = wsse__Security;
    this->soap->header->SubscriptionId = SubscriptionId;
}

::SOAP_ENV__Header *CredentialBindingProxy::soap_header()
{
    return this->soap->header;
}

::SOAP_ENV__Fault *CredentialBindingProxy::soap_fault()
{
    return this->soap->fault;
}

const char *CredentialBindingProxy::soap_fault_string()
{
    return *soap_faultstring(this->soap);
}

const char *CredentialBindingProxy::soap_fault_detail()
{
    return *soap_faultdetail(this->soap);
}

int CredentialBindingProxy::soap_close_socket()
{
    return soap_closesock(this->soap);
}

int CredentialBindingProxy::soap_force_close_socket()
{
    return soap_force_closesock(this->soap);
}

void CredentialBindingProxy::soap_print_fault(FILE *fd)
{
    ::soap_print_fault(this->soap, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void CredentialBindingProxy::soap_stream_fault(std::ostream& os)
{
    ::soap_stream_fault(this->soap, os);
}
#endif

char *CredentialBindingProxy::soap_sprint_fault(char *buf, size_t len)
{
    return ::soap_sprint_fault(this->soap, buf, len);
}
#endif

int CredentialBindingProxy::GetServiceCapabilities(const char *endpoint, const char *soap_action, _onvifCredential__GetServiceCapabilities *onvifCredential__GetServiceCapabilities, _onvifCredential__GetServiceCapabilitiesResponse &onvifCredential__GetServiceCapabilitiesResponse)
{
    struct __onvifCredential__GetServiceCapabilities soap_tmp___onvifCredential__GetServiceCapabilities;
    if (endpoint)
        soap_endpoint = endpoint;
    if (soap_action == NULL)
        soap_action = "http://www.onvif.org/ver10/credential/wsdl/GetServiceCapabilities";
    soap_tmp___onvifCredential__GetServiceCapabilities.onvifCredential__GetServiceCapabilities = onvifCredential__GetServiceCapabilities;
    soap_begin(soap);
    soap->encodingStyle = NULL;
    soap_serializeheader(soap);
    soap_serialize___onvifCredential__GetServiceCapabilities(soap, &soap_tmp___onvifCredential__GetServiceCapabilities);
    if (soap_begin_count(soap))
        return soap->error;
    if (soap->mode & SOAP_IO_LENGTH)
    {
        if (soap_envelope_begin_out(soap)
         || soap_putheader(soap)
         || soap_body_begin_out(soap)
         || soap_put___onvifCredential__GetServiceCapabilities(soap, &soap_tmp___onvifCredential__GetServiceCapabilities, "-onvifCredential:GetServiceCapabilities", "")
         || soap_body_end_out(soap)
         || soap_envelope_end_out(soap))
             return soap->error;
    }
    if (soap_end_count(soap))
        return soap->error;
    if (soap_connect(soap, soap_endpoint, soap_action)
     || soap_envelope_begin_out(soap)
     || soap_putheader(soap)
     || soap_body_begin_out(soap)
     || soap_put___onvifCredential__GetServiceCapabilities(soap, &soap_tmp___onvifCredential__GetServiceCapabilities, "-onvifCredential:GetServiceCapabilities", "")
     || soap_body_end_out(soap)
     || soap_envelope_end_out(soap)
     || soap_end_send(soap))
        return soap_closesock(soap);
    if (!static_cast<_onvifCredential__GetServiceCapabilitiesResponse*>(&onvifCredential__GetServiceCapabilitiesResponse)) // NULL ref?
        return soap_closesock(soap);
    onvifCredential__GetServiceCapabilitiesResponse.soap_default(soap);
    if (soap_begin_recv(soap)
     || soap_envelope_begin_in(soap)
     || soap_recv_header(soap)
     || soap_body_begin_in(soap))
        return soap_closesock(soap);
    onvifCredential__GetServiceCapabilitiesResponse.soap_get(soap, "onvifCredential:GetServiceCapabilitiesResponse", NULL);
    if (soap->error)
        return soap_recv_fault(soap, 0);
    if (soap_body_end_in(soap)
     || soap_envelope_end_in(soap)
     || soap_end_recv(soap))
        return soap_closesock(soap);
    return soap_closesock(soap);
}

int CredentialBindingProxy::GetSupportedFormatTypes(const char *endpoint, const char *soap_action, _onvifCredential__GetSupportedFormatTypes *onvifCredential__GetSupportedFormatTypes, _onvifCredential__GetSupportedFormatTypesResponse &onvifCredential__GetSupportedFormatTypesResponse)
{
    struct __onvifCredential__GetSupportedFormatTypes soap_tmp___onvifCredential__GetSupportedFormatTypes;
    if (endpoint)
        soap_endpoint = endpoint;
    if (soap_action == NULL)
        soap_action = "http://www.onvif.org/ver10/credential/wsdl/GetSupportedFormatTypes";
    soap_tmp___onvifCredential__GetSupportedFormatTypes.onvifCredential__GetSupportedFormatTypes = onvifCredential__GetSupportedFormatTypes;
    soap_begin(soap);
    soap->encodingStyle = NULL;
    soap_serializeheader(soap);
    soap_serialize___onvifCredential__GetSupportedFormatTypes(soap, &soap_tmp___onvifCredential__GetSupportedFormatTypes);
    if (soap_begin_count(soap))
        return soap->error;
    if (soap->mode & SOAP_IO_LENGTH)
    {
        if (soap_envelope_begin_out(soap)
         || soap_putheader(soap)
         || soap_body_begin_out(soap)
         || soap_put___onvifCredential__GetSupportedFormatTypes(soap, &soap_tmp___onvifCredential__GetSupportedFormatTypes, "-onvifCredential:GetSupportedFormatTypes", "")
         || soap_body_end_out(soap)
         || soap_envelope_end_out(soap))
             return soap->error;
    }
    if (soap_end_count(soap))
        return soap->error;
    if (soap_connect(soap, soap_endpoint, soap_action)
     || soap_envelope_begin_out(soap)
     || soap_putheader(soap)
     || soap_body_begin_out(soap)
     || soap_put___onvifCredential__GetSupportedFormatTypes(soap, &soap_tmp___onvifCredential__GetSupportedFormatTypes, "-onvifCredential:GetSupportedFormatTypes", "")
     || soap_body_end_out(soap)
     || soap_envelope_end_out(soap)
     || soap_end_send(soap))
        return soap_closesock(soap);
    if (!static_cast<_onvifCredential__GetSupportedFormatTypesResponse*>(&onvifCredential__GetSupportedFormatTypesResponse)) // NULL ref?
        return soap_closesock(soap);
    onvifCredential__GetSupportedFormatTypesResponse.soap_default(soap);
    if (soap_begin_recv(soap)
     || soap_envelope_begin_in(soap)
     || soap_recv_header(soap)
     || soap_body_begin_in(soap))
        return soap_closesock(soap);
    onvifCredential__GetSupportedFormatTypesResponse.soap_get(soap, "onvifCredential:GetSupportedFormatTypesResponse", NULL);
    if (soap->error)
        return soap_recv_fault(soap, 0);
    if (soap_body_end_in(soap)
     || soap_envelope_end_in(soap)
     || soap_end_recv(soap))
        return soap_closesock(soap);
    return soap_closesock(soap);
}

int CredentialBindingProxy::GetCredentialInfo(const char *endpoint, const char *soap_action, _onvifCredential__GetCredentialInfo *onvifCredential__GetCredentialInfo, _onvifCredential__GetCredentialInfoResponse &onvifCredential__GetCredentialInfoResponse)
{
    struct __onvifCredential__GetCredentialInfo soap_tmp___onvifCredential__GetCredentialInfo;
    if (endpoint)
        soap_endpoint = endpoint;
    if (soap_action == NULL)
        soap_action = "http://www.onvif.org/ver10/credential/wsdl/GetCredentialInfo";
    soap_tmp___onvifCredential__GetCredentialInfo.onvifCredential__GetCredentialInfo = onvifCredential__GetCredentialInfo;
    soap_begin(soap);
    soap->encodingStyle = NULL;
    soap_serializeheader(soap);
    soap_serialize___onvifCredential__GetCredentialInfo(soap, &soap_tmp___onvifCredential__GetCredentialInfo);
    if (soap_begin_count(soap))
        return soap->error;
    if (soap->mode & SOAP_IO_LENGTH)
    {
        if (soap_envelope_begin_out(soap)
         || soap_putheader(soap)
         || soap_body_begin_out(soap)
         || soap_put___onvifCredential__GetCredentialInfo(soap, &soap_tmp___onvifCredential__GetCredentialInfo, "-onvifCredential:GetCredentialInfo", "")
         || soap_body_end_out(soap)
         || soap_envelope_end_out(soap))
             return soap->error;
    }
    if (soap_end_count(soap))
        return soap->error;
    if (soap_connect(soap, soap_endpoint, soap_action)
     || soap_envelope_begin_out(soap)
     || soap_putheader(soap)
     || soap_body_begin_out(soap)
     || soap_put___onvifCredential__GetCredentialInfo(soap, &soap_tmp___onvifCredential__GetCredentialInfo, "-onvifCredential:GetCredentialInfo", "")
     || soap_body_end_out(soap)
     || soap_envelope_end_out(soap)
     || soap_end_send(soap))
        return soap_closesock(soap);
    if (!static_cast<_onvifCredential__GetCredentialInfoResponse*>(&onvifCredential__GetCredentialInfoResponse)) // NULL ref?
        return soap_closesock(soap);
    onvifCredential__GetCredentialInfoResponse.soap_default(soap);
    if (soap_begin_recv(soap)
     || soap_envelope_begin_in(soap)
     || soap_recv_header(soap)
     || soap_body_begin_in(soap))
        return soap_closesock(soap);
    onvifCredential__GetCredentialInfoResponse.soap_get(soap, "onvifCredential:GetCredentialInfoResponse", NULL);
    if (soap->error)
        return soap_recv_fault(soap, 0);
    if (soap_body_end_in(soap)
     || soap_envelope_end_in(soap)
     || soap_end_recv(soap))
        return soap_closesock(soap);
    return soap_closesock(soap);
}

int CredentialBindingProxy::GetCredentialInfoList(const char *endpoint, const char *soap_action, _onvifCredential__GetCredentialInfoList *onvifCredential__GetCredentialInfoList, _onvifCredential__GetCredentialInfoListResponse &onvifCredential__GetCredentialInfoListResponse)
{
    struct __onvifCredential__GetCredentialInfoList soap_tmp___onvifCredential__GetCredentialInfoList;
    if (endpoint)
        soap_endpoint = endpoint;
    if (soap_action == NULL)
        soap_action = "http://www.onvif.org/ver10/credential/wsdl/GetCredentialInfoList";
    soap_tmp___onvifCredential__GetCredentialInfoList.onvifCredential__GetCredentialInfoList = onvifCredential__GetCredentialInfoList;
    soap_begin(soap);
    soap->encodingStyle = NULL;
    soap_serializeheader(soap);
    soap_serialize___onvifCredential__GetCredentialInfoList(soap, &soap_tmp___onvifCredential__GetCredentialInfoList);
    if (soap_begin_count(soap))
        return soap->error;
    if (soap->mode & SOAP_IO_LENGTH)
    {
        if (soap_envelope_begin_out(soap)
         || soap_putheader(soap)
         || soap_body_begin_out(soap)
         || soap_put___onvifCredential__GetCredentialInfoList(soap, &soap_tmp___onvifCredential__GetCredentialInfoList, "-onvifCredential:GetCredentialInfoList", "")
         || soap_body_end_out(soap)
         || soap_envelope_end_out(soap))
             return soap->error;
    }
    if (soap_end_count(soap))
        return soap->error;
    if (soap_connect(soap, soap_endpoint, soap_action)
     || soap_envelope_begin_out(soap)
     || soap_putheader(soap)
     || soap_body_begin_out(soap)
     || soap_put___onvifCredential__GetCredentialInfoList(soap, &soap_tmp___onvifCredential__GetCredentialInfoList, "-onvifCredential:GetCredentialInfoList", "")
     || soap_body_end_out(soap)
     || soap_envelope_end_out(soap)
     || soap_end_send(soap))
        return soap_closesock(soap);
    if (!static_cast<_onvifCredential__GetCredentialInfoListResponse*>(&onvifCredential__GetCredentialInfoListResponse)) // NULL ref?
        return soap_closesock(soap);
    onvifCredential__GetCredentialInfoListResponse.soap_default(soap);
    if (soap_begin_recv(soap)
     || soap_envelope_begin_in(soap)
     || soap_recv_header(soap)
     || soap_body_begin_in(soap))
        return soap_closesock(soap);
    onvifCredential__GetCredentialInfoListResponse.soap_get(soap, "onvifCredential:GetCredentialInfoListResponse", NULL);
    if (soap->error)
        return soap_recv_fault(soap, 0);
    if (soap_body_end_in(soap)
     || soap_envelope_end_in(soap)
     || soap_end_recv(soap))
        return soap_closesock(soap);
    return soap_closesock(soap);
}

int CredentialBindingProxy::GetCredentials(const char *endpoint, const char *soap_action, _onvifCredential__GetCredentials *onvifCredential__GetCredentials, _onvifCredential__GetCredentialsResponse &onvifCredential__GetCredentialsResponse)
{
    struct __onvifCredential__GetCredentials soap_tmp___onvifCredential__GetCredentials;
    if (endpoint)
        soap_endpoint = endpoint;
    if (soap_action == NULL)
        soap_action = "http://www.onvif.org/ver10/credential/wsdl/GetCredentials";
    soap_tmp___onvifCredential__GetCredentials.onvifCredential__GetCredentials = onvifCredential__GetCredentials;
    soap_begin(soap);
    soap->encodingStyle = NULL;
    soap_serializeheader(soap);
    soap_serialize___onvifCredential__GetCredentials(soap, &soap_tmp___onvifCredential__GetCredentials);
    if (soap_begin_count(soap))
        return soap->error;
    if (soap->mode & SOAP_IO_LENGTH)
    {
        if (soap_envelope_begin_out(soap)
         || soap_putheader(soap)
         || soap_body_begin_out(soap)
         || soap_put___onvifCredential__GetCredentials(soap, &soap_tmp___onvifCredential__GetCredentials, "-onvifCredential:GetCredentials", "")
         || soap_body_end_out(soap)
         || soap_envelope_end_out(soap))
             return soap->error;
    }
    if (soap_end_count(soap))
        return soap->error;
    if (soap_connect(soap, soap_endpoint, soap_action)
     || soap_envelope_begin_out(soap)
     || soap_putheader(soap)
     || soap_body_begin_out(soap)
     || soap_put___onvifCredential__GetCredentials(soap, &soap_tmp___onvifCredential__GetCredentials, "-onvifCredential:GetCredentials", "")
     || soap_body_end_out(soap)
     || soap_envelope_end_out(soap)
     || soap_end_send(soap))
        return soap_closesock(soap);
    if (!static_cast<_onvifCredential__GetCredentialsResponse*>(&onvifCredential__GetCredentialsResponse)) // NULL ref?
        return soap_closesock(soap);
    onvifCredential__GetCredentialsResponse.soap_default(soap);
    if (soap_begin_recv(soap)
     || soap_envelope_begin_in(soap)
     || soap_recv_header(soap)
     || soap_body_begin_in(soap))
        return soap_closesock(soap);
    onvifCredential__GetCredentialsResponse.soap_get(soap, "onvifCredential:GetCredentialsResponse", NULL);
    if (soap->error)
        return soap_recv_fault(soap, 0);
    if (soap_body_end_in(soap)
     || soap_envelope_end_in(soap)
     || soap_end_recv(soap))
        return soap_closesock(soap);
    return soap_closesock(soap);
}

int CredentialBindingProxy::GetCredentialList(const char *endpoint, const char *soap_action, _onvifCredential__GetCredentialList *onvifCredential__GetCredentialList, _onvifCredential__GetCredentialListResponse &onvifCredential__GetCredentialListResponse)
{
    struct __onvifCredential__GetCredentialList soap_tmp___onvifCredential__GetCredentialList;
    if (endpoint)
        soap_endpoint = endpoint;
    if (soap_action == NULL)
        soap_action = "http://www.onvif.org/ver10/credential/wsdl/GetCredentialList";
    soap_tmp___onvifCredential__GetCredentialList.onvifCredential__GetCredentialList = onvifCredential__GetCredentialList;
    soap_begin(soap);
    soap->encodingStyle = NULL;
    soap_serializeheader(soap);
    soap_serialize___onvifCredential__GetCredentialList(soap, &soap_tmp___onvifCredential__GetCredentialList);
    if (soap_begin_count(soap))
        return soap->error;
    if (soap->mode & SOAP_IO_LENGTH)
    {
        if (soap_envelope_begin_out(soap)
         || soap_putheader(soap)
         || soap_body_begin_out(soap)
         || soap_put___onvifCredential__GetCredentialList(soap, &soap_tmp___onvifCredential__GetCredentialList, "-onvifCredential:GetCredentialList", "")
         || soap_body_end_out(soap)
         || soap_envelope_end_out(soap))
             return soap->error;
    }
    if (soap_end_count(soap))
        return soap->error;
    if (soap_connect(soap, soap_endpoint, soap_action)
     || soap_envelope_begin_out(soap)
     || soap_putheader(soap)
     || soap_body_begin_out(soap)
     || soap_put___onvifCredential__GetCredentialList(soap, &soap_tmp___onvifCredential__GetCredentialList, "-onvifCredential:GetCredentialList", "")
     || soap_body_end_out(soap)
     || soap_envelope_end_out(soap)
     || soap_end_send(soap))
        return soap_closesock(soap);
    if (!static_cast<_onvifCredential__GetCredentialListResponse*>(&onvifCredential__GetCredentialListResponse)) // NULL ref?
        return soap_closesock(soap);
    onvifCredential__GetCredentialListResponse.soap_default(soap);
    if (soap_begin_recv(soap)
     || soap_envelope_begin_in(soap)
     || soap_recv_header(soap)
     || soap_body_begin_in(soap))
        return soap_closesock(soap);
    onvifCredential__GetCredentialListResponse.soap_get(soap, "onvifCredential:GetCredentialListResponse", NULL);
    if (soap->error)
        return soap_recv_fault(soap, 0);
    if (soap_body_end_in(soap)
     || soap_envelope_end_in(soap)
     || soap_end_recv(soap))
        return soap_closesock(soap);
    return soap_closesock(soap);
}

int CredentialBindingProxy::CreateCredential(const char *endpoint, const char *soap_action, _onvifCredential__CreateCredential *onvifCredential__CreateCredential, _onvifCredential__CreateCredentialResponse &onvifCredential__CreateCredentialResponse)
{
    struct __onvifCredential__CreateCredential soap_tmp___onvifCredential__CreateCredential;
    if (endpoint)
        soap_endpoint = endpoint;
    if (soap_action == NULL)
        soap_action = "http://www.onvif.org/ver10/credential/wsdl/CreateCredential";
    soap_tmp___onvifCredential__CreateCredential.onvifCredential__CreateCredential = onvifCredential__CreateCredential;
    soap_begin(soap);
    soap->encodingStyle = NULL;
    soap_serializeheader(soap);
    soap_serialize___onvifCredential__CreateCredential(soap, &soap_tmp___onvifCredential__CreateCredential);
    if (soap_begin_count(soap))
        return soap->error;
    if (soap->mode & SOAP_IO_LENGTH)
    {
        if (soap_envelope_begin_out(soap)
         || soap_putheader(soap)
         || soap_body_begin_out(soap)
         || soap_put___onvifCredential__CreateCredential(soap, &soap_tmp___onvifCredential__CreateCredential, "-onvifCredential:CreateCredential", "")
         || soap_body_end_out(soap)
         || soap_envelope_end_out(soap))
             return soap->error;
    }
    if (soap_end_count(soap))
        return soap->error;
    if (soap_connect(soap, soap_endpoint, soap_action)
     || soap_envelope_begin_out(soap)
     || soap_putheader(soap)
     || soap_body_begin_out(soap)
     || soap_put___onvifCredential__CreateCredential(soap, &soap_tmp___onvifCredential__CreateCredential, "-onvifCredential:CreateCredential", "")
     || soap_body_end_out(soap)
     || soap_envelope_end_out(soap)
     || soap_end_send(soap))
        return soap_closesock(soap);
    if (!static_cast<_onvifCredential__CreateCredentialResponse*>(&onvifCredential__CreateCredentialResponse)) // NULL ref?
        return soap_closesock(soap);
    onvifCredential__CreateCredentialResponse.soap_default(soap);
    if (soap_begin_recv(soap)
     || soap_envelope_begin_in(soap)
     || soap_recv_header(soap)
     || soap_body_begin_in(soap))
        return soap_closesock(soap);
    onvifCredential__CreateCredentialResponse.soap_get(soap, "onvifCredential:CreateCredentialResponse", NULL);
    if (soap->error)
        return soap_recv_fault(soap, 0);
    if (soap_body_end_in(soap)
     || soap_envelope_end_in(soap)
     || soap_end_recv(soap))
        return soap_closesock(soap);
    return soap_closesock(soap);
}

int CredentialBindingProxy::SetCredential(const char *endpoint, const char *soap_action, _onvifCredential__SetCredential *onvifCredential__SetCredential, _onvifCredential__SetCredentialResponse &onvifCredential__SetCredentialResponse)
{
    struct __onvifCredential__SetCredential soap_tmp___onvifCredential__SetCredential;
    if (endpoint)
        soap_endpoint = endpoint;
    if (soap_action == NULL)
        soap_action = "http://www.onvif.org/ver10/credential/wsdl/SetCredential";
    soap_tmp___onvifCredential__SetCredential.onvifCredential__SetCredential = onvifCredential__SetCredential;
    soap_begin(soap);
    soap->encodingStyle = NULL;
    soap_serializeheader(soap);
    soap_serialize___onvifCredential__SetCredential(soap, &soap_tmp___onvifCredential__SetCredential);
    if (soap_begin_count(soap))
        return soap->error;
    if (soap->mode & SOAP_IO_LENGTH)
    {
        if (soap_envelope_begin_out(soap)
         || soap_putheader(soap)
         || soap_body_begin_out(soap)
         || soap_put___onvifCredential__SetCredential(soap, &soap_tmp___onvifCredential__SetCredential, "-onvifCredential:SetCredential", "")
         || soap_body_end_out(soap)
         || soap_envelope_end_out(soap))
             return soap->error;
    }
    if (soap_end_count(soap))
        return soap->error;
    if (soap_connect(soap, soap_endpoint, soap_action)
     || soap_envelope_begin_out(soap)
     || soap_putheader(soap)
     || soap_body_begin_out(soap)
     || soap_put___onvifCredential__SetCredential(soap, &soap_tmp___onvifCredential__SetCredential, "-onvifCredential:SetCredential", "")
     || soap_body_end_out(soap)
     || soap_envelope_end_out(soap)
     || soap_end_send(soap))
        return soap_closesock(soap);
    if (!static_cast<_onvifCredential__SetCredentialResponse*>(&onvifCredential__SetCredentialResponse)) // NULL ref?
        return soap_closesock(soap);
    onvifCredential__SetCredentialResponse.soap_default(soap);
    if (soap_begin_recv(soap)
     || soap_envelope_begin_in(soap)
     || soap_recv_header(soap)
     || soap_body_begin_in(soap))
        return soap_closesock(soap);
    onvifCredential__SetCredentialResponse.soap_get(soap, "onvifCredential:SetCredentialResponse", NULL);
    if (soap->error)
        return soap_recv_fault(soap, 0);
    if (soap_body_end_in(soap)
     || soap_envelope_end_in(soap)
     || soap_end_recv(soap))
        return soap_closesock(soap);
    return soap_closesock(soap);
}

int CredentialBindingProxy::ModifyCredential(const char *endpoint, const char *soap_action, _onvifCredential__ModifyCredential *onvifCredential__ModifyCredential, _onvifCredential__ModifyCredentialResponse &onvifCredential__ModifyCredentialResponse)
{
    struct __onvifCredential__ModifyCredential soap_tmp___onvifCredential__ModifyCredential;
    if (endpoint)
        soap_endpoint = endpoint;
    if (soap_action == NULL)
        soap_action = "http://www.onvif.org/ver10/credential/wsdl/ModifyCredential";
    soap_tmp___onvifCredential__ModifyCredential.onvifCredential__ModifyCredential = onvifCredential__ModifyCredential;
    soap_begin(soap);
    soap->encodingStyle = NULL;
    soap_serializeheader(soap);
    soap_serialize___onvifCredential__ModifyCredential(soap, &soap_tmp___onvifCredential__ModifyCredential);
    if (soap_begin_count(soap))
        return soap->error;
    if (soap->mode & SOAP_IO_LENGTH)
    {
        if (soap_envelope_begin_out(soap)
         || soap_putheader(soap)
         || soap_body_begin_out(soap)
         || soap_put___onvifCredential__ModifyCredential(soap, &soap_tmp___onvifCredential__ModifyCredential, "-onvifCredential:ModifyCredential", "")
         || soap_body_end_out(soap)
         || soap_envelope_end_out(soap))
             return soap->error;
    }
    if (soap_end_count(soap))
        return soap->error;
    if (soap_connect(soap, soap_endpoint, soap_action)
     || soap_envelope_begin_out(soap)
     || soap_putheader(soap)
     || soap_body_begin_out(soap)
     || soap_put___onvifCredential__ModifyCredential(soap, &soap_tmp___onvifCredential__ModifyCredential, "-onvifCredential:ModifyCredential", "")
     || soap_body_end_out(soap)
     || soap_envelope_end_out(soap)
     || soap_end_send(soap))
        return soap_closesock(soap);
    if (!static_cast<_onvifCredential__ModifyCredentialResponse*>(&onvifCredential__ModifyCredentialResponse)) // NULL ref?
        return soap_closesock(soap);
    onvifCredential__ModifyCredentialResponse.soap_default(soap);
    if (soap_begin_recv(soap)
     || soap_envelope_begin_in(soap)
     || soap_recv_header(soap)
     || soap_body_begin_in(soap))
        return soap_closesock(soap);
    onvifCredential__ModifyCredentialResponse.soap_get(soap, "onvifCredential:ModifyCredentialResponse", NULL);
    if (soap->error)
        return soap_recv_fault(soap, 0);
    if (soap_body_end_in(soap)
     || soap_envelope_end_in(soap)
     || soap_end_recv(soap))
        return soap_closesock(soap);
    return soap_closesock(soap);
}

int CredentialBindingProxy::DeleteCredential(const char *endpoint, const char *soap_action, _onvifCredential__DeleteCredential *onvifCredential__DeleteCredential, _onvifCredential__DeleteCredentialResponse &onvifCredential__DeleteCredentialResponse)
{
    struct __onvifCredential__DeleteCredential soap_tmp___onvifCredential__DeleteCredential;
    if (endpoint)
        soap_endpoint = endpoint;
    if (soap_action == NULL)
        soap_action = "http://www.onvif.org/ver10/credential/wsdl/DeleteCredential";
    soap_tmp___onvifCredential__DeleteCredential.onvifCredential__DeleteCredential = onvifCredential__DeleteCredential;
    soap_begin(soap);
    soap->encodingStyle = NULL;
    soap_serializeheader(soap);
    soap_serialize___onvifCredential__DeleteCredential(soap, &soap_tmp___onvifCredential__DeleteCredential);
    if (soap_begin_count(soap))
        return soap->error;
    if (soap->mode & SOAP_IO_LENGTH)
    {
        if (soap_envelope_begin_out(soap)
         || soap_putheader(soap)
         || soap_body_begin_out(soap)
         || soap_put___onvifCredential__DeleteCredential(soap, &soap_tmp___onvifCredential__DeleteCredential, "-onvifCredential:DeleteCredential", "")
         || soap_body_end_out(soap)
         || soap_envelope_end_out(soap))
             return soap->error;
    }
    if (soap_end_count(soap))
        return soap->error;
    if (soap_connect(soap, soap_endpoint, soap_action)
     || soap_envelope_begin_out(soap)
     || soap_putheader(soap)
     || soap_body_begin_out(soap)
     || soap_put___onvifCredential__DeleteCredential(soap, &soap_tmp___onvifCredential__DeleteCredential, "-onvifCredential:DeleteCredential", "")
     || soap_body_end_out(soap)
     || soap_envelope_end_out(soap)
     || soap_end_send(soap))
        return soap_closesock(soap);
    if (!static_cast<_onvifCredential__DeleteCredentialResponse*>(&onvifCredential__DeleteCredentialResponse)) // NULL ref?
        return soap_closesock(soap);
    onvifCredential__DeleteCredentialResponse.soap_default(soap);
    if (soap_begin_recv(soap)
     || soap_envelope_begin_in(soap)
     || soap_recv_header(soap)
     || soap_body_begin_in(soap))
        return soap_closesock(soap);
    onvifCredential__DeleteCredentialResponse.soap_get(soap, "onvifCredential:DeleteCredentialResponse", NULL);
    if (soap->error)
        return soap_recv_fault(soap, 0);
    if (soap_body_end_in(soap)
     || soap_envelope_end_in(soap)
     || soap_end_recv(soap))
        return soap_closesock(soap);
    return soap_closesock(soap);
}

int CredentialBindingProxy::GetCredentialState(const char *endpoint, const char *soap_action, _onvifCredential__GetCredentialState *onvifCredential__GetCredentialState, _onvifCredential__GetCredentialStateResponse &onvifCredential__GetCredentialStateResponse)
{
    struct __onvifCredential__GetCredentialState soap_tmp___onvifCredential__GetCredentialState;
    if (endpoint)
        soap_endpoint = endpoint;
    if (soap_action == NULL)
        soap_action = "http://www.onvif.org/ver10/credential/wsdl/GetCredentialState";
    soap_tmp___onvifCredential__GetCredentialState.onvifCredential__GetCredentialState = onvifCredential__GetCredentialState;
    soap_begin(soap);
    soap->encodingStyle = NULL;
    soap_serializeheader(soap);
    soap_serialize___onvifCredential__GetCredentialState(soap, &soap_tmp___onvifCredential__GetCredentialState);
    if (soap_begin_count(soap))
        return soap->error;
    if (soap->mode & SOAP_IO_LENGTH)
    {
        if (soap_envelope_begin_out(soap)
         || soap_putheader(soap)
         || soap_body_begin_out(soap)
         || soap_put___onvifCredential__GetCredentialState(soap, &soap_tmp___onvifCredential__GetCredentialState, "-onvifCredential:GetCredentialState", "")
         || soap_body_end_out(soap)
         || soap_envelope_end_out(soap))
             return soap->error;
    }
    if (soap_end_count(soap))
        return soap->error;
    if (soap_connect(soap, soap_endpoint, soap_action)
     || soap_envelope_begin_out(soap)
     || soap_putheader(soap)
     || soap_body_begin_out(soap)
     || soap_put___onvifCredential__GetCredentialState(soap, &soap_tmp___onvifCredential__GetCredentialState, "-onvifCredential:GetCredentialState", "")
     || soap_body_end_out(soap)
     || soap_envelope_end_out(soap)
     || soap_end_send(soap))
        return soap_closesock(soap);
    if (!static_cast<_onvifCredential__GetCredentialStateResponse*>(&onvifCredential__GetCredentialStateResponse)) // NULL ref?
        return soap_closesock(soap);
    onvifCredential__GetCredentialStateResponse.soap_default(soap);
    if (soap_begin_recv(soap)
     || soap_envelope_begin_in(soap)
     || soap_recv_header(soap)
     || soap_body_begin_in(soap))
        return soap_closesock(soap);
    onvifCredential__GetCredentialStateResponse.soap_get(soap, "onvifCredential:GetCredentialStateResponse", NULL);
    if (soap->error)
        return soap_recv_fault(soap, 0);
    if (soap_body_end_in(soap)
     || soap_envelope_end_in(soap)
     || soap_end_recv(soap))
        return soap_closesock(soap);
    return soap_closesock(soap);
}

int CredentialBindingProxy::EnableCredential(const char *endpoint, const char *soap_action, _onvifCredential__EnableCredential *onvifCredential__EnableCredential, _onvifCredential__EnableCredentialResponse &onvifCredential__EnableCredentialResponse)
{
    struct __onvifCredential__EnableCredential soap_tmp___onvifCredential__EnableCredential;
    if (endpoint)
        soap_endpoint = endpoint;
    if (soap_action == NULL)
        soap_action = "http://www.onvif.org/ver10/credential/wsdl/EnableCredential";
    soap_tmp___onvifCredential__EnableCredential.onvifCredential__EnableCredential = onvifCredential__EnableCredential;
    soap_begin(soap);
    soap->encodingStyle = NULL;
    soap_serializeheader(soap);
    soap_serialize___onvifCredential__EnableCredential(soap, &soap_tmp___onvifCredential__EnableCredential);
    if (soap_begin_count(soap))
        return soap->error;
    if (soap->mode & SOAP_IO_LENGTH)
    {
        if (soap_envelope_begin_out(soap)
         || soap_putheader(soap)
         || soap_body_begin_out(soap)
         || soap_put___onvifCredential__EnableCredential(soap, &soap_tmp___onvifCredential__EnableCredential, "-onvifCredential:EnableCredential", "")
         || soap_body_end_out(soap)
         || soap_envelope_end_out(soap))
             return soap->error;
    }
    if (soap_end_count(soap))
        return soap->error;
    if (soap_connect(soap, soap_endpoint, soap_action)
     || soap_envelope_begin_out(soap)
     || soap_putheader(soap)
     || soap_body_begin_out(soap)
     || soap_put___onvifCredential__EnableCredential(soap, &soap_tmp___onvifCredential__EnableCredential, "-onvifCredential:EnableCredential", "")
     || soap_body_end_out(soap)
     || soap_envelope_end_out(soap)
     || soap_end_send(soap))
        return soap_closesock(soap);
    if (!static_cast<_onvifCredential__EnableCredentialResponse*>(&onvifCredential__EnableCredentialResponse)) // NULL ref?
        return soap_closesock(soap);
    onvifCredential__EnableCredentialResponse.soap_default(soap);
    if (soap_begin_recv(soap)
     || soap_envelope_begin_in(soap)
     || soap_recv_header(soap)
     || soap_body_begin_in(soap))
        return soap_closesock(soap);
    onvifCredential__EnableCredentialResponse.soap_get(soap, "onvifCredential:EnableCredentialResponse", NULL);
    if (soap->error)
        return soap_recv_fault(soap, 0);
    if (soap_body_end_in(soap)
     || soap_envelope_end_in(soap)
     || soap_end_recv(soap))
        return soap_closesock(soap);
    return soap_closesock(soap);
}

int CredentialBindingProxy::DisableCredential(const char *endpoint, const char *soap_action, _onvifCredential__DisableCredential *onvifCredential__DisableCredential, _onvifCredential__DisableCredentialResponse &onvifCredential__DisableCredentialResponse)
{
    struct __onvifCredential__DisableCredential soap_tmp___onvifCredential__DisableCredential;
    if (endpoint)
        soap_endpoint = endpoint;
    if (soap_action == NULL)
        soap_action = "http://www.onvif.org/ver10/credential/wsdl/DisableCredential";
    soap_tmp___onvifCredential__DisableCredential.onvifCredential__DisableCredential = onvifCredential__DisableCredential;
    soap_begin(soap);
    soap->encodingStyle = NULL;
    soap_serializeheader(soap);
    soap_serialize___onvifCredential__DisableCredential(soap, &soap_tmp___onvifCredential__DisableCredential);
    if (soap_begin_count(soap))
        return soap->error;
    if (soap->mode & SOAP_IO_LENGTH)
    {
        if (soap_envelope_begin_out(soap)
         || soap_putheader(soap)
         || soap_body_begin_out(soap)
         || soap_put___onvifCredential__DisableCredential(soap, &soap_tmp___onvifCredential__DisableCredential, "-onvifCredential:DisableCredential", "")
         || soap_body_end_out(soap)
         || soap_envelope_end_out(soap))
             return soap->error;
    }
    if (soap_end_count(soap))
        return soap->error;
    if (soap_connect(soap, soap_endpoint, soap_action)
     || soap_envelope_begin_out(soap)
     || soap_putheader(soap)
     || soap_body_begin_out(soap)
     || soap_put___onvifCredential__DisableCredential(soap, &soap_tmp___onvifCredential__DisableCredential, "-onvifCredential:DisableCredential", "")
     || soap_body_end_out(soap)
     || soap_envelope_end_out(soap)
     || soap_end_send(soap))
        return soap_closesock(soap);
    if (!static_cast<_onvifCredential__DisableCredentialResponse*>(&onvifCredential__DisableCredentialResponse)) // NULL ref?
        return soap_closesock(soap);
    onvifCredential__DisableCredentialResponse.soap_default(soap);
    if (soap_begin_recv(soap)
     || soap_envelope_begin_in(soap)
     || soap_recv_header(soap)
     || soap_body_begin_in(soap))
        return soap_closesock(soap);
    onvifCredential__DisableCredentialResponse.soap_get(soap, "onvifCredential:DisableCredentialResponse", NULL);
    if (soap->error)
        return soap_recv_fault(soap, 0);
    if (soap_body_end_in(soap)
     || soap_envelope_end_in(soap)
     || soap_end_recv(soap))
        return soap_closesock(soap);
    return soap_closesock(soap);
}

int CredentialBindingProxy::ResetAntipassbackViolation(const char *endpoint, const char *soap_action, _onvifCredential__ResetAntipassbackViolation *onvifCredential__ResetAntipassbackViolation, _onvifCredential__ResetAntipassbackViolationResponse &onvifCredential__ResetAntipassbackViolationResponse)
{
    struct __onvifCredential__ResetAntipassbackViolation soap_tmp___onvifCredential__ResetAntipassbackViolation;
    if (endpoint)
        soap_endpoint = endpoint;
    if (soap_action == NULL)
        soap_action = "http://www.onvif.org/ver10/credential/wsdl/ResetAntipassbackViolation";
    soap_tmp___onvifCredential__ResetAntipassbackViolation.onvifCredential__ResetAntipassbackViolation = onvifCredential__ResetAntipassbackViolation;
    soap_begin(soap);
    soap->encodingStyle = NULL;
    soap_serializeheader(soap);
    soap_serialize___onvifCredential__ResetAntipassbackViolation(soap, &soap_tmp___onvifCredential__ResetAntipassbackViolation);
    if (soap_begin_count(soap))
        return soap->error;
    if (soap->mode & SOAP_IO_LENGTH)
    {
        if (soap_envelope_begin_out(soap)
         || soap_putheader(soap)
         || soap_body_begin_out(soap)
         || soap_put___onvifCredential__ResetAntipassbackViolation(soap, &soap_tmp___onvifCredential__ResetAntipassbackViolation, "-onvifCredential:ResetAntipassbackViolation", "")
         || soap_body_end_out(soap)
         || soap_envelope_end_out(soap))
             return soap->error;
    }
    if (soap_end_count(soap))
        return soap->error;
    if (soap_connect(soap, soap_endpoint, soap_action)
     || soap_envelope_begin_out(soap)
     || soap_putheader(soap)
     || soap_body_begin_out(soap)
     || soap_put___onvifCredential__ResetAntipassbackViolation(soap, &soap_tmp___onvifCredential__ResetAntipassbackViolation, "-onvifCredential:ResetAntipassbackViolation", "")
     || soap_body_end_out(soap)
     || soap_envelope_end_out(soap)
     || soap_end_send(soap))
        return soap_closesock(soap);
    if (!static_cast<_onvifCredential__ResetAntipassbackViolationResponse*>(&onvifCredential__ResetAntipassbackViolationResponse)) // NULL ref?
        return soap_closesock(soap);
    onvifCredential__ResetAntipassbackViolationResponse.soap_default(soap);
    if (soap_begin_recv(soap)
     || soap_envelope_begin_in(soap)
     || soap_recv_header(soap)
     || soap_body_begin_in(soap))
        return soap_closesock(soap);
    onvifCredential__ResetAntipassbackViolationResponse.soap_get(soap, "onvifCredential:ResetAntipassbackViolationResponse", NULL);
    if (soap->error)
        return soap_recv_fault(soap, 0);
    if (soap_body_end_in(soap)
     || soap_envelope_end_in(soap)
     || soap_end_recv(soap))
        return soap_closesock(soap);
    return soap_closesock(soap);
}

int CredentialBindingProxy::GetCredentialIdentifiers(const char *endpoint, const char *soap_action, _onvifCredential__GetCredentialIdentifiers *onvifCredential__GetCredentialIdentifiers, _onvifCredential__GetCredentialIdentifiersResponse &onvifCredential__GetCredentialIdentifiersResponse)
{
    struct __onvifCredential__GetCredentialIdentifiers soap_tmp___onvifCredential__GetCredentialIdentifiers;
    if (endpoint)
        soap_endpoint = endpoint;
    if (soap_action == NULL)
        soap_action = "http://www.onvif.org/ver10/credential/wsdl/GetCredentialIdentifiers";
    soap_tmp___onvifCredential__GetCredentialIdentifiers.onvifCredential__GetCredentialIdentifiers = onvifCredential__GetCredentialIdentifiers;
    soap_begin(soap);
    soap->encodingStyle = NULL;
    soap_serializeheader(soap);
    soap_serialize___onvifCredential__GetCredentialIdentifiers(soap, &soap_tmp___onvifCredential__GetCredentialIdentifiers);
    if (soap_begin_count(soap))
        return soap->error;
    if (soap->mode & SOAP_IO_LENGTH)
    {
        if (soap_envelope_begin_out(soap)
         || soap_putheader(soap)
         || soap_body_begin_out(soap)
         || soap_put___onvifCredential__GetCredentialIdentifiers(soap, &soap_tmp___onvifCredential__GetCredentialIdentifiers, "-onvifCredential:GetCredentialIdentifiers", "")
         || soap_body_end_out(soap)
         || soap_envelope_end_out(soap))
             return soap->error;
    }
    if (soap_end_count(soap))
        return soap->error;
    if (soap_connect(soap, soap_endpoint, soap_action)
     || soap_envelope_begin_out(soap)
     || soap_putheader(soap)
     || soap_body_begin_out(soap)
     || soap_put___onvifCredential__GetCredentialIdentifiers(soap, &soap_tmp___onvifCredential__GetCredentialIdentifiers, "-onvifCredential:GetCredentialIdentifiers", "")
     || soap_body_end_out(soap)
     || soap_envelope_end_out(soap)
     || soap_end_send(soap))
        return soap_closesock(soap);
    if (!static_cast<_onvifCredential__GetCredentialIdentifiersResponse*>(&onvifCredential__GetCredentialIdentifiersResponse)) // NULL ref?
        return soap_closesock(soap);
    onvifCredential__GetCredentialIdentifiersResponse.soap_default(soap);
    if (soap_begin_recv(soap)
     || soap_envelope_begin_in(soap)
     || soap_recv_header(soap)
     || soap_body_begin_in(soap))
        return soap_closesock(soap);
    onvifCredential__GetCredentialIdentifiersResponse.soap_get(soap, "onvifCredential:GetCredentialIdentifiersResponse", NULL);
    if (soap->error)
        return soap_recv_fault(soap, 0);
    if (soap_body_end_in(soap)
     || soap_envelope_end_in(soap)
     || soap_end_recv(soap))
        return soap_closesock(soap);
    return soap_closesock(soap);
}

int CredentialBindingProxy::SetCredentialIdentifier(const char *endpoint, const char *soap_action, _onvifCredential__SetCredentialIdentifier *onvifCredential__SetCredentialIdentifier, _onvifCredential__SetCredentialIdentifierResponse &onvifCredential__SetCredentialIdentifierResponse)
{
    struct __onvifCredential__SetCredentialIdentifier soap_tmp___onvifCredential__SetCredentialIdentifier;
    if (endpoint)
        soap_endpoint = endpoint;
    if (soap_action == NULL)
        soap_action = "http://www.onvif.org/ver10/credential/wsdl/SetCredentialIdentifier";
    soap_tmp___onvifCredential__SetCredentialIdentifier.onvifCredential__SetCredentialIdentifier = onvifCredential__SetCredentialIdentifier;
    soap_begin(soap);
    soap->encodingStyle = NULL;
    soap_serializeheader(soap);
    soap_serialize___onvifCredential__SetCredentialIdentifier(soap, &soap_tmp___onvifCredential__SetCredentialIdentifier);
    if (soap_begin_count(soap))
        return soap->error;
    if (soap->mode & SOAP_IO_LENGTH)
    {
        if (soap_envelope_begin_out(soap)
         || soap_putheader(soap)
         || soap_body_begin_out(soap)
         || soap_put___onvifCredential__SetCredentialIdentifier(soap, &soap_tmp___onvifCredential__SetCredentialIdentifier, "-onvifCredential:SetCredentialIdentifier", "")
         || soap_body_end_out(soap)
         || soap_envelope_end_out(soap))
             return soap->error;
    }
    if (soap_end_count(soap))
        return soap->error;
    if (soap_connect(soap, soap_endpoint, soap_action)
     || soap_envelope_begin_out(soap)
     || soap_putheader(soap)
     || soap_body_begin_out(soap)
     || soap_put___onvifCredential__SetCredentialIdentifier(soap, &soap_tmp___onvifCredential__SetCredentialIdentifier, "-onvifCredential:SetCredentialIdentifier", "")
     || soap_body_end_out(soap)
     || soap_envelope_end_out(soap)
     || soap_end_send(soap))
        return soap_closesock(soap);
    if (!static_cast<_onvifCredential__SetCredentialIdentifierResponse*>(&onvifCredential__SetCredentialIdentifierResponse)) // NULL ref?
        return soap_closesock(soap);
    onvifCredential__SetCredentialIdentifierResponse.soap_default(soap);
    if (soap_begin_recv(soap)
     || soap_envelope_begin_in(soap)
     || soap_recv_header(soap)
     || soap_body_begin_in(soap))
        return soap_closesock(soap);
    onvifCredential__SetCredentialIdentifierResponse.soap_get(soap, "onvifCredential:SetCredentialIdentifierResponse", NULL);
    if (soap->error)
        return soap_recv_fault(soap, 0);
    if (soap_body_end_in(soap)
     || soap_envelope_end_in(soap)
     || soap_end_recv(soap))
        return soap_closesock(soap);
    return soap_closesock(soap);
}

int CredentialBindingProxy::DeleteCredentialIdentifier(const char *endpoint, const char *soap_action, _onvifCredential__DeleteCredentialIdentifier *onvifCredential__DeleteCredentialIdentifier, _onvifCredential__DeleteCredentialIdentifierResponse &onvifCredential__DeleteCredentialIdentifierResponse)
{
    struct __onvifCredential__DeleteCredentialIdentifier soap_tmp___onvifCredential__DeleteCredentialIdentifier;
    if (endpoint)
        soap_endpoint = endpoint;
    if (soap_action == NULL)
        soap_action = "http://www.onvif.org/ver10/credential/wsdl/DeleteCredentialIdentifier";
    soap_tmp___onvifCredential__DeleteCredentialIdentifier.onvifCredential__DeleteCredentialIdentifier = onvifCredential__DeleteCredentialIdentifier;
    soap_begin(soap);
    soap->encodingStyle = NULL;
    soap_serializeheader(soap);
    soap_serialize___onvifCredential__DeleteCredentialIdentifier(soap, &soap_tmp___onvifCredential__DeleteCredentialIdentifier);
    if (soap_begin_count(soap))
        return soap->error;
    if (soap->mode & SOAP_IO_LENGTH)
    {
        if (soap_envelope_begin_out(soap)
         || soap_putheader(soap)
         || soap_body_begin_out(soap)
         || soap_put___onvifCredential__DeleteCredentialIdentifier(soap, &soap_tmp___onvifCredential__DeleteCredentialIdentifier, "-onvifCredential:DeleteCredentialIdentifier", "")
         || soap_body_end_out(soap)
         || soap_envelope_end_out(soap))
             return soap->error;
    }
    if (soap_end_count(soap))
        return soap->error;
    if (soap_connect(soap, soap_endpoint, soap_action)
     || soap_envelope_begin_out(soap)
     || soap_putheader(soap)
     || soap_body_begin_out(soap)
     || soap_put___onvifCredential__DeleteCredentialIdentifier(soap, &soap_tmp___onvifCredential__DeleteCredentialIdentifier, "-onvifCredential:DeleteCredentialIdentifier", "")
     || soap_body_end_out(soap)
     || soap_envelope_end_out(soap)
     || soap_end_send(soap))
        return soap_closesock(soap);
    if (!static_cast<_onvifCredential__DeleteCredentialIdentifierResponse*>(&onvifCredential__DeleteCredentialIdentifierResponse)) // NULL ref?
        return soap_closesock(soap);
    onvifCredential__DeleteCredentialIdentifierResponse.soap_default(soap);
    if (soap_begin_recv(soap)
     || soap_envelope_begin_in(soap)
     || soap_recv_header(soap)
     || soap_body_begin_in(soap))
        return soap_closesock(soap);
    onvifCredential__DeleteCredentialIdentifierResponse.soap_get(soap, "onvifCredential:DeleteCredentialIdentifierResponse", NULL);
    if (soap->error)
        return soap_recv_fault(soap, 0);
    if (soap_body_end_in(soap)
     || soap_envelope_end_in(soap)
     || soap_end_recv(soap))
        return soap_closesock(soap);
    return soap_closesock(soap);
}

int CredentialBindingProxy::GetCredentialAccessProfiles(const char *endpoint, const char *soap_action, _onvifCredential__GetCredentialAccessProfiles *onvifCredential__GetCredentialAccessProfiles, _onvifCredential__GetCredentialAccessProfilesResponse &onvifCredential__GetCredentialAccessProfilesResponse)
{
    struct __onvifCredential__GetCredentialAccessProfiles soap_tmp___onvifCredential__GetCredentialAccessProfiles;
    if (endpoint)
        soap_endpoint = endpoint;
    if (soap_action == NULL)
        soap_action = "http://www.onvif.org/ver10/credential/wsdl/GetCredentialAccessProfiles";
    soap_tmp___onvifCredential__GetCredentialAccessProfiles.onvifCredential__GetCredentialAccessProfiles = onvifCredential__GetCredentialAccessProfiles;
    soap_begin(soap);
    soap->encodingStyle = NULL;
    soap_serializeheader(soap);
    soap_serialize___onvifCredential__GetCredentialAccessProfiles(soap, &soap_tmp___onvifCredential__GetCredentialAccessProfiles);
    if (soap_begin_count(soap))
        return soap->error;
    if (soap->mode & SOAP_IO_LENGTH)
    {
        if (soap_envelope_begin_out(soap)
         || soap_putheader(soap)
         || soap_body_begin_out(soap)
         || soap_put___onvifCredential__GetCredentialAccessProfiles(soap, &soap_tmp___onvifCredential__GetCredentialAccessProfiles, "-onvifCredential:GetCredentialAccessProfiles", "")
         || soap_body_end_out(soap)
         || soap_envelope_end_out(soap))
             return soap->error;
    }
    if (soap_end_count(soap))
        return soap->error;
    if (soap_connect(soap, soap_endpoint, soap_action)
     || soap_envelope_begin_out(soap)
     || soap_putheader(soap)
     || soap_body_begin_out(soap)
     || soap_put___onvifCredential__GetCredentialAccessProfiles(soap, &soap_tmp___onvifCredential__GetCredentialAccessProfiles, "-onvifCredential:GetCredentialAccessProfiles", "")
     || soap_body_end_out(soap)
     || soap_envelope_end_out(soap)
     || soap_end_send(soap))
        return soap_closesock(soap);
    if (!static_cast<_onvifCredential__GetCredentialAccessProfilesResponse*>(&onvifCredential__GetCredentialAccessProfilesResponse)) // NULL ref?
        return soap_closesock(soap);
    onvifCredential__GetCredentialAccessProfilesResponse.soap_default(soap);
    if (soap_begin_recv(soap)
     || soap_envelope_begin_in(soap)
     || soap_recv_header(soap)
     || soap_body_begin_in(soap))
        return soap_closesock(soap);
    onvifCredential__GetCredentialAccessProfilesResponse.soap_get(soap, "onvifCredential:GetCredentialAccessProfilesResponse", NULL);
    if (soap->error)
        return soap_recv_fault(soap, 0);
    if (soap_body_end_in(soap)
     || soap_envelope_end_in(soap)
     || soap_end_recv(soap))
        return soap_closesock(soap);
    return soap_closesock(soap);
}

int CredentialBindingProxy::SetCredentialAccessProfiles(const char *endpoint, const char *soap_action, _onvifCredential__SetCredentialAccessProfiles *onvifCredential__SetCredentialAccessProfiles, _onvifCredential__SetCredentialAccessProfilesResponse &onvifCredential__SetCredentialAccessProfilesResponse)
{
    struct __onvifCredential__SetCredentialAccessProfiles soap_tmp___onvifCredential__SetCredentialAccessProfiles;
    if (endpoint)
        soap_endpoint = endpoint;
    if (soap_action == NULL)
        soap_action = "http://www.onvif.org/ver10/credential/wsdl/SetCredentialAccessProfiles";
    soap_tmp___onvifCredential__SetCredentialAccessProfiles.onvifCredential__SetCredentialAccessProfiles = onvifCredential__SetCredentialAccessProfiles;
    soap_begin(soap);
    soap->encodingStyle = NULL;
    soap_serializeheader(soap);
    soap_serialize___onvifCredential__SetCredentialAccessProfiles(soap, &soap_tmp___onvifCredential__SetCredentialAccessProfiles);
    if (soap_begin_count(soap))
        return soap->error;
    if (soap->mode & SOAP_IO_LENGTH)
    {
        if (soap_envelope_begin_out(soap)
         || soap_putheader(soap)
         || soap_body_begin_out(soap)
         || soap_put___onvifCredential__SetCredentialAccessProfiles(soap, &soap_tmp___onvifCredential__SetCredentialAccessProfiles, "-onvifCredential:SetCredentialAccessProfiles", "")
         || soap_body_end_out(soap)
         || soap_envelope_end_out(soap))
             return soap->error;
    }
    if (soap_end_count(soap))
        return soap->error;
    if (soap_connect(soap, soap_endpoint, soap_action)
     || soap_envelope_begin_out(soap)
     || soap_putheader(soap)
     || soap_body_begin_out(soap)
     || soap_put___onvifCredential__SetCredentialAccessProfiles(soap, &soap_tmp___onvifCredential__SetCredentialAccessProfiles, "-onvifCredential:SetCredentialAccessProfiles", "")
     || soap_body_end_out(soap)
     || soap_envelope_end_out(soap)
     || soap_end_send(soap))
        return soap_closesock(soap);
    if (!static_cast<_onvifCredential__SetCredentialAccessProfilesResponse*>(&onvifCredential__SetCredentialAccessProfilesResponse)) // NULL ref?
        return soap_closesock(soap);
    onvifCredential__SetCredentialAccessProfilesResponse.soap_default(soap);
    if (soap_begin_recv(soap)
     || soap_envelope_begin_in(soap)
     || soap_recv_header(soap)
     || soap_body_begin_in(soap))
        return soap_closesock(soap);
    onvifCredential__SetCredentialAccessProfilesResponse.soap_get(soap, "onvifCredential:SetCredentialAccessProfilesResponse", NULL);
    if (soap->error)
        return soap_recv_fault(soap, 0);
    if (soap_body_end_in(soap)
     || soap_envelope_end_in(soap)
     || soap_end_recv(soap))
        return soap_closesock(soap);
    return soap_closesock(soap);
}

int CredentialBindingProxy::DeleteCredentialAccessProfiles(const char *endpoint, const char *soap_action, _onvifCredential__DeleteCredentialAccessProfiles *onvifCredential__DeleteCredentialAccessProfiles, _onvifCredential__DeleteCredentialAccessProfilesResponse &onvifCredential__DeleteCredentialAccessProfilesResponse)
{
    struct __onvifCredential__DeleteCredentialAccessProfiles soap_tmp___onvifCredential__DeleteCredentialAccessProfiles;
    if (endpoint)
        soap_endpoint = endpoint;
    if (soap_action == NULL)
        soap_action = "http://www.onvif.org/ver10/credential/wsdl/DeleteCredentialAccessProfiles";
    soap_tmp___onvifCredential__DeleteCredentialAccessProfiles.onvifCredential__DeleteCredentialAccessProfiles = onvifCredential__DeleteCredentialAccessProfiles;
    soap_begin(soap);
    soap->encodingStyle = NULL;
    soap_serializeheader(soap);
    soap_serialize___onvifCredential__DeleteCredentialAccessProfiles(soap, &soap_tmp___onvifCredential__DeleteCredentialAccessProfiles);
    if (soap_begin_count(soap))
        return soap->error;
    if (soap->mode & SOAP_IO_LENGTH)
    {
        if (soap_envelope_begin_out(soap)
         || soap_putheader(soap)
         || soap_body_begin_out(soap)
         || soap_put___onvifCredential__DeleteCredentialAccessProfiles(soap, &soap_tmp___onvifCredential__DeleteCredentialAccessProfiles, "-onvifCredential:DeleteCredentialAccessProfiles", "")
         || soap_body_end_out(soap)
         || soap_envelope_end_out(soap))
             return soap->error;
    }
    if (soap_end_count(soap))
        return soap->error;
    if (soap_connect(soap, soap_endpoint, soap_action)
     || soap_envelope_begin_out(soap)
     || soap_putheader(soap)
     || soap_body_begin_out(soap)
     || soap_put___onvifCredential__DeleteCredentialAccessProfiles(soap, &soap_tmp___onvifCredential__DeleteCredentialAccessProfiles, "-onvifCredential:DeleteCredentialAccessProfiles", "")
     || soap_body_end_out(soap)
     || soap_envelope_end_out(soap)
     || soap_end_send(soap))
        return soap_closesock(soap);
    if (!static_cast<_onvifCredential__DeleteCredentialAccessProfilesResponse*>(&onvifCredential__DeleteCredentialAccessProfilesResponse)) // NULL ref?
        return soap_closesock(soap);
    onvifCredential__DeleteCredentialAccessProfilesResponse.soap_default(soap);
    if (soap_begin_recv(soap)
     || soap_envelope_begin_in(soap)
     || soap_recv_header(soap)
     || soap_body_begin_in(soap))
        return soap_closesock(soap);
    onvifCredential__DeleteCredentialAccessProfilesResponse.soap_get(soap, "onvifCredential:DeleteCredentialAccessProfilesResponse", NULL);
    if (soap->error)
        return soap_recv_fault(soap, 0);
    if (soap_body_end_in(soap)
     || soap_envelope_end_in(soap)
     || soap_end_recv(soap))
        return soap_closesock(soap);
    return soap_closesock(soap);
}
/* End of client proxy code */
