/* soapRuleEngineBindingProxy.h
   Generated by gSOAP 2.8.66 for ../result/interim/onvif.h_

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapRuleEngineBindingProxy_H
#define soapRuleEngineBindingProxy_H
#include "soapH.h"

    class SOAP_CMAC RuleEngineBindingProxy {
      public:
        /// Context to manage proxy IO and data
        struct soap *soap;
        bool soap_own; ///< flag indicating that this context is owned by this proxy when context is shared
        /// Endpoint URL of service 'RuleEngineBindingProxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in ../result/interim/onvif.h_, if any
        /// Construct a proxy with new managing context
        RuleEngineBindingProxy();
        /// Copy constructor
        RuleEngineBindingProxy(const RuleEngineBindingProxy& rhs);
        /// Construct proxy given a shared managing context
        RuleEngineBindingProxy(struct soap*);
        /// Constructor taking an endpoint URL
        RuleEngineBindingProxy(const char *endpoint);
        /// Constructor taking input and output mode flags for the new managing context
        RuleEngineBindingProxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        RuleEngineBindingProxy(const char *endpoint, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        RuleEngineBindingProxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes non-shared managing context only (use destroy() to delete deserialized data)
        virtual ~RuleEngineBindingProxy();
        /// Initializer used by constructors
        virtual void RuleEngineBindingProxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual RuleEngineBindingProxy *copy();
        /// Copy assignment
        RuleEngineBindingProxy& operator=(const RuleEngineBindingProxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Add SOAP Header to message
        virtual void soap_header(char *wsa5__MessageID, struct wsa5__RelatesToType *wsa5__RelatesTo, struct wsa5__EndpointReferenceType *wsa5__From, struct wsa5__EndpointReferenceType *wsa5__ReplyTo, struct wsa5__EndpointReferenceType *wsa5__FaultTo, char *wsa5__To, char *wsa5__Action, struct chan__ChannelInstanceType *chan__ChannelInstance, struct wsdd__AppSequenceType *wsdd__AppSequence, struct _wsse__Security *wsse__Security, char *SubscriptionId);
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault string (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail as string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        /// Web service operation 'GetSupportedRules' (returns SOAP_OK or error code)
        virtual int GetSupportedRules(_onvifAnalytics__GetSupportedRules *onvifAnalytics__GetSupportedRules, _onvifAnalytics__GetSupportedRulesResponse &onvifAnalytics__GetSupportedRulesResponse)
        { return this->GetSupportedRules(NULL, NULL, onvifAnalytics__GetSupportedRules, onvifAnalytics__GetSupportedRulesResponse); }
        virtual int GetSupportedRules(const char *soap_endpoint, const char *soap_action, _onvifAnalytics__GetSupportedRules *onvifAnalytics__GetSupportedRules, _onvifAnalytics__GetSupportedRulesResponse &onvifAnalytics__GetSupportedRulesResponse);
        /// Web service operation 'CreateRules' (returns SOAP_OK or error code)
        virtual int CreateRules(_onvifAnalytics__CreateRules *onvifAnalytics__CreateRules, _onvifAnalytics__CreateRulesResponse &onvifAnalytics__CreateRulesResponse)
        { return this->CreateRules(NULL, NULL, onvifAnalytics__CreateRules, onvifAnalytics__CreateRulesResponse); }
        virtual int CreateRules(const char *soap_endpoint, const char *soap_action, _onvifAnalytics__CreateRules *onvifAnalytics__CreateRules, _onvifAnalytics__CreateRulesResponse &onvifAnalytics__CreateRulesResponse);
        /// Web service operation 'DeleteRules' (returns SOAP_OK or error code)
        virtual int DeleteRules(_onvifAnalytics__DeleteRules *onvifAnalytics__DeleteRules, _onvifAnalytics__DeleteRulesResponse &onvifAnalytics__DeleteRulesResponse)
        { return this->DeleteRules(NULL, NULL, onvifAnalytics__DeleteRules, onvifAnalytics__DeleteRulesResponse); }
        virtual int DeleteRules(const char *soap_endpoint, const char *soap_action, _onvifAnalytics__DeleteRules *onvifAnalytics__DeleteRules, _onvifAnalytics__DeleteRulesResponse &onvifAnalytics__DeleteRulesResponse);
        /// Web service operation 'GetRules' (returns SOAP_OK or error code)
        virtual int GetRules(_onvifAnalytics__GetRules *onvifAnalytics__GetRules, _onvifAnalytics__GetRulesResponse &onvifAnalytics__GetRulesResponse)
        { return this->GetRules(NULL, NULL, onvifAnalytics__GetRules, onvifAnalytics__GetRulesResponse); }
        virtual int GetRules(const char *soap_endpoint, const char *soap_action, _onvifAnalytics__GetRules *onvifAnalytics__GetRules, _onvifAnalytics__GetRulesResponse &onvifAnalytics__GetRulesResponse);
        /// Web service operation 'GetRuleOptions' (returns SOAP_OK or error code)
        virtual int GetRuleOptions(_onvifAnalytics__GetRuleOptions *onvifAnalytics__GetRuleOptions, _onvifAnalytics__GetRuleOptionsResponse &onvifAnalytics__GetRuleOptionsResponse)
        { return this->GetRuleOptions(NULL, NULL, onvifAnalytics__GetRuleOptions, onvifAnalytics__GetRuleOptionsResponse); }
        virtual int GetRuleOptions(const char *soap_endpoint, const char *soap_action, _onvifAnalytics__GetRuleOptions *onvifAnalytics__GetRuleOptions, _onvifAnalytics__GetRuleOptionsResponse &onvifAnalytics__GetRuleOptionsResponse);
        /// Web service operation 'ModifyRules' (returns SOAP_OK or error code)
        virtual int ModifyRules(_onvifAnalytics__ModifyRules *onvifAnalytics__ModifyRules, _onvifAnalytics__ModifyRulesResponse &onvifAnalytics__ModifyRulesResponse)
        { return this->ModifyRules(NULL, NULL, onvifAnalytics__ModifyRules, onvifAnalytics__ModifyRulesResponse); }
        virtual int ModifyRules(const char *soap_endpoint, const char *soap_action, _onvifAnalytics__ModifyRules *onvifAnalytics__ModifyRules, _onvifAnalytics__ModifyRulesResponse &onvifAnalytics__ModifyRulesResponse);
    };
#endif
