/* soapScheduleBindingService.h
   Generated by gSOAP 2.8.66 for ../result/interim/onvif.h_

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapScheduleBindingService_H
#define soapScheduleBindingService_H
#include "soapH.h"

    class SOAP_CMAC ScheduleBindingService {
      public:
        /// Context to manage service IO and data
        struct soap *soap;
        bool soap_own;  ///< flag indicating that this context is owned by this service when context is shared
        /// Variables globally declared in ../result/interim/onvif.h_, if any
        /// Construct a service with new managing context
        ScheduleBindingService();
        /// Copy constructor
        ScheduleBindingService(const ScheduleBindingService&);
        /// Construct service given a shared managing context
        ScheduleBindingService(struct soap*);
        /// Constructor taking input+output mode flags for the new managing context
        ScheduleBindingService(soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        ScheduleBindingService(soap_mode imode, soap_mode omode);
        /// Destructor deletes non-shared managing context only (use destroy() to delete deserialized data)
        virtual ~ScheduleBindingService();
        /// Delete all deserialized data (with soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to defaults
        virtual void reset();
        /// Initializer used by constructors
        virtual void ScheduleBindingService_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual ScheduleBindingService *copy() SOAP_PURE_VIRTUAL_COPY;
        /// Copy assignment
        ScheduleBindingService& operator=(const ScheduleBindingService&);
        /// Close connection (normally automatic)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Return sender-related fault to sender
        virtual int soap_senderfault(const char *string, const char *detailXML);
        /// Return sender-related fault with SOAP 1.2 subcode to sender
        virtual int soap_senderfault(const char *subcodeQName, const char *string, const char *detailXML);
        /// Return receiver-related fault to sender
        virtual int soap_receiverfault(const char *string, const char *detailXML);
        /// Return receiver-related fault with SOAP 1.2 subcode to sender
        virtual int soap_receiverfault(const char *subcodeQName, const char *string, const char *detailXML);
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Add SOAP Header to message
        virtual void soap_header(char *wsa5__MessageID, struct wsa5__RelatesToType *wsa5__RelatesTo, struct wsa5__EndpointReferenceType *wsa5__From, struct wsa5__EndpointReferenceType *wsa5__ReplyTo, struct wsa5__EndpointReferenceType *wsa5__FaultTo, char *wsa5__To, char *wsa5__Action, struct chan__ChannelInstanceType *chan__ChannelInstance, struct wsdd__AppSequenceType *wsdd__AppSequence, struct _wsse__Security *wsse__Security, char *SubscriptionId);
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
    #ifndef WITH_NOIO
        /// Run simple single-thread (iterative, non-SSL) service on port until a connection error occurs (returns SOAP_OK or error code), use this->bind_flag = SO_REUSEADDR to rebind for immediate rerun
        virtual int run(int port);
    #if defined(WITH_OPENSSL) || defined(WITH_GNUTLS)
        /// Run simple single-thread SSL service on port until a connection error occurs (returns SOAP_OK or error code), use this->bind_flag = SO_REUSEADDR to rebind for immediate rerun
        virtual int ssl_run(int port);
    #endif
        /// Bind service to port (returns master socket or SOAP_INVALID_SOCKET)
        virtual SOAP_SOCKET bind(const char *host, int port, int backlog);
        /// Accept next request (returns socket or SOAP_INVALID_SOCKET)
        virtual SOAP_SOCKET accept();
    #if defined(WITH_OPENSSL) || defined(WITH_GNUTLS)
        /// When SSL is used, after accept() should perform and accept SSL handshake
        virtual int ssl_accept();
    #endif
    #endif
        /// After accept() serve this request (returns SOAP_OK or error code)
        virtual int serve();
        /// Used by serve() to dispatch a request (returns SOAP_OK or error code)
        virtual int dispatch();
        virtual int dispatch(struct soap *soap);
        ///
        /// Service operations are listed below (you should define these)
        /// Note: compile with -DWITH_PURE_VIRTUAL for pure virtual methods
        ///
        /// Web service operation 'GetServiceCapabilities' (returns SOAP_OK or error code)
        virtual int GetServiceCapabilities(_onvifScedule__GetServiceCapabilities *onvifScedule__GetServiceCapabilities, _onvifScedule__GetServiceCapabilitiesResponse &onvifScedule__GetServiceCapabilitiesResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'GetScheduleState' (returns SOAP_OK or error code)
        virtual int GetScheduleState(_onvifScedule__GetScheduleState *onvifScedule__GetScheduleState, _onvifScedule__GetScheduleStateResponse &onvifScedule__GetScheduleStateResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'GetScheduleInfo' (returns SOAP_OK or error code)
        virtual int GetScheduleInfo(_onvifScedule__GetScheduleInfo *onvifScedule__GetScheduleInfo, _onvifScedule__GetScheduleInfoResponse &onvifScedule__GetScheduleInfoResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'GetScheduleInfoList' (returns SOAP_OK or error code)
        virtual int GetScheduleInfoList(_onvifScedule__GetScheduleInfoList *onvifScedule__GetScheduleInfoList, _onvifScedule__GetScheduleInfoListResponse &onvifScedule__GetScheduleInfoListResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'GetSchedules' (returns SOAP_OK or error code)
        virtual int GetSchedules(_onvifScedule__GetSchedules *onvifScedule__GetSchedules, _onvifScedule__GetSchedulesResponse &onvifScedule__GetSchedulesResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'GetScheduleList' (returns SOAP_OK or error code)
        virtual int GetScheduleList(_onvifScedule__GetScheduleList *onvifScedule__GetScheduleList, _onvifScedule__GetScheduleListResponse &onvifScedule__GetScheduleListResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'CreateSchedule' (returns SOAP_OK or error code)
        virtual int CreateSchedule(_onvifScedule__CreateSchedule *onvifScedule__CreateSchedule, _onvifScedule__CreateScheduleResponse &onvifScedule__CreateScheduleResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'SetSchedule' (returns SOAP_OK or error code)
        virtual int SetSchedule(_onvifScedule__SetSchedule *onvifScedule__SetSchedule, _onvifScedule__SetScheduleResponse &onvifScedule__SetScheduleResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'ModifySchedule' (returns SOAP_OK or error code)
        virtual int ModifySchedule(_onvifScedule__ModifySchedule *onvifScedule__ModifySchedule, _onvifScedule__ModifyScheduleResponse &onvifScedule__ModifyScheduleResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'DeleteSchedule' (returns SOAP_OK or error code)
        virtual int DeleteSchedule(_onvifScedule__DeleteSchedule *onvifScedule__DeleteSchedule, _onvifScedule__DeleteScheduleResponse &onvifScedule__DeleteScheduleResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'GetSpecialDayGroupInfo' (returns SOAP_OK or error code)
        virtual int GetSpecialDayGroupInfo(_onvifScedule__GetSpecialDayGroupInfo *onvifScedule__GetSpecialDayGroupInfo, _onvifScedule__GetSpecialDayGroupInfoResponse &onvifScedule__GetSpecialDayGroupInfoResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'GetSpecialDayGroupInfoList' (returns SOAP_OK or error code)
        virtual int GetSpecialDayGroupInfoList(_onvifScedule__GetSpecialDayGroupInfoList *onvifScedule__GetSpecialDayGroupInfoList, _onvifScedule__GetSpecialDayGroupInfoListResponse &onvifScedule__GetSpecialDayGroupInfoListResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'GetSpecialDayGroups' (returns SOAP_OK or error code)
        virtual int GetSpecialDayGroups(_onvifScedule__GetSpecialDayGroups *onvifScedule__GetSpecialDayGroups, _onvifScedule__GetSpecialDayGroupsResponse &onvifScedule__GetSpecialDayGroupsResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'GetSpecialDayGroupList' (returns SOAP_OK or error code)
        virtual int GetSpecialDayGroupList(_onvifScedule__GetSpecialDayGroupList *onvifScedule__GetSpecialDayGroupList, _onvifScedule__GetSpecialDayGroupListResponse &onvifScedule__GetSpecialDayGroupListResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'CreateSpecialDayGroup' (returns SOAP_OK or error code)
        virtual int CreateSpecialDayGroup(_onvifScedule__CreateSpecialDayGroup *onvifScedule__CreateSpecialDayGroup, _onvifScedule__CreateSpecialDayGroupResponse &onvifScedule__CreateSpecialDayGroupResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'SetSpecialDayGroup' (returns SOAP_OK or error code)
        virtual int SetSpecialDayGroup(_onvifScedule__SetSpecialDayGroup *onvifScedule__SetSpecialDayGroup, _onvifScedule__SetSpecialDayGroupResponse &onvifScedule__SetSpecialDayGroupResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'ModifySpecialDayGroup' (returns SOAP_OK or error code)
        virtual int ModifySpecialDayGroup(_onvifScedule__ModifySpecialDayGroup *onvifScedule__ModifySpecialDayGroup, _onvifScedule__ModifySpecialDayGroupResponse &onvifScedule__ModifySpecialDayGroupResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'DeleteSpecialDayGroup' (returns SOAP_OK or error code)
        virtual int DeleteSpecialDayGroup(_onvifScedule__DeleteSpecialDayGroup *onvifScedule__DeleteSpecialDayGroup, _onvifScedule__DeleteSpecialDayGroupResponse &onvifScedule__DeleteSpecialDayGroupResponse) SOAP_PURE_VIRTUAL;
    };
#endif
