#!/bin/bash  
grunt testportal:userclean1:default | tee log-userclean1.txt
kill $(lsof -t -i :4444)
grunt testportal:userclean2:default | tee log-userclean2.txt
kill $(lsof -t -i :4444)
grunt testportal:account1:default | tee log-account1.txt
kill $(lsof -t -i :4444)
grunt testportal:account2:default | tee log-account2.txt
kill $(lsof -t -i :4444)
grunt testportal:login1:default | tee log-login1.txt
kill $(lsof -t -i :4444)
grunt testportal:login2:default | tee log-login2.txt
kill $(lsof -t -i :4444)
grunt testportal:login3:default | tee log-login3.txt
kill $(lsof -t -i :4444)
grunt testportal:register1:default | tee log-register1.txt
kill $(lsof -t -i :4444)
grunt testportal:register2:default | tee log-register2.txt
kill $(lsof -t -i :4444)
grunt testportal:register3:default | tee log-register3.txt
kill $(lsof -t -i :4444)
grunt testportal:restorepass1:default | tee log-restorepass1.txt
kill $(lsof -t -i :4444)
grunt testportal:restorepass2:default | tee log-restorepass2.txt
kill $(lsof -t -i :4444)
grunt testportal:restorepass3:default | tee log-restorepass3.txt
kill $(lsof -t -i :4444)
grunt testportal:systems:default | tee log-systems.txt
kill $(lsof -t -i :4444)
grunt testportal:smoke:default | tee log-smoke.txt