#!/bin/bash -e

COMPANY_NAME=${deb.customization.company.name}

. /usr/share/debconf/confmodule

if [ -n "$DEBIAN_SCRIPT_DEBUG" ]; then set -v -x; DEBIAN_SCRIPT_TRACE=1; fi
${DEBIAN_SCRIPT_TRACE:+ echo "#42#DEBUG# RUNNING $0 $*" 1>&2 }
 
export PATH=$PATH:/sbin:/usr/sbin:/bin:/usr/bin

ETC_DIR="/opt/$COMPANY_NAME/mediaserver/etc"
CONFIG_FILE="$ETC_DIR/mediaserver.conf"
ECS_CONFIG_FILE="/opt/$COMPANY_NAME/entcontroller/etc/entcontroller.conf"

# This is necessary because changed configuration options should take effect 
# immediately.
if status $COMPANY_NAME-mediaserver | grep "start/running" > /dev/null; then
  stop $COMPANY_NAME-mediaserver
fi

# Default ECS connection parameters
ECS_HOST_DEFAULT="localhost"
if [ -f "$ECS_CONFIG_FILE" ]; then
    ECS_PORT_DEFAULT=$(cat $ECS_CONFIG_FILE | grep "^port=" | head -1 | sed 's/port=\(.*\)/\1/g')
else
    ECS_PORT_DEFAULT="7001"
fi
ECS_LOGIN_DEFAULT="admin"

# Default MS parameters
PORT_DEFAULT="7002"
TRANSPORT_DEAULT="auto"
PUBLIC_IP_ENABLED_DEFAULT="auto"

function replace_var {
    file=$1; shift
    name=$1; shift
    value=$1; shift

    if grep "$name=" $file > /dev/null 2>&1
        tmpfile=$(mktemp)
        while read line
        do
              echo ${line/$name=*/$name=$value}
        done < "$file" > "$tmpfile" && mv "$tmpfile" "$file"
    then
        sed -i "/\[General\]/a \
$name=$value" $file
    fi   
}

function read_config {
    ECS_HOST=$ECS_HOST_DEFAULT
    ECS_PORT=$ECS_PORT_DEFAULT
    ECS_LOGIN=$ECS_LOGIN_DEFAULT
    PORT=$PORT_DEFAULT
    TRANSPORT=$TRANSPORT_DEFAULT
    PUBLIC_IP_ENABLED=$PUBLIC_IP_ENABLED_DEFAULT

    [ -f $CONFIG_FILE ] || { true; return; }

    ECS_HOST=$(cat $CONFIG_FILE | grep "^appserverHost=" | head -1 | sed 's/appserverHost=\(.*\)/\1/g')
    ECS_PORT=$(cat $CONFIG_FILE | grep "^appserverPort=" | head -1 | sed 's/appserverPort=\(.*\)/\1/g')
    ECS_LOGIN=$(cat $CONFIG_FILE | grep "^appserverLogin=" | head -1 | sed 's/appserverLogin=\(.*\)/\1/g')
    ECS_PASSWORD=$(cat $CONFIG_FILE | grep "^appserverPassword=" | head -1 | sed 's/appserverPassword=\(.*\)/\1/g')
    PORT=$(cat $CONFIG_FILE | grep "^port=" | head -1 | sed 's/port=\(.*\)/\1/g')
    TRANSPORT=$(cat $CONFIG_FILE | grep "^rtspTransport=" | head -1 | sed 's/rtspTransport=\(.*\)/\1/g')
    PUBLIC_IP_ENABLED=$(cat $CONFIG_FILE | grep "^publicIPEnabled=" | head -1 | sed 's/publicIPEnabled=\(.*\)/\1/g')
    STATIC_PUBLIC_IP=$(cat $CONFIG_FILE | grep "^staticPublicIP=" | head -1 | sed 's/staticPublicIP=\(.*\)/\1/g')

    # Compatibility option
    if [ -z "$PORT" ]
    then
        PORT=$(cat $CONFIG_FILE | grep rtspPort | head -1 | sed 's/rtspPort=\(.*\)/\1/g')
    else
        PORT=$PORT_DEFAULT
    fi
}

function write_config {
    [ -d $ETC_DIR ] || mkdir $ETC_DIR
    [ -f $CONFIG_FILE ] || echo "[General]" > $CONFIG_FILE

    replace_var $CONFIG_FILE appserverHost "$ECS_HOST"
    replace_var $CONFIG_FILE appserverPort "$ECS_PORT"
    replace_var $CONFIG_FILE appserverLogin "$ECS_LOGIN"
    replace_var $CONFIG_FILE appserverPassword "$ECS_PASSWORD"
    replace_var $CONFIG_FILE rtspPort "$PORT"
    replace_var $CONFIG_FILE rtspTransport "$TRANSPORT"
    replace_var $CONFIG_FILE publicIPEnabled "$PUBLIC_IP_ENABLED"
    replace_var $CONFIG_FILE staticPublicIP "$STATIC_PUBLIC_IP"
}

function to_int {
    local -i num="10#${1}"
    echo "${num}"
}

function port_is_ok {
    local port="$1"
    local -i port_num=$(to_int "${port}" 2>/dev/null)
 
    if (( $port_num < 1 || $port_num > 65535 )) ; then
        return 1
    fi
 
    return 0
}

function create_dir {
    local dir="$1";

    mkdir -p "$dir"
}

function ask_for_value {
    local varname="$1"
    local default="$2"
    local full_name="$COMPANY_NAME-mediaserver/$varname"
    local error_message="${full_name}_invalid"

    # Support unattened install
    db_get $full_name
    if [ "$RET" = "" ]; then
        [ -n "$default" ] && db_set $full_name $default 
    fi

    db_input high $full_name || true
    db_go

    while :
    do
        db_get $full_name
        { validate_$varname $RET 2> /dev/null; STATUS=$?; } || true        
        [ $STATUS -eq 0 ] && break # validation passes
        [ $STATUS -ne 1 ] && break # no validation function or invalid

        db_input high $error_message
        db_go

        { db_input high $full_name; STATUS=$?; } || true
        [ $STATUS -eq 30 ] && break
        db_go
    done

    RESULT="$RET"
    db_unregister $full_name
    echo $RESULT
}

function validate_ecsPassword {
    [ -n "$1" ]
}

function validate_port {
    port_is_ok $1
}

function validate_storage {
  [[ "$1" == /* ]]
}

case "$1" in
  configure)
      read_config

      ECS_HOST=$(ask_for_value ecsHost "$ECS_HOST")
      ECS_PORT=$(ask_for_value ecsPort "$ECS_PORT")
      ECS_LOGIN=$(ask_for_value ecsLogin "$ECS_LOGIN")
      ECS_PASSWORD=$(ask_for_value ecsPassword "$ECS_PASSWORD")
      PORT=$(ask_for_value port "$PORT")
      TRANSPORT=$(ask_for_value transport "$TRANSPORT")

      PUBLIC_IP_ENABLED=$(ask_for_value publicIPEnabled "$PUBLIC_IP_ENABLED")

      case $PUBLIC_IP_ENABLED in
          auto)
            PUBLIC_IP_ENABLED=1
            ;;
          disabled)
            PUBLIC_IP_ENABLED=0
            ;;
          manual)
            PUBLIC_IP_ENABLED=2
            ;;
      esac

      if [ "$PUBLIC_IP_ENABLED" -eq 2 ]
      then
          STATIC_PUBLIC_IP=$(ask_for_value staticPublicIP "$STATIC_PUBLIC_IP")
      fi

      write_config
  ;;

  abort-upgrade|abort-remove|abort-configure)
  ;;

  *)
    echo "postinst called with unknown argument '$1'" 1>&2
    exit 1
  ;;
esac

[ -d $VARDIR ] || mkdir $VARDIR

if [ -e "/etc/init/$COMPANY_NAME-mediaserver.conf" ]; then
	invoke-rc.d $COMPANY_NAME-mediaserver start || exit $?
fi
update-rc.d -f $COMPANY_NAME-mediaserver remove >/dev/null || exit $?

exit 0
