#!/bin/bash -e

COMPANY_NAME=@deb.customization.company.name@
FULLVERSION=@release.version@.@buildNumber@
TARGET=/opt/$COMPANY_NAME/client/$FULLVERSION

. /usr/share/debconf/confmodule

if [ -n "$DEBIAN_SCRIPT_DEBUG" ]; then set -v -x; DEBIAN_SCRIPT_TRACE=1; fi
${DEBIAN_SCRIPT_TRACE:+ echo "#42#DEBUG# RUNNING $0 $*" 1>&2 }

pkill applauncher-bin || true
