## Copyright 2018-present Network Optix, Inc. Licensed under MPL 2.0: www.mozilla.org/MPL/2.0/

mark_as_advanced(Qt6AndroidExtras_DIR)
mark_as_advanced(Qt6Concurrent_DIR)
mark_as_advanced(Qt6Core_DIR)
mark_as_advanced(Qt6Gui_DIR)
mark_as_advanced(Qt6LinguistTools_DIR)
mark_as_advanced(Qt6Multimedia_DIR)
mark_as_advanced(Qt6Network_DIR)
mark_as_advanced(Qt6OpenGL_DIR)
mark_as_advanced(Qt6Qml_DIR)
mark_as_advanced(Qt6QuickWidgets_DIR)
mark_as_advanced(Qt6Quick_DIR)
mark_as_advanced(Qt6Sql_DIR)
mark_as_advanced(Qt6WebChannel_DIR)
mark_as_advanced(Qt6WebKitWidgets_DIR)
mark_as_advanced(Qt6WebKit_DIR)
mark_as_advanced(Qt6WebSockets_DIR)
mark_as_advanced(Qt6Widgets_DIR)
mark_as_advanced(Qt6Xml_DIR)
mark_as_advanced(Qt6SerialPort_DIR)
mark_as_advanced(Qt6_DIR)
