<?xml version="1.0" encoding="UTF-8"?>
<TS language="en_US" sourcelanguage="en" version="2.1">
  <context>
    <name>global</name>
    <message>
      <source>PRODUCT_NAME</source>
      <translation>FlyView Cloud</translation>
    </message>
    <message>
      <source>CLIENT_PROTOCOL</source>
      <translation>fly-vms</translation>
    </message>
    <message>
      <source>VMS_NAME</source>
      <translation>FlyView</translation>
    </message>
    <message>
      <source>{{downloadLink}}</source>
      <translation>http://www.flyviewvms.ru</translation>
    </message>
    <message>
      <source>{{supportLink}}</source>
      <translation>support@flyvi.ru</translation>
    </message>
    <message>
      <source>{{supportLinkText}}</source>
      <translation>support@flyvi.ru</translation>
    </message>
    <message>
      <source>{{companyUrl}}</source>
      <translation>http://www.ipera.ru</translation>
    </message>
    <message>
      <source>{{portalDomain}}</source>
      <translation>cloud-demo.hdw.mx</translation>
    </message>
    <message>
      <source>{{iOSappID}}</source>
      <translation>32NH529F85.ru.ipera.FlyView</translation>
    </message>
    <message>
      <source>COMPANY_NAME</source>
      <translation>iPera</translation>
    </message>
  </context>
</TS>
