#pragma once

struct QnMultiserverRequestContext;
struct QnGetBookmarksRequestContext;
struct QnGetBookmarkTagsRequestContext;
struct QnUpdateBookmarkRequestContext;
struct QnDeleteBookmarkRequestContext;

