/* soapDeviceIOBindingProxy.h
   Generated by gSOAP 2.8.8 from onvif.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapDeviceIOBindingProxy_H
#define soapDeviceIOBindingProxy_H
#include "soapH.h"

class SOAP_CMAC DeviceIOBindingProxy
{ public:
	struct soap *soap;
	bool own;
	/// Endpoint URL of service 'DeviceIOBindingProxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	DeviceIOBindingProxy();
	/// Constructor to use/share an engine state
	DeviceIOBindingProxy(struct soap*);
	/// Constructor with endpoint URL
	DeviceIOBindingProxy(const char *url);
	/// Constructor with engine input+output mode control
	DeviceIOBindingProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	DeviceIOBindingProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	DeviceIOBindingProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~DeviceIOBindingProxy();
	/// Initializer used by constructors
	virtual	void DeviceIOBindingProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (uses soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to default
	virtual	void reset();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Put SOAP Header in message
	virtual	void soap_header(struct _wsse__Security *wsse__Security, char *wsa__MessageID, struct wsa__Relationship *wsa__RelatesTo, struct wsa__EndpointReferenceType *wsa__From, struct wsa__EndpointReferenceType *wsa__ReplyTo, struct wsa__EndpointReferenceType *wsa__FaultTo, char *wsa__To, char *wsa__Action, struct wsdd__AppSequenceType *wsdd__AppSequence);
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'GetServiceCapabilities' (returns error code or SOAP_OK)
	virtual	int GetServiceCapabilities(_onvifDeviceIO__GetServiceCapabilities *onvifDeviceIO__GetServiceCapabilities, _onvifDeviceIO__GetServiceCapabilitiesResponse *onvifDeviceIO__GetServiceCapabilitiesResponse) { return GetServiceCapabilities(NULL, NULL, onvifDeviceIO__GetServiceCapabilities, onvifDeviceIO__GetServiceCapabilitiesResponse); }
	virtual	int GetServiceCapabilities(const char *endpoint, const char *soap_action, _onvifDeviceIO__GetServiceCapabilities *onvifDeviceIO__GetServiceCapabilities, _onvifDeviceIO__GetServiceCapabilitiesResponse *onvifDeviceIO__GetServiceCapabilitiesResponse);

	/// Web service operation 'GetRelayOutputOptions' (returns error code or SOAP_OK)
	virtual	int GetRelayOutputOptions(_onvifDeviceIO__GetRelayOutputOptions *onvifDeviceIO__GetRelayOutputOptions, _onvifDeviceIO__GetRelayOutputOptionsResponse *onvifDeviceIO__GetRelayOutputOptionsResponse) { return GetRelayOutputOptions(NULL, NULL, onvifDeviceIO__GetRelayOutputOptions, onvifDeviceIO__GetRelayOutputOptionsResponse); }
	virtual	int GetRelayOutputOptions(const char *endpoint, const char *soap_action, _onvifDeviceIO__GetRelayOutputOptions *onvifDeviceIO__GetRelayOutputOptions, _onvifDeviceIO__GetRelayOutputOptionsResponse *onvifDeviceIO__GetRelayOutputOptionsResponse);

	/// Web service operation 'GetAudioSources' (returns error code or SOAP_OK)
	virtual	int GetAudioSources(_onvifMedia__GetAudioSources *onvifMedia__GetAudioSources, _onvifMedia__GetAudioSourcesResponse *onvifMedia__GetAudioSourcesResponse) { return GetAudioSources(NULL, NULL, onvifMedia__GetAudioSources, onvifMedia__GetAudioSourcesResponse); }
	virtual	int GetAudioSources(const char *endpoint, const char *soap_action, _onvifMedia__GetAudioSources *onvifMedia__GetAudioSources, _onvifMedia__GetAudioSourcesResponse *onvifMedia__GetAudioSourcesResponse);

	/// Web service operation 'GetAudioOutputs' (returns error code or SOAP_OK)
	virtual	int GetAudioOutputs(_onvifMedia__GetAudioOutputs *onvifMedia__GetAudioOutputs, _onvifMedia__GetAudioOutputsResponse *onvifMedia__GetAudioOutputsResponse) { return GetAudioOutputs(NULL, NULL, onvifMedia__GetAudioOutputs, onvifMedia__GetAudioOutputsResponse); }
	virtual	int GetAudioOutputs(const char *endpoint, const char *soap_action, _onvifMedia__GetAudioOutputs *onvifMedia__GetAudioOutputs, _onvifMedia__GetAudioOutputsResponse *onvifMedia__GetAudioOutputsResponse);

	/// Web service operation 'GetVideoSources' (returns error code or SOAP_OK)
	virtual	int GetVideoSources(_onvifMedia__GetVideoSources *onvifMedia__GetVideoSources, _onvifMedia__GetVideoSourcesResponse *onvifMedia__GetVideoSourcesResponse) { return GetVideoSources(NULL, NULL, onvifMedia__GetVideoSources, onvifMedia__GetVideoSourcesResponse); }
	virtual	int GetVideoSources(const char *endpoint, const char *soap_action, _onvifMedia__GetVideoSources *onvifMedia__GetVideoSources, _onvifMedia__GetVideoSourcesResponse *onvifMedia__GetVideoSourcesResponse);

	/// Web service operation 'GetVideoOutputs' (returns error code or SOAP_OK)
	virtual	int GetVideoOutputs(_onvifDeviceIO__GetVideoOutputs *onvifDeviceIO__GetVideoOutputs, _onvifDeviceIO__GetVideoOutputsResponse *onvifDeviceIO__GetVideoOutputsResponse) { return GetVideoOutputs(NULL, NULL, onvifDeviceIO__GetVideoOutputs, onvifDeviceIO__GetVideoOutputsResponse); }
	virtual	int GetVideoOutputs(const char *endpoint, const char *soap_action, _onvifDeviceIO__GetVideoOutputs *onvifDeviceIO__GetVideoOutputs, _onvifDeviceIO__GetVideoOutputsResponse *onvifDeviceIO__GetVideoOutputsResponse);

	/// Web service operation 'GetVideoSourceConfiguration' (returns error code or SOAP_OK)
	virtual	int GetVideoSourceConfiguration(_onvifDeviceIO__GetVideoSourceConfiguration *onvifDeviceIO__GetVideoSourceConfiguration, _onvifDeviceIO__GetVideoSourceConfigurationResponse *onvifDeviceIO__GetVideoSourceConfigurationResponse) { return GetVideoSourceConfiguration(NULL, NULL, onvifDeviceIO__GetVideoSourceConfiguration, onvifDeviceIO__GetVideoSourceConfigurationResponse); }
	virtual	int GetVideoSourceConfiguration(const char *endpoint, const char *soap_action, _onvifDeviceIO__GetVideoSourceConfiguration *onvifDeviceIO__GetVideoSourceConfiguration, _onvifDeviceIO__GetVideoSourceConfigurationResponse *onvifDeviceIO__GetVideoSourceConfigurationResponse);

	/// Web service operation 'GetVideoOutputConfiguration' (returns error code or SOAP_OK)
	virtual	int GetVideoOutputConfiguration(_onvifDeviceIO__GetVideoOutputConfiguration *onvifDeviceIO__GetVideoOutputConfiguration, _onvifDeviceIO__GetVideoOutputConfigurationResponse *onvifDeviceIO__GetVideoOutputConfigurationResponse) { return GetVideoOutputConfiguration(NULL, NULL, onvifDeviceIO__GetVideoOutputConfiguration, onvifDeviceIO__GetVideoOutputConfigurationResponse); }
	virtual	int GetVideoOutputConfiguration(const char *endpoint, const char *soap_action, _onvifDeviceIO__GetVideoOutputConfiguration *onvifDeviceIO__GetVideoOutputConfiguration, _onvifDeviceIO__GetVideoOutputConfigurationResponse *onvifDeviceIO__GetVideoOutputConfigurationResponse);

	/// Web service operation 'GetAudioSourceConfiguration' (returns error code or SOAP_OK)
	virtual	int GetAudioSourceConfiguration(_onvifDeviceIO__GetAudioSourceConfiguration *onvifDeviceIO__GetAudioSourceConfiguration, _onvifDeviceIO__GetAudioSourceConfigurationResponse *onvifDeviceIO__GetAudioSourceConfigurationResponse) { return GetAudioSourceConfiguration(NULL, NULL, onvifDeviceIO__GetAudioSourceConfiguration, onvifDeviceIO__GetAudioSourceConfigurationResponse); }
	virtual	int GetAudioSourceConfiguration(const char *endpoint, const char *soap_action, _onvifDeviceIO__GetAudioSourceConfiguration *onvifDeviceIO__GetAudioSourceConfiguration, _onvifDeviceIO__GetAudioSourceConfigurationResponse *onvifDeviceIO__GetAudioSourceConfigurationResponse);

	/// Web service operation 'GetAudioOutputConfiguration' (returns error code or SOAP_OK)
	virtual	int GetAudioOutputConfiguration(_onvifDeviceIO__GetAudioOutputConfiguration *onvifDeviceIO__GetAudioOutputConfiguration, _onvifDeviceIO__GetAudioOutputConfigurationResponse *onvifDeviceIO__GetAudioOutputConfigurationResponse) { return GetAudioOutputConfiguration(NULL, NULL, onvifDeviceIO__GetAudioOutputConfiguration, onvifDeviceIO__GetAudioOutputConfigurationResponse); }
	virtual	int GetAudioOutputConfiguration(const char *endpoint, const char *soap_action, _onvifDeviceIO__GetAudioOutputConfiguration *onvifDeviceIO__GetAudioOutputConfiguration, _onvifDeviceIO__GetAudioOutputConfigurationResponse *onvifDeviceIO__GetAudioOutputConfigurationResponse);

	/// Web service operation 'SetVideoSourceConfiguration' (returns error code or SOAP_OK)
	virtual	int SetVideoSourceConfiguration(_onvifDeviceIO__SetVideoSourceConfiguration *onvifDeviceIO__SetVideoSourceConfiguration, _onvifDeviceIO__SetVideoSourceConfigurationResponse *onvifDeviceIO__SetVideoSourceConfigurationResponse) { return SetVideoSourceConfiguration(NULL, NULL, onvifDeviceIO__SetVideoSourceConfiguration, onvifDeviceIO__SetVideoSourceConfigurationResponse); }
	virtual	int SetVideoSourceConfiguration(const char *endpoint, const char *soap_action, _onvifDeviceIO__SetVideoSourceConfiguration *onvifDeviceIO__SetVideoSourceConfiguration, _onvifDeviceIO__SetVideoSourceConfigurationResponse *onvifDeviceIO__SetVideoSourceConfigurationResponse);

	/// Web service operation 'SetVideoOutputConfiguration' (returns error code or SOAP_OK)
	virtual	int SetVideoOutputConfiguration(_onvifDeviceIO__SetVideoOutputConfiguration *onvifDeviceIO__SetVideoOutputConfiguration, _onvifDeviceIO__SetVideoOutputConfigurationResponse *onvifDeviceIO__SetVideoOutputConfigurationResponse) { return SetVideoOutputConfiguration(NULL, NULL, onvifDeviceIO__SetVideoOutputConfiguration, onvifDeviceIO__SetVideoOutputConfigurationResponse); }
	virtual	int SetVideoOutputConfiguration(const char *endpoint, const char *soap_action, _onvifDeviceIO__SetVideoOutputConfiguration *onvifDeviceIO__SetVideoOutputConfiguration, _onvifDeviceIO__SetVideoOutputConfigurationResponse *onvifDeviceIO__SetVideoOutputConfigurationResponse);

	/// Web service operation 'SetAudioSourceConfiguration' (returns error code or SOAP_OK)
	virtual	int SetAudioSourceConfiguration(_onvifDeviceIO__SetAudioSourceConfiguration *onvifDeviceIO__SetAudioSourceConfiguration, _onvifDeviceIO__SetAudioSourceConfigurationResponse *onvifDeviceIO__SetAudioSourceConfigurationResponse) { return SetAudioSourceConfiguration(NULL, NULL, onvifDeviceIO__SetAudioSourceConfiguration, onvifDeviceIO__SetAudioSourceConfigurationResponse); }
	virtual	int SetAudioSourceConfiguration(const char *endpoint, const char *soap_action, _onvifDeviceIO__SetAudioSourceConfiguration *onvifDeviceIO__SetAudioSourceConfiguration, _onvifDeviceIO__SetAudioSourceConfigurationResponse *onvifDeviceIO__SetAudioSourceConfigurationResponse);

	/// Web service operation 'SetAudioOutputConfiguration' (returns error code or SOAP_OK)
	virtual	int SetAudioOutputConfiguration(_onvifDeviceIO__SetAudioOutputConfiguration *onvifDeviceIO__SetAudioOutputConfiguration, _onvifDeviceIO__SetAudioOutputConfigurationResponse *onvifDeviceIO__SetAudioOutputConfigurationResponse) { return SetAudioOutputConfiguration(NULL, NULL, onvifDeviceIO__SetAudioOutputConfiguration, onvifDeviceIO__SetAudioOutputConfigurationResponse); }
	virtual	int SetAudioOutputConfiguration(const char *endpoint, const char *soap_action, _onvifDeviceIO__SetAudioOutputConfiguration *onvifDeviceIO__SetAudioOutputConfiguration, _onvifDeviceIO__SetAudioOutputConfigurationResponse *onvifDeviceIO__SetAudioOutputConfigurationResponse);

	/// Web service operation 'GetVideoSourceConfigurationOptions' (returns error code or SOAP_OK)
	virtual	int GetVideoSourceConfigurationOptions(_onvifDeviceIO__GetVideoSourceConfigurationOptions *onvifDeviceIO__GetVideoSourceConfigurationOptions, _onvifDeviceIO__GetVideoSourceConfigurationOptionsResponse *onvifDeviceIO__GetVideoSourceConfigurationOptionsResponse) { return GetVideoSourceConfigurationOptions(NULL, NULL, onvifDeviceIO__GetVideoSourceConfigurationOptions, onvifDeviceIO__GetVideoSourceConfigurationOptionsResponse); }
	virtual	int GetVideoSourceConfigurationOptions(const char *endpoint, const char *soap_action, _onvifDeviceIO__GetVideoSourceConfigurationOptions *onvifDeviceIO__GetVideoSourceConfigurationOptions, _onvifDeviceIO__GetVideoSourceConfigurationOptionsResponse *onvifDeviceIO__GetVideoSourceConfigurationOptionsResponse);

	/// Web service operation 'GetVideoOutputConfigurationOptions' (returns error code or SOAP_OK)
	virtual	int GetVideoOutputConfigurationOptions(_onvifDeviceIO__GetVideoOutputConfigurationOptions *onvifDeviceIO__GetVideoOutputConfigurationOptions, _onvifDeviceIO__GetVideoOutputConfigurationOptionsResponse *onvifDeviceIO__GetVideoOutputConfigurationOptionsResponse) { return GetVideoOutputConfigurationOptions(NULL, NULL, onvifDeviceIO__GetVideoOutputConfigurationOptions, onvifDeviceIO__GetVideoOutputConfigurationOptionsResponse); }
	virtual	int GetVideoOutputConfigurationOptions(const char *endpoint, const char *soap_action, _onvifDeviceIO__GetVideoOutputConfigurationOptions *onvifDeviceIO__GetVideoOutputConfigurationOptions, _onvifDeviceIO__GetVideoOutputConfigurationOptionsResponse *onvifDeviceIO__GetVideoOutputConfigurationOptionsResponse);

	/// Web service operation 'GetAudioSourceConfigurationOptions' (returns error code or SOAP_OK)
	virtual	int GetAudioSourceConfigurationOptions(_onvifDeviceIO__GetAudioSourceConfigurationOptions *onvifDeviceIO__GetAudioSourceConfigurationOptions, _onvifDeviceIO__GetAudioSourceConfigurationOptionsResponse *onvifDeviceIO__GetAudioSourceConfigurationOptionsResponse) { return GetAudioSourceConfigurationOptions(NULL, NULL, onvifDeviceIO__GetAudioSourceConfigurationOptions, onvifDeviceIO__GetAudioSourceConfigurationOptionsResponse); }
	virtual	int GetAudioSourceConfigurationOptions(const char *endpoint, const char *soap_action, _onvifDeviceIO__GetAudioSourceConfigurationOptions *onvifDeviceIO__GetAudioSourceConfigurationOptions, _onvifDeviceIO__GetAudioSourceConfigurationOptionsResponse *onvifDeviceIO__GetAudioSourceConfigurationOptionsResponse);

	/// Web service operation 'GetAudioOutputConfigurationOptions' (returns error code or SOAP_OK)
	virtual	int GetAudioOutputConfigurationOptions(_onvifDeviceIO__GetAudioOutputConfigurationOptions *onvifDeviceIO__GetAudioOutputConfigurationOptions, _onvifDeviceIO__GetAudioOutputConfigurationOptionsResponse *onvifDeviceIO__GetAudioOutputConfigurationOptionsResponse) { return GetAudioOutputConfigurationOptions(NULL, NULL, onvifDeviceIO__GetAudioOutputConfigurationOptions, onvifDeviceIO__GetAudioOutputConfigurationOptionsResponse); }
	virtual	int GetAudioOutputConfigurationOptions(const char *endpoint, const char *soap_action, _onvifDeviceIO__GetAudioOutputConfigurationOptions *onvifDeviceIO__GetAudioOutputConfigurationOptions, _onvifDeviceIO__GetAudioOutputConfigurationOptionsResponse *onvifDeviceIO__GetAudioOutputConfigurationOptionsResponse);

	/// Web service operation 'GetRelayOutputs' (returns error code or SOAP_OK)
	virtual	int GetRelayOutputs(_onvifDevice__GetRelayOutputs *onvifDevice__GetRelayOutputs, _onvifDevice__GetRelayOutputsResponse *onvifDevice__GetRelayOutputsResponse) { return GetRelayOutputs(NULL, NULL, onvifDevice__GetRelayOutputs, onvifDevice__GetRelayOutputsResponse); }
	virtual	int GetRelayOutputs(const char *endpoint, const char *soap_action, _onvifDevice__GetRelayOutputs *onvifDevice__GetRelayOutputs, _onvifDevice__GetRelayOutputsResponse *onvifDevice__GetRelayOutputsResponse);

	/// Web service operation 'SetRelayOutputSettings' (returns error code or SOAP_OK)
	virtual	int SetRelayOutputSettings(_onvifDeviceIO__SetRelayOutputSettings *onvifDeviceIO__SetRelayOutputSettings, _onvifDeviceIO__SetRelayOutputSettingsResponse *onvifDeviceIO__SetRelayOutputSettingsResponse) { return SetRelayOutputSettings(NULL, NULL, onvifDeviceIO__SetRelayOutputSettings, onvifDeviceIO__SetRelayOutputSettingsResponse); }
	virtual	int SetRelayOutputSettings(const char *endpoint, const char *soap_action, _onvifDeviceIO__SetRelayOutputSettings *onvifDeviceIO__SetRelayOutputSettings, _onvifDeviceIO__SetRelayOutputSettingsResponse *onvifDeviceIO__SetRelayOutputSettingsResponse);

	/// Web service operation 'SetRelayOutputState' (returns error code or SOAP_OK)
	virtual	int SetRelayOutputState(_onvifDevice__SetRelayOutputState *onvifDevice__SetRelayOutputState, _onvifDevice__SetRelayOutputStateResponse *onvifDevice__SetRelayOutputStateResponse) { return SetRelayOutputState(NULL, NULL, onvifDevice__SetRelayOutputState, onvifDevice__SetRelayOutputStateResponse); }
	virtual	int SetRelayOutputState(const char *endpoint, const char *soap_action, _onvifDevice__SetRelayOutputState *onvifDevice__SetRelayOutputState, _onvifDevice__SetRelayOutputStateResponse *onvifDevice__SetRelayOutputStateResponse);

	/// Web service operation 'GetDigitalInputs' (returns error code or SOAP_OK)
	virtual	int GetDigitalInputs(_onvifDeviceIO__GetDigitalInputs *onvifDeviceIO__GetDigitalInputs, _onvifDeviceIO__GetDigitalInputsResponse *onvifDeviceIO__GetDigitalInputsResponse) { return GetDigitalInputs(NULL, NULL, onvifDeviceIO__GetDigitalInputs, onvifDeviceIO__GetDigitalInputsResponse); }
	virtual	int GetDigitalInputs(const char *endpoint, const char *soap_action, _onvifDeviceIO__GetDigitalInputs *onvifDeviceIO__GetDigitalInputs, _onvifDeviceIO__GetDigitalInputsResponse *onvifDeviceIO__GetDigitalInputsResponse);

	/// Web service operation 'GetSerialPorts' (returns error code or SOAP_OK)
	virtual	int GetSerialPorts(_onvifDeviceIO__GetSerialPorts *onvifDeviceIO__GetSerialPorts, _onvifDeviceIO__GetSerialPortsResponse *onvifDeviceIO__GetSerialPortsResponse) { return GetSerialPorts(NULL, NULL, onvifDeviceIO__GetSerialPorts, onvifDeviceIO__GetSerialPortsResponse); }
	virtual	int GetSerialPorts(const char *endpoint, const char *soap_action, _onvifDeviceIO__GetSerialPorts *onvifDeviceIO__GetSerialPorts, _onvifDeviceIO__GetSerialPortsResponse *onvifDeviceIO__GetSerialPortsResponse);

	/// Web service operation 'GetSerialPortConfiguration' (returns error code or SOAP_OK)
	virtual	int GetSerialPortConfiguration(_onvifDeviceIO__GetSerialPortConfiguration *onvifDeviceIO__GetSerialPortConfiguration, _onvifDeviceIO__GetSerialPortConfigurationResponse *onvifDeviceIO__GetSerialPortConfigurationResponse) { return GetSerialPortConfiguration(NULL, NULL, onvifDeviceIO__GetSerialPortConfiguration, onvifDeviceIO__GetSerialPortConfigurationResponse); }
	virtual	int GetSerialPortConfiguration(const char *endpoint, const char *soap_action, _onvifDeviceIO__GetSerialPortConfiguration *onvifDeviceIO__GetSerialPortConfiguration, _onvifDeviceIO__GetSerialPortConfigurationResponse *onvifDeviceIO__GetSerialPortConfigurationResponse);

	/// Web service operation 'SetSerialPortConfiguration' (returns error code or SOAP_OK)
	virtual	int SetSerialPortConfiguration(_onvifDeviceIO__SetSerialPortConfiguration *onvifDeviceIO__SetSerialPortConfiguration, _onvifDeviceIO__SetSerialPortConfigurationResponse *onvifDeviceIO__SetSerialPortConfigurationResponse) { return SetSerialPortConfiguration(NULL, NULL, onvifDeviceIO__SetSerialPortConfiguration, onvifDeviceIO__SetSerialPortConfigurationResponse); }
	virtual	int SetSerialPortConfiguration(const char *endpoint, const char *soap_action, _onvifDeviceIO__SetSerialPortConfiguration *onvifDeviceIO__SetSerialPortConfiguration, _onvifDeviceIO__SetSerialPortConfigurationResponse *onvifDeviceIO__SetSerialPortConfigurationResponse);

	/// Web service operation 'GetSerialPortConfigurationOptions' (returns error code or SOAP_OK)
	virtual	int GetSerialPortConfigurationOptions(_onvifDeviceIO__GetSerialPortConfigurationOptions *onvifDeviceIO__GetSerialPortConfigurationOptions, _onvifDeviceIO__GetSerialPortConfigurationOptionsResponse *onvifDeviceIO__GetSerialPortConfigurationOptionsResponse) { return GetSerialPortConfigurationOptions(NULL, NULL, onvifDeviceIO__GetSerialPortConfigurationOptions, onvifDeviceIO__GetSerialPortConfigurationOptionsResponse); }
	virtual	int GetSerialPortConfigurationOptions(const char *endpoint, const char *soap_action, _onvifDeviceIO__GetSerialPortConfigurationOptions *onvifDeviceIO__GetSerialPortConfigurationOptions, _onvifDeviceIO__GetSerialPortConfigurationOptionsResponse *onvifDeviceIO__GetSerialPortConfigurationOptionsResponse);

	/// Web service operation 'SendReceiveSerialCommand' (returns error code or SOAP_OK)
	virtual	int SendReceiveSerialCommand(_onvifDeviceIO__SendReceiveSerialCommand *onvifDeviceIO__SendReceiveSerialCommand, _onvifDeviceIO__SendReceiveSerialCommandResponse *onvifDeviceIO__SendReceiveSerialCommandResponse) { return SendReceiveSerialCommand(NULL, NULL, onvifDeviceIO__SendReceiveSerialCommand, onvifDeviceIO__SendReceiveSerialCommandResponse); }
	virtual	int SendReceiveSerialCommand(const char *endpoint, const char *soap_action, _onvifDeviceIO__SendReceiveSerialCommand *onvifDeviceIO__SendReceiveSerialCommand, _onvifDeviceIO__SendReceiveSerialCommandResponse *onvifDeviceIO__SendReceiveSerialCommandResponse);
};
#endif
