include(common/linux.profile)

TOOLCHAIN_PREFIX=aarch64-linux-gnu

[settings]
arch=armv8

[env]
TOOLCHAIN_PREFIX=$TOOLCHAIN_PREFIX
CC=$TOOLCHAIN_PREFIX-gcc
CXX=$TOOLCHAIN_PREFIX-g++
RANLIB=$TOOLCHAIN_PREFIX-ranlib
AS=$TOOLCHAIN_PREFIX-as
STRIP=$TOOLCHAIN_PREFIX-strip
