// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

#import "Resource.pb.h"

@class Layout;
@class Layout_Builder;
@class Layout_Item;
@class Layout_Item_Builder;
@class Layout_Item_Resource;
@class Layout_Item_Resource_Builder;
@class Resource;
@class Resource_Builder;
@class Resource_Property;
@class Resource_Property_Builder;
@class Resources;
@class Resources_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface LayoutRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface Layout : PBGeneratedMessage {
@private
  BOOL hasUserCanEdit_:1;
  BOOL hasLocked_:1;
  BOOL hasCellAspectRatio_:1;
  BOOL hasCellSpacingWidth_:1;
  BOOL hasCellSpacingHeight_:1;
  BOOL hasBackgroundOpacity_:1;
  BOOL hasBackgroundWidth_:1;
  BOOL hasBackgroundHeight_:1;
  BOOL hasBackgroundImageFilename_:1;
  BOOL userCanEdit_:1;
  BOOL locked_:1;
  Float64 cellAspectRatio;
  Float64 cellSpacingWidth;
  Float64 cellSpacingHeight;
  Float64 backgroundOpacity;
  int32_t backgroundWidth;
  int32_t backgroundHeight;
  NSString* backgroundImageFilename;
  NSMutableArray * itemArray;
}
- (BOOL) hasCellAspectRatio;
- (BOOL) hasCellSpacingWidth;
- (BOOL) hasCellSpacingHeight;
- (BOOL) hasUserCanEdit;
- (BOOL) hasLocked;
- (BOOL) hasBackgroundImageFilename;
- (BOOL) hasBackgroundWidth;
- (BOOL) hasBackgroundHeight;
- (BOOL) hasBackgroundOpacity;
@property (readonly) Float64 cellAspectRatio;
@property (readonly) Float64 cellSpacingWidth;
@property (readonly) Float64 cellSpacingHeight;
@property (readonly, strong) NSArray * item;
- (BOOL) userCanEdit;
- (BOOL) locked;
@property (readonly, strong) NSString* backgroundImageFilename;
@property (readonly) int32_t backgroundWidth;
@property (readonly) int32_t backgroundHeight;
@property (readonly) Float64 backgroundOpacity;
- (Layout_Item*)itemAtIndex:(NSUInteger)index;

+ (Layout*) defaultInstance;
- (Layout*) defaultInstance;

+ (id<PBExtensionField>) resource;
- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Layout_Builder*) builder;
+ (Layout_Builder*) builder;
+ (Layout_Builder*) builderWithPrototype:(Layout*) prototype;
- (Layout_Builder*) toBuilder;

+ (Layout*) parseFromData:(NSData*) data;
+ (Layout*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Layout*) parseFromInputStream:(NSInputStream*) input;
+ (Layout*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Layout*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Layout*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Layout_Item : PBGeneratedMessage {
@private
  BOOL hasLeft_:1;
  BOOL hasTop_:1;
  BOOL hasRight_:1;
  BOOL hasBottom_:1;
  BOOL hasRotation_:1;
  BOOL hasZoomLeft_:1;
  BOOL hasZoomTop_:1;
  BOOL hasZoomRight_:1;
  BOOL hasZoomBottom_:1;
  BOOL hasFlags_:1;
  BOOL hasUuid_:1;
  BOOL hasZoomTargetUuid_:1;
  BOOL hasContrastParams_:1;
  BOOL hasDewarpingParams_:1;
  BOOL hasResource_:1;
  Float64 left;
  Float64 top;
  Float64 right;
  Float64 bottom;
  Float64 rotation;
  Float64 zoomLeft;
  Float64 zoomTop;
  Float64 zoomRight;
  Float64 zoomBottom;
  int32_t flags;
  NSString* uuid;
  NSString* zoomTargetUuid;
  NSString* contrastParams;
  NSString* dewarpingParams;
  Layout_Item_Resource* resource;
}
- (BOOL) hasUuid;
- (BOOL) hasFlags;
- (BOOL) hasLeft;
- (BOOL) hasTop;
- (BOOL) hasRight;
- (BOOL) hasBottom;
- (BOOL) hasRotation;
- (BOOL) hasResource;
- (BOOL) hasZoomLeft;
- (BOOL) hasZoomTop;
- (BOOL) hasZoomRight;
- (BOOL) hasZoomBottom;
- (BOOL) hasZoomTargetUuid;
- (BOOL) hasContrastParams;
- (BOOL) hasDewarpingParams;
@property (readonly, strong) NSString* uuid;
@property (readonly) int32_t flags;
@property (readonly) Float64 left;
@property (readonly) Float64 top;
@property (readonly) Float64 right;
@property (readonly) Float64 bottom;
@property (readonly) Float64 rotation;
@property (readonly, strong) Layout_Item_Resource* resource;
@property (readonly) Float64 zoomLeft;
@property (readonly) Float64 zoomTop;
@property (readonly) Float64 zoomRight;
@property (readonly) Float64 zoomBottom;
@property (readonly, strong) NSString* zoomTargetUuid;
@property (readonly, strong) NSString* contrastParams;
@property (readonly, strong) NSString* dewarpingParams;

+ (Layout_Item*) defaultInstance;
- (Layout_Item*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Layout_Item_Builder*) builder;
+ (Layout_Item_Builder*) builder;
+ (Layout_Item_Builder*) builderWithPrototype:(Layout_Item*) prototype;
- (Layout_Item_Builder*) toBuilder;

+ (Layout_Item*) parseFromData:(NSData*) data;
+ (Layout_Item*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Layout_Item*) parseFromInputStream:(NSInputStream*) input;
+ (Layout_Item*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Layout_Item*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Layout_Item*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Layout_Item_Resource : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  BOOL hasPath_:1;
  int32_t id;
  NSString* path;
}
- (BOOL) hasId;
- (BOOL) hasPath;
@property (readonly) int32_t id;
@property (readonly, strong) NSString* path;

+ (Layout_Item_Resource*) defaultInstance;
- (Layout_Item_Resource*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Layout_Item_Resource_Builder*) builder;
+ (Layout_Item_Resource_Builder*) builder;
+ (Layout_Item_Resource_Builder*) builderWithPrototype:(Layout_Item_Resource*) prototype;
- (Layout_Item_Resource_Builder*) toBuilder;

+ (Layout_Item_Resource*) parseFromData:(NSData*) data;
+ (Layout_Item_Resource*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Layout_Item_Resource*) parseFromInputStream:(NSInputStream*) input;
+ (Layout_Item_Resource*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Layout_Item_Resource*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Layout_Item_Resource*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Layout_Item_Resource_Builder : PBGeneratedMessage_Builder {
@private
  Layout_Item_Resource* result;
}

- (Layout_Item_Resource*) defaultInstance;

- (Layout_Item_Resource_Builder*) clear;
- (Layout_Item_Resource_Builder*) clone;

- (Layout_Item_Resource*) build;
- (Layout_Item_Resource*) buildPartial;

- (Layout_Item_Resource_Builder*) mergeFrom:(Layout_Item_Resource*) other;
- (Layout_Item_Resource_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Layout_Item_Resource_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (int32_t) id;
- (Layout_Item_Resource_Builder*) setId:(int32_t) value;
- (Layout_Item_Resource_Builder*) clearId;

- (BOOL) hasPath;
- (NSString*) path;
- (Layout_Item_Resource_Builder*) setPath:(NSString*) value;
- (Layout_Item_Resource_Builder*) clearPath;
@end

@interface Layout_Item_Builder : PBGeneratedMessage_Builder {
@private
  Layout_Item* result;
}

- (Layout_Item*) defaultInstance;

- (Layout_Item_Builder*) clear;
- (Layout_Item_Builder*) clone;

- (Layout_Item*) build;
- (Layout_Item*) buildPartial;

- (Layout_Item_Builder*) mergeFrom:(Layout_Item*) other;
- (Layout_Item_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Layout_Item_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUuid;
- (NSString*) uuid;
- (Layout_Item_Builder*) setUuid:(NSString*) value;
- (Layout_Item_Builder*) clearUuid;

- (BOOL) hasFlags;
- (int32_t) flags;
- (Layout_Item_Builder*) setFlags:(int32_t) value;
- (Layout_Item_Builder*) clearFlags;

- (BOOL) hasLeft;
- (Float64) left;
- (Layout_Item_Builder*) setLeft:(Float64) value;
- (Layout_Item_Builder*) clearLeft;

- (BOOL) hasTop;
- (Float64) top;
- (Layout_Item_Builder*) setTop:(Float64) value;
- (Layout_Item_Builder*) clearTop;

- (BOOL) hasRight;
- (Float64) right;
- (Layout_Item_Builder*) setRight:(Float64) value;
- (Layout_Item_Builder*) clearRight;

- (BOOL) hasBottom;
- (Float64) bottom;
- (Layout_Item_Builder*) setBottom:(Float64) value;
- (Layout_Item_Builder*) clearBottom;

- (BOOL) hasRotation;
- (Float64) rotation;
- (Layout_Item_Builder*) setRotation:(Float64) value;
- (Layout_Item_Builder*) clearRotation;

- (BOOL) hasResource;
- (Layout_Item_Resource*) resource;
- (Layout_Item_Builder*) setResource:(Layout_Item_Resource*) value;
- (Layout_Item_Builder*) setResourceBuilder:(Layout_Item_Resource_Builder*) builderForValue;
- (Layout_Item_Builder*) mergeResource:(Layout_Item_Resource*) value;
- (Layout_Item_Builder*) clearResource;

- (BOOL) hasZoomLeft;
- (Float64) zoomLeft;
- (Layout_Item_Builder*) setZoomLeft:(Float64) value;
- (Layout_Item_Builder*) clearZoomLeft;

- (BOOL) hasZoomTop;
- (Float64) zoomTop;
- (Layout_Item_Builder*) setZoomTop:(Float64) value;
- (Layout_Item_Builder*) clearZoomTop;

- (BOOL) hasZoomRight;
- (Float64) zoomRight;
- (Layout_Item_Builder*) setZoomRight:(Float64) value;
- (Layout_Item_Builder*) clearZoomRight;

- (BOOL) hasZoomBottom;
- (Float64) zoomBottom;
- (Layout_Item_Builder*) setZoomBottom:(Float64) value;
- (Layout_Item_Builder*) clearZoomBottom;

- (BOOL) hasZoomTargetUuid;
- (NSString*) zoomTargetUuid;
- (Layout_Item_Builder*) setZoomTargetUuid:(NSString*) value;
- (Layout_Item_Builder*) clearZoomTargetUuid;

- (BOOL) hasContrastParams;
- (NSString*) contrastParams;
- (Layout_Item_Builder*) setContrastParams:(NSString*) value;
- (Layout_Item_Builder*) clearContrastParams;

- (BOOL) hasDewarpingParams;
- (NSString*) dewarpingParams;
- (Layout_Item_Builder*) setDewarpingParams:(NSString*) value;
- (Layout_Item_Builder*) clearDewarpingParams;
@end

@interface Layout_Builder : PBGeneratedMessage_Builder {
@private
  Layout* result;
}

- (Layout*) defaultInstance;

- (Layout_Builder*) clear;
- (Layout_Builder*) clone;

- (Layout*) build;
- (Layout*) buildPartial;

- (Layout_Builder*) mergeFrom:(Layout*) other;
- (Layout_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Layout_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCellAspectRatio;
- (Float64) cellAspectRatio;
- (Layout_Builder*) setCellAspectRatio:(Float64) value;
- (Layout_Builder*) clearCellAspectRatio;

- (BOOL) hasCellSpacingWidth;
- (Float64) cellSpacingWidth;
- (Layout_Builder*) setCellSpacingWidth:(Float64) value;
- (Layout_Builder*) clearCellSpacingWidth;

- (BOOL) hasCellSpacingHeight;
- (Float64) cellSpacingHeight;
- (Layout_Builder*) setCellSpacingHeight:(Float64) value;
- (Layout_Builder*) clearCellSpacingHeight;

- (NSMutableArray *)item;
- (Layout_Item*)itemAtIndex:(NSUInteger)index;
- (Layout_Builder *)addItem:(Layout_Item*)value;
- (Layout_Builder *)setItemArray:(NSArray *)array;
- (Layout_Builder *)clearItem;

- (BOOL) hasUserCanEdit;
- (BOOL) userCanEdit;
- (Layout_Builder*) setUserCanEdit:(BOOL) value;
- (Layout_Builder*) clearUserCanEdit;

- (BOOL) hasLocked;
- (BOOL) locked;
- (Layout_Builder*) setLocked:(BOOL) value;
- (Layout_Builder*) clearLocked;

- (BOOL) hasBackgroundImageFilename;
- (NSString*) backgroundImageFilename;
- (Layout_Builder*) setBackgroundImageFilename:(NSString*) value;
- (Layout_Builder*) clearBackgroundImageFilename;

- (BOOL) hasBackgroundWidth;
- (int32_t) backgroundWidth;
- (Layout_Builder*) setBackgroundWidth:(int32_t) value;
- (Layout_Builder*) clearBackgroundWidth;

- (BOOL) hasBackgroundHeight;
- (int32_t) backgroundHeight;
- (Layout_Builder*) setBackgroundHeight:(int32_t) value;
- (Layout_Builder*) clearBackgroundHeight;

- (BOOL) hasBackgroundOpacity;
- (Float64) backgroundOpacity;
- (Layout_Builder*) setBackgroundOpacity:(Float64) value;
- (Layout_Builder*) clearBackgroundOpacity;
@end

