REM place %FILE%.msi here

SET FILE=networkoptix-hdwitness-full-2.3.0.0-windows-x64
SET APPSERVER_PORT=7011
SET APPSERVER_PASSWORD=234
SET SERVER_APPSERVER_HOST=localhost

msiexec.exe /quiet /norestart /l*v %FILE%.log /i %FILE%.msi INSTALL_ECS=1 INSTALL_SERVER=1 INSTALL_CLIENT=1 APPSERVER_PORT=%APPSERVER_PORT% APPSERVER_PASSWORD=%APPSERVER_PASSWORD% SERVER_APPSERVER_HOST=%SERVER_APPSERVER_HOST% SERVER_APPSERVER_PORT=%APPSERVER_PORT% SERVER_APPSERVER_LOGIN=admin SERVER_APPSERVER_PASSWORD=%APPSERVER_PASSWORD%