REM place %FILE%.msi here

SET FILE=hdwitness-2.2.0.6040-windows-x64-release-full
SET APPSERVER_PORT=7011
SET APPSERVER_PASSWORD=234
SET SERVER_APPSERVER_HOST=10.0.2.119

msiexec.exe /quiet /norestart /l*v %FILE%.log /i %FILE%.msi INSTALL_ECS=1 INSTALL_SERVER=1 INSTALL_CLIENT=1 APPSERVER_PORT=%APPSERVER_PORT% APPSERVER_PASSWORD=%APPSERVER_PASSWORD% SERVER_APPSERVER_HOST=%SERVER_APPSERVER_HOST% SERVER_APPSERVER_PORT=%APPSERVER_PORT% SERVER_APPSERVER_LOGIN=admin SERVER_APPSERVER_PASSWORD=%APPSERVER_PASSWORD%