<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="en" sourcelanguage="en">
<context>
    <name>QnContextHelp</name>
    <message>
        <source>ContextId_Scene</source>
        <translation>&lt;html&gt;
	&lt;head&gt;
		&lt;title&gt;&lt;/title&gt;
	&lt;/head&gt;
	&lt;body&gt;
		&lt;p&gt;
			&amp;nbsp;&lt;/p&gt;
		&lt;p&gt;
			&lt;strong&gt;&lt;span style=&quot;font-size:16px;&quot;&gt;&lt;span style=&quot;color:#ffff00;&quot;&gt;SCENE SHORTCUTS&lt;/span&gt;&lt;/strong&gt;&lt;/p&gt;
		&lt;div&gt;
			&lt;span style=&quot;color:#99ff99;&quot;&gt;&lt;strong&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;Move&lt;/span&gt;&lt;/strong&gt;&lt;/span&gt;&lt;/div&gt;
		&lt;div&gt;
			&lt;span style=&quot;font-size:12px;&quot;&gt;Right Click Drag (CTRL + Arrows)&lt;/span&gt;&lt;/div&gt;
		&lt;div&gt;
			&amp;nbsp;&lt;/div&gt;
		&lt;div&gt;
			&lt;strong style=&quot;color: rgb(153, 255, 153); &quot;&gt;&lt;span style=&quot;font-size: 14px; &quot;&gt;Zoom&lt;/span&gt;&lt;/strong&gt;&lt;/div&gt;
		&lt;div&gt;
			&lt;span style=&quot;font-size:12px;&quot;&gt;Mouse Wheel&lt;/span&gt;&lt;/div&gt;
		&lt;div&gt;
			&amp;nbsp;&lt;/div&gt;
		&lt;div&gt;
			&lt;strong style=&quot;color: rgb(153, 255, 153); &quot;&gt;&lt;span style=&quot;font-size: 14px; &quot;&gt;Distance&lt;/span&gt;&lt;/strong&gt;&lt;/div&gt;
		&lt;div&gt;
			&lt;span style=&quot;font-size:12px;&quot;&gt;CTRL + Mouse Wheel&lt;/span&gt;&lt;/div&gt;
		&lt;div&gt;
			&amp;nbsp;&lt;/div&gt;
		&lt;div&gt;
			&lt;strong style=&quot;color: rgb(153, 255, 153); &quot;&gt;&lt;span style=&quot;font-size: 14px; &quot;&gt;Fin in View&lt;/span&gt;&lt;/strong&gt;&lt;/div&gt;
		&lt;div&gt;
			&lt;span style=&quot;font-size:12px;&quot;&gt;Double Click (Asterisk)&lt;/span&gt;&lt;/div&gt;
		&lt;div&gt;
			&amp;nbsp;&lt;/div&gt;
		&lt;div&gt;
			&lt;strong style=&quot;color: rgb(153, 255, 153); &quot;&gt;&lt;span style=&quot;font-size: 14px; &quot;&gt;Context Menu&lt;/span&gt;&lt;/strong&gt;&lt;/div&gt;
		&lt;div&gt;
			&lt;span style=&quot;font-size:12px;&quot;&gt;Right Click&lt;/span&gt;&lt;/div&gt;
		&lt;div&gt;
			&amp;nbsp;&lt;/div&gt;
		&lt;div&gt;
			&amp;nbsp;&lt;/div&gt;
		&lt;div&gt;
			&amp;nbsp;&lt;/div&gt;
		&lt;div&gt;
			&lt;strong&gt;&lt;span style=&quot;font-size:16px;&quot;&gt;&lt;span style=&quot;color:#ffff00;&quot;&gt;ITEMS&amp;#39; SHORTCUTS&lt;/span&gt;&lt;/span&gt;&lt;/strong&gt;&lt;/div&gt;
		&lt;div&gt;
			&amp;nbsp;&lt;/div&gt;
		&lt;div&gt;
			&lt;strong style=&quot;color: rgb(153, 255, 153); &quot;&gt;&lt;span style=&quot;font-size: 14px; &quot;&gt;Toggle Select&lt;/span&gt;&lt;/strong&gt;&lt;/div&gt;
		&lt;div&gt;
			&lt;span style=&quot;font-size:12px;&quot;&gt;Left Click&lt;/span&gt;&lt;/div&gt;
		&lt;div&gt;
			&amp;nbsp;&lt;/div&gt;
		&lt;div&gt;
			&lt;strong style=&quot;color: rgb(153, 255, 153); &quot;&gt;&lt;span style=&quot;font-size: 14px; &quot;&gt;Multi Select&lt;/span&gt;&lt;/strong&gt;&lt;/div&gt;
		&lt;div&gt;
			&lt;span style=&quot;font-size:12px;&quot;&gt;CTRL + Left Click&lt;/span&gt;&lt;/div&gt;
		&lt;div&gt;
			&amp;nbsp;&lt;/div&gt;
		&lt;div&gt;
			&lt;strong style=&quot;color: rgb(153, 255, 153); &quot;&gt;&lt;span style=&quot;font-size: 14px; &quot;&gt;Context Menu&lt;/span&gt;&lt;/strong&gt;&lt;/div&gt;
		&lt;div&gt;
			&lt;span style=&quot;font-size:12px;&quot;&gt;Right Click&lt;/span&gt;&lt;/div&gt;
		&lt;div&gt;
			&amp;nbsp;&lt;/div&gt;
		&lt;div&gt;
			&lt;strong style=&quot;color: rgb(153, 255, 153); &quot;&gt;&lt;span style=&quot;font-size: 14px; &quot;&gt;Move Selection&lt;/span&gt;&lt;/strong&gt;&lt;/div&gt;
		&lt;div&gt;
			&lt;span style=&quot;font-size:12px;&quot;&gt;Arrow Keys&lt;/span&gt;&lt;/div&gt;
		&lt;div&gt;
			&amp;nbsp;&lt;/div&gt;
		&lt;div&gt;
			&lt;strong style=&quot;color: rgb(153, 255, 153); &quot;&gt;&lt;span style=&quot;font-size: 14px; &quot;&gt;Resize&lt;/span&gt;&lt;/strong&gt;&lt;/div&gt;
		&lt;div&gt;
			&lt;span style=&quot;font-size:12px;&quot;&gt;Drag a Corner&lt;/span&gt;&lt;/div&gt;
		&lt;div&gt;
			&amp;nbsp;&lt;/div&gt;
		&lt;div&gt;
			&lt;strong style=&quot;color: rgb(153, 255, 153); &quot;&gt;&lt;span style=&quot;font-size: 14px; &quot;&gt;Move/Switch&lt;/span&gt;&lt;/strong&gt;&lt;/div&gt;
		&lt;div&gt;
			&lt;span style=&quot;font-size:12px;&quot;&gt;Drag&amp;#39;n&amp;#39;Drop&lt;/span&gt;&lt;/div&gt;
		&lt;div&gt;
			&amp;nbsp;&lt;/div&gt;
		&lt;div&gt;
			&lt;strong style=&quot;color: rgb(153, 255, 153); &quot;&gt;&lt;span style=&quot;font-size: 14px; &quot;&gt;Toggle Fullscreen&lt;/span&gt;&lt;/strong&gt;&lt;/div&gt;
		&lt;div&gt;
			&lt;span style=&quot;font-size:12px;&quot;&gt;Double Click (ENTER)&lt;/span&gt;&lt;/div&gt;
		&lt;div&gt;
			&amp;nbsp;&lt;/div&gt;
		&lt;div&gt;
			&lt;strong style=&quot;color: rgb(153, 255, 153); &quot;&gt;&lt;span style=&quot;font-size: 14px; &quot;&gt;Zoom&lt;/span&gt;&lt;/strong&gt;&lt;/div&gt;
		&lt;div&gt;
			&lt;span style=&quot;font-size:12px;&quot;&gt;Mouse Wheel&lt;/span&gt;&lt;/div&gt;
		&lt;div&gt;
			&amp;nbsp;&lt;/div&gt;
		&lt;div&gt;
			&lt;strong style=&quot;color: rgb(153, 255, 153); &quot;&gt;&lt;span style=&quot;font-size: 14px; &quot;&gt;Rotate (Coarse)&lt;/span&gt;&lt;/strong&gt;&lt;/div&gt;
		&lt;div&gt;
			&lt;span style=&quot;font-size:12px;&quot;&gt;CTRL+ALT+Left Click Drag&lt;/span&gt;&lt;/div&gt;
		&lt;div&gt;
			&amp;nbsp;&lt;/div&gt;
		&lt;div&gt;
			&lt;strong style=&quot;color: rgb(153, 255, 153); &quot;&gt;&lt;span style=&quot;font-size: 14px; &quot;&gt;Rotate (Fine)&lt;/span&gt;&lt;/strong&gt;&lt;/div&gt;
		&lt;div&gt;
			&lt;span style=&quot;font-size:12px;&quot;&gt;ALT+Left Click Drag&lt;/span&gt;&lt;/div&gt;
	&lt;/body&gt;
&lt;/html&gt;

</translation>
    </message>
    <message>
        <source>ContextId_MotionGrid</source>
        <translation>&lt;html&gt;
	&lt;head&gt;
		&lt;title&gt;&lt;/title&gt;
	&lt;/head&gt;
	&lt;body&gt;
		&lt;p&gt;
			&amp;nbsp;&lt;/p&gt;
		&lt;p&gt;
			&lt;span style=&quot;font-size:16px;&quot;&gt;&lt;strong&gt;&lt;span style=&quot;color:#ffff00;&quot;&gt;MRS SHORTCUTS&lt;/span&gt;&lt;/strong&gt;&lt;/span&gt;&lt;/p&gt;
		&lt;div&gt;
			&lt;span style=&quot;color:#99ff99;&quot;&gt;&lt;strong&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;Select Area (MRS)&lt;/span&gt;&lt;/strong&gt;&lt;/span&gt;&lt;/div&gt;
		&lt;div&gt;
			&lt;span style=&quot;font-size: 12px; &quot;&gt;SHIFT&lt;/span&gt;&lt;span style=&quot;font-size:12px;&quot;&gt;&amp;nbsp;+ Drag&lt;/span&gt;&lt;/div&gt;
		&lt;div&gt;
			&amp;nbsp;&lt;/div&gt;
		&lt;div&gt;
			&lt;strong style=&quot;color: rgb(153, 255, 153); &quot;&gt;&lt;span style=&quot;font-size: 14px; &quot;&gt;Add Area&lt;/span&gt;&lt;/strong&gt;&lt;/div&gt;
		&lt;div&gt;
			&lt;span style=&quot;font-size: 12px; &quot;&gt;CTRL + SHIFT + Drag&lt;/span&gt;&lt;/div&gt;
		&lt;div&gt;
			&amp;nbsp;&lt;/div&gt;
		&lt;div&gt;
			&lt;strong style=&quot;color: rgb(153, 255, 153); &quot;&gt;&lt;span style=&quot;font-size: 14px; &quot;&gt;Clear Selection&lt;/span&gt;&lt;/strong&gt;&lt;/div&gt;
		&lt;div&gt;
			&lt;span style=&quot;font-size: 12px;&quot;&gt;Left Click&lt;/span&gt;&lt;/div&gt;
		&lt;div&gt;
			&amp;nbsp;&lt;/div&gt;
		&lt;div&gt;
			&amp;nbsp;&lt;/div&gt;
		&lt;div&gt;
			&lt;p&gt;
				&lt;span style=&quot;font-size:16px;&quot;&gt;&lt;strong&gt;&lt;span style=&quot;color: rgb(255, 255, 0); &quot;&gt;TIPS&lt;/span&gt;&lt;/strong&gt;&lt;/span&gt;&lt;/p&gt;
			&lt;div&gt;
				&lt;span style=&quot;color: rgb(153, 255, 153); &quot;&gt;&lt;strong&gt;&lt;span style=&quot;font-size: 14px; &quot;&gt;MRS For Multi Cameras&lt;/span&gt;&lt;/strong&gt;&lt;/span&gt;&lt;/div&gt;
			&lt;div&gt;
				&lt;span style=&quot;font-size: 12px;&quot;&gt;Combine Areas in Different Items&lt;/span&gt;&lt;/div&gt;
			&lt;div&gt;
				&amp;nbsp;&lt;/div&gt;
			&lt;div&gt;
				&lt;strong style=&quot;color: rgb(153, 255, 153); &quot;&gt;&lt;span style=&quot;font-size: 14px; &quot;&gt;Switch Off MRS&lt;/span&gt;&lt;/strong&gt;&lt;/div&gt;
			&lt;div&gt;
				&lt;span style=&quot;font-size: 12px; &quot;&gt;Press MRS Button Below&lt;/span&gt;&lt;/div&gt;
		&lt;/div&gt;
		&lt;div&gt;
			&amp;nbsp;&lt;/div&gt;
	&lt;/body&gt;
&lt;/html&gt;
</translation>
    </message>
    <message>
        <source>ContextId_Slider</source>
        <translation>&lt;html&gt;
	&lt;head&gt;
		&lt;title&gt;&lt;/title&gt;
	&lt;/head&gt;
	&lt;body&gt;
		&lt;p&gt;
			&amp;nbsp;&lt;/p&gt;
		&lt;p&gt;
			&lt;span style=&quot;font-size:16px;&quot;&gt;&lt;strong&gt;&lt;span style=&quot;color:#ffff00;&quot;&gt;PLAYBACK TIPS&lt;/span&gt;&lt;/strong&gt;&lt;/span&gt;&lt;/p&gt;
		&lt;div&gt;
			&lt;span style=&quot;color:#99ff99;&quot;&gt;&lt;strong&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;Toggle Play/Pause&lt;/span&gt;&lt;/strong&gt;&lt;/span&gt;&lt;/div&gt;
		&lt;div&gt;
			&lt;span style=&quot;font-size: 12px;&quot;&gt;&amp;gt; or || buttons (SPACE)&lt;/span&gt;&lt;/div&gt;
		&lt;div&gt;
			&amp;nbsp;&lt;/div&gt;
		&lt;div&gt;
			&lt;strong style=&quot;color: rgb(153, 255, 153); &quot;&gt;&lt;span style=&quot;font-size: 14px; &quot;&gt;FF/Rew&lt;/span&gt;&lt;/strong&gt;&lt;/div&gt;
		&lt;div&gt;
			&lt;span style=&quot;font-size: 12px; &quot;&gt;&amp;lt;&amp;lt; and &amp;gt;&amp;gt; &amp;nbsp;buttons &lt;/span&gt;&lt;/div&gt;
		&lt;div&gt;
			&lt;span style=&quot;font-size: 12px; &quot;&gt;Speed Slider&lt;/span&gt;&lt;/div&gt;
		&lt;div&gt;
			&lt;span style=&quot;font-size: 12px; &quot;&gt;Mouse Wheel on Speed Slider&lt;/span&gt;&lt;/div&gt;
		&lt;div&gt;
			&amp;nbsp;&lt;/div&gt;
		&lt;div&gt;
			&lt;strong style=&quot;color: rgb(153, 255, 153); &quot;&gt;&lt;span style=&quot;font-size: 14px; &quot;&gt;Prev/Next Recorded Chunk&lt;/span&gt;&lt;/strong&gt;&lt;/div&gt;
		&lt;div&gt;
			&lt;span style=&quot;font-size: 12px;&quot;&gt;|&amp;lt;&amp;lt; and &amp;gt;&amp;gt;| &amp;nbsp;buttons&lt;/span&gt;&lt;/div&gt;
		&lt;div&gt;
			&lt;div&gt;
				&amp;nbsp;&lt;/div&gt;
			&lt;div&gt;
				&lt;b style=&quot;color: rgb(153, 255, 153); font-size: 14px; &quot;&gt;Prev/&lt;/b&gt;&lt;font color=&quot;#99ff99&quot;&gt;&lt;span style=&quot;font-size: 14px;&quot;&gt;&lt;b&gt;Next Frame (on Pause)&lt;/b&gt;&lt;/span&gt;&lt;/font&gt;&lt;/div&gt;
			&lt;div&gt;
				&lt;span style=&quot;font-size: 12px; &quot;&gt;|&amp;lt; and &amp;gt;| &amp;nbsp;buttons&lt;/span&gt;&lt;/div&gt;
			&lt;div&gt;
				&lt;span style=&quot;font-size: 12px; &quot;&gt;Mouse Wheel on Speed Slider&lt;/span&gt;&lt;/div&gt;
			&lt;div&gt;
				&lt;span style=&quot;font-size: 12px;&quot;&gt;Speed Slider&lt;/span&gt;&lt;/div&gt;
			&lt;div&gt;
				&amp;nbsp;&lt;/div&gt;
			&lt;div&gt;
				&lt;font color=&quot;#99ff99&quot;&gt;&lt;span style=&quot;font-size: 14px;&quot;&gt;&lt;b&gt;Adjust Volume&lt;/b&gt;&lt;/span&gt;&lt;/font&gt;&lt;/div&gt;
			&lt;div&gt;
				&lt;span style=&quot;font-size: 12px; &quot;&gt;Use Volume Slider&lt;/span&gt;&lt;/div&gt;
			&lt;div&gt;
				&lt;span style=&quot;font-size: 12px; &quot;&gt;Mouse Wheel on Volume &amp;nbsp;Slider&lt;/span&gt;&lt;/div&gt;
			&lt;div&gt;
				&lt;span style=&quot;font-size: 12px; &quot;&gt;Mute Button&lt;/span&gt;&lt;/div&gt;
			&lt;div&gt;
				&amp;nbsp;&lt;/div&gt;
			&lt;div&gt;
				&lt;p&gt;
					&lt;span style=&quot;font-size: 16px; &quot;&gt;&lt;strong&gt;&lt;span style=&quot;color: rgb(255, 255, 0); &quot;&gt;NAVIGATION TIPS&lt;/span&gt;&lt;/strong&gt;&lt;/span&gt;&lt;/p&gt;
			&lt;/div&gt;
			&lt;div&gt;
				&lt;strong style=&quot;color: rgb(153, 255, 153); &quot;&gt;&lt;span style=&quot;font-size: 14px; &quot;&gt;Change Position/Go to Archive&lt;/span&gt;&lt;/strong&gt;&lt;/div&gt;
			&lt;div&gt;
				&lt;span style=&quot;font-size: 12px; &quot;&gt;Click on Time Line or Time Scale&lt;/span&gt;&lt;/div&gt;
			&lt;div&gt;
				&lt;span style=&quot;font-size: 12px; &quot;&gt;Drag Time Slider&amp;nbsp;&lt;/span&gt;&lt;/div&gt;
		&lt;/div&gt;
		&lt;div&gt;
			&amp;nbsp;&lt;/div&gt;
		&lt;div&gt;
			&lt;div&gt;
				&lt;strong style=&quot;color: rgb(153, 255, 153); &quot;&gt;&lt;span style=&quot;font-size: 14px; &quot;&gt;Zoom Time Scale&lt;/span&gt;&lt;/strong&gt;&lt;/div&gt;
			&lt;div&gt;
				&lt;span style=&quot;font-size: 12px; &quot;&gt;Mouse Wheel on Time Scale&lt;/span&gt;&lt;/div&gt;
			&lt;div&gt;
				&amp;nbsp;&lt;/div&gt;
		&lt;/div&gt;
		&lt;div&gt;
			&lt;div&gt;
				&lt;strong style=&quot;color: rgb(153, 255, 153); &quot;&gt;&lt;span style=&quot;font-size: 14px; &quot;&gt;Switch to Live&lt;/span&gt;&lt;/strong&gt;&lt;/div&gt;
			&lt;div&gt;
				&lt;span style=&quot;font-size: 12px; &quot;&gt;LIVE Button&lt;/span&gt;&lt;/div&gt;
			&lt;div&gt;
				&amp;nbsp;&lt;/div&gt;
		&lt;/div&gt;
		&lt;div&gt;
			&lt;p&gt;
				&lt;span style=&quot;font-size:16px;&quot;&gt;&lt;strong&gt;&lt;span style=&quot;color: rgb(255, 255, 0); &quot;&gt;GENERAL&lt;/span&gt;&lt;/strong&gt;&lt;/span&gt;&lt;/p&gt;
			&lt;div&gt;
				&lt;span style=&quot;color: rgb(153, 255, 153); &quot;&gt;&lt;strong&gt;&lt;span style=&quot;font-size: 14px; &quot;&gt;Context Menu&lt;/span&gt;&lt;/strong&gt;&lt;/span&gt;&lt;/div&gt;
			&lt;div&gt;
				&lt;span style=&quot;font-size: 12px;&quot;&gt;Right Click&lt;/span&gt;&lt;/div&gt;
			&lt;div&gt;
				&amp;nbsp;&lt;/div&gt;
			&lt;div&gt;
				&lt;strong style=&quot;color: rgb(153, 255, 153); &quot;&gt;&lt;span style=&quot;font-size: 14px; &quot;&gt;Toggle Sync Cameras&lt;/span&gt;&lt;/strong&gt;&lt;/div&gt;
			&lt;div&gt;
				&lt;span style=&quot;font-size: 12px; &quot;&gt;SYNC button&lt;/span&gt;&lt;/div&gt;
			&lt;div&gt;
				&amp;nbsp;&lt;/div&gt;
			&lt;div&gt;
				&lt;strong style=&quot;color: rgb(153, 255, 153); &quot;&gt;&lt;span style=&quot;font-size: 14px; &quot;&gt;Switch MRS Off&lt;/span&gt;&lt;/strong&gt;&lt;/div&gt;
			&lt;div&gt;
				&lt;span style=&quot;font-size: 12px; &quot;&gt;MRS Button&lt;/span&gt;&lt;/div&gt;
			&lt;div&gt;
				&amp;nbsp;&lt;/div&gt;
			&lt;div&gt;
				&lt;strong style=&quot;color: rgb(153, 255, 153); &quot;&gt;&lt;span style=&quot;font-size: 14px; &quot;&gt;Select Region to Export&lt;/span&gt;&lt;/strong&gt;&lt;/div&gt;
			&lt;div&gt;
				&lt;span style=&quot;font-size: 12px; &quot;&gt;SHIFT+Click (Context Menu)&lt;/span&gt;&lt;/div&gt;
		&lt;/div&gt;
		&lt;div&gt;
			&amp;nbsp;&lt;/div&gt;
	&lt;/body&gt;
&lt;/html&gt;
</translation>
    </message>
    <message>
        <source>ContextId_Tree</source>
        <translation>&lt;html&gt;
	&lt;head&gt;
		&lt;title&gt;&lt;/title&gt;
	&lt;/head&gt;
	&lt;body&gt;
		&lt;p&gt;
			&amp;nbsp;&lt;/p&gt;
		&lt;p&gt;
			&lt;span style=&quot;font-size:16px;&quot;&gt;&lt;strong&gt;&lt;span style=&quot;color:#ffff00;&quot;&gt;RESOURCES TREE TIPS&lt;/span&gt;&lt;/strong&gt;&lt;/span&gt;&lt;/p&gt;
		&lt;div&gt;
			&lt;strong style=&quot;color: rgb(153, 255, 153); &quot;&gt;&lt;span style=&quot;font-size: 14px; &quot;&gt;Always Visible&lt;/span&gt;&lt;/strong&gt;&lt;/div&gt;
		&lt;div&gt;
			&lt;span style=&quot;font-size: 12px; &quot;&gt;Pin Button&lt;/span&gt;&lt;/div&gt;
		&lt;div&gt;
			&amp;nbsp;&lt;/div&gt;
		&lt;div&gt;
			&lt;div&gt;
				&lt;strong style=&quot;color: rgb(153, 255, 153); &quot;&gt;&lt;span style=&quot;font-size: 14px; &quot;&gt;Context Menu&lt;/span&gt;&lt;/strong&gt;&lt;/div&gt;
			&lt;div&gt;
				&lt;span style=&quot;font-size: 12px; &quot;&gt;Right Click&lt;/span&gt;&lt;/div&gt;
			&lt;div&gt;
				&amp;nbsp;&lt;/div&gt;
		&lt;/div&gt;
		&lt;div&gt;
			&lt;span style=&quot;color:#99ff99;&quot;&gt;&lt;strong&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;Open Item(s)&lt;/span&gt;&lt;/strong&gt;&lt;/span&gt;&lt;/div&gt;
		&lt;div&gt;
			&lt;span style=&quot;font-size: 12px;&quot;&gt;Drag Item(s) to scene&lt;/span&gt;&lt;/div&gt;
		&lt;div&gt;
			&lt;span style=&quot;font-size: 12px;&quot;&gt;Double Click on Item&lt;/span&gt;&lt;/div&gt;
		&lt;div&gt;
			&amp;nbsp;&lt;/div&gt;
		&lt;div&gt;
			&lt;div&gt;
				&lt;font color=&quot;#99ff99&quot;&gt;&lt;span style=&quot;font-size: 14px; &quot;&gt;&lt;b&gt;Multi-Selection&lt;/b&gt;&lt;/span&gt;&lt;/font&gt;&lt;/div&gt;
			&lt;div&gt;
				&lt;span style=&quot;font-size: 12px; &quot;&gt;SHIFT + Click&lt;/span&gt;&lt;/div&gt;
		&lt;/div&gt;
		&lt;div&gt;
			&amp;nbsp;&lt;/div&gt;
		&lt;div&gt;
			&lt;strong style=&quot;color: rgb(153, 255, 153); &quot;&gt;&lt;span style=&quot;font-size: 14px; &quot;&gt;Add Item to Layout&lt;/span&gt;&lt;/strong&gt;&lt;/div&gt;
		&lt;div&gt;
			&lt;span style=&quot;font-size: 12px; &quot;&gt;Drag Item within Resources Tree&lt;/span&gt;&lt;/div&gt;
		&lt;div&gt;
			&lt;span style=&quot;font-size: 12px; &quot;&gt;CTRL + Drag Item&lt;/span&gt;&lt;span style=&quot;font-size: 12px; &quot;&gt;&amp;nbsp;From Scene&lt;/span&gt;&lt;/div&gt;
		&lt;div&gt;
			&amp;nbsp;&lt;/div&gt;
		&lt;div&gt;
			&lt;strong style=&quot;color: rgb(153, 255, 153); &quot;&gt;&lt;span style=&quot;font-size: 14px; &quot;&gt;New Layout&lt;/span&gt;&lt;/strong&gt;&lt;/div&gt;
		&lt;div&gt;
			&lt;span style=&quot;font-size: 12px;&quot;&gt;Open New Tab&lt;/span&gt;&lt;/div&gt;
		&lt;div&gt;
			&lt;div&gt;
				&amp;nbsp;&lt;/div&gt;
			&lt;div&gt;
				&lt;font color=&quot;#99ff99&quot;&gt;&lt;span style=&quot;font-size: 14px;&quot;&gt;&lt;b&gt;Copy Layout to User&lt;/b&gt;&lt;/span&gt;&lt;/font&gt;&lt;/div&gt;
			&lt;div&gt;
				&lt;span style=&quot;font-size: 12px; &quot;&gt;Drag within Tree&lt;/span&gt;&lt;/div&gt;
		&lt;/div&gt;
		&lt;p&gt;
			&amp;nbsp;&lt;/p&gt;
	&lt;/body&gt;
&lt;/html&gt;
</translation>
    </message>
    <message>
        <source>ContextId_Search</source>
        <translation>
            Type search context help here
        </translation>
    </message>
</context>
</TS>
