// Copyright 2018-present Network Optix, Inc. Licensed under MPL 2.0: www.mozilla.org/MPL/2.0/

#include "certificate_verifier.h"

#include <future>

#include <QtCore/QDir>
#include <QtCore/QFile>
#include <QtCore/QPointer>

#include <core/resource/media_server_resource.h>
#include <core/resource_management/resource_pool.h>
#include <nx/network/nx_network_ini.h>
#include <nx/network/socket_factory.h>
#include <nx/network/ssl/certificate.h>
#include <nx/network/ssl/helpers.h>
#include <nx/utils/log/log.h>
#include <nx/vms/client/core/ini.h>
#include <nx/vms/common/system_settings.h>

#include "certificate_storage.h"

namespace nx::vms::client::core {

using CertificateValidationLevel = network::server_certificate::ValidationLevel;

struct CertificateVerifier::Private
{
    template<typename Chain>
    Status verifyCertificateByStorage(
        const nx::Uuid& serverId,
        const Chain& chain,
        bool acceptExpired) const
    {
        // Normally both storages should be available. If not, return an error.
        if (!NX_ASSERT(connectionCertificatesStorage)
            || !NX_ASSERT(autoGeneratedCertificatesStorage))
        {
            return Status::notFound;
        }

        if (!NX_ASSERT(!serverId.isNull()))
            return Status::notFound;

        if (!NX_ASSERT(!chain.empty()))
            return Status::notFound;

        if (certificateValidationLevel == CertificateValidationLevel::disabled)
            return Status::ok;

        const auto& certificate = chain[0];

        NX_VERBOSE(this, "Validating certificate for the server %1", serverId);

        const auto connectionCertificatePublicKey =
            connectionCertificatesStorage->pinnedCertificate(serverId);
        const auto autoGeneratedCertificatePublicKey =
            autoGeneratedCertificatesStorage->pinnedCertificate(serverId);

        if (!connectionCertificatePublicKey && !autoGeneratedCertificatePublicKey)
        {
            NX_VERBOSE(this, "Certificate public key was not found");
            return Status::notFound;
        }

        const auto expiresAt = std::chrono::duration_cast<std::chrono::seconds>(
            certificate.notAfter().time_since_epoch());
        // Current spec says that we should not report a severe error when the certificate is shown
        // to user for the first time. Therefore we check expiration time only at this point.
        if (expiresAt.count() < QDateTime::currentSecsSinceEpoch() && !acceptExpired)
        {
            NX_VERBOSE(this, "Certificate has expired");
            return Status::mismatch;
        }

        if (connectionCertificatePublicKey == certificate.publicKey())
        {
            NX_VERBOSE(this,
                "Found pinned connection certificate: %1",
                *connectionCertificatePublicKey);
            return Status::ok;
        }
        if (autoGeneratedCertificatePublicKey == certificate.publicKey())
        {
            NX_VERBOSE(this,
                "Found pinned auto-generated certificate: %1",
                *autoGeneratedCertificatePublicKey);
            return Status::ok;
        }

        NX_VERBOSE(this,
            "Certificate mismatch for the server %1. Pinned: %2 and %3, actual: %4",
            serverId,
            connectionCertificatePublicKey,
            autoGeneratedCertificatePublicKey,
            certificate.publicKey());

        return Status::mismatch;
    }

    void pinCertificate(
        const nx::Uuid& serverId,
        const std::string& publicKey,
        CertificateType certType)
    {
        switch (certType)
        {
            case CertificateType::autogenerated:
                autoGeneratedCertificatesStorage->pinCertificate(serverId, publicKey);
                break;
            case CertificateType::connection:
                connectionCertificatesStorage->pinCertificate(serverId, publicKey);
                break;
            default:
                NX_ASSERT(false, "Unknown certificate type");
        }
    }

    std::optional<std::string> pinnedCertificate(
        const nx::Uuid& serverId,
        CertificateType certType)
    {
        switch (certType)
        {
            case CertificateType::autogenerated:
                return autoGeneratedCertificatesStorage->pinnedCertificate(serverId);
            case CertificateType::connection:
                return connectionCertificatesStorage->pinnedCertificate(serverId);
            default:
                NX_ASSERT(false, "Unknown certificate type");
                return {};
        }
    }

    mutable Mutex mutex;

    CertificateValidationLevel certificateValidationLevel = CertificateValidationLevel::strict;
    QPointer<CertificateStorage> connectionCertificatesStorage;
    QPointer<CertificateStorage> autoGeneratedCertificatesStorage;
};

CertificateVerifier::CertificateVerifier(
    network::server_certificate::ValidationLevel certificateValidationLevel,
    CertificateStorage* connectionCertificatesStorage,
    CertificateStorage* autoGeneratedCertificatesStorage,
    QObject* parent)
    :
    base_type(parent),
    d(new Private())
{
    d->certificateValidationLevel = certificateValidationLevel;
    d->connectionCertificatesStorage = connectionCertificatesStorage;
    d->autoGeneratedCertificatesStorage = autoGeneratedCertificatesStorage;

    if (QString path = ini().rootCertificatesFolder; !path.isEmpty())
    {
        QDir folder(path);
        if (!NX_ASSERT(folder.exists(), "Root certificates folder does not exist: %1", path))
            return;

        const auto entries = folder.entryList({"*.pem", "*.crt"}, QDir::Files);
        for (const auto& fileName: entries)
        {
            QFile f(folder.absoluteFilePath(fileName));
            if (!f.open(QIODevice::ReadOnly | QIODevice::Text))
            {
                NX_WARNING(this, "Cannot open file %1", folder.absoluteFilePath(fileName));
                continue;
            }
            nx::vms::common::AbstractCertificateVerifier::loadTrustedCertificate(
                f.readAll(), fileName);
        }
    }
}

CertificateVerifier::~CertificateVerifier()
{
}

nx::network::ssl::AdapterFunc CertificateVerifier::makeGeneralAdapterFunc(
    const std::string& expectedKey, const std::string& expectedHost)
{
    if (!nx::network::ini().verifyVmsSslCertificates)
        return nx::network::ssl::kAcceptAnyCertificate;

    return nx::network::ssl::makeAdapterFunc(
        [expectedKey, expectedHost](auto chain)
        {
            return verifyBySystemCertificates(chain, expectedHost)
                || (NX_ASSERT(!chain.empty()) && chain[0].publicKey() == expectedKey);
        });
}

nx::network::ssl::AdapterFunc CertificateVerifier::makeRestrictedAdapterFunc(
    const std::string& expectedKey)
{
    if (!nx::network::ini().verifyVmsSslCertificates)
        return nx::network::ssl::kAcceptAnyCertificate;

    return nx::network::ssl::makeAdapterFunc(
        [expectedKey](auto chain)
        {
            return NX_ASSERT(!chain.empty()) && (chain[0].publicKey() == expectedKey);
        });
}

CertificateVerifier::Status CertificateVerifier::verifyCertificate(
    const nx::Uuid& serverId,
    const nx::network::ssl::CertificateChain& chain,
    bool acceptExpired) const
{
    NX_MUTEX_LOCKER lock(&d->mutex);
    return d->verifyCertificateByStorage(serverId, chain, acceptExpired);
}

void CertificateVerifier::setValidationLevel(CertificateValidationLevel certificateValidationLevel)
{
    NX_MUTEX_LOCKER lock(&d->mutex);
    d->certificateValidationLevel = certificateValidationLevel;
}

void CertificateVerifier::pinCertificate(
    const nx::Uuid& serverId,
    const std::string& publicKey,
    CertificateType certType)
{
    NX_MUTEX_LOCKER lock(&d->mutex);
    d->pinCertificate(serverId, publicKey, certType);
}

std::optional<std::string> CertificateVerifier::pinnedCertificate(
    const nx::Uuid& serverId,
    CertificateType certType)
{
    NX_MUTEX_LOCKER lock(&d->mutex);
    return d->pinnedCertificate(serverId, certType);
}

} // namespace nx::vms::client::core
