// Copyright 2018-present Network Optix, Inc. Licensed under MPL 2.0: www.mozilla.org/MPL/2.0/

#include "server_certificate_watcher.h"

#include <QtCore/QPointer>

#include <core/resource/media_server_resource.h>
#include <nx/network/ssl/certificate.h>
#include <nx/utils/log/assert.h>
#include <nx/vms/client/core/network/remote_connection.h>
#include <nx/vms/client/core/resource/session_resources_signal_listener.h>

#include "certificate_cache.h"
#include "certificate_verifier.h"

namespace {

const auto kMinimumSupportedVersion = nx::utils::SoftwareVersion(5, 0);

} // namespace

namespace nx::vms::client::core {

ServerCertificateWatcher::ServerCertificateWatcher(
    SystemContext* systemContext,
    CertificateVerifier* certificateVerifier,
    QObject* parent)
    :
    base_type(parent),
    SystemContextAware(systemContext)
{
    auto pinCertificates =
        [this, certificateVerifier = QPointer<CertificateVerifier>(certificateVerifier)](
            const QnMediaServerResourcePtr& server)
        {
            if (!NX_ASSERT(certificateVerifier))
                return;

            // Servers v4.2 or older shouldn't have certificate data.
            if (server->getVersion() < kMinimumSupportedVersion)
                return;

            using namespace nx::network::ssl;

            auto updateKey =
                [this, certificateVerifier, serverId = server->getId()](
                    const std::string& pem,
                    CertificateVerifier::CertificateType certType)
                {
                    if (pem.empty())
                        return;

                    std::vector<Certificate> certificates = Certificate::parse(pem);
                    if (certificates.empty())
                        return;

                    const auto publicKey = certificates[0].publicKey();

                    // Update cached certificate and pin it if possible.
                    auto cache = this->cache();
                    if (!NX_ASSERT(cache))
                        return;

                    auto cached = cache->certificate(serverId, certType);
                    auto pinned = certificateVerifier->pinnedCertificate(serverId, certType);

                    if (cached == pinned)
                        certificateVerifier->pinCertificate(serverId, publicKey, certType);

                    cache->addCertificate(serverId, publicKey, certType);
                };
            updateKey(
                server->certificate(),
                CertificateVerifier::CertificateType::autogenerated);
            updateKey(
                server->userProvidedCertificate(),
                CertificateVerifier::CertificateType::connection);
        };

    auto serverListener = new SessionResourcesSignalListener<QnMediaServerResource>(
        systemContext,
        this);

    serverListener->setOnAddedHandler(
        [pinCertificates](const QnMediaServerResourceList& servers)
        {
            for (const auto& server: servers)
                pinCertificates(server);
        });

    serverListener->addOnSignalHandler(
        &QnMediaServerResource::certificateChanged,
        pinCertificates);

    serverListener->setOnRemovedHandler(
        [this](const QnMediaServerResourceList& servers)
        {
            if (auto cache = this->cache())
            {
                for (const auto& server: servers)
                    cache->removeCertificates(server->getId());
            }
        });

    serverListener->start();
}

std::shared_ptr<CertificateCache> ServerCertificateWatcher::cache() const
{
    if (auto connection = this->connection())
        return connection->certificateCache();

    return {};
}

} // namespace nx::vms::client::core
