# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-06 01:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20170505_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Product'),
        ),
    ]
