# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-20 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_datastructure_meta_settings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blank',
        ),
    ]
