# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-29 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_auto_20170802_1950'),
    ]

    operations = [
        migrations.RunSQL(
            sql=['ALTER TABLE cms_datarecord MODIFY value LONGTEXT CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci'],
            reverse_sql=['ALTER TABLE cms_datarecord MODIFY value LONGTEXT']
        )
    ]
