# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-19 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_datastructure_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
    ]
