# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-26 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_context_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastructure',
            name='order',
            field=models.IntegerField(default=100000),
        ),
        migrations.AlterField(
            model_name='datastructure',
            name='type',
            field=models.IntegerField(choices=[(0, 'Text'), (1, 'Image'), (2, 'HTML'), (3, 'Long Text'), (4, 'File')], default=0),
        ),
        migrations.AlterIndexTogether(
            name='datastructure',
            index_together=set([('context', 'order')]),
        ),
    ]
