# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-15 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0025_product_can_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentversion',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cms.Product'),
        ),
    ]
