# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-05-02 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0029_contexttemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='context',
            name='template',
        ),
        migrations.AddField(
            model_name='contexttemplate',
            name='template',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
