# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-11-08 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0046_auto_20181024_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergroupstocustomizationpermissions',
            options={},
        ),
        migrations.AlterField(
            model_name='customization',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, help_text='Parent is the customization that the current customization depends on.<br>\n                               The main purpose is to control how the integration review process works.\n                               <br><br>\n                               If there is a parent:<br>\n                               - A review will be locked until the parent accepts that review.<br>\n                               - If the parent rejects a review it will automatically be rejected for this\n                               customization.<br><br>\n                               If there is no parent selected or the parent is not in the review an integration\n                               can be reviewed whenever.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_customizations', to='cms.Customization'),
        ),
        migrations.AlterField(
            model_name='customization',
            name='public_downloads',
            field=models.BooleanField(default=True, help_text='Any user can view the downloads page.'),
        ),
        migrations.AlterField(
            model_name='customization',
            name='public_release_history',
            field=models.BooleanField(default=False, help_text='Any user can view the release history page.'),
        ),
        migrations.AlterField(
            model_name='customization',
            name='trust_parent',
            field=models.BooleanField(default=False, help_text='Automatically accepts integrations the parent\n                                                                   customization accepts.'),
        ),
        migrations.AlterField(
            model_name='datastructure',
            name='meta_settings',
            field=jsonfield.fields.JSONField(blank=True, default={}, help_text="For the regex field \\ needs to be escaped with another '\\'"),
        ),
        migrations.AlterField(
            model_name='datastructure',
            name='type',
            field=models.IntegerField(choices=[(0, 'Text'), (1, 'Image'), (2, 'HTML'), (3, 'Long Text'), (4, 'File'), (5, 'GUID'), (6, 'Select'), (7, 'External File'), (8, 'External Image')], default=0),
        ),
    ]
