# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-11-29 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0047_auto_20181108_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastructure',
            name='type',
            field=models.IntegerField(choices=[(0, 'Text'), (1, 'Image'), (2, 'HTML'), (3, 'Long Text'), (4, 'File'), (5, 'GUID'), (6, 'Select'), (7, 'External File'), (8, 'External Image'), (9, 'Check Box')], default=0),
        ),
    ]
