# Generated by Django 2.2 on 2019-05-08 19:42

from django.db import migrations


def remove_permissions(apps, schema_editor):
    codenames_to_remove = ['can_access_product',
                           'can_view_customization',
                           'can_view_pending',
                           'publish_version',
                           'force_update',
                           'add_usergroupstocustomizationpermissions',
                           'change_usergroupstocustomizationpermissions',
                           'delete_usergroupstocustomizationpermissions',
                           'view_usergroupstocustomizationpermissions']
    Permission = apps.get_model('auth.Permission')
    Permission.objects.filter(codename__in=codenames_to_remove).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0051_auto_20190412_2012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customization',
            options={'permissions': (('access_customization', 'Can access customization'),)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': (('access_product', 'Can access product'),), 'verbose_name': 'asset', 'verbose_name_plural': 'assets'},
        ),
        migrations.AlterModelOptions(
            name='productcustomizationreview',
            options={'permissions': (('publish_version', 'Can publish content to production'), ('force_update', 'Can forcibly update content')), 'verbose_name': 'review', 'verbose_name_plural': 'reviews'},
        ),
        migrations.RunPython(remove_permissions)
    ]
