# Generated by Django 2.2 on 2019-05-24 01:57

import cms.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0054_auto_20190522_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(default=cms.models.get_integration_type, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.ProductType'),
        ),
    ]
