# Generated by Django 2.2 on 2019-06-01 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0056_auto_20190529_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='contact_email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
