# Generated by Django 2.2 on 2019-06-11 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0058_datastructure_deprecated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarecord',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.ContentVersion'),
        ),
    ]
