#pragma once

#include <nx/vms/api/analytics/manifest_items.h>
#include <nx/fusion/model_functions_fwd.h>
#include <nx/utils/uuid.h>

namespace nx::vms::api::analytics {

// TODO: Move this class to server-only library; eliminate its usages in the Client.
/**
 * The JSON-serializable data structure that is given by each Analytics Engine's DeviceAgent to the
 * Server after the DeviceAgent has been created by the Engine.
 */
struct NX_VMS_API DeviceAgentManifest
{
    /** Whitelist of Event types for types declared in the owner Engine manifest. */
    QList<QString> supportedEventTypeIds;

    /** Whitelist of Object types for types declared in the owner Engine manifest. */
    QList<QString> supportedObjectTypeIds;

    /**
     * Types of Events that can be generated by this particular DeviceAgent instance, in addition
     * to the types declared in the Engine manifest.
     */
    QList<EventType> eventTypes;

    /**
     * Types of Objects that can be generated by this particular DeviceAgent instance, in addition
     * to the types declared in the Engine manifest.
     */
    QList<ObjectType> objectTypes;

    /** Groups used to group Object and Event types declared by this manifest. */
    QList<Group> groups;
};

#define DeviceAgentManifest_Fields \
    (supportedEventTypeIds)(supportedObjectTypeIds)(eventTypes)(objectTypes)(groups)

QN_FUSION_DECLARE_FUNCTIONS(DeviceAgentManifest, (json), NX_VMS_API)

} // namespace nx::vms::api::analytics
