pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["adding_cameras_manually.htm","Working with DW Spectrum &#62; Configuring Cameras &#62; Adding Cameras &#62; Adding Cameras Manually","Adding Cameras Manually",""],
["adding_items_to_layouts.htm","Working with DW Spectrum &#62; Configuring Layouts &#62; Setting up a Layout &#62; Adding Items to Layouts","Adding Items to Layouts",""],
["additional_software_requirements.htm","DW Spectrum&#174; Installation and Configuration Guide &#62; DW Spectrum System Requirements &#62; Software Requirements &#62; Additional Software Requirements","Additional Software Requirements",""],
["adjusting_the_layout_look_and_feel.htm","Working with DW Spectrum &#62; Configuring Layouts &#62; Setting up a Layout &#62; Adjusting the Layout Look and Feel","Adjusting the Layout Look and Feel",""],
["adjusting_volume_while_viewing_local_files.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Playing Back Local Files in DW Spectrum &#62; Adjusting Volume while Viewing Local Files","Adjusting Volume while Viewing Local Files",""],
["all-in-one_installation.htm","DW Spectrum&#174; Installation and Configuration Guide &#62; DW Spectrum Install Guide (Windows) &#62; All-in-one installation","All-in-one installation",""],
["bandwidth_requirements.htm","DW Spectrum&#174; Installation and Configuration Guide &#62; DW Spectrum System Requirements &#62; Network Requirements &#62; Bandwidth Requirements","Bandwidth Requirements",""],
["changing_aspect_ratio_of_the_scene_cells.htm","Working with DW Spectrum &#62; Configuring Layouts &#62; Setting up a Layout &#62; Adjusting the Layout Look and Feel &#62; Changing Aspect Ratio of the Scene Cells","Changing Aspect Ratio of the Scene Cells",""],
["changing_interface_language.htm","Working with DW Spectrum &#62; DW Spectrum User Interface Overview &#62; Changing Interface Language","Changing Interface Language",""],
["changing_multi-channel_video_a.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Exporting &#62; Exporting the Layout in Multi-Video Format &#62; Changing Multi-Channel Video after Export","Changing Multi-Channel Video after Export",""],
["changing_the_distance_between_items.htm","Working with DW Spectrum &#62; Configuring Layouts &#62; Setting up a Layout &#62; Adjusting the Layout Look and Feel &#62; Changing the distance between items","Changing the distance between items",""],
["changing_user_settings.htm","Working with DW Spectrum &#62; Users Management &#62; Changing User Settings","Changing User Settings",""],
["choosing_the_best_installation_configuration.htm","DW Spectrum&#174; Installation and Configuration Guide &#62; DW Spectrum Install Guide (Windows) &#62; Choosing the Best Installation Configuration","Choosing the Best Installation Configuration",""],
["client_hardware_requirements.htm","DW Spectrum&#174; Installation and Configuration Guide &#62; DW Spectrum System Requirements &#62; Hardware Requirements &#62; Client Hardware Requirements","Client Hardware Requirements",""],
["configuring_audio_for_the_camera_(admin_only).htm","Working with DW Spectrum &#62; Configuring Cameras &#62; Setting Up Cameras &#62; Configuring Audio for the Camera","Configuring Audio for the Camera",""],
["configuring_cameras.htm","Working with DW Spectrum &#62; Configuring Cameras","Configuring Cameras",""],
["configuring_camera_authentication_(admin_only).htm","Working with DW Spectrum &#62; Configuring Cameras &#62; Setting Up Cameras &#62; Configuring Camera Authentication","Configuring Camera Authentication",""],
["configuring_enterprise_controller.htm","DW Spectrum&#174; Installation and Configuration Guide &#62; DW Spectrum Install Guide (Windows) &#62; Configuring DW Spectrum Components after Installation &#62; Configuring Enterprise Controller","Configuring Enterprise Controller",""],
["configuring_hd_witness_components_after_installati.htm","DW Spectrum&#174; Installation and Configuration Guide &#62; DW Spectrum Install Guide (Windows) &#62; Configuring DW Spectrum Components after Installation","Configuring DW Spectrum Components after Installation",""],
["configuring_layouts.htm","Working with DW Spectrum &#62; Configuring Layouts","Configuring Layouts",""],
["configuring_media_folders.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Playing Back Local Files in DW Spectrum &#62; Configuring Media Folders","Configuring Media Folders",""],
["configuring_media_server.htm","DW Spectrum&#174; Installation and Configuration Guide &#62; DW Spectrum Install Guide (Windows) &#62; Configuring DW Spectrum Components after Installation &#62; Configuring Media Server","Configuring Media Server",""],
["configuring_media_servers_additional_settings_(ad.htm","Working with DW Spectrum &#62; Obtaining and Configuring Media Server’s Additional Settings (Admin Only)","Obtaining and Configuring Media Server’s Additional Settings (Admin Only)",""],
["configuring_media_server_storages_(admin_only).htm","Working with DW Spectrum &#62; Obtaining and Configuring Media Server’s Additional Settings (Admin Only) &#62; Configuring Media Server Storages (Admin Only)","Configuring Media Server Storages (Admin Only)",""],
["configuring_proprietary_camera_parameters.htm","Working with DW Spectrum &#62; Configuring Cameras &#62; Setting Up Cameras &#62; Configuring Proprietary Camera Parameters","Configuring Proprietary Camera Parameters",""],
["connecting_to_enterprise_controller_and_working_of.htm","Working with DW Spectrum &#62; Connecting to Enterprise Controller and Working Offline","Connecting to Enterprise Controller and Working Offline",""],
["context_menu.htm","Working with DW Spectrum &#62; DW Spectrum User Interface Overview &#62; Context Menu","Context Menu",""],
["copying_layouts_between_users_(admin_only).htm","Working with DW Spectrum &#62; Configuring Layouts &#62; Assigning Layouts to Users (Admin Only)","Assigning Layouts to Users (Admin Only)",""],
["cpu_and_bandwidth_saving_durin.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Watching Cameras in DW Spectrum &#62; CPU and Bandwidth Saving during Playback (RADASS)","CPU and Bandwidth Saving during Playback (RADASS)",""],
["creating_a_new_layout_(admin_only).htm","Working with DW Spectrum &#62; Configuring Layouts &#62; Creating a New Layout (Admin Only)","Creating a New Layout (Admin Only)",""],
["creating_a_new_user_(admin_only).htm","Working with DW Spectrum &#62; Users Management &#62; Creating a New User (Admin Only)","Creating a New User (Admin Only)",""],
["custom_installation_(all-in-one).htm","DW Spectrum&#174; Installation and Configuration Guide &#62; DW Spectrum Install Guide (Windows) &#62; All-in-one installation &#62; Custom Installation (All-in-One)","Custom Installation (All-in-One)",""],
["deleting_a_camera_(admin_only).htm","Working with DW Spectrum &#62; Configuring Cameras &#62; Deleting a Camera (Admin Only)","Deleting a Camera (Admin Only)",""],
["deleting_a_user_(admin_only).htm","Working with DW Spectrum &#62; Users Management &#62; Deleting a User (Admin Only)","Deleting a User (Admin Only)",""],
["deleting_layouts_(admin_only).htm","Working with DW Spectrum &#62; Configuring Layouts &#62; Deleting Layouts (Admin Only)","Deleting Layouts (Admin Only)",""],
["deleting_media_server_(admin_only).htm","Working with DW Spectrum &#62; Obtaining and Configuring Media Server’s Additional Settings (Admin Only) &#62; Deleting Media Server (Admin Only)","Deleting Media Server (Admin Only)",""],
["discovering_cameras_automatica.htm","Working with DW Spectrum &#62; Configuring Cameras &#62; Adding Cameras &#62; Discovering Cameras Automatically","Discovering Cameras Automatically",""],
["distinguishing_tabs_and_layouts.htm","Working with DW Spectrum &#62; Configuring Layouts &#62; Distinguishing Tabs and Layouts","Distinguishing Tabs and Layouts",""],
["dual_stream_recording_radass.htm","Working with DW Spectrum &#62; Configuring Cameras &#62; Setting Up Cameras &#62; Setting up Recording Schedule &#62; Dual Stream Recording (RADASS)","Dual Stream Recording (RADASS)",""],
["editing_recording_schedule.htm","Working with DW Spectrum &#62; Configuring Cameras &#62; Setting Up Cameras &#62; Setting up Recording Schedule &#62; Editing Recording Schedule","Editing Recording Schedule",""],
["exporting.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Exporting","Exporting",""],
["exporting_a_recorded_region_from_a_camera.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Exporting &#62; Exporting Recorded Region from Single Camera","Exporting Recorded Region from Single Camera",""],
["exporting_the_layout_in_multi-.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Exporting &#62; Exporting the Layout in Multi-Video Format","Exporting the Layout in Multi-Video Format",""],
["forensic_analysis.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Forensic Analysis","Forensic Analysis",""],
["forwarding_traffic_from_private_to_public_subnets_.htm","DW Spectrum&#174; Installation and Configuration Guide &#62; DW Spectrum System Requirements &#62; Network Requirements &#62; Forwarding Traffic from Private to Public Subnets via Mediaproxy Component","Forwarding Traffic from Private to Public Subnets via Mediaproxy Component",""],
["fullscreen.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Forensic Analysis &#62; Expanding Items to Fullscreen","Expanding Items to Fullscreen",""],
["full_screen_and_windowed_mode.htm","Working with DW Spectrum &#62; DW Spectrum User Interface Overview &#62; Full Screen and Windowed Mode","Full Screen and Windowed Mode",""],
["getting_context_help.htm","Working with DW Spectrum &#62; DW Spectrum User Interface Overview &#62; Getting Context Help","Getting Context Help",""],
["glossary.htm","Glossary","Glossary",""],
["hd_witness_1_2_-_variable_changed_ftsearch.htm","No title","DW Spectrum Guide Contents | Index | Search Enter one or more keywords to search (&#39;*&#39; and &#39;?&#39; wildcards are supported): ",""],
["hd_witness_architecture.htm","DW Spectrum&#174; Installation and Configuration Guide &#62; DW Spectrum Architecture","DW Spectrum Architecture",""],
["hd_witness_install_guide_(windows).htm","DW Spectrum&#174; Installation and Configuration Guide &#62; DW Spectrum Install Guide (Windows)","DW Spectrum Install Guide (Windows)",""],
["hd_witness_install_guide_linux.htm","DW Spectrum&#174; Installation and Configuration Guide &#62; DW Spectrum Install Guide (Linux)","DW Spectrum Install Guide (Linux)",""],
["hd_witness_quick_start.htm","Working with DW Spectrum &#62; DW Spectrum Quick Start","DW Spectrum Quick Start",""],
["hd_witness_requirements.htm","DW Spectrum&#174; Installation and Configuration Guide &#62; DW Spectrum System Requirements","DW Spectrum System Requirements",""],
["hd_witness_user_interface_overview.htm","Working with DW Spectrum &#62; DW Spectrum User Interface Overview","DW Spectrum User Interface Overview",""],
["hd_witness%AE.htm","DW Spectrum&#174;","DW Spectrum&#174;",""],
["hd_witness%AE_installation_and_configuration_guide.htm","DW Spectrum&#174; Installation and Configuration Guide","DW Spectrum&#174; Installation and Configuration Guide",""],
["installing_client_only.htm","DW Spectrum&#174; Installation and Configuration Guide &#62; DW Spectrum Install Guide (Windows) &#62; Installing Client Only","Installing Client Only",""],
["installing_enterprise_controller_and_media_server_.htm","DW Spectrum&#174; Installation and Configuration Guide &#62; DW Spectrum Install Guide (Windows) &#62; Installing Enterprise Controller and Media Server on one computer","Installing Enterprise Controller and Media Server on one computer",""],
["installing_media_server_and_connecting_it_to_exist.htm","DW Spectrum&#174; Installation and Configuration Guide &#62; DW Spectrum Install Guide (Windows) &#62; Installing Media Server and Connecting it to Existing Enterprise Controller","Installing Media Server and Connecting it to Existing Enterprise Controller",""],
["introducing_user_roles.htm","Working with DW Spectrum &#62; Introducing User Roles","Introducing User Roles",""],
["launching_and_closing_hd_witness_client.htm","Working with DW Spectrum &#62; Launching and Closing DW Spectrum Client","Launching and Closing DW Spectrum Client",""],
["list_of_supported_camera_vendors.htm","DW Spectrum&#174; Installation and Configuration Guide &#62; DW Spectrum System Requirements &#62; List of Supported Camera Vendors","List of Supported Camera Vendors",""],
["local_files_structure_in_resource_tree.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Playing Back Local Files in DW Spectrum &#62; Local files structure in Resource Tree","Local files structure in Resource Tree",""],
["main_menu.htm","Working with DW Spectrum &#62; DW Spectrum User Interface Overview &#62; Main Menu","Main Menu",""],
["monitoring_media_servers.htm","Working with DW Spectrum &#62; Obtaining and Configuring Media Server’s Additional Settings (Admin Only) &#62; Monitoring Media Servers (Admin Only)","Monitoring Media Servers (Admin Only)",""],
["moving_and_swapping_items_within_scene.htm","Working with DW Spectrum &#62; Configuring Layouts &#62; Setting up a Layout &#62; Adjusting the Layout Look and Feel &#62; Moving and swapping items within Scene","Moving and swapping items within Scene",""],
["navigating_through_archive_and.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Watching Cameras in DW Spectrum &#62; Navigating through Archive and Live","Navigating through Archive and Live",""],
["navigating_through_local_files.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Playing Back Local Files in DW Spectrum &#62; Navigating Through Local Files","Navigating Through Local Files",""],
["navigating_through_several_cameras_synchronously.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Watching Cameras in DW Spectrum &#62; Navigating through Archive and Live &#62; Navigating through several cameras synchronously","Navigating through several cameras synchronously",""],
["network_requirements.htm","DW Spectrum&#174; Installation and Configuration Guide &#62; DW Spectrum System Requirements &#62; Network Requirements","Network Requirements",""],
["obtaining_and_activating_hd_witness_licenses.htm","Working with DW Spectrum &#62; Obtaining and Activating DW Spectrum Licenses","Obtaining and Activating DW Spectrum Licenses (Admin Only)",""],
["obtaining_cameras_ip_and_mac.htm","Working with DW Spectrum &#62; Configuring Cameras &#62; Setting Up Cameras &#62; Obtaining Camera’s IP and MAC","Obtaining Camera’s IP and MAC",""],
["obtaining_hd_witness.htm","DW Spectrum&#174; Installation and Configuration Guide &#62; DW Spectrum Install Guide (Windows) &#62; Obtaining DW Spectrum","Obtaining DW Spectrum",""],
["obtaining_system_logs.htm","Troubleshooting and Contacting Support &#62; Obtaining System Logs","Obtaining System Logs",""],
["obtaining_the_current_network_configuration.htm","Troubleshooting and Contacting Support &#62; Obtaining the Current Network Configuration","Obtaining the Current Network Configuration",""],
["opening_and_closing_saved_layouts.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Watching Cameras in DW Spectrum &#62; Opening and Closing Saved Layouts","Opening and Closing Saved Layouts",""],
["opening_camera_settings_dialog.htm","Working with DW Spectrum &#62; Configuring Cameras &#62; Setting Up Cameras","Setting Up Cameras",""],
["opening_local_files__outside_of_media_folders.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Playing Back Local Files in DW Spectrum &#62; Opening Local Files Outside of Media Folders","Opening Local Files Outside of Media Folders",""],
["operating_system_requirements.htm","DW Spectrum&#174; Installation and Configuration Guide &#62; DW Spectrum System Requirements &#62; Software Requirements &#62; Operating System Requirements","Operating System Requirements",""],
["pan-temporal_timeline.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Watching Cameras in DW Spectrum &#62; Navigating through Archive and Live &#62; Pan-Temporal Timeline","Pan-Temporal Timeline",""],
["panic_recording.htm","Working with DW Spectrum &#62; Configuring Cameras &#62; Setting Up Cameras &#62; Setting up Recording Schedule &#62; Panic Recording","Panic Recording",""],
["performing_screen_recording.htm","Working with DW Spectrum &#62; Screen Recording (Windows Only) &#62; Performing Screen Recording","Performing Screen Recording",""],
["performing_smart_search.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Watching Cameras in DW Spectrum &#62; Searching through Archive &#62; Performing Smart Motion Search","Performing Smart Motion Search",""],
["playback_in_hd_witness.htm","Working with DW Spectrum &#62; Playback in DW Spectrum","Playback in DW Spectrum",""],
["playback_panel.htm","Working with DW Spectrum &#62; DW Spectrum User Interface Overview &#62; Playback Panel","Playback Panel",""],
["playing_back_local_files_in_hd_witness.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Playing Back Local Files in DW Spectrum","Playing Back Local Files in DW Spectrum",""],
["ports_and_firewall_requirements.htm","DW Spectrum&#174; Installation and Configuration Guide &#62; DW Spectrum System Requirements &#62; Network Requirements &#62; Ports and Firewall Requirements","Ports and Firewall Requirements",""],
["quick_installation_(all-in-one).htm","DW Spectrum&#174; Installation and Configuration Guide &#62; DW Spectrum Install Guide (Windows) &#62; All-in-one installation &#62; Quick Installation (All-in-One)","Quick Installation (All-in-One)",""],
["removing_item(s)_from_layouts.htm","Working with DW Spectrum &#62; Configuring Layouts &#62; Setting up a Layout &#62; Removing Item(s) from Layouts","Removing Item(s) from Layouts",""],
["renaming_a_camera.htm","Working with DW Spectrum &#62; Configuring Cameras &#62; Setting Up Cameras &#62; Renaming a Camera","Renaming a Camera",""],
["requirements_for_addressing_ip.htm","DW Spectrum&#174; Installation and Configuration Guide &#62; DW Spectrum System Requirements &#62; Network Requirements &#62; Requirements for Addressing IP","Requirements for Addressing IP",""],
["resizing_items_within_scene.htm","Working with DW Spectrum &#62; Configuring Layouts &#62; Setting up a Layout &#62; Adjusting the Layout Look and Feel &#62; Resizing items within Scene","Resizing items within Scene",""],
["rotate.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Forensic Analysis &#62; Rotate","Rotate",""],
["saving_layouts_(admin_only).htm","Working with DW Spectrum &#62; Configuring Layouts &#62; Setting up a Layout &#62; Saving Layouts (Admin Only)","Saving Layouts (Admin Only)",""],
["scene.htm","Working with DW Spectrum &#62; DW Spectrum User Interface Overview &#62; Scene and Layouts","Scene and Layouts",""],
["screen_recording.htm","Working with DW Spectrum &#62; Screen Recording (Windows Only)","Screen Recording (Windows Only)",""],
["search.htm","Working with DW Spectrum &#62; DW Spectrum User Interface Overview &#62; Search","Search",""],
["searching_through_archive.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Watching Cameras in DW Spectrum &#62; Searching through Archive","Searching through Archive",""],
["selecting_items.htm","Working with DW Spectrum &#62; Configuring Layouts &#62; Setting up a Layout &#62; Adjusting the Layout Look and Feel &#62; Selecting items","Selecting items",""],
["server_hardware_requirements.htm","DW Spectrum&#174; Installation and Configuration Guide &#62; DW Spectrum System Requirements &#62; Hardware Requirements &#62; Server Hardware Requirements","Server Hardware Requirements",""],
["setting_same_parameters_for_multiple_cameras_(admi.htm","Working with DW Spectrum &#62; Configuring Cameras &#62; Setting Same Parameters for Multiple Cameras","Setting Same Parameters for Multiple Cameras",""],
["setting_up_a_layout.htm","Working with DW Spectrum &#62; Configuring Layouts &#62; Setting up a Layout","Setting up a Layout",""],
["setting_up_motion_mask_and_motion_sensitivity_(adm.htm","Working with DW Spectrum &#62; Configuring Cameras &#62; Setting Up Cameras &#62; Setting up Motion Mask and Motion Sensitivity","Setting up Motion Mask and Motion Sensitivity",""],
["setting_up_ptz.htm","Working with DW Spectrum &#62; Configuring Cameras &#62; Setting Up Cameras &#62; Setting up PTZ","Setting up PTZ",""],
["setting_up_recording_schedule_(admin_only).htm","Working with DW Spectrum &#62; Configuring Cameras &#62; Setting Up Cameras &#62; Setting up Recording Schedule","Setting up Recording Schedule",""],
["setting_up_screen_recording.htm","Working with DW Spectrum &#62; Screen Recording (Windows Only) &#62; Setting up Screen Recording","Setting up Screen Recording",""],
["showing_and_hiding_side_panels.htm","Working with DW Spectrum &#62; DW Spectrum User Interface Overview &#62; Showing and Hiding Side Panels","Showing and Hiding Side Panels",""],
["software_requirements.htm","DW Spectrum&#174; Installation and Configuration Guide &#62; DW Spectrum System Requirements &#62; Software Requirements","Software Requirements",""],
["starting_and_stopping_hd_witness_server_components.htm","DW Spectrum&#174; Installation and Configuration Guide &#62; DW Spectrum Install Guide (Windows) &#62; Starting and Stopping DW Spectrum Server Components","Starting and Stopping DW Spectrum Server Components",""],
["swapping_cameras_between_media_servers_(admin_only.htm","Working with DW Spectrum &#62; Configuring Cameras &#62; Swapping Cameras between Media Servers (Admin Only)","Swapping Cameras between Media Servers (Admin Only)",""],
["tabs.htm","Working with DW Spectrum &#62; DW Spectrum User Interface Overview &#62; Tabs","Tabs",""],
["taking_a_screenshot.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Taking a Screenshot","Taking a Screenshot",""],
["thumbnail_search.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Watching Cameras in DW Spectrum &#62; Searching through Archive &#62; Thumbnail Search","Thumbnail Search",""],
["time_synchronization_between_system_components.htm","DW Spectrum&#174; Installation and Configuration Guide &#62; DW Spectrum System Requirements &#62; Network Requirements &#62; Time Synchronization between System Components","Time Synchronization between System Components",""],
["tours.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Tours","Tours",""],
["troubleshooting_and_contacting_support.htm","Troubleshooting and Contacting Support","Troubleshooting and Contacting Support",""],
["uninstalling_hd_witness.htm","DW Spectrum&#174; Installation and Configuration Guide &#62; DW Spectrum Install Guide (Windows) &#62; Uninstalling DW Spectrum","Uninstalling DW Spectrum",""],
["upgrading_hd_witness.htm","DW Spectrum&#174; Installation and Configuration Guide &#62; Upgrading DW Spectrum","Upgrading DW Spectrum",""],
["upgrading_hd_witness_or_changing_installed_compone.htm","DW Spectrum&#174; Installation and Configuration Guide &#62; DW Spectrum Install Guide (Windows) &#62; Upgrading DW Spectrum or changing installed components","Upgrading DW Spectrum or changing installed components",""],
["users_management.htm","Working with DW Spectrum &#62; Users Management","Users Management",""],
["using_calendar.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Watching Cameras in DW Spectrum &#62; Searching through Archive &#62; Using Calendar","Using Calendar",""],
["using_fit_in_view.htm","Working with DW Spectrum &#62; Configuring Layouts &#62; Setting up a Layout &#62; Adjusting the Layout Look and Feel &#62; Using Fit In View","Using Fit In View",""],
["using_thumbnails_for_better_navigation.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Watching Cameras in DW Spectrum &#62; Searching through Archive &#62; Using Thumbnails for Better Navigation","Using Thumbnails for Better Navigation",""],
["viewing_and_checking_the_validity_of_exported_vide.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Exporting &#62; Checking the Validity of Exported Videos","Checking the Validity of Exported Videos",""],
["viewing_camera_stream_information.htm","Working with DW Spectrum &#62; DW Spectrum User Interface Overview &#62; Items on Layouts and Scene","Items on Layouts and Scene",""],
["viewing_multi-channel_videos.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Exporting &#62; Exporting the Layout in Multi-Video Format &#62; Viewing Multi-Channel Videos","Viewing Multi-Channel Videos",""],
["viewing_videos_exported_from_a.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Exporting &#62; Viewing Videos Exported from a Single Camera","Viewing Videos Exported from a Single Camera",""],
["watching_cameras_in_hd_witness.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Watching Cameras in DW Spectrum","Watching Cameras in DW Spectrum",""],
["web-client.htm","DW Spectrum&#174; Installation and Configuration Guide &#62; Web-Client","Web-Client",""],
["working_with_a_resource_tree.htm","Working with DW Spectrum &#62; DW Spectrum User Interface Overview &#62; Working with Resource Tree","Working with Resource Tree",""],
["working_with_several_hd_witness_windows.htm","Working with DW Spectrum &#62; Configuring Layouts &#62; Setting up a Layout &#62; Working with Several DW Spectrum Windows","Working with Several DW Spectrum Windows",""],
["zoom.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Forensic Analysis &#62; Zoom","Zoom",""]];
