pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["adding_cameras.htm","Working with DW Spectrum &#62; Cameras Management &#62; Adding Cameras","Adding Cameras",""],
["adding_cameras_manually.htm","Working with DW Spectrum &#62; Cameras Management &#62; Adding Cameras &#62; Adding Cameras Manually (Admin Only)","Adding Cameras Manually (Admin Only)",""],
["adding_items_to_layouts.htm","Working with DW Spectrum &#62; Layouts Management &#62; Setting up Layout &#62; Adding Items to Layouts","Adding Items to Layouts",""],
["adjusting_the_layout_look_and_feel.htm","Working with DW Spectrum &#62; Layouts Management &#62; Setting up Layout &#62; Adjusting the Layout Look and Feel","Adjusting the Layout Look and Feel",""],
["adjusting_volume_while_viewing_local_files.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Playing Back Local Files in DW Spectrum &#62; Adjusting Volume while Viewing Local Files","Adjusting Volume while Viewing Local Files",""],
["changing_aspect_ratio_of_the_scene_cells.htm","Working with DW Spectrum &#62; Layouts Management &#62; Setting up Layout &#62; Adjusting the Layout Look and Feel &#62; Changing Aspect Ratio of Scene Cells","Changing Aspect Ratio of Scene Cells",""],
["changing_interface_language.htm","Working with DW Spectrum &#62; DW Spectrum User Interface Overview &#62; Changing Interface Language","Changing Interface Language",""],
["changing_multi-channel_video_a.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Exporting &#62; Multi-Video Export &#62; Changing Multi-Videos after Export","Changing Multi-Videos after Export",""],
["changing_the_distance_between_items.htm","Working with DW Spectrum &#62; Layouts Management &#62; Setting up Layout &#62; Adjusting the Layout Look and Feel &#62; Changing Distance between Items","Changing Distance between Items",""],
["changing_user_settings.htm","Working with DW Spectrum &#62; Users Management &#62; Changing User Settings","Changing User Settings",""],
["configuring_audio_for_the_camera_(admin_only).htm","Working with DW Spectrum &#62; Cameras Management &#62; Setting Up Cameras &#62; Configuring Audio for the Camera","Configuring Audio for the Camera",""],
["configuring_cameras.htm","Working with DW Spectrum &#62; Cameras Management","Cameras Management",""],
["configuring_camera_authentication_(admin_only).htm","Working with DW Spectrum &#62; Cameras Management &#62; Setting Up Cameras &#62; Configuring Camera&#39;s Authentication","Configuring Camera&#39;s Authentication",""],
["configuring_layouts.htm","Working with DW Spectrum &#62; Layouts Management","Layouts Management",""],
["configuring_media_folders.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Playing Back Local Files in DW Spectrum &#62; Configuring Media Folders","Configuring Media Folders",""],
["configuring_media_servers_additional_settings_(ad.htm","Working with DW Spectrum &#62; Obtaining and Configuring Media Server’s Additional Settings (Admin Only)","Obtaining and Configuring Media Server’s Additional Settings (Admin Only)",""],
["configuring_media_server_storages_(admin_only).htm","Working with DW Spectrum &#62; Obtaining and Configuring Media Server’s Additional Settings (Admin Only) &#62; Configuring Media Server Storages (Admin Only)","Configuring Media Server Storages (Admin Only)",""],
["configuring_proprietary_camera_parameters.htm","Working with DW Spectrum &#62; Cameras Management &#62; Setting Up Cameras &#62; Configuring Proprietary Camera Parameters","Configuring Proprietary Camera Parameters",""],
["connecting_to_enterprise_controller_and_working_of.htm","Working with DW Spectrum &#62; Connecting to Enterprise Controller and Working Offline","Connecting to Enterprise Controller and Working Offline",""],
["context_menu.htm","Working with DW Spectrum &#62; DW Spectrum User Interface Overview &#62; Context Menu","Context Menu",""],
["copying_layouts_between_users_(admin_only).htm","Working with DW Spectrum &#62; Layouts Management &#62; Assigning Layouts to Users (Admin Only)","Assigning Layouts to Users (Admin Only)",""],
["cpu_and_bandwidth_saving_durin.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Watching Cameras in DW Spectrum &#62; CPU and Bandwidth Saving during Playback (RADASS)","CPU and Bandwidth Saving during Playback (RADASS)",""],
["creating_a_new_layout_(admin_only).htm","Working with DW Spectrum &#62; Layouts Management &#62; Creating New Layout (Admin Only)","Creating New Layout (Admin Only)",""],
["creating_a_new_user_(admin_only).htm","Working with DW Spectrum &#62; Users Management &#62; Creating New User (Admin Only)","Creating New User (Admin Only)",""],
["deleting_a_camera_(admin_only).htm","Working with DW Spectrum &#62; Cameras Management &#62; Deleting Cameras (Admin Only)","Deleting Cameras (Admin Only)",""],
["deleting_a_user_(admin_only).htm","Working with DW Spectrum &#62; Users Management &#62; Deleting User (Admin Only)","Deleting User (Admin Only)",""],
["deleting_layouts_(admin_only).htm","Working with DW Spectrum &#62; Layouts Management &#62; Deleting Layouts (Admin Only)","Deleting Layouts (Admin Only)",""],
["deleting_media_server_(admin_only).htm","Working with DW Spectrum &#62; Obtaining and Configuring Media Server’s Additional Settings (Admin Only) &#62; Deleting Media Server (Admin Only)","Deleting Media Server (Admin Only)",""],
["discovering_cameras_automatica.htm","Working with DW Spectrum &#62; Cameras Management &#62; Adding Cameras &#62; Discovering Cameras Automatically","Discovering Cameras Automatically",""],
["dual_stream_recording_radass.htm","Working with DW Spectrum &#62; Cameras Management &#62; Setting Up Cameras &#62; Setting up Recording Schedule &#62; Dual Stream Recording Specifics (RADASS)","Dual Stream Recording Specifics (RADASS)",""],
["editing_recording_schedule.htm","Working with DW Spectrum &#62; Cameras Management &#62; Setting Up Cameras &#62; Setting up Recording Schedule &#62; Editing Recording Schedule","Editing Recording Schedule",""],
["exporting.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Exporting","Exporting",""],
["exporting_a_recorded_region_from_a_camera.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Exporting &#62; Single Camera Export &#62; Exporting Recorded Region from Single Camera","Exporting Recorded Region from Single Camera",""],
["exporting_the_layout_in_multi-.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Exporting &#62; Multi-Video Export &#62; Exporting Layout in Multi-Video Format","Exporting Layout in Multi-Video Format",""],
["forensic_analysis.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Forensic Analysis","Forensic Analysis",""],
["fullscreen.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Forensic Analysis &#62; Expanding Items to Fullscreen","Expanding Items to Fullscreen",""],
["full_screen_and_windowed_mode.htm","Working with DW Spectrum &#62; DW Spectrum User Interface Overview &#62; Full Screen and Windowed Mode","Full Screen and Windowed Mode",""],
["getting_context_help.htm","Working with DW Spectrum &#62; DW Spectrum User Interface Overview &#62; Getting Context Help","Getting Context Help",""],
["glossary.htm","Glossary","Glossary",""],
["hd_witness_1_3_-_client_ftsearch.htm","No title","DW Spectrum Guide Contents | Index | Search Enter one or more keywords to search (&#39;*&#39; and &#39;?&#39; wildcards are supported): ",""],
["hd_witness_install_guide_(windows).htm","HD Witness Install Guide (Windows)","DW Spectrum Install Guide (Windows)",""],
["hd_witness_install_guide_linux.htm","HD Witness Install Guide (Linux)","DW Spectrum Install Guide (Linux)",""],
["hd_witness_quick_start.htm","Working with DW Spectrum &#62; DW Spectrum Quick Start","DW Spectrum Quick Start",""],
["hd_witness_requirements.htm","HD Witness System Requirements","DW Spectrum System Requirements",""],
["hd_witness_user_interface_overview.htm","Working with DW Spectrum &#62; DW Spectrum User Interface Overview","DW Spectrum User Interface Overview",""],
["introducing_user_roles.htm","Working with DW Spectrum &#62; Introducing User Roles","Introducing User Roles",""],
["launching_and_closing_hd_witness_client.htm","Working with DW Spectrum &#62; Launching and Closing DW Spectrum Client","Launching and Closing DW Spectrum Client",""],
["local_files_structure_in_resource_tree.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Playing Back Local Files in DW Spectrum &#62; Local files structure in Resource Tree","Local files structure in Resource Tree",""],
["main_menu.htm","Working with DW Spectrum &#62; DW Spectrum User Interface Overview &#62; Main Menu","Main Menu",""],
["monitoring_media_servers.htm","Working with DW Spectrum &#62; Obtaining and Configuring Media Server’s Additional Settings (Admin Only) &#62; Monitoring Media Servers (Admin Only)","Monitoring Media Servers (Admin Only)",""],
["moving_and_swapping_items_within_scene.htm","Working with DW Spectrum &#62; Layouts Management &#62; Setting up Layout &#62; Adjusting the Layout Look and Feel &#62; Moving and Swapping Items within Scene","Moving and Swapping Items within Scene",""],
["multi-video_export.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Exporting &#62; Multi-Video Export","Multi-Video Export",""],
["navigating_through_archive_and.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Watching Cameras in DW Spectrum &#62; Navigating through Archive and Live","Navigating through Archive and Live",""],
["navigating_through_local_files.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Playing Back Local Files in DW Spectrum &#62; Navigating Through Local Files","Navigating Through Local Files",""],
["navigating_through_several_cameras_synchronously.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Watching Cameras in DW Spectrum &#62; Navigating through Archive and Live &#62; Navigating through Several Cameras Synchronously","Navigating through Several Cameras Synchronously",""],
["obtaining_and_activating_hd_witness_licenses.htm","Working with DW Spectrum &#62; Obtaining and Activating DW Spectrum Licenses","Obtaining and Activating DW Spectrum Licenses (Admin Only)",""],
["obtaining_cameras_ip_and_mac.htm","Working with DW Spectrum &#62; Cameras Management &#62; Setting Up Cameras &#62; Obtaining Camera’s IP and MAC","Obtaining Camera’s IP and MAC",""],
["opening_and_closing_saved_layouts.htm","Working with DW Spectrum &#62; Layouts Management &#62; Opening and Closing Saved Layouts","Opening and Closing Saved Layouts",""],
["opening_camera_settings_dialog.htm","Working with DW Spectrum &#62; Cameras Management &#62; Setting Up Cameras","Setting Up Cameras",""],
["opening_local_files__outside_of_media_folders.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Playing Back Local Files in DW Spectrum &#62; Opening Local Files Outside of Media Folders","Opening Local Files Outside of Media Folders",""],
["pan-temporal_timeline.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Watching Cameras in DW Spectrum &#62; Navigating through Archive and Live &#62; Pan-Temporal Time Line","Pan-Temporal Time Line",""],
["panic_recording.htm","Working with DW Spectrum &#62; Cameras Management &#62; Setting Up Cameras &#62; Setting up Recording Schedule &#62; Panic Recording","Panic Recording",""],
["performing_screen_recording.htm","Working with DW Spectrum &#62; Screen Recording (Windows Only) &#62; Performing Screen Recording","Performing Screen Recording",""],
["performing_smart_search.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Watching Cameras in DW Spectrum &#62; Searching through Archive &#62; Performing Smart Motion Search","Performing Smart Motion Search",""],
["playback_in_hd_witness.htm","Working with DW Spectrum &#62; Playback in DW Spectrum","Playback in DW Spectrum",""],
["playback_panel.htm","Working with DW Spectrum &#62; DW Spectrum User Interface Overview &#62; Playback Panel","Playback Panel",""],
["playing_back_local_files_in_hd_witness.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Playing Back Local Files in DW Spectrum","Playing Back Local Files in DW Spectrum",""],
["removing_item(s)_from_layouts.htm","Working with DW Spectrum &#62; Layouts Management &#62; Setting up Layout &#62; Removing Item(s) from Layouts","Removing Item(s) from Layouts",""],
["renaming_a_camera.htm","Working with DW Spectrum &#62; Cameras Management &#62; Setting Up Cameras &#62; Renaming a Camera","Renaming a Camera",""],
["resetting_a_camera.htm","Working with DW Spectrum &#62; Cameras Management &#62; Setting Up Cameras &#62; Configuring Proprietary Camera Parameters &#62; Resetting a Camera","Resetting a Camera",""],
["resizing_items_within_scene.htm","Working with DW Spectrum &#62; Layouts Management &#62; Setting up Layout &#62; Adjusting the Layout Look and Feel &#62; Resizing Items within Scene","Resizing Items within Scene",""],
["rotate.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Forensic Analysis &#62; Rotate","Rotate",""],
["saving_layouts_(admin_only).htm","Working with DW Spectrum &#62; Layouts Management &#62; Setting up Layout &#62; Saving Layouts (Admin Only)","Saving Layouts (Admin Only)",""],
["screen_recording.htm","Working with DW Spectrum &#62; Screen Recording (Windows Only)","Screen Recording (Windows Only)",""],
["search.htm","Working with DW Spectrum &#62; DW Spectrum User Interface Overview &#62; Search","Search",""],
["searching_through_archive.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Watching Cameras in DW Spectrum &#62; Searching through Archive","Searching through Archive",""],
["selecting_items.htm","Working with DW Spectrum &#62; Layouts Management &#62; Setting up Layout &#62; Adjusting the Layout Look and Feel &#62; Selecting items","Selecting items",""],
["setting_same_parameters_for_multiple_cameras_(admi.htm","Working with DW Spectrum &#62; Cameras Management &#62; Setting Same Parameters for Multiple Cameras","Setting Same Parameters for Multiple Cameras",""],
["setting_up_a_layout.htm","Working with DW Spectrum &#62; Layouts Management &#62; Setting up Layout","Setting up Layout",""],
["setting_up_motion_mask_and_motion_sensitivity_(adm.htm","Working with DW Spectrum &#62; Cameras Management &#62; Setting Up Cameras &#62; Setting up Motion Mask and Motion Sensitivity","Setting up Motion Mask and Motion Sensitivity",""],
["setting_up_ptz.htm","Working with DW Spectrum &#62; Cameras Management &#62; Setting Up Cameras &#62; Setting up PTZ","Setting up PTZ",""],
["setting_up_recording_schedule_(admin_only).htm","Working with DW Spectrum &#62; Cameras Management &#62; Setting Up Cameras &#62; Setting up Recording Schedule","Setting up Recording Schedule",""],
["setting_up_screen_recording.htm","Working with DW Spectrum &#62; Screen Recording (Windows Only) &#62; Setting up Screen Recording","Setting up Screen Recording",""],
["showing_and_hiding_side_panels.htm","Working with DW Spectrum &#62; DW Spectrum User Interface Overview &#62; Showing and Hiding Side Panels","Showing and Hiding Side Panels",""],
["single_camera_export.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Exporting &#62; Single Camera Export","Single Camera Export",""],
["swapping_cameras_between_media_servers_(admin_only.htm","Working with DW Spectrum &#62; Cameras Management &#62; Swapping Cameras between Media Servers (Admin Only)","Swapping Cameras between Media Servers (Admin Only)",""],
["tabs.htm","Working with DW Spectrum &#62; DW Spectrum User Interface Overview &#62; Tabs and Layouts","Tabs and Layouts",""],
["taking_a_screenshot.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Taking Screenshot","Taking Screenshot",""],
["thumbnail_search.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Watching Cameras in DW Spectrum &#62; Searching through Archive &#62; Thumbnail Search","Thumbnail Search",""],
["tours.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Tours","Tours",""],
["troubleshooting_and_contacting_support.htm","Troubleshooting and Contacting Support","Troubleshooting and Contacting Support",""],
["upgrading_firmware_for_a_camer.htm","Working with DW Spectrum &#62; Cameras Management &#62; Setting Up Cameras &#62; Configuring Proprietary Camera Parameters &#62; Upgrading Firmware for a Camera","Upgrading Firmware for a Camera",""],
["upgrading_hd_witness.htm","Upgrading HD Witness","Upgrading DW Spectrum",""],
["users_management.htm","Working with DW Spectrum &#62; Users Management","Users Management",""],
["using_calendar.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Watching Cameras in DW Spectrum &#62; Searching through Archive &#62; Using Calendar","Using Calendar",""],
["using_fit_in_view.htm","Working with DW Spectrum &#62; Layouts Management &#62; Setting up Layout &#62; Adjusting the Layout Look and Feel &#62; Using Fit In View","Using Fit In View",""],
["using_thumbnails_for_better_navigation.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Watching Cameras in DW Spectrum &#62; Searching through Archive &#62; Using Thumbnails for Better Navigation","Using Thumbnails for Better Navigation",""],
["viewing_and_checking_the_validity_of_exported_vide.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Exporting &#62; Checking the Validity of Exported Videos","Checking the Validity of Exported Videos",""],
["viewing_camera_stream_information.htm","Working with DW Spectrum &#62; DW Spectrum User Interface Overview &#62; Items on Layouts and Scene","Items on Layouts and Scene",""],
["viewing_multi-channel_videos.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Exporting &#62; Multi-Video Export &#62; Viewing Multi-Videos","Viewing Multi-Videos",""],
["viewing_videos_exported_from_a.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Exporting &#62; Single Camera Export &#62; Viewing Videos Exported from Single Camera","Viewing Videos Exported from Single Camera",""],
["watching_cameras_in_hd_witness.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Watching Cameras in DW Spectrum","Watching Cameras in DW Spectrum",""],
["web-client.htm","Web-Client","Web-Client",""],
["working_with_a_resource_tree.htm","Working with DW Spectrum &#62; DW Spectrum User Interface Overview &#62; Working with Resource Tree","Working with Resource Tree",""],
["working_with_several_hd_witness_windows.htm","Working with DW Spectrum &#62; Layouts Management &#62; Setting up Layout &#62; Working with Several DW Spectrum Windows","Working with Several DW Spectrum Windows",""],
["zoom.htm","Working with DW Spectrum &#62; Playback in DW Spectrum &#62; Forensic Analysis &#62; Zoom","Zoom",""]];
