#ifndef QN_COMMON_LEXICAL_H
#define QN_COMMON_LEXICAL_H

#include <utils/common/lexical.h>
#include <utils/common/json.h>

QN_DECLARE_LEXICAL_SERIALIZATION_FUNCTIONS(Qn::PtzAction)
QN_DECLARE_LEXICAL_SERIALIZATION_FUNCTIONS(Qn::PtzCoordinateSpace)

QN_DEFINE_LEXICAL_JSON_SERIALIZATION_FUNCTIONS(Qn::PtzAction)
QN_DEFINE_LEXICAL_JSON_SERIALIZATION_FUNCTIONS(Qn::PtzCoordinateSpace)

#endif // QN_COMMON_LEXICAL_H
