win32 {
  QMAKE_LFLAGS += /MACHINE:${arch} /LARGEADDRESSAWARE
  QMAKE_LFLAGS_DEBUG += /NODEFAULTLIB:libc /NODEFAULTLIB:libcmt /NODEFAULTLIB:msvcrt /NODEFAULTLIB:libcd /NODEFAULTLIB:libcmtd
  QMAKE_CXXFLAGS += /wd4250
}
