version: '3'
services:
  webapp:
    image: dockermediaserver
    ports:
      - "7001:7001"
    network_mode: "host"
    volumes:
      - /home/kyle/develop/nx_vms/cloud_portal/robot_tests/Docker/data:/dock