set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_C_COMPILER "${PACKAGES_DIR}/linux-x64/gcc-7.3.0/bin/gcc")
set(CMAKE_CXX_COMPILER "${PACKAGES_DIR}/linux-x64/gcc-7.3.0/bin/g++")
