ssh:
  private_key: ~/.func_tests/private_key
vm_host:
  registry: ~/.func_tests/registry
  address: 127.0.0.1
vm_types:
  linux:
    power_on_timeout: 20
    name_prefix: ubuntu-14.04-
    template:
      vm: ubuntu-14.04-template
      snapshot: template
    port_forwarding:
      host_ports_base: 33000
      host_ports_per_vm: 10
      forwarded_ports:
        product:
          protocol: tcp
          guest_port: 7001
          host_port_offset: 1
        ssh:
          protocol: tcp
          guest_port: 22
          host_port_offset: 2
  windows:
    power_on_timeout: 600  # After SysPrep, first boot takes several minutes to prepare user profile.
    name_prefix: windows-10-
    template:
      mv: windows-10-template
      snapshot: template
    port_forwarding:
      host_ports_base: 35000
      host_ports_per_vm: 10
      forwarded_ports:
        product:
          protocol: tcp
          guest_port: 7001
          host_port_offset: 1
        winrm-http:
          protocol: tcp
          guest_port: 5985
          host_port_offset: 5
