# Default logging configuration.
# See: https://docs.python.org/2/library/logging.config.html#dictionary-schema-details.
# Structure is exactly as `logging.config.dictConfig` accepts.

version: 1
disable_existing_loggers: false
formatters:
  default:
    format: '%(asctime)-15s %(name)s %(levelname)s %(message)s'
handlers:
  stderr:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default
    stream: ext://sys.stderr
loggers:
  SMB.SMBConnection:
    level: INFO
  paramiko.transport:
    level: INFO
root:
  level: DEBUG  # Default is `WARNING`.
  handlers: [stderr]
