// -* mode: groovy -*-
// Continuous integration main jenkinsfile


@Library('jenkins')
import org.nx.jenkins.CiRunner


def main() {
	def runner = new CiRunner(this, env, params, currentBuild)
	runner.main(
		build_tool: 'cmake',
		should_run_fun_tests: false,
	)
}

main()
