#!/bin/bash
killall gpm
export LD_LIBRARY_PATH=/opt/third_party/lib:/opt/networkoptix/mediaserver/lib
LD_PRELOAD="/opt/networkoptix/lite_client/lib/ldpreloadhook.so" /opt/networkoptix/lite_client/bin/mobile_client
#/opt/networkoptix/lite_client/bin/mobile_client
