#!/bin/bash
killall gpm
export LD_LIBRARY_PATH=/opt/networkoptix/lib:/opt/networkoptix/lib/ffmpeg
LD_PRELOAD="/opt/networkoptix/lite_client/lib/ldpreloadhook.so" /opt/networkoptix/lite_client/bin/mobile_client
#/opt/networkoptix/lite_client/bin/mobile_client
