#!/bin/bash

echo $*
export LESS_TERMCAP_ue=
export vcs_info_msg_1_=
export PAGER=less
export LESS_TERMCAP_us=
export VDPAU_OSD=1
export vcs_info_msg_0_=
export LANG=en_US.UTF-8
export SHLVL=3
export LESS_TERMCAP_so=
export DISPLAY=:0
export VDPAU_DRIVER=sunxi
export COLORTERM=yes
export LESS_TERMCAP_se=
export CUSTOMIZATION=${deb.customization.company.name}
export LD_LIBRARY_PATH=/opt/$CUSTOMIZATION/lib:/opt/$CUSTOMIZATION/lib/ffmpeg
BIN_NAME=mobile_client

killall gpm

# Failed to determine EDID on some TVs, so commenting this section
#if ! (get-edid | parse-edid | grep -Fxq 'Section "Monitor"') 2>/dev/null; then
#    AUTO_LOGIN_MODE="--auto-login=disabled"
#fi

LD_PRELOAD="/opt/$CUSTOMIZATION/lib/ldpreloadhook.so"
/opt/$CUSTOMIZATION/lite_client/bin/mobile_client $* $AUTO_LOGIN_MODE >>/opt/$CUSTOMIZATION/mediaserver/var/log/mobile_client.log

if ! pgrep mobile_client > /dev/null; then
    # Turning the screen blank after Lite Client terminates.
    echo "1" >/sys/class/graphics/fb0/blank
fi    
