[http]
endpoints = 0.0.0.0:3375
sslEndpoints = 0.0.0.0:3385

[database/sql]
driverName = QSQLITE 
name = /opt/networkoptix/cloud_storage_service/var/log/cloud_storage_service.sqlite

[database/p2pDb/discovery]
enabled = true

[log]
logLevel=DEBUG2

[geoIp]
dbPath = /opt/networkoptix/cloud_storage_service/var/GeoLite2-City.mmdb

[statistics]
enabled = false