###########################################################################
##                                                                       ##
##                Centre for Speech Technology Research                  ##
##                     University of Edinburgh, UK                       ##
##                         Copyright (c) 1999                            ##
##                        All Rights Reserved.                           ##
##                                                                       ##
##  Permission is hereby granted, free of charge, to use and distribute  ##
##  this software and its documentation without restriction, including   ##
##  without limitation the rights to use, copy, modify, merge, publish,  ##
##  distribute, sublicense, and/or sell copies of this work, and to      ##
##  permit persons to whom this work is furnished to do so, subject to   ##
##  the following conditions:                                            ##
##   1. The code must retain the above copyright notice, this list of    ##
##      conditions and the following disclaimer.                         ##
##   2. Any modifications must be clearly marked as such.                ##
##   3. Original authors' names are not deleted.                         ##
##   4. The authors' names are not used to endorse or promote products   ##
##      derived from this software without specific prior written        ##
##      permission.                                                      ##
##                                                                       ##
##  THE UNIVERSITY OF EDINBURGH AND THE CONTRIBUTORS TO THIS WORK        ##
##  DISCLAIM ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING      ##
##  ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO EVENT   ##
##  SHALL THE UNIVERSITY OF EDINBURGH NOR THE CONTRIBUTORS BE LIABLE     ##
##  FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES    ##
##  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN   ##
##  AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,          ##
##  ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF       ##
##  THIS SOFTWARE.                                                       ##
##                                                                       ##
###########################################################################
##                     Author :  Paul Taylor                             ##
##-----------------------------------------------------------------------##
##                                                                       ##
##                    figures and equations                              ##
##                                                                       ##
##=======================================================================##
TOP=../..
DIRNAME=doc/arch_doc
GIFS = eq01.gif eq02.gif eq03.gif eq04.gif eq05.gif eq06.gif eq07.gif \
       eq08.gif eq09.gif figure01.gif figure02.gif figure03.gif \
       figure04.gif figure05.gif figure06.gif figure07.gif \
       figure15.gif tilt_eq01.gif tilt_eq02.gif tilt_eq03.gif \
       tilt_eq04.gif tilt_eq05.gif tilt_eq06.gif tilt_eq07.gif \
       tilt_eq08.gif tilt_eq09.gif tilt_eq10.gif tilt_eq11.gif \
       tilt_fig01.gif tilt_fig02.gif tilt_fig03.gif track_fig01.gif
FIGS = tilt_fig01.fig tilt_fig02.fig track_fig01.fig

FILES = Makefile $(FIGS) $(GIFS)

include $(TOP)/config/common_make_rules












