/* soapPTZBindingProxy.cpp
   Generated by gSOAP 2.8.8 from onvif.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#include "soapPTZBindingProxy.h"

PTZBindingProxy::PTZBindingProxy()
{	this->soap = soap_new();
	this->own = true;
	PTZBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

PTZBindingProxy::PTZBindingProxy(struct soap *_soap)
{	this->soap = _soap;
	this->own = false;
	PTZBindingProxy_init(_soap->imode, _soap->omode);
}

PTZBindingProxy::PTZBindingProxy(const char *url)
{	this->soap = soap_new();
	this->own = true;
	PTZBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = url;
}

PTZBindingProxy::PTZBindingProxy(soap_mode iomode)
{	this->soap = soap_new();
	this->own = true;
	PTZBindingProxy_init(iomode, iomode);
}

PTZBindingProxy::PTZBindingProxy(const char *url, soap_mode iomode)
{	this->soap = soap_new();
	this->own = true;
	PTZBindingProxy_init(iomode, iomode);
	soap_endpoint = url;
}

PTZBindingProxy::PTZBindingProxy(soap_mode imode, soap_mode omode)
{	this->soap = soap_new();
	this->own = true;
	PTZBindingProxy_init(imode, omode);
}

PTZBindingProxy::~PTZBindingProxy()
{	if (this->own)
		soap_free(this->soap);
}

void PTZBindingProxy::PTZBindingProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this->soap, imode);
	soap_omode(this->soap, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://schemas.xmlsoap.org/soap/envelope/", NULL},
	{"SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://schemas.xmlsoap.org/soap/encoding/", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"c14n", "http://www.w3.org/2001/10/xml-exc-c14n#", NULL, NULL},
	{"wsu", "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd", NULL, NULL},
	{"xenc", "http://www.w3.org/2001/04/xmlenc#", NULL, NULL},
	{"ds", "http://www.w3.org/2000/09/xmldsig#", NULL, NULL},
	{"wsse", "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd", "http://docs.oasis-open.org/wss/oasis-wss-wssecurity-secext-1.1.xsd", NULL},
	{"wsa", "http://schemas.xmlsoap.org/ws/2004/08/addressing", NULL, NULL},
	{"wsdd", "http://schemas.xmlsoap.org/ws/2005/04/discovery", NULL, NULL},
	{"ns1", "http://www.w3.org/2005/08/addressing", NULL, NULL},
	{"oasisWsrf", "http://docs.oasis-open.org/wsrf/bf-2", NULL, NULL},
	{"xmime", "http://tempuri.org/xmime.xsd", NULL, NULL},
	{"ns5", "http://www.w3.org/2004/08/xop/include", NULL, NULL},
	{"onvifXsd", "http://www.onvif.org/ver10/schema", NULL, NULL},
	{"oasisWsnT1", "http://docs.oasis-open.org/wsn/t-1", NULL, NULL},
	{"oasisWsrfR2", "http://docs.oasis-open.org/wsrf/r-2", NULL, NULL},
	{"ns2", "http://www.onvif.org/ver10/events/wsdl/PausableSubscriptionManagerBinding", NULL, NULL},
	{"onvifDevice", "http://www.onvif.org/ver10/device/wsdl", NULL, NULL},
	{"onvifDeviceIO", "http://www.onvif.org/ver10/deviceIO/wsdl", NULL, NULL},
	{"onvifImg", "http://www.onvif.org/ver20/imaging/wsdl", NULL, NULL},
	{"onvifMedia", "http://www.onvif.org/ver10/media/wsdl", NULL, NULL},
	{"onvifPtz", "http://www.onvif.org/ver20/ptz/wsdl", NULL, NULL},
	{"tev-cpb", "http://www.onvif.org/ver10/events/wsdl/CreatePullPointBinding", NULL, NULL},
	{"tev-eb", "http://www.onvif.org/ver10/events/wsdl/EventBinding", NULL, NULL},
	{"tev-ncb", "http://www.onvif.org/ver10/events/wsdl/NotificationConsumerBinding", NULL, NULL},
	{"tev-npb", "http://www.onvif.org/ver10/events/wsdl/NotificationProducerBinding", NULL, NULL},
	{"oasisWsnB2", "http://docs.oasis-open.org/wsn/b-2", NULL, NULL},
	{"tev-ppb", "http://www.onvif.org/ver10/events/wsdl/PullPointBinding", NULL, NULL},
	{"tev-pps", "http://www.onvif.org/ver10/events/wsdl/PullPointSubscriptionBinding", NULL, NULL},
	{"onvifEvents", "http://www.onvif.org/ver10/events/wsdl", NULL, NULL},
	{"tev-smb", "http://www.onvif.org/ver10/events/wsdl/SubscriptionManagerBinding", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_set_namespaces(this->soap, namespaces);
}

void PTZBindingProxy::destroy()
{	soap_destroy(this->soap);
	soap_end(this->soap);
}

void PTZBindingProxy::reset()
{	destroy();
	soap_done(this->soap);
	soap_init(this->soap);
	PTZBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

void PTZBindingProxy::soap_noheader()
{	this->soap->header = NULL;
}

void PTZBindingProxy::soap_header(struct _wsse__Security *wsse__Security, char *wsa__MessageID, struct wsa__Relationship *wsa__RelatesTo, struct wsa__EndpointReferenceType *wsa__From, struct wsa__EndpointReferenceType *wsa__ReplyTo, struct wsa__EndpointReferenceType *wsa__FaultTo, char *wsa__To, char *wsa__Action, struct wsdd__AppSequenceType *wsdd__AppSequence)
{	::soap_header(this->soap);
	this->soap->header->wsse__Security = wsse__Security;
	this->soap->header->wsa__MessageID = wsa__MessageID;
	this->soap->header->wsa__RelatesTo = wsa__RelatesTo;
	this->soap->header->wsa__From = wsa__From;
	this->soap->header->wsa__ReplyTo = wsa__ReplyTo;
	this->soap->header->wsa__FaultTo = wsa__FaultTo;
	this->soap->header->wsa__To = wsa__To;
	this->soap->header->wsa__Action = wsa__Action;
	this->soap->header->wsdd__AppSequence = wsdd__AppSequence;
}

const SOAP_ENV__Header *PTZBindingProxy::soap_header()
{	return this->soap->header;
}

const SOAP_ENV__Fault *PTZBindingProxy::soap_fault()
{	return this->soap->fault;
}

const char *PTZBindingProxy::soap_fault_string()
{	return *soap_faultstring(this->soap);
}

const char *PTZBindingProxy::soap_fault_detail()
{	return *soap_faultdetail(this->soap);
}

int PTZBindingProxy::soap_close_socket()
{	return soap_closesock(this->soap);
}

int PTZBindingProxy::soap_force_close_socket()
{	return soap_force_closesock(this->soap);
}

void PTZBindingProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this->soap, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void PTZBindingProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this->soap, os);
}
#endif

char *PTZBindingProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this->soap, buf, len);
}
#endif

int PTZBindingProxy::GetServiceCapabilities(const char *endpoint, const char *soap_action, _onvifPtz__GetServiceCapabilities *onvifPtz__GetServiceCapabilities, _onvifPtz__GetServiceCapabilitiesResponse *onvifPtz__GetServiceCapabilitiesResponse)
{	struct soap *soap = this->soap;
	struct __onvifPtz__GetServiceCapabilities soap_tmp___onvifPtz__GetServiceCapabilities;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_action)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/GetServiceCapabilities";
	soap->encodingStyle = NULL;
	soap_tmp___onvifPtz__GetServiceCapabilities.onvifPtz__GetServiceCapabilities = onvifPtz__GetServiceCapabilities;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___onvifPtz__GetServiceCapabilities(soap, &soap_tmp___onvifPtz__GetServiceCapabilities);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___onvifPtz__GetServiceCapabilities(soap, &soap_tmp___onvifPtz__GetServiceCapabilities, "-onvifPtz:GetServiceCapabilities", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___onvifPtz__GetServiceCapabilities(soap, &soap_tmp___onvifPtz__GetServiceCapabilities, "-onvifPtz:GetServiceCapabilities", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!onvifPtz__GetServiceCapabilitiesResponse)
		return soap_closesock(soap);
	onvifPtz__GetServiceCapabilitiesResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	onvifPtz__GetServiceCapabilitiesResponse->soap_get(soap, "onvifPtz:GetServiceCapabilitiesResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::GetConfigurations(const char *endpoint, const char *soap_action, _onvifPtz__GetConfigurations *onvifPtz__GetConfigurations, _onvifPtz__GetConfigurationsResponse *onvifPtz__GetConfigurationsResponse)
{	struct soap *soap = this->soap;
	struct __onvifPtz__GetConfigurations soap_tmp___onvifPtz__GetConfigurations;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_action)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/GetConfigurations";
	soap->encodingStyle = NULL;
	soap_tmp___onvifPtz__GetConfigurations.onvifPtz__GetConfigurations = onvifPtz__GetConfigurations;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___onvifPtz__GetConfigurations(soap, &soap_tmp___onvifPtz__GetConfigurations);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___onvifPtz__GetConfigurations(soap, &soap_tmp___onvifPtz__GetConfigurations, "-onvifPtz:GetConfigurations", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___onvifPtz__GetConfigurations(soap, &soap_tmp___onvifPtz__GetConfigurations, "-onvifPtz:GetConfigurations", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!onvifPtz__GetConfigurationsResponse)
		return soap_closesock(soap);
	onvifPtz__GetConfigurationsResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	onvifPtz__GetConfigurationsResponse->soap_get(soap, "onvifPtz:GetConfigurationsResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::GetPresets(const char *endpoint, const char *soap_action, _onvifPtz__GetPresets *onvifPtz__GetPresets, _onvifPtz__GetPresetsResponse *onvifPtz__GetPresetsResponse)
{	struct soap *soap = this->soap;
	struct __onvifPtz__GetPresets soap_tmp___onvifPtz__GetPresets;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_action)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/GetPresets";
	soap->encodingStyle = NULL;
	soap_tmp___onvifPtz__GetPresets.onvifPtz__GetPresets = onvifPtz__GetPresets;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___onvifPtz__GetPresets(soap, &soap_tmp___onvifPtz__GetPresets);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___onvifPtz__GetPresets(soap, &soap_tmp___onvifPtz__GetPresets, "-onvifPtz:GetPresets", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___onvifPtz__GetPresets(soap, &soap_tmp___onvifPtz__GetPresets, "-onvifPtz:GetPresets", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!onvifPtz__GetPresetsResponse)
		return soap_closesock(soap);
	onvifPtz__GetPresetsResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	onvifPtz__GetPresetsResponse->soap_get(soap, "onvifPtz:GetPresetsResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::SetPreset(const char *endpoint, const char *soap_action, _onvifPtz__SetPreset *onvifPtz__SetPreset, _onvifPtz__SetPresetResponse *onvifPtz__SetPresetResponse)
{	struct soap *soap = this->soap;
	struct __onvifPtz__SetPreset soap_tmp___onvifPtz__SetPreset;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_action)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/SetPreset";
	soap->encodingStyle = NULL;
	soap_tmp___onvifPtz__SetPreset.onvifPtz__SetPreset = onvifPtz__SetPreset;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___onvifPtz__SetPreset(soap, &soap_tmp___onvifPtz__SetPreset);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___onvifPtz__SetPreset(soap, &soap_tmp___onvifPtz__SetPreset, "-onvifPtz:SetPreset", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___onvifPtz__SetPreset(soap, &soap_tmp___onvifPtz__SetPreset, "-onvifPtz:SetPreset", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!onvifPtz__SetPresetResponse)
		return soap_closesock(soap);
	onvifPtz__SetPresetResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	onvifPtz__SetPresetResponse->soap_get(soap, "onvifPtz:SetPresetResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::RemovePreset(const char *endpoint, const char *soap_action, _onvifPtz__RemovePreset *onvifPtz__RemovePreset, _onvifPtz__RemovePresetResponse *onvifPtz__RemovePresetResponse)
{	struct soap *soap = this->soap;
	struct __onvifPtz__RemovePreset soap_tmp___onvifPtz__RemovePreset;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_action)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/RemovePreset";
	soap->encodingStyle = NULL;
	soap_tmp___onvifPtz__RemovePreset.onvifPtz__RemovePreset = onvifPtz__RemovePreset;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___onvifPtz__RemovePreset(soap, &soap_tmp___onvifPtz__RemovePreset);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___onvifPtz__RemovePreset(soap, &soap_tmp___onvifPtz__RemovePreset, "-onvifPtz:RemovePreset", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___onvifPtz__RemovePreset(soap, &soap_tmp___onvifPtz__RemovePreset, "-onvifPtz:RemovePreset", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!onvifPtz__RemovePresetResponse)
		return soap_closesock(soap);
	onvifPtz__RemovePresetResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	onvifPtz__RemovePresetResponse->soap_get(soap, "onvifPtz:RemovePresetResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::GotoPreset(const char *endpoint, const char *soap_action, _onvifPtz__GotoPreset *onvifPtz__GotoPreset, _onvifPtz__GotoPresetResponse *onvifPtz__GotoPresetResponse)
{	struct soap *soap = this->soap;
	struct __onvifPtz__GotoPreset soap_tmp___onvifPtz__GotoPreset;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_action)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/GotoPreset";
	soap->encodingStyle = NULL;
	soap_tmp___onvifPtz__GotoPreset.onvifPtz__GotoPreset = onvifPtz__GotoPreset;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___onvifPtz__GotoPreset(soap, &soap_tmp___onvifPtz__GotoPreset);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___onvifPtz__GotoPreset(soap, &soap_tmp___onvifPtz__GotoPreset, "-onvifPtz:GotoPreset", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___onvifPtz__GotoPreset(soap, &soap_tmp___onvifPtz__GotoPreset, "-onvifPtz:GotoPreset", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!onvifPtz__GotoPresetResponse)
		return soap_closesock(soap);
	onvifPtz__GotoPresetResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	onvifPtz__GotoPresetResponse->soap_get(soap, "onvifPtz:GotoPresetResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::GetStatus(const char *endpoint, const char *soap_action, _onvifPtz__GetStatus *onvifPtz__GetStatus, _onvifPtz__GetStatusResponse *onvifPtz__GetStatusResponse)
{	struct soap *soap = this->soap;
	struct __onvifPtz__GetStatus soap_tmp___onvifPtz__GetStatus;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_action)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/GetStatus";
	soap->encodingStyle = NULL;
	soap_tmp___onvifPtz__GetStatus.onvifPtz__GetStatus = onvifPtz__GetStatus;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___onvifPtz__GetStatus(soap, &soap_tmp___onvifPtz__GetStatus);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___onvifPtz__GetStatus(soap, &soap_tmp___onvifPtz__GetStatus, "-onvifPtz:GetStatus", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___onvifPtz__GetStatus(soap, &soap_tmp___onvifPtz__GetStatus, "-onvifPtz:GetStatus", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!onvifPtz__GetStatusResponse)
		return soap_closesock(soap);
	onvifPtz__GetStatusResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	onvifPtz__GetStatusResponse->soap_get(soap, "onvifPtz:GetStatusResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::GetConfiguration(const char *endpoint, const char *soap_action, _onvifPtz__GetConfiguration *onvifPtz__GetConfiguration, _onvifPtz__GetConfigurationResponse *onvifPtz__GetConfigurationResponse)
{	struct soap *soap = this->soap;
	struct __onvifPtz__GetConfiguration soap_tmp___onvifPtz__GetConfiguration;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_action)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/GetConfiguration";
	soap->encodingStyle = NULL;
	soap_tmp___onvifPtz__GetConfiguration.onvifPtz__GetConfiguration = onvifPtz__GetConfiguration;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___onvifPtz__GetConfiguration(soap, &soap_tmp___onvifPtz__GetConfiguration);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___onvifPtz__GetConfiguration(soap, &soap_tmp___onvifPtz__GetConfiguration, "-onvifPtz:GetConfiguration", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___onvifPtz__GetConfiguration(soap, &soap_tmp___onvifPtz__GetConfiguration, "-onvifPtz:GetConfiguration", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!onvifPtz__GetConfigurationResponse)
		return soap_closesock(soap);
	onvifPtz__GetConfigurationResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	onvifPtz__GetConfigurationResponse->soap_get(soap, "onvifPtz:GetConfigurationResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::GetNodes(const char *endpoint, const char *soap_action, _onvifPtz__GetNodes *onvifPtz__GetNodes, _onvifPtz__GetNodesResponse *onvifPtz__GetNodesResponse)
{	struct soap *soap = this->soap;
	struct __onvifPtz__GetNodes soap_tmp___onvifPtz__GetNodes;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_action)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/GetNodes";
	soap->encodingStyle = NULL;
	soap_tmp___onvifPtz__GetNodes.onvifPtz__GetNodes = onvifPtz__GetNodes;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___onvifPtz__GetNodes(soap, &soap_tmp___onvifPtz__GetNodes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___onvifPtz__GetNodes(soap, &soap_tmp___onvifPtz__GetNodes, "-onvifPtz:GetNodes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___onvifPtz__GetNodes(soap, &soap_tmp___onvifPtz__GetNodes, "-onvifPtz:GetNodes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!onvifPtz__GetNodesResponse)
		return soap_closesock(soap);
	onvifPtz__GetNodesResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	onvifPtz__GetNodesResponse->soap_get(soap, "onvifPtz:GetNodesResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::GetNode(const char *endpoint, const char *soap_action, _onvifPtz__GetNode *onvifPtz__GetNode, _onvifPtz__GetNodeResponse *onvifPtz__GetNodeResponse)
{	struct soap *soap = this->soap;
	struct __onvifPtz__GetNode soap_tmp___onvifPtz__GetNode;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_action)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/GetNode";
	soap->encodingStyle = NULL;
	soap_tmp___onvifPtz__GetNode.onvifPtz__GetNode = onvifPtz__GetNode;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___onvifPtz__GetNode(soap, &soap_tmp___onvifPtz__GetNode);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___onvifPtz__GetNode(soap, &soap_tmp___onvifPtz__GetNode, "-onvifPtz:GetNode", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___onvifPtz__GetNode(soap, &soap_tmp___onvifPtz__GetNode, "-onvifPtz:GetNode", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!onvifPtz__GetNodeResponse)
		return soap_closesock(soap);
	onvifPtz__GetNodeResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	onvifPtz__GetNodeResponse->soap_get(soap, "onvifPtz:GetNodeResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::SetConfiguration(const char *endpoint, const char *soap_action, _onvifPtz__SetConfiguration *onvifPtz__SetConfiguration, _onvifPtz__SetConfigurationResponse *onvifPtz__SetConfigurationResponse)
{	struct soap *soap = this->soap;
	struct __onvifPtz__SetConfiguration soap_tmp___onvifPtz__SetConfiguration;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_action)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/SetConfiguration";
	soap->encodingStyle = NULL;
	soap_tmp___onvifPtz__SetConfiguration.onvifPtz__SetConfiguration = onvifPtz__SetConfiguration;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___onvifPtz__SetConfiguration(soap, &soap_tmp___onvifPtz__SetConfiguration);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___onvifPtz__SetConfiguration(soap, &soap_tmp___onvifPtz__SetConfiguration, "-onvifPtz:SetConfiguration", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___onvifPtz__SetConfiguration(soap, &soap_tmp___onvifPtz__SetConfiguration, "-onvifPtz:SetConfiguration", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!onvifPtz__SetConfigurationResponse)
		return soap_closesock(soap);
	onvifPtz__SetConfigurationResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	onvifPtz__SetConfigurationResponse->soap_get(soap, "onvifPtz:SetConfigurationResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::GetConfigurationOptions(const char *endpoint, const char *soap_action, _onvifPtz__GetConfigurationOptions *onvifPtz__GetConfigurationOptions, _onvifPtz__GetConfigurationOptionsResponse *onvifPtz__GetConfigurationOptionsResponse)
{	struct soap *soap = this->soap;
	struct __onvifPtz__GetConfigurationOptions soap_tmp___onvifPtz__GetConfigurationOptions;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_action)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/GetConfigurationOptions";
	soap->encodingStyle = NULL;
	soap_tmp___onvifPtz__GetConfigurationOptions.onvifPtz__GetConfigurationOptions = onvifPtz__GetConfigurationOptions;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___onvifPtz__GetConfigurationOptions(soap, &soap_tmp___onvifPtz__GetConfigurationOptions);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___onvifPtz__GetConfigurationOptions(soap, &soap_tmp___onvifPtz__GetConfigurationOptions, "-onvifPtz:GetConfigurationOptions", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___onvifPtz__GetConfigurationOptions(soap, &soap_tmp___onvifPtz__GetConfigurationOptions, "-onvifPtz:GetConfigurationOptions", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!onvifPtz__GetConfigurationOptionsResponse)
		return soap_closesock(soap);
	onvifPtz__GetConfigurationOptionsResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	onvifPtz__GetConfigurationOptionsResponse->soap_get(soap, "onvifPtz:GetConfigurationOptionsResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::GotoHomePosition(const char *endpoint, const char *soap_action, _onvifPtz__GotoHomePosition *onvifPtz__GotoHomePosition, _onvifPtz__GotoHomePositionResponse *onvifPtz__GotoHomePositionResponse)
{	struct soap *soap = this->soap;
	struct __onvifPtz__GotoHomePosition soap_tmp___onvifPtz__GotoHomePosition;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_action)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/GotoHomePosition";
	soap->encodingStyle = NULL;
	soap_tmp___onvifPtz__GotoHomePosition.onvifPtz__GotoHomePosition = onvifPtz__GotoHomePosition;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___onvifPtz__GotoHomePosition(soap, &soap_tmp___onvifPtz__GotoHomePosition);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___onvifPtz__GotoHomePosition(soap, &soap_tmp___onvifPtz__GotoHomePosition, "-onvifPtz:GotoHomePosition", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___onvifPtz__GotoHomePosition(soap, &soap_tmp___onvifPtz__GotoHomePosition, "-onvifPtz:GotoHomePosition", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!onvifPtz__GotoHomePositionResponse)
		return soap_closesock(soap);
	onvifPtz__GotoHomePositionResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	onvifPtz__GotoHomePositionResponse->soap_get(soap, "onvifPtz:GotoHomePositionResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::SetHomePosition(const char *endpoint, const char *soap_action, _onvifPtz__SetHomePosition *onvifPtz__SetHomePosition, _onvifPtz__SetHomePositionResponse *onvifPtz__SetHomePositionResponse)
{	struct soap *soap = this->soap;
	struct __onvifPtz__SetHomePosition soap_tmp___onvifPtz__SetHomePosition;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_action)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/SetHomePosition";
	soap->encodingStyle = NULL;
	soap_tmp___onvifPtz__SetHomePosition.onvifPtz__SetHomePosition = onvifPtz__SetHomePosition;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___onvifPtz__SetHomePosition(soap, &soap_tmp___onvifPtz__SetHomePosition);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___onvifPtz__SetHomePosition(soap, &soap_tmp___onvifPtz__SetHomePosition, "-onvifPtz:SetHomePosition", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___onvifPtz__SetHomePosition(soap, &soap_tmp___onvifPtz__SetHomePosition, "-onvifPtz:SetHomePosition", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!onvifPtz__SetHomePositionResponse)
		return soap_closesock(soap);
	onvifPtz__SetHomePositionResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	onvifPtz__SetHomePositionResponse->soap_get(soap, "onvifPtz:SetHomePositionResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::ContinuousMove(const char *endpoint, const char *soap_action, _onvifPtz__ContinuousMove *onvifPtz__ContinuousMove, _onvifPtz__ContinuousMoveResponse *onvifPtz__ContinuousMoveResponse)
{	struct soap *soap = this->soap;
	struct __onvifPtz__ContinuousMove soap_tmp___onvifPtz__ContinuousMove;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_action)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/ContinuousMove";
	soap->encodingStyle = NULL;
	soap_tmp___onvifPtz__ContinuousMove.onvifPtz__ContinuousMove = onvifPtz__ContinuousMove;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___onvifPtz__ContinuousMove(soap, &soap_tmp___onvifPtz__ContinuousMove);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___onvifPtz__ContinuousMove(soap, &soap_tmp___onvifPtz__ContinuousMove, "-onvifPtz:ContinuousMove", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___onvifPtz__ContinuousMove(soap, &soap_tmp___onvifPtz__ContinuousMove, "-onvifPtz:ContinuousMove", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!onvifPtz__ContinuousMoveResponse)
		return soap_closesock(soap);
	onvifPtz__ContinuousMoveResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	onvifPtz__ContinuousMoveResponse->soap_get(soap, "onvifPtz:ContinuousMoveResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::RelativeMove(const char *endpoint, const char *soap_action, _onvifPtz__RelativeMove *onvifPtz__RelativeMove, _onvifPtz__RelativeMoveResponse *onvifPtz__RelativeMoveResponse)
{	struct soap *soap = this->soap;
	struct __onvifPtz__RelativeMove soap_tmp___onvifPtz__RelativeMove;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_action)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/RelativeMove";
	soap->encodingStyle = NULL;
	soap_tmp___onvifPtz__RelativeMove.onvifPtz__RelativeMove = onvifPtz__RelativeMove;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___onvifPtz__RelativeMove(soap, &soap_tmp___onvifPtz__RelativeMove);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___onvifPtz__RelativeMove(soap, &soap_tmp___onvifPtz__RelativeMove, "-onvifPtz:RelativeMove", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___onvifPtz__RelativeMove(soap, &soap_tmp___onvifPtz__RelativeMove, "-onvifPtz:RelativeMove", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!onvifPtz__RelativeMoveResponse)
		return soap_closesock(soap);
	onvifPtz__RelativeMoveResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	onvifPtz__RelativeMoveResponse->soap_get(soap, "onvifPtz:RelativeMoveResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::SendAuxiliaryCommand(const char *endpoint, const char *soap_action, _onvifPtz__SendAuxiliaryCommand *onvifPtz__SendAuxiliaryCommand, _onvifPtz__SendAuxiliaryCommandResponse *onvifPtz__SendAuxiliaryCommandResponse)
{	struct soap *soap = this->soap;
	struct __onvifPtz__SendAuxiliaryCommand soap_tmp___onvifPtz__SendAuxiliaryCommand;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_action)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/SendAuxiliaryCommand";
	soap->encodingStyle = NULL;
	soap_tmp___onvifPtz__SendAuxiliaryCommand.onvifPtz__SendAuxiliaryCommand = onvifPtz__SendAuxiliaryCommand;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___onvifPtz__SendAuxiliaryCommand(soap, &soap_tmp___onvifPtz__SendAuxiliaryCommand);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___onvifPtz__SendAuxiliaryCommand(soap, &soap_tmp___onvifPtz__SendAuxiliaryCommand, "-onvifPtz:SendAuxiliaryCommand", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___onvifPtz__SendAuxiliaryCommand(soap, &soap_tmp___onvifPtz__SendAuxiliaryCommand, "-onvifPtz:SendAuxiliaryCommand", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!onvifPtz__SendAuxiliaryCommandResponse)
		return soap_closesock(soap);
	onvifPtz__SendAuxiliaryCommandResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	onvifPtz__SendAuxiliaryCommandResponse->soap_get(soap, "onvifPtz:SendAuxiliaryCommandResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::AbsoluteMove(const char *endpoint, const char *soap_action, _onvifPtz__AbsoluteMove *onvifPtz__AbsoluteMove, _onvifPtz__AbsoluteMoveResponse *onvifPtz__AbsoluteMoveResponse)
{	struct soap *soap = this->soap;
	struct __onvifPtz__AbsoluteMove soap_tmp___onvifPtz__AbsoluteMove;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_action)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/AbsoluteMove";
	soap->encodingStyle = NULL;
	soap_tmp___onvifPtz__AbsoluteMove.onvifPtz__AbsoluteMove = onvifPtz__AbsoluteMove;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___onvifPtz__AbsoluteMove(soap, &soap_tmp___onvifPtz__AbsoluteMove);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___onvifPtz__AbsoluteMove(soap, &soap_tmp___onvifPtz__AbsoluteMove, "-onvifPtz:AbsoluteMove", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___onvifPtz__AbsoluteMove(soap, &soap_tmp___onvifPtz__AbsoluteMove, "-onvifPtz:AbsoluteMove", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!onvifPtz__AbsoluteMoveResponse)
		return soap_closesock(soap);
	onvifPtz__AbsoluteMoveResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	onvifPtz__AbsoluteMoveResponse->soap_get(soap, "onvifPtz:AbsoluteMoveResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::Stop(const char *endpoint, const char *soap_action, _onvifPtz__Stop *onvifPtz__Stop, _onvifPtz__StopResponse *onvifPtz__StopResponse)
{	struct soap *soap = this->soap;
	struct __onvifPtz__Stop soap_tmp___onvifPtz__Stop;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_action)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/Stop";
	soap->encodingStyle = NULL;
	soap_tmp___onvifPtz__Stop.onvifPtz__Stop = onvifPtz__Stop;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___onvifPtz__Stop(soap, &soap_tmp___onvifPtz__Stop);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___onvifPtz__Stop(soap, &soap_tmp___onvifPtz__Stop, "-onvifPtz:Stop", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___onvifPtz__Stop(soap, &soap_tmp___onvifPtz__Stop, "-onvifPtz:Stop", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!onvifPtz__StopResponse)
		return soap_closesock(soap);
	onvifPtz__StopResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	onvifPtz__StopResponse->soap_get(soap, "onvifPtz:StopResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::GetPresetTours(const char *endpoint, const char *soap_action, _onvifPtz__GetPresetTours *onvifPtz__GetPresetTours, _onvifPtz__GetPresetToursResponse *onvifPtz__GetPresetToursResponse)
{	struct soap *soap = this->soap;
	struct __onvifPtz__GetPresetTours soap_tmp___onvifPtz__GetPresetTours;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_action)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/GetPresetTours";
	soap->encodingStyle = NULL;
	soap_tmp___onvifPtz__GetPresetTours.onvifPtz__GetPresetTours = onvifPtz__GetPresetTours;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___onvifPtz__GetPresetTours(soap, &soap_tmp___onvifPtz__GetPresetTours);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___onvifPtz__GetPresetTours(soap, &soap_tmp___onvifPtz__GetPresetTours, "-onvifPtz:GetPresetTours", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___onvifPtz__GetPresetTours(soap, &soap_tmp___onvifPtz__GetPresetTours, "-onvifPtz:GetPresetTours", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!onvifPtz__GetPresetToursResponse)
		return soap_closesock(soap);
	onvifPtz__GetPresetToursResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	onvifPtz__GetPresetToursResponse->soap_get(soap, "onvifPtz:GetPresetToursResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::GetPresetTour(const char *endpoint, const char *soap_action, _onvifPtz__GetPresetTour *onvifPtz__GetPresetTour, _onvifPtz__GetPresetTourResponse *onvifPtz__GetPresetTourResponse)
{	struct soap *soap = this->soap;
	struct __onvifPtz__GetPresetTour soap_tmp___onvifPtz__GetPresetTour;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_action)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/GetPresetTour";
	soap->encodingStyle = NULL;
	soap_tmp___onvifPtz__GetPresetTour.onvifPtz__GetPresetTour = onvifPtz__GetPresetTour;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___onvifPtz__GetPresetTour(soap, &soap_tmp___onvifPtz__GetPresetTour);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___onvifPtz__GetPresetTour(soap, &soap_tmp___onvifPtz__GetPresetTour, "-onvifPtz:GetPresetTour", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___onvifPtz__GetPresetTour(soap, &soap_tmp___onvifPtz__GetPresetTour, "-onvifPtz:GetPresetTour", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!onvifPtz__GetPresetTourResponse)
		return soap_closesock(soap);
	onvifPtz__GetPresetTourResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	onvifPtz__GetPresetTourResponse->soap_get(soap, "onvifPtz:GetPresetTourResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::GetPresetTourOptions(const char *endpoint, const char *soap_action, _onvifPtz__GetPresetTourOptions *onvifPtz__GetPresetTourOptions, _onvifPtz__GetPresetTourOptionsResponse *onvifPtz__GetPresetTourOptionsResponse)
{	struct soap *soap = this->soap;
	struct __onvifPtz__GetPresetTourOptions soap_tmp___onvifPtz__GetPresetTourOptions;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_action)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/GetPresetTourOptions";
	soap->encodingStyle = NULL;
	soap_tmp___onvifPtz__GetPresetTourOptions.onvifPtz__GetPresetTourOptions = onvifPtz__GetPresetTourOptions;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___onvifPtz__GetPresetTourOptions(soap, &soap_tmp___onvifPtz__GetPresetTourOptions);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___onvifPtz__GetPresetTourOptions(soap, &soap_tmp___onvifPtz__GetPresetTourOptions, "-onvifPtz:GetPresetTourOptions", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___onvifPtz__GetPresetTourOptions(soap, &soap_tmp___onvifPtz__GetPresetTourOptions, "-onvifPtz:GetPresetTourOptions", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!onvifPtz__GetPresetTourOptionsResponse)
		return soap_closesock(soap);
	onvifPtz__GetPresetTourOptionsResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	onvifPtz__GetPresetTourOptionsResponse->soap_get(soap, "onvifPtz:GetPresetTourOptionsResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::CreatePresetTour(const char *endpoint, const char *soap_action, _onvifPtz__CreatePresetTour *onvifPtz__CreatePresetTour, _onvifPtz__CreatePresetTourResponse *onvifPtz__CreatePresetTourResponse)
{	struct soap *soap = this->soap;
	struct __onvifPtz__CreatePresetTour soap_tmp___onvifPtz__CreatePresetTour;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_action)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/CreatePresetTour";
	soap->encodingStyle = NULL;
	soap_tmp___onvifPtz__CreatePresetTour.onvifPtz__CreatePresetTour = onvifPtz__CreatePresetTour;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___onvifPtz__CreatePresetTour(soap, &soap_tmp___onvifPtz__CreatePresetTour);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___onvifPtz__CreatePresetTour(soap, &soap_tmp___onvifPtz__CreatePresetTour, "-onvifPtz:CreatePresetTour", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___onvifPtz__CreatePresetTour(soap, &soap_tmp___onvifPtz__CreatePresetTour, "-onvifPtz:CreatePresetTour", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!onvifPtz__CreatePresetTourResponse)
		return soap_closesock(soap);
	onvifPtz__CreatePresetTourResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	onvifPtz__CreatePresetTourResponse->soap_get(soap, "onvifPtz:CreatePresetTourResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::ModifyPresetTour(const char *endpoint, const char *soap_action, _onvifPtz__ModifyPresetTour *onvifPtz__ModifyPresetTour, _onvifPtz__ModifyPresetTourResponse *onvifPtz__ModifyPresetTourResponse)
{	struct soap *soap = this->soap;
	struct __onvifPtz__ModifyPresetTour soap_tmp___onvifPtz__ModifyPresetTour;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_action)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/ModifyPresetTour";
	soap->encodingStyle = NULL;
	soap_tmp___onvifPtz__ModifyPresetTour.onvifPtz__ModifyPresetTour = onvifPtz__ModifyPresetTour;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___onvifPtz__ModifyPresetTour(soap, &soap_tmp___onvifPtz__ModifyPresetTour);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___onvifPtz__ModifyPresetTour(soap, &soap_tmp___onvifPtz__ModifyPresetTour, "-onvifPtz:ModifyPresetTour", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___onvifPtz__ModifyPresetTour(soap, &soap_tmp___onvifPtz__ModifyPresetTour, "-onvifPtz:ModifyPresetTour", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!onvifPtz__ModifyPresetTourResponse)
		return soap_closesock(soap);
	onvifPtz__ModifyPresetTourResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	onvifPtz__ModifyPresetTourResponse->soap_get(soap, "onvifPtz:ModifyPresetTourResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::OperatePresetTour(const char *endpoint, const char *soap_action, _onvifPtz__OperatePresetTour *onvifPtz__OperatePresetTour, _onvifPtz__OperatePresetTourResponse *onvifPtz__OperatePresetTourResponse)
{	struct soap *soap = this->soap;
	struct __onvifPtz__OperatePresetTour soap_tmp___onvifPtz__OperatePresetTour;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_action)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/OperatePresetTour";
	soap->encodingStyle = NULL;
	soap_tmp___onvifPtz__OperatePresetTour.onvifPtz__OperatePresetTour = onvifPtz__OperatePresetTour;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___onvifPtz__OperatePresetTour(soap, &soap_tmp___onvifPtz__OperatePresetTour);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___onvifPtz__OperatePresetTour(soap, &soap_tmp___onvifPtz__OperatePresetTour, "-onvifPtz:OperatePresetTour", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___onvifPtz__OperatePresetTour(soap, &soap_tmp___onvifPtz__OperatePresetTour, "-onvifPtz:OperatePresetTour", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!onvifPtz__OperatePresetTourResponse)
		return soap_closesock(soap);
	onvifPtz__OperatePresetTourResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	onvifPtz__OperatePresetTourResponse->soap_get(soap, "onvifPtz:OperatePresetTourResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::RemovePresetTour(const char *endpoint, const char *soap_action, _onvifPtz__RemovePresetTour *onvifPtz__RemovePresetTour, _onvifPtz__RemovePresetTourResponse *onvifPtz__RemovePresetTourResponse)
{	struct soap *soap = this->soap;
	struct __onvifPtz__RemovePresetTour soap_tmp___onvifPtz__RemovePresetTour;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_action)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/RemovePresetTour";
	soap->encodingStyle = NULL;
	soap_tmp___onvifPtz__RemovePresetTour.onvifPtz__RemovePresetTour = onvifPtz__RemovePresetTour;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___onvifPtz__RemovePresetTour(soap, &soap_tmp___onvifPtz__RemovePresetTour);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___onvifPtz__RemovePresetTour(soap, &soap_tmp___onvifPtz__RemovePresetTour, "-onvifPtz:RemovePresetTour", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___onvifPtz__RemovePresetTour(soap, &soap_tmp___onvifPtz__RemovePresetTour, "-onvifPtz:RemovePresetTour", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!onvifPtz__RemovePresetTourResponse)
		return soap_closesock(soap);
	onvifPtz__RemovePresetTourResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	onvifPtz__RemovePresetTourResponse->soap_get(soap, "onvifPtz:RemovePresetTourResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
