function(nx_force_include target)
    foreach(file ${ARGN})
        if(MSVC)
            target_compile_options(${target} PRIVATE "/FI${file}")
        else()
            target_compile_options(${target} PRIVATE "-include${file}")
        endif()
    endforeach()
endfunction()
