set(release.version ${releaseVersion})
set(parsedVersion.majorVersion ${PROJECT_VERSION_MAJOR})
set(parsedVersion.minorVersion ${PROJECT_VERSION_MINOR})
set(parsedVersion.incrementalVersion ${PROJECT_VERSION_PATCH})

set(ffmpeg.version ${ffmpeg_version})
set(boost.version ${boost_version})
set(sigar.version ${sigar_version})

#TODO Find out how to determine the desired --config
set(config "Release")
set(build.configuration ${config})
set(environment.dir "$ENV{environment}")
set(root.dir ${CMAKE_SOURCE_DIR})
set(qt.dir ${QT_DIR})
set(customization.dir ${customization_dir})
set(bin_source_dir "${CMAKE_BINARY_DIR}/${config}/bin")

#artifact names
set(artifact.name.client "${client_distribution_name}")
set(artifact.name.server "${server_distribution_name}")
set(artifact.name.bundle "${bundle_distribution_name}")
set(artifact.name.servertool "${servertool_distribution_name}")
set(artifact.name.client_update "${client_update_distribution_name}")
set(artifact.name.server_update "${server_update_distribution_name}")
set(artifact.name.paxton "${paxton_distribution_name}")
set(artifact.name.paxton_plugin "${paxton_plugin_distribution_name}")
set(artifact.name.cdb "${cdb_distribution_name}")
set(artifact.name.hpm "${hpm_distribution_name}")
set(artifact.name.client_debug "${client_debug_distribution_name}")
set(artifact.name.server_debug "${server_debug_distribution_name}")
set(artifact.name.misc_debug "${misc_debug_distribution_name}")
set(artifact.name.libs_debug "${libs_debug_distribution_name}")
set(artifact.name.cloud_debug "${cloud_debug_distribution_name}")
set(artifact.name.testcamera "${testcamera_distribution_name}")
set(mobile_client_distribution_name "${mobile_client_distribution_name}")
set(artifact.name.product "${product_distribution_name}")

if(WINDOWS)
    set(product.title "${company.name} ${display.product.name} Setup v.${release.version}")
endif()