set(qt_version "5.6.2" CACHE STRING "")
set(boost_version "1.60.0" CACHE STRING "")
set(openssl_version "1.0.2e" CACHE STRING "")
set(ffmpeg_version "3.1.1" CACHE STRING "")
set(quazip_version "0.7.1" CACHE STRING "")
set(onvif_version "2.1.2-io2" CACHE STRING "")
set(sigar_version "1.7" CACHE STRING "")
set(openldap_version "2.4.42" CACHE STRING "")
set(sasl_version "2.1.26" CACHE STRING "")
set(openal_version "1.16" CACHE STRING "")
set(libjpeg-turbo_version "1.4.2" CACHE STRING "")
set(libcreateprocess_version "0.1" CACHE STRING "")
set(festival_version "2.1" CACHE STRING "")
set(festival-vox_version ${festival_version} CACHE STRING "")
set(vmux_version "1.0.0" CACHE STRING "")
set(gtest_version "1.7.0" CACHE STRING "")
set(gmock_version "1.7.0" CACHE STRING "")
set(gcc_version "4.9.4" CACHE STRING "")

set(help_version "${customization}-${releaseVersion}")
