if(targetDevice)
    if(targetDevice MATCHES "bpi|bananapi")
        nx_rdep_sync_package(bpi/gcc-4.8.3)
    elseif(targetDevice STREQUAL "rpi")
        nx_rdep_sync_package(rpi/gcc-4.9.4)
    elseif(targetDevice STREQUAL "edge1")
        nx_rdep_sync_package(isd_s2/gcc-4.9.3)
    elseif(targetDevice MATCHES "android")
        if("$ENV{ANDROID_NDK}" STREQUAL "" OR NOT IS_DIRECTORY "$ENV{ANDROID_NDK}")
            nx_rdep_sync_package(android/android-ndk)
        endif()
        if("$ENV{ANDROID_HOME}" STREQUAL "" OR NOT IS_DIRECTORY "$ENV{ANDROID_HOME}")
            nx_rdep_sync_package(android/android-sdk)
        endif()
    endif()
endif()
