if(targetDevice)
    if(targetDevice MATCHES "bpi|bananapi")
        nx_rdep_sync_package(linux-arm/gcc-7.2.0)
        set(toolchain_directory "${PACKAGES_DIR}/linux-arm/gcc-7.2.0")
    elseif(targetDevice STREQUAL "rpi")
        nx_rdep_sync_package(linux-arm/gcc-7.2.0)
        nx_rdep_sync_package(linux-arm/glib-2.0)
        set(toolchain_directory "${PACKAGES_DIR}/linux-arm/gcc-7.2.0")
    elseif(targetDevice STREQUAL "edge1")
        nx_rdep_sync_package(isd_s2/gcc-4.9.3)
    elseif(targetDevice MATCHES "android")
        if("$ENV{ANDROID_NDK}" STREQUAL "" OR NOT IS_DIRECTORY "$ENV{ANDROID_NDK}")
            nx_rdep_sync_package(android/android-ndk)
        endif()
        if("$ENV{ANDROID_HOME}" STREQUAL "" OR NOT IS_DIRECTORY "$ENV{ANDROID_HOME}")
            nx_rdep_sync_package(android/android-sdk)
        endif()
    endif()
endif()
