function(detect_target)
    if(box STREQUAL "none")
        if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
            set(LINUX TRUE PARENT_SCOPE)
            set(detected_platform "linux")
            set(detected_modification "ubuntu")
            if(CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64")
                set(detected_arch "x64")
            elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "x86")
                set(detected_arch "x86")
            else()
                message(FATAL_ERROR
                    "Cannot detect your system architecture ${CMAKE_SYSTEM_PROCESSOR}")
            endif()
        elseif(CMAKE_SYSTEM_NAME STREQUAL "Windows")
            set(WINDOWS TRUE PARENT_SCOPE)
            set(detected_platform "windows")
            set(detected_modification "winxp")
            if(CMAKE_SYSTEM_PROCESSOR STREQUAL "AMD64")
                set(detected_arch "x64")
            elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "x86")
                set(detected_arch "x86")
            else()
                message(FATAL_ERROR
                    "Cannot detect your system architecture ${CMAKE_SYSTEM_PROCESSOR}")
            endif()
        elseif(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
            set(MACOSX TRUE PARENT_SCOPE)
            set(detected_arch "x64")
            set(detected_platform "macosx")
            set(detected_modification "macosx")
        elseif(CMAKE_SYSTEM_NAME STREQUAL "Android")
            set(LINUX TRUE PARENT_SCOPE)
            set(ANDROID TRUE PARENT_SCOPE)
            set(detected_arch "arm")
            set(detected_platform "android")
            set(detected_modification "")
        else()
            message(FATAL_ERROR
                "Cannot detect parameters for your system ${CMAKE_SYSTEM_NAME}")
        endif()

        set(detected_target ${detected_platform}-${detected_arch})
    else()
        set(LINUX TRUE PARENT_SCOPE)
        set(detected_arch "arm")
        set(detected_platform "linux")
        set(detected_modification ${box})

        if(box STREQUAL "bananapi")
            set(detected_target "bpi")
        else()
            set(detected_target ${box})
        endif()
    endif()

    set(arch ${detected_arch} CACHE INTERNAL "")
    set(platform ${detected_platform} CACHE INTERNAL "")
    set(modification ${detected_modification} CACHE INTERNAL "")
    set(rdep_target ${detected_target} CACHE INTERNAL "")
endfunction()

detect_target()
