// Copyright 2018-present Network Optix, Inc. Licensed under MPL 2.0: www.mozilla.org/MPL/2.0/

#pragma once

#include "analytics_event.h"
#include "analytics_object_event.h"
#include "backup_finished_event.h"
#include "camera_input_event.h"
#include "debug_event.h"
#include "device_disconnected_event.h"
#include "device_ip_conflict_event.h"
#include "fan_error_event.h"
#include "generic_event.h"
#include "ldap_sync_issue_event.h"
#include "license_issue_event.h"
#include "motion_event.h"
#include "network_issue_event.h"
#include "plugin_diagnostic_event.h"
#include "poe_over_budget_event.h"
#include "server_certificate_error_event.h"
#include "server_conflict_event.h"
#include "server_failure_event.h"
#include "server_started_event.h"
#include "soft_trigger_event.h"
#include "storage_issue_event.h"
