#!/bin/sh

RETVAL=0

SERVICE_NAME=mediaserver
CUSTOMIZATION=${deb.customization.company.name}
PREFIX=/usr/local/apps/$CUSTOMIZATION/mediaserver/
BIN_NAME=mediaserver
BIN_PATH=$PREFIX/bin/$BIN_NAME
STORAGE_PATH=/media/mmcblk0p1
LOG_LEVEL=WARN

export LD_LIBRARY_PATH=$PREFIX/lib
export VMS_PLUGIN_DIR=$PREFIX/plugins

echo "/media/mmcblk0p1/cores/core.%p" > /proc/sys/kernel/core_pattern
ulimit -c unlimited

start() {
    SERVICE_PID="`/bin/pidof $BIN_NAME`"
    if [ ! -z "$SERVICE_PID" ]
    then
       echo "$SERVICE_NAME is already running with pid $SERVICE_PID"
       return 0
    fi

    touch $STORAGE_PATH 2>/dev/null 1>&2
    if [ $? -ne 0 ]; then
        #echo "RO"
        mount -o rw,remount $STORAGE_PATH
    fi

    echo -n "Starting $BIN_NAME..... "
    $BIN_PATH -e --conf-file=$PREFIX/etc/mediaserver.conf --log-level=$LOG_LEVEL --msg-log-level=DEBUG1 2>/dev/null 1>&2&
    if [ `/bin/pidof $BIN_NAME` ]
    then
        echo "OK"
    fi
}

startquiet() {
    start
}

stop() {
    echo -n "Stopping $BIN_NAME..... "
    /usr/bin/killall $1 $BIN_NAME 1>/dev/null
    while [ `/bin/pidof $BIN_NAME` ]
    do
        /bin/sleep 1
    done
    echo "OK"
}

start_watchdog() {
    WATCHDOG_PID="`/bin/ps aux | /bin/grep run_watchdog | /bin/grep -v grep | cut -b 1-5 | sort -r | head -n 1`"
    if [ ! -z "$WATCHDOG_PID" ]; then
        echo "$CUSTOMIZATION-mediaserver watchdog is already running with pid $WATCHDOG_PID"
        return 0
    fi
    /bin/sh -c "/etc/init.d/S99$CUSTOMIZATION-mediaserver run_watchdog" 2>/dev/null 1>&2&
    echo "$SERVICE_NAME watchdog has been started"
}

stop_watchdog() {
    WATCHDOG_PID="`/bin/ps aux | /bin/grep run_watchdog | /bin/grep -v grep | cut -b 1-5 | sort -r | head -n 1`"
    if [ -z "$WATCHDOG_PID" ]; then
        echo "$CUSTOMIZATION-mediaserver watchdog is not running"
        return 0
    fi
    
    echo -n "Stopping $CUSTOMIZATION-mediaserver watchdog..... "
    kill $WATCHDOG_PID
    sleep 1
    echo "OK"
}

run_watchdog() {
    while true
    do
        start
        sleep 20
    done
}


#
#   Main script
#
case "$1" in
    start)
        start
        start_watchdog
        ;;

    startquiet)
        start
        ;;

    start_console)
        $BIN_PATH -e --conf-file=$PREFIX/etc/mediaserver.conf --log-level=$LOG_LEVEL --msg-log-level=DEBUG1
        ;;

    start_gdb)
        gdbserver 0.0.0.0:12345 $BIN_PATH -e --conf-file=$PREFIX/etc/mediaserver.conf --log-level=$LOG_LEVEL
        ;;

    stop)
        stop_watchdog
        stop
        ;;

    kill)
        stop_watchdog
        stop -9
        ;;

    status)
        SERVICE_PID="`/bin/pidof $BIN_NAME`"
        if [ ! -z $SERVICE_PID ]
        then
            echo "$SERVICE_NAME is running with pid $SERVICE_PID"
            exit 0
        else
            echo "$SERVICE_NAME is stopped"
            exit 1
        fi
        ;;

    server_status)
        if [ `/bin/pidof $BIN_NAME` ]
        then
            echo "1"
        fi
        ;;

    restart|reload|force-reload)
        stop
        while [ `/bin/pidof $BIN_NAME` ]
        do
            /bin/sleep 1
        done
        start
        ;;

    start_watchdog)
        start_watchdog
        ;;

    run_watchdog)
        run_watchdog
        ;;
        
    stop_watchdog)
        stop_watchdog
        ;;

    *)
        echo "Usage: $0 {start|startquiet|stop|restart|status}"
        exit 1
esac

exit $RETVAL
