#!/bin/sh

CUSTOMIZATION="@deb.customization.company.name@"

SECONDS_TO_WAIT_BEFORE_KILL_9=120
KILL_IF_HIGH_MEM_USAGE=1

SERVICE_NAME="mediaserver"
MEDIASERVER_DIR="/opt/$CUSTOMIZATION/mediaserver"
BIN_NAME="mediaserver"
BIN_PATH="$MEDIASERVER_DIR/bin/$BIN_NAME"
STORAGE_PATH="/sdcard"
HTTP_LOG_LEVEL="none"
LOGS_PATH="/sdcard/mserver.data/log"
LOG_OUTPUT_FLAG="$LOGS_PATH/log_output.flag"
OUTPUT_LOG="$LOGS_PATH/mediaserver-out.log"

export VMS_PLUGIN_DIR="$MEDIASERVER_DIR/plugins"
export SASL_PATH="$MEDIASERVER_DIR/lib/sasl2"

# ATTENTION: The args should not contain spaces, because busybox shell does not support arrays.
RUN_ARGS="\
-e \
--conf-file=$MEDIASERVER_DIR/etc/mediaserver.conf \
--runtime-conf-file=$MEDIASERVER_DIR/etc/running_time.conf \
--msg-log-level=$HTTP_LOG_LEVEL \
"

checkSdCard()
{
    # Make sure that STORAGE_PATH dir exists and is in /proc/mounts.
    if ! grep "$STORAGE_PATH" /proc/mounts >/dev/null 2>&1 || [ ! -d "$STORAGE_PATH" ]; then
        echo "SD card not inserted"
        return 1
    fi
}

start()
{
    SERVICE_PID=$(pidof "$BIN_NAME")
    if [ ! -z "$SERVICE_PID" ]; then
       echo "$SERVICE_NAME is already running with pid $SERVICE_PID"
       return 0
    fi

    checkSdCard

    if ! touch "$STORAGE_PATH" >/dev/null 2>&1; then
        #echo "RO"
        mount -o rw,remount "$STORAGE_PATH"
    fi

    if [ -f "$LOG_OUTPUT_FLAG" ]; then
        mkdir -p "$(dirname "$OUTPUT_LOG")"
        REDIRECT_OUTPUT="$OUTPUT_LOG"
    else
        REDIRECT_OUTPUT="/dev/null"
    fi

    echo "Starting Media Server, outputting to $REDIRECT_OUTPUT, with command:"
    set -x
    "$BIN_PATH" $RUN_ARGS >>"$REDIRECT_OUTPUT" 2>&1 &
    { set +x; } 2>/dev/null

    sleep 1
    # See if server instantly crashes.
    if [ "$(pidof "$BIN_NAME")" ]; then
        echo "OK"
    else
        echo "FAILED"
        return 1
    fi
}

startquiet()
{
    start
}

stop() # [signal]
{
    SIGNAL="$1" #< Can be empty.

    echo "Stopping $BIN_NAME..."
    /usr/bin/killall $SIGNAL "$BIN_NAME" >/dev/null
    local i=0
    while [ "$(pidof "$BIN_NAME")" ]; do
        /bin/sleep 1
        let i++
        if [ $i -gt $SECONDS_TO_WAIT_BEFORE_KILL_9 ]; then
            echo -n "sending 9 signal...    "
            /usr/bin/killall -9 "$BIN_NAME" >/dev/null 2>&1
        fi
    done
    echo "DONE"
}

printWatchdogPid()
{
    pgrep -f -- "-c $0"
}

start_watchdog()
{
    WATCHDOG_PID=$(printWatchdogPid)
    if [ ! -z "$WATCHDOG_PID" ]; then
        echo "$CUSTOMIZATION-mediaserver watchdog is already running with pid $WATCHDOG_PID"
        return 0
    fi

    /bin/sh -c "$0 run_watchdog" >/dev/null 2>&1 &
    echo "$SERVICE_NAME watchdog has been started"
}

stop_watchdog()
{
    WATCHDOG_PID=$(printWatchdogPid)
    if [ -z "$WATCHDOG_PID" ]; then
        echo "$CUSTOMIZATION-mediaserver watchdog is not running"
        return 0
    fi

    echo "Stopping $CUSTOMIZATION-mediaserver watchdog..."
    kill "$WATCHDOG_PID"
    sleep 1
    echo "OK"
}

kill_ms_if_high_mem_usage()
{
    MSERVER_PID=$(pidof "$BIN_NAME")
    if [ -z "$MSERVER_PID" ]; then
        exit 0
    fi

    MEM_USAGE=$(cat /proc/$MSERVER_PID/status \
        |grep VmRSS |cut -d ":" -f2 |tr -d "\t " |cut -d "k" -f 1)

    if [ "$MEM_USAGE" -gt 89000 ]; then
        kill -FPE "$MSERVER_PID"
    fi
}

run_watchdog()
{
    while true; do
        start
        if [ ! -z "$KILL_IF_HIGH_MEM_USAGE" ]; then
            kill_ms_if_high_mem_usage
        fi
        sleep 20
    done
}

help()
{
    cat <<EOF
Usage: $0 <command>
Supported commands:
start # Start mediaserver and watchdog, enabling output to $OUTPUT_LOG if $LOG_OUTPUT_FLAG exists.
startquiet # Start mediaserver.
start_console # Run mediaserver in foreground without output redirection.
start_gdb # Run mediaserver under gdb.
stop # Stop watchdog and kill mediaserver with SIGINT.
kill # Stop watchdog and kill mediaserver with SIGKILL.
status # Report whether mediaserver is running, and its pid. Exit status is non-zero if stopped.
server_status # Output 1 if mediaserver is running, otherwise, do nothing.
restart, reload, force-reload # Stop watchdog and mediaserver, start mediaserver and watchdog.
start_watchdog # Start watchdog service in background.
run_watchdog # Run watchdog in foreground.
stop_watchdog # Stop watchdog service, if any.
EOF
}

#--------------------------------------------------------------------------------------------------
# main

echo "$STORAGE_PATH/cores/core.%p" >/proc/sys/kernel/core_pattern
if [ ! -e "$STORAGE_PATH/cores" ]; then
    mkdir "$STORAGE_PATH/cores"
fi
ulimit -c unlimited

case "$1" in
    start)
        start && start_watchdog
        ;;
    startquiet)
        start
        ;;
    start_console)
        set -x
        checkSdCard
        "$BIN_PATH" $RUN_ARGS
        ;;
    start_gdb)
        set -x
        checkSdCard
        gdbserver 0.0.0.0:12345 "$BIN_PATH" $RUN_ARGS
        ;;
    stop)
        stop_watchdog
        stop
        ;;
    kill)
        stop_watchdog
        stop -9
        ;;
    status)
        SERVICE_PID=$(pidof "$BIN_NAME")
        if [ ! -z "$SERVICE_PID" ]; then
            echo "$SERVICE_NAME is running with pid $SERVICE_PID"
            exit 0
        else
            echo "$SERVICE_NAME is stopped"
            exit 1
        fi
        ;;
    server_status)
        if [ "$(pidof "$BIN_NAME")" ]; then
            echo "1"
        fi
        ;;
    restart|reload|force-reload)
        stop_watchdog
        stop
        echo "Waiting for mediaserver process to end..."
        while [ "$(pidof "$BIN_NAME")" ]; do
            /bin/sleep 1
        done
        start && start_watchdog
        ;;
    start_watchdog)
        start_watchdog
        ;;
    run_watchdog)
        run_watchdog
        ;;
    stop_watchdog)
        stop_watchdog
        ;;
    *)
        help
        exit 1
esac
