
files:
  -
    source: '/webadmin/**/*.*'
    translation: '%original_file_name%'
    ignore:
      - /webadmin/views/debug.html
      - /webadmin/views/sdkeula.html
  -
    source: '/*.*'
    translation: '%file_name%%locale_with_underscore%.%file_extension%'
    ignore:
      - crowdin.yaml
