<?xml version="1.0" encoding="UTF-8"?>
<TS language="en_US" sourcelanguage="en" version="2.1">
  <context>
    <name>global</name>
    <message>
      <source>{{PRODUCT_NAME}}</source>
      <translation>SK Cloud</translation>
    </message>
    <message>
      <source>{{CLIENT_PROTOCOL}}</source>
      <translation>sk-vms</translation>
    </message>
    <message>
      <source>{{VMS_NAME}}</source>
      <translation>SK_VMS</translation>
    </message>
    <message>
      <source>{{downloadLink}}</source>
      <translation>http://sk-vms.systemk.co.jp/</translation>
    </message>
    <message>
      <source>{{supportLink}}</source>
      <translation>mailto:marketing@systemk.co.jp</translation>
    </message>
    <message>
      <source>{{supportLinkText}}</source>
      <translation>marketing@systemk.co.jp</translation>
    </message>
    <message>
      <source>{{companyUrl}}</source>
      <translation>http://systemk.co.jp/</translation>
    </message>
    <message>
      <source>{{iOSappID}}</source>
      <translation>MXZQG6QD9L.jp.co.systemk.SkMobile</translation>
    </message>
    <message>
      <source>{{IOS_APP_LINK}}</source>
      <translation>disabled</translation>
    </message>
    <message>
      <source>{{ANDROID_APP_LINK}}</source>
      <translation>https://play.google.com/store/apps/details?id=jp.co.systemk.skvms</translation>
    </message>     
    <message>
      <source>{{COMPANY_NAME}}</source>
      <translation>EZ Pro</translation>
    </message>
  </context>
</TS>
