<head>
	<title>EST Class Hierachy</title>
</head>
<body background="http://www.cstr.ed.ac.uk/images/cstr_background.jpg" 
	bgcolor="#ffffff" link="#0000ff" 
	vlink="#dd0000" text="#000088" alink="9000ff">

<A HREF = "http://www.cstr.ed.ac.uk/">
	<IMG align=left BORDER=0 SRC = "cstr.gif"></A> 
<A HREF="http://www.cstr.ed.ac.uk/projects/speech_tools.html">
	<IMG BORDER=0 ALIGN=right SRC="est.jpg" width=150 height=93></A>
<br>

<h1>
	Edinburgh Speech Tools<br>
	<small><small><b>V1.1.0 August 1998</b></small></small>
</h1>
<br clear=left>
